
stages:
 - build
 - deploy

### configure (CMake project configuration) and build (generate, install)
build_site:
  stage: build
  script:
    - chmod 700 ./share/ci/prepare_static_site_ci.sh
    - ./share/ci/prepare_static_site_ci.sh
    - ./configure_workspace.sh
    - ./build_site.sh
    - ./publish_site.sh
  artifacts:
    paths:
    - public
  only:
    - master
  interruptible: true
  tags:
    - pid
    - site


### upload the static site (using gitlab pages)
pages:
  stage: deploy
  script:
    - echo "[PID] generating static web site"
  artifacts:
    paths:
    - public
  only:
    - master
  interruptible: true
  tags:
    - pid
    - site
