set(eigen_PID_KNOWN_VERSION 3.2.0;3.2.9;3.3.4;3.3.7)

set(eigen_PID_KNOWN_VERSION_3.2.0_GREATER_VERSIONS_COMPATIBLE_UP_TO 3.3.7 CACHE INTERNAL "")
set(eigen_PID_KNOWN_VERSION_3.2.9_GREATER_VERSIONS_COMPATIBLE_UP_TO 3.3.7 CACHE INTERNAL "")
set(eigen_PID_KNOWN_VERSION_3.3.4_GREATER_VERSIONS_COMPATIBLE_UP_TO 3.3.7 CACHE INTERNAL "")
finding_External_Package(eigen)
