set(opencv_PID_KNOWN_VERSION 2.4.11;3.4.0;3.4.1;4.0.1)

set(opencv_PID_KNOWN_VERSION_2.4.11_GREATER_VERSIONS_COMPATIBLE_UP_TO 3.4.0 CACHE INTERNAL "")
set(opencv_PID_KNOWN_VERSION_3.4.0_GREATER_VERSIONS_COMPATIBLE_UP_TO 4.0.1 CACHE INTERNAL "")
set(opencv_PID_KNOWN_VERSION_3.4.1_GREATER_VERSIONS_COMPATIBLE_UP_TO 4.0.1 CACHE INTERNAL "")
finding_External_Package(opencv)
