#### referencing wrapper of external package osqp-eigen ####
set(osqp-eigen_PID_WRAPPER_CONTACT_AUTHOR _Sonny_Tarbouriech CACHE INTERNAL "")
set(osqp-eigen_PID_WRAPPER_CONTACT_INSTITUTION _LIRMM CACHE INTERNAL "")
set(osqp-eigen_PID_WRAPPER_CONTACT_MAIL  CACHE INTERNAL "")
set(osqp-eigen_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(osqp-eigen_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/rob-miscellaneous/osqp-eigen CACHE INTERNAL "")
set(osqp-eigen_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(osqp-eigen_PID_WRAPPER_SITE_INTRODUCTION "OSQP is a is a numerical optimization package for solving convex quadratic programs" CACHE INTERNAL "")
set(osqp-eigen_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Sonny_Tarbouriech(_LIRMM);_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(osqp-eigen_PID_WRAPPER_YEARS 2019 CACHE INTERNAL "")
set(osqp-eigen_PID_WRAPPER_LICENSE GNUGPL CACHE INTERNAL "")
set(osqp-eigen_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/osqp-eigen.git CACHE INTERNAL "")
set(osqp-eigen_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/osqp-eigen.git CACHE INTERNAL "")
set(osqp-eigen_DESCRIPTION "Eigen;wrapper;for;OSQP;library" CACHE INTERNAL "")
set(osqp-eigen_FRAMEWORK rpc CACHE INTERNAL "")
set(osqp-eigen_CATEGORIES "algorithm/optimization" CACHE INTERNAL "")
set(osqp-eigen_AUTHORS "Giulio Romualdi and Stefano Dafarra" CACHE INTERNAL "")
set(osqp-eigen_PROJECT_SITE https://github.com/robotology/osqp-eigen CACHE INTERNAL "")
set(osqp-eigen_LICENSES GNUGPL CACHE INTERNAL "")
set(osqp-eigen_REFERENCES  CACHE INTERNAL "")
