#### referencing package ethercatcpp-core mode ####
set(ethercatcpp-core_MAIN_AUTHOR _Arnaud_Meline CACHE INTERNAL "")
set(ethercatcpp-core_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(ethercatcpp-core_CONTACT_MAIL  CACHE INTERNAL "")
set(ethercatcpp-core_FRAMEWORK ethercatcpp CACHE INTERNAL "")
set(ethercatcpp-core_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(ethercatcpp-core_PROJECT_PAGE https://gite.lirmm.fr/ethercatcpp/ethercatcpp-core CACHE INTERNAL "")
set(ethercatcpp-core_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(ethercatcpp-core_SITE_INTRODUCTION ethercatcpp-core;is;a;package;providing;the;ethercat;core;driver;and;driver;for;beckhoff;devices. CACHE INTERNAL "")
set(ethercatcpp-core_AUTHORS_AND_INSTITUTIONS "_Arnaud_Meline(_LIRMM)" CACHE INTERNAL "")
set(ethercatcpp-core_DESCRIPTION "ethercat driver libraries for UNIX" CACHE INTERNAL "")
set(ethercatcpp-core_YEARS 2017 CACHE INTERNAL "")
set(ethercatcpp-core_LICENSE CeCILL-C CACHE INTERNAL "")
set(ethercatcpp-core_ADDRESS git@gite.lirmm.fr:ethercatcpp/ethercatcpp-core.git CACHE INTERNAL "")
set(ethercatcpp-core_PUBLIC_ADDRESS https://gite.lirmm.fr/ethercatcpp/ethercatcpp-core.git CACHE INTERNAL "")
set(ethercatcpp-core_CATEGORIES "ethercat;ethercat/network_device;ethercat/sensor/encoder" CACHE INTERNAL "")
set(ethercatcpp-core_REFERENCES  CACHE INTERNAL "")
