#### referencing package wui-cpp mode ####
set(wui-cpp_MAIN_AUTHOR _Benjamin Navarro CACHE INTERNAL "")
set(wui-cpp_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(wui-cpp_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(wui-cpp_FRAMEWORK  CACHE INTERNAL "")
set(wui-cpp_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(wui-cpp_PROJECT_PAGE  CACHE INTERNAL "")
set(wui-cpp_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(wui-cpp_SITE_INTRODUCTION  CACHE INTERNAL "")
set(wui-cpp_AUTHORS_AND_INSTITUTIONS "_Benjamin Navarro(_LIRMM)" CACHE INTERNAL "")
set(wui-cpp_DESCRIPTION "WUI-CPP is an easy to use Web-based GUI for your C++ programs." CACHE INTERNAL "")
set(wui-cpp_YEARS 2018 CACHE INTERNAL "")
set(wui-cpp_LICENSE GNULGPL CACHE INTERNAL "")
set(wui-cpp_ADDRESS git@github.com:BenjaminNavarro/wui-cpp.git CACHE INTERNAL "")
set(wui-cpp_PUBLIC_ADDRESS https://github.com/BenjaminNavarro/wui-cpp.git CACHE INTERNAL "")
set(wui-cpp_CATEGORIES CACHE INTERNAL "")
set(wui-cpp_REFERENCES  CACHE INTERNAL "")
