#### referencing package shadow-hand-biotac-calibration mode ####
set(shadow-hand-biotac-calibration_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(shadow-hand-biotac-calibration_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(shadow-hand-biotac-calibration_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(shadow-hand-biotac-calibration_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM);_Prajval_Kumar(_LIRMM)" CACHE INTERNAL "")
set(shadow-hand-biotac-calibration_DESCRIPTION Calibration procedure for the Biotacs CACHE INTERNAL "")
set(shadow-hand-biotac-calibration_YEARS 2015 CACHE INTERNAL "")
set(shadow-hand-biotac-calibration_LICENSE CeCILL-C CACHE INTERNAL "")
set(shadow-hand-biotac-calibration_ADDRESS git@gite.lirmm.fr:shadow-hands/shadow-hand-biotac-calibration.git CACHE INTERNAL "")
set(shadow-hand-biotac-calibration_CATEGORIES "hand/shadow-dexterous;knowbotics/hand" CACHE INTERNAL "")
set(shadow-hand-biotac-calibration_REFERENCES  CACHE INTERNAL "")
