#### referencing wrapper of external package wiring_pi ####
set(wiring_pi_PID_WRAPPER_CONTACT_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(wiring_pi_PID_WRAPPER_CONTACT_INSTITUTION  CACHE INTERNAL "")
set(wiring_pi_PID_WRAPPER_CONTACT_MAIL  CACHE INTERNAL "")
set(wiring_pi_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(wiring_pi_PID_WRAPPER_PROJECT_PAGE  CACHE INTERNAL "")
set(wiring_pi_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(wiring_pi_PID_WRAPPER_SITE_INTRODUCTION  CACHE INTERNAL "")
set(wiring_pi_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Robin_Passama()" CACHE INTERNAL "")
set(wiring_pi_PID_WRAPPER_YEARS 2018 CACHE INTERNAL "")
set(wiring_pi_PID_WRAPPER_LICENSE GNULGPL CACHE INTERNAL "")
set(wiring_pi_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:explore-rov/Drivers/wiring_pi.git CACHE INTERNAL "")
set(wiring_pi_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/explore-rov/Drivers/wiring_pi.git CACHE INTERNAL "")
set(wiring_pi_DESCRIPTION "PID wrapper for the wiringPi project" CACHE INTERNAL "")
set(wiring_pi_FRAMEWORK  CACHE INTERNAL "")
set(wiring_pi_CATEGORIES CACHE INTERNAL "")
set(wiring_pi_AUTHORS "Drogon.net contributors" CACHE INTERNAL "")
set(wiring_pi_PROJECT_SITE http://wiringpi.com CACHE INTERNAL "")
set(wiring_pi_LICENSES GNU LGPL CACHE INTERNAL "")
set(wiring_pi_REFERENCES  CACHE INTERNAL "")
