#### referencing package rob-knowbotics mode ####
set(rob-knowbotics_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(rob-knowbotics_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(rob-knowbotics_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(rob-knowbotics_AUTHORS_AND_INSTITUTIONS ;"_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(rob-knowbotics_DESCRIPTION an API to ease integration of various robotics code CACHE INTERNAL "")
set(rob-knowbotics_YEARS 2014 CACHE INTERNAL "")
set(rob-knowbotics_LICENSE CeCILL-C CACHE INTERNAL "")
set(rob-knowbotics_ADDRESS git@rob-dev.lirmm.fr:rob-developers/rob-knowbotics.git CACHE INTERNAL "")
set(rob-knowbotics_CATEGORIES data/primitive;data/physic;data/geometry CACHE INTERNAL "")
set(rob-knowbotics_REFERENCES  CACHE INTERNAL "")
