#### referencing wrapper of external package wxwidgets ####
set(wxwidgets_PID_WRAPPER_CONTACT_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(wxwidgets_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(wxwidgets_PID_WRAPPER_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(wxwidgets_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(wxwidgets_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/pid/wxwidgets CACHE INTERNAL "")
set(wxwidgets_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(wxwidgets_PID_WRAPPER_SITE_INTRODUCTION this;project;is;a;PID;wrapper;for;external;project;called;wxWidgets.;wxWidgets;is;a;multi-platform;native;GUI;C++;library. CACHE INTERNAL "")
set(wxwidgets_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr)" CACHE INTERNAL "")
set(wxwidgets_PID_WRAPPER_YEARS 2018 CACHE INTERNAL "")
set(wxwidgets_PID_WRAPPER_LICENSE GNULGPL CACHE INTERNAL "")
set(wxwidgets_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:pid/wxwidgets.git CACHE INTERNAL "")
set(wxwidgets_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/wxwidgets.git CACHE INTERNAL "")
set(wxwidgets_DESCRIPTION "wxWidgets is a C++ library that lets developers create applications for Windows, Mac OS X, Linux and other platforms with a single code base, repackaged for PID" CACHE INTERNAL "")
set(wxwidgets_FRAMEWORK pid CACHE INTERNAL "")
set(wxwidgets_CATEGORIES "programming/gui" CACHE INTERNAL "")
set(wxwidgets_AUTHORS "wxWidgets authors" CACHE INTERNAL "")
set(wxwidgets_PROJECT_SITE http://www.wxwidgets.org CACHE INTERNAL "")
set(wxwidgets_LICENSES GNULGPL License CACHE INTERNAL "")
set(wxwidgets_REFERENCES  CACHE INTERNAL "")
