#### referencing wrapper of external package libfreenect2 ####
set(libfreenect2_PID_WRAPPER_CONTACT_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(libfreenect2_PID_WRAPPER_CONTACT_INSTITUTION _LIRMM CACHE INTERNAL "")
set(libfreenect2_PID_WRAPPER_CONTACT_MAIL  CACHE INTERNAL "")
set(libfreenect2_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(libfreenect2_PID_WRAPPER_PROJECT_PAGE  CACHE INTERNAL "")
set(libfreenect2_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(libfreenect2_PID_WRAPPER_SITE_INTRODUCTION  CACHE INTERNAL "")
set(libfreenect2_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(libfreenect2_PID_WRAPPER_YEARS 2018 CACHE INTERNAL "")
set(libfreenect2_PID_WRAPPER_LICENSE GNUGPL CACHE INTERNAL "")
set(libfreenect2_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:rob-vision-devices/libfreenect2.git CACHE INTERNAL "")
set(libfreenect2_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-vision-devices/libfreenect2.git CACHE INTERNAL "")
set(libfreenect2_DESCRIPTION "PID;wrapper;of;libfreenect2,;driver;library;for;Microsoft;kinect;2;RGBD;camera" CACHE INTERNAL "")
set(libfreenect2_FRAMEWORK  CACHE INTERNAL "")
set(libfreenect2_CATEGORIES CACHE INTERNAL "")
set(libfreenect2_AUTHORS "OpenKinect project contributors" CACHE INTERNAL "")
set(libfreenect2_PROJECT_SITE https://github.com/OpenKinect CACHE INTERNAL "")
set(libfreenect2_LICENSES GNU GPL CACHE INTERNAL "")
set(libfreenect2_REFERENCES  CACHE INTERNAL "")
