#### referencing package knowbotics mode ####
set(knowbotics_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(knowbotics_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(knowbotics_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(knowbotics_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM);_Benjamin_Navarro(_LIRMM);_Andrea_Cherubini(_LIRMM)" CACHE INTERNAL "")
set(knowbotics_DESCRIPTION an API to ease integration of various robotics code CACHE INTERNAL "")
set(knowbotics_YEARS 2014 CACHE INTERNAL "")
set(knowbotics_LICENSE CeCILL-C CACHE INTERNAL "")
set(knowbotics_ADDRESS git@gite.lirmm.fr:knowbotics/knowbotics.git CACHE INTERNAL "")
set(knowbotics_CATEGORIES knowbotics/generic CACHE INTERNAL "")
set(knowbotics_REFERENCES  CACHE INTERNAL "")
