#### referencing package imglibs-leapmotion mode ####
set(imglibs-leapmotion_MAIN_AUTHOR _Mohamed_HAIJOUBI CACHE INTERNAL "")
set(imglibs-leapmotion_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(imglibs-leapmotion_CONTACT_MAIL  CACHE INTERNAL "")
set(imglibs-leapmotion_FRAMEWORK  CACHE INTERNAL "")
set(imglibs-leapmotion_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(imglibs-leapmotion_PROJECT_PAGE  CACHE INTERNAL "")
set(imglibs-leapmotion_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(imglibs-leapmotion_SITE_INTRODUCTION  CACHE INTERNAL "")
set(imglibs-leapmotion_AUTHORS_AND_INSTITUTIONS "_Mohamed_HAIJOUBI(_LIRMM)" CACHE INTERNAL "")
set(imglibs-leapmotion_DESCRIPTION "Convertion for leapmotion" CACHE INTERNAL "")
set(imglibs-leapmotion_YEARS 2017 CACHE INTERNAL "")
set(imglibs-leapmotion_LICENSE CeCILL CACHE INTERNAL "")
set(imglibs-leapmotion_ADDRESS git@gite.lirmm.fr:rob-vision/imglibs-leapmotion.git CACHE INTERNAL "")
set(imglibs-leapmotion_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(imglibs-leapmotion_CATEGORIES CACHE INTERNAL "")
set(imglibs-leapmotion_REFERENCES  CACHE INTERNAL "")
