#### referencing package visual-servoing-knowbotics mode ####
set(visual-servoing-knowbotics_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(visual-servoing-knowbotics_MAIN_INSTITUTION _LIRMM_EMAIL_passama@lirmm.fr CACHE INTERNAL "")
set(visual-servoing-knowbotics_CONTACT_MAIL  CACHE INTERNAL "")
set(visual-servoing-knowbotics_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM_EMAIL_passama@lirmm.fr);_Andrea_Cherubini(_LIRMM)" CACHE INTERNAL "")
set(visual-servoing-knowbotics_DESCRIPTION visual-servoing-knowbotics provides a set of knowbotics API to deal with visual servoing CACHE INTERNAL "")
set(visual-servoing-knowbotics_YEARS 2016 CACHE INTERNAL "")
set(visual-servoing-knowbotics_LICENSE CeCILL-C CACHE INTERNAL "")
set(visual-servoing-knowbotics_ADDRESS git@gite.lirmm.fr:knowbotics/visual-servoing-knowbotics.git CACHE INTERNAL "")
set(visual-servoing-knowbotics_CATEGORIES CACHE INTERNAL "")
set(visual-servoing-knowbotics_AVAILABLE_PLATFORMS linux64cxx11;linux64;linux32;macosx64 CACHE INTERNAL "")
set(visual-servoing-knowbotics_AVAILABLE_PLATFORM_linux64cxx11_OS linux CACHE INTERNAL "")
set(visual-servoing-knowbotics_AVAILABLE_PLATFORM_linux64cxx11_ARCH 64 CACHE INTERNAL "")
set(visual-servoing-knowbotics_AVAILABLE_PLATFORM_linux64cxx11_ABI CXX11 CACHE INTERNAL "")
set(visual-servoing-knowbotics_AVAILABLE_PLATFORM_linux64cxx11_CONFIGURATION posix CACHE INTERNAL "")
set(visual-servoing-knowbotics_AVAILABLE_PLATFORM_linux64_OS linux CACHE INTERNAL "")
set(visual-servoing-knowbotics_AVAILABLE_PLATFORM_linux64_ARCH 64 CACHE INTERNAL "")
set(visual-servoing-knowbotics_AVAILABLE_PLATFORM_linux64_ABI CXX CACHE INTERNAL "")
set(visual-servoing-knowbotics_AVAILABLE_PLATFORM_linux64_CONFIGURATION posix CACHE INTERNAL "")
set(visual-servoing-knowbotics_AVAILABLE_PLATFORM_linux32_OS linux CACHE INTERNAL "")
set(visual-servoing-knowbotics_AVAILABLE_PLATFORM_linux32_ARCH 32 CACHE INTERNAL "")
set(visual-servoing-knowbotics_AVAILABLE_PLATFORM_linux32_ABI CXX CACHE INTERNAL "")
set(visual-servoing-knowbotics_AVAILABLE_PLATFORM_linux32_CONFIGURATION posix CACHE INTERNAL "")
set(visual-servoing-knowbotics_AVAILABLE_PLATFORM_macosx64_OS macosx CACHE INTERNAL "")
set(visual-servoing-knowbotics_AVAILABLE_PLATFORM_macosx64_ARCH 64 CACHE INTERNAL "")
set(visual-servoing-knowbotics_AVAILABLE_PLATFORM_macosx64_ABI CXX CACHE INTERNAL "")
set(visual-servoing-knowbotics_AVAILABLE_PLATFORM_macosx64_CONFIGURATION posix CACHE INTERNAL "")
set(visual-servoing-knowbotics_REFERENCES  CACHE INTERNAL "")
