#### referencing package target-pose-in-robot-frame mode ####
set(target-pose-in-robot-frame_MAIN_AUTHOR _Abdellah_Khelloufi CACHE INTERNAL "")
set(target-pose-in-robot-frame_MAIN_INSTITUTION  CACHE INTERNAL "")
set(target-pose-in-robot-frame_CONTACT_MAIL  CACHE INTERNAL "")
set(target-pose-in-robot-frame_AUTHORS_AND_INSTITUTIONS "_Abdellah_Khelloufi()" CACHE INTERNAL "")
set(target-pose-in-robot-frame_DESCRIPTION Calculate the target pose in the robot frame using odometry and target pose in the world frame. CACHE INTERNAL "")
set(target-pose-in-robot-frame_YEARS 2017 CACHE INTERNAL "")
set(target-pose-in-robot-frame_LICENSE CeCILL CACHE INTERNAL "")
set(target-pose-in-robot-frame_ADDRESS git@gite.lirmm.fr:abdellah_khe_at_gmail_com/target-pose-in-robot-frame.git CACHE INTERNAL "")
set(target-pose-in-robot-frame_CATEGORIES "mobile-robot/modified-youbot;mobile-robot/simulated;knowbotics/mobile-robot;simulator/vrep" CACHE INTERNAL "")
set(target-pose-in-robot-frame_AVAILABLE_PLATFORMS linux64cxx11;linux64;linux32;macosx64 CACHE INTERNAL "")
set(target-pose-in-robot-frame_AVAILABLE_PLATFORM_linux64cxx11_OS linux CACHE INTERNAL "")
set(target-pose-in-robot-frame_AVAILABLE_PLATFORM_linux64cxx11_ARCH 64 CACHE INTERNAL "")
set(target-pose-in-robot-frame_AVAILABLE_PLATFORM_linux64cxx11_ABI CXX11 CACHE INTERNAL "")
set(target-pose-in-robot-frame_AVAILABLE_PLATFORM_linux64cxx11_CONFIGURATION  CACHE INTERNAL "")
set(target-pose-in-robot-frame_AVAILABLE_PLATFORM_linux64_OS linux CACHE INTERNAL "")
set(target-pose-in-robot-frame_AVAILABLE_PLATFORM_linux64_ARCH 64 CACHE INTERNAL "")
set(target-pose-in-robot-frame_AVAILABLE_PLATFORM_linux64_ABI CXX CACHE INTERNAL "")
set(target-pose-in-robot-frame_AVAILABLE_PLATFORM_linux64_CONFIGURATION  CACHE INTERNAL "")
set(target-pose-in-robot-frame_AVAILABLE_PLATFORM_linux32_OS linux CACHE INTERNAL "")
set(target-pose-in-robot-frame_AVAILABLE_PLATFORM_linux32_ARCH 32 CACHE INTERNAL "")
set(target-pose-in-robot-frame_AVAILABLE_PLATFORM_linux32_ABI CXX CACHE INTERNAL "")
set(target-pose-in-robot-frame_AVAILABLE_PLATFORM_linux32_CONFIGURATION  CACHE INTERNAL "")
set(target-pose-in-robot-frame_AVAILABLE_PLATFORM_macosx64_OS macosx CACHE INTERNAL "")
set(target-pose-in-robot-frame_AVAILABLE_PLATFORM_macosx64_ARCH 64 CACHE INTERNAL "")
set(target-pose-in-robot-frame_AVAILABLE_PLATFORM_macosx64_ABI CXX CACHE INTERNAL "")
set(target-pose-in-robot-frame_AVAILABLE_PLATFORM_macosx64_CONFIGURATION  CACHE INTERNAL "")
set(target-pose-in-robot-frame_REFERENCES  CACHE INTERNAL "")
