#### referencing wrapper of external package kfr ####
set(kfr_PID_WRAPPER_CONTACT_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(kfr_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(kfr_PID_WRAPPER_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(kfr_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(kfr_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/rob-miscellaneous/kfr CACHE INTERNAL "")
set(kfr_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(kfr_PID_WRAPPER_SITE_INTRODUCTION "wrapper of KFR signal processing library" CACHE INTERNAL "")
set(kfr_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr)" CACHE INTERNAL "")
set(kfr_PID_WRAPPER_YEARS 2020 CACHE INTERNAL "")
set(kfr_PID_WRAPPER_LICENSE CeCILL CACHE INTERNAL "")
set(kfr_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/kfr.git CACHE INTERNAL "")
set(kfr_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/kfr.git CACHE INTERNAL "")
set(kfr_DESCRIPTION "wrapper of KFR signal processing library" CACHE INTERNAL "")
set(kfr_FRAMEWORK rpc CACHE INTERNAL "")
set(kfr_CATEGORIES "algorithm/signal" CACHE INTERNAL "")
set(kfr_AUTHORS "Dan Levin and contributors" CACHE INTERNAL "")
set(kfr_PROJECT_SITE https://www.kfr.dev CACHE INTERNAL "")
set(kfr_LICENSES GPL-2.0 CACHE INTERNAL "")
set(kfr_REFERENCES  CACHE INTERNAL "")
