#### referencing package rob-vision mode ####
set(rob-vision_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(rob-vision_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(rob-vision_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(rob-vision_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(rob-vision_DESCRIPTION A library for image processing CACHE INTERNAL "")
set(rob-vision_YEARS 2016 CACHE INTERNAL "")
set(rob-vision_LICENSE CeCILL-C CACHE INTERNAL "")
set(rob-vision_ADDRESS git@gite.lirmm.fr:rob-vision/rob-vision.git CACHE INTERNAL "")
set(rob-vision_CATEGORIES CACHE INTERNAL "")
set(rob-vision_AVAILABLE_PLATFORMS linux64cxx11;linux64;linux32;macosx64 CACHE INTERNAL "")
set(rob-vision_AVAILABLE_PLATFORM_linux64cxx11_OS linux CACHE INTERNAL "")
set(rob-vision_AVAILABLE_PLATFORM_linux64cxx11_ARCH 64 CACHE INTERNAL "")
set(rob-vision_AVAILABLE_PLATFORM_linux64cxx11_ABI CXX11 CACHE INTERNAL "")
set(rob-vision_AVAILABLE_PLATFORM_linux64cxx11_CONFIGURATION x11;imagemagic;posix CACHE INTERNAL "")
set(rob-vision_AVAILABLE_PLATFORM_linux64_OS linux CACHE INTERNAL "")
set(rob-vision_AVAILABLE_PLATFORM_linux64_ARCH 64 CACHE INTERNAL "")
set(rob-vision_AVAILABLE_PLATFORM_linux64_ABI CXX CACHE INTERNAL "")
set(rob-vision_AVAILABLE_PLATFORM_linux64_CONFIGURATION x11;imagemagic;posix CACHE INTERNAL "")
set(rob-vision_AVAILABLE_PLATFORM_linux32_OS linux CACHE INTERNAL "")
set(rob-vision_AVAILABLE_PLATFORM_linux32_ARCH 32 CACHE INTERNAL "")
set(rob-vision_AVAILABLE_PLATFORM_linux32_ABI CXX CACHE INTERNAL "")
set(rob-vision_AVAILABLE_PLATFORM_linux32_CONFIGURATION x11;imagemagic;posix CACHE INTERNAL "")
set(rob-vision_AVAILABLE_PLATFORM_macosx64_OS macosx CACHE INTERNAL "")
set(rob-vision_AVAILABLE_PLATFORM_macosx64_ARCH 64 CACHE INTERNAL "")
set(rob-vision_AVAILABLE_PLATFORM_macosx64_ABI CXX CACHE INTERNAL "")
set(rob-vision_AVAILABLE_PLATFORM_macosx64_CONFIGURATION x11;imagemagic;posix CACHE INTERNAL "")
set(rob-vision_REFERENCES  CACHE INTERNAL "")
