#### referencing package imglibs-interop mode ####
set(imglibs-interop_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(imglibs-interop_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(imglibs-interop_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(imglibs-interop_FRAMEWORK  CACHE INTERNAL "")
set(imglibs-interop_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(imglibs-interop_PROJECT_PAGE  CACHE INTERNAL "")
set(imglibs-interop_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(imglibs-interop_SITE_INTRODUCTION  CACHE INTERNAL "")
set(imglibs-interop_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM);_Sebastien_Druon(_LIRMM);_Mohamed_Haijoubi(_LIRMM)" CACHE INTERNAL "")
set(imglibs-interop_DESCRIPTION "A library for image interoperability" CACHE INTERNAL "")
set(imglibs-interop_YEARS 2016 CACHE INTERNAL "")
set(imglibs-interop_LICENSE CeCILL-C CACHE INTERNAL "")
set(imglibs-interop_ADDRESS git@gite.lirmm.fr:rob-vision/imglibs-interop.git CACHE INTERNAL "")
set(imglibs-interop_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(imglibs-interop_CATEGORIES CACHE INTERNAL "")
set(imglibs-interop_REFERENCES  CACHE INTERNAL "")
