#### referencing package eigen-cdd mode ####
set(eigen-cdd_MAIN_AUTHOR _Vincent_Samy CACHE INTERNAL "")
set(eigen-cdd_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(eigen-cdd_CONTACT_MAIL vsamy@outlook.fr CACHE INTERNAL "")
set(eigen-cdd_FRAMEWORK  CACHE INTERNAL "")
set(eigen-cdd_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(eigen-cdd_PROJECT_PAGE  CACHE INTERNAL "")
set(eigen-cdd_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(eigen-cdd_SITE_INTRODUCTION  CACHE INTERNAL "")
set(eigen-cdd_AUTHORS_AND_INSTITUTIONS "_Vincent_Samy(_LIRMM)" CACHE INTERNAL "")
set(eigen-cdd_DESCRIPTION "Small Eigen Wrapper of cdd. Based on Fukuda's library named [cdd](https://www.inf.ethz.ch/personal/fukudak/cdd_home)" CACHE INTERNAL "")
set(eigen-cdd_YEARS 2017;2017 CACHE INTERNAL "")
set(eigen-cdd_LICENSE CeCILL-C CACHE INTERNAL "")
set(eigen-cdd_ADDRESS git@github.com:vsamy/eigen-cdd.git CACHE INTERNAL "")
set(eigen-cdd_PUBLIC_ADDRESS https://github.com/vsamy/eigen-cdd.git CACHE INTERNAL "")
set(eigen-cdd_CATEGORIES CACHE INTERNAL "")
set(eigen-cdd_REFERENCES  CACHE INTERNAL "")
