#### referencing package rkcl-otg-reflexxes mode ####
set(rkcl-otg-reflexxes_MAIN_AUTHOR _Sonny_Tarbouriech CACHE INTERNAL "")
set(rkcl-otg-reflexxes_MAIN_INSTITUTION _Tecnalia CACHE INTERNAL "")
set(rkcl-otg-reflexxes_CONTACT_MAIL  CACHE INTERNAL "")
set(rkcl-otg-reflexxes_FRAMEWORK  CACHE INTERNAL "")
set(rkcl-otg-reflexxes_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rkcl-otg-reflexxes_PROJECT_PAGE  CACHE INTERNAL "")
set(rkcl-otg-reflexxes_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rkcl-otg-reflexxes_SITE_INTRODUCTION  CACHE INTERNAL "")
set(rkcl-otg-reflexxes_AUTHORS_AND_INSTITUTIONS "_Sonny_Tarbouriech(_Tecnalia)" CACHE INTERNAL "")
set(rkcl-otg-reflexxes_DESCRIPTION "TODO:;input;a;short;description;of;package;rkcl-otg-reflexxes;utility;here" CACHE INTERNAL "")
set(rkcl-otg-reflexxes_YEARS 2019 CACHE INTERNAL "")
set(rkcl-otg-reflexxes_LICENSE CeCILL CACHE INTERNAL "")
set(rkcl-otg-reflexxes_ADDRESS git@gitlab.com:rkcl/rkcl-otg-reflexxes.git CACHE INTERNAL "")
set(rkcl-otg-reflexxes_PUBLIC_ADDRESS https://gitlab.com/rkcl/rkcl-otg-reflexxes.git CACHE INTERNAL "")
set(rkcl-otg-reflexxes_CATEGORIES CACHE INTERNAL "")
set(rkcl-otg-reflexxes_REFERENCES  CACHE INTERNAL "")
