#### referencing package eigen-qp mode ####
set(eigen-qp_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(eigen-qp_MAIN_INSTITUTION  CACHE INTERNAL "")
set(eigen-qp_CONTACT_MAIL  CACHE INTERNAL "")
set(eigen-qp_FRAMEWORK  CACHE INTERNAL "")
set(eigen-qp_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(eigen-qp_PROJECT_PAGE  CACHE INTERNAL "")
set(eigen-qp_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(eigen-qp_SITE_INTRODUCTION  CACHE INTERNAL "")
set(eigen-qp_AUTHORS_AND_INSTITUTIONS "_Robin_Passama();_Joris_Vaillant(_LIRMM);_Pierre_Gergondet(_JRL)" CACHE INTERNAL "")
set(eigen-qp_DESCRIPTION "quadratic programming solvers through Eigen3 library, by Joris Vaillant (<joris dot vaillant at gmail dot com>) and QLD solver for eigen by JRL. PID native package wrapping projects https://github.com/jrl-umi3218/eigen-quadprog and https://github.com/jrl-umi3218/eigen-qld" CACHE INTERNAL "")
set(eigen-qp_YEARS 2017 CACHE INTERNAL "")
set(eigen-qp_LICENSE GNULGPL CACHE INTERNAL "")
set(eigen-qp_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/eigen-qp.git CACHE INTERNAL "")
set(eigen-qp_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/eigen-qp.git CACHE INTERNAL "")
set(eigen-qp_CATEGORIES CACHE INTERNAL "")
set(eigen-qp_REFERENCES  CACHE INTERNAL "")
