#### referencing wrapper of external package fltk ####
set(fltk_PID_WRAPPER_CONTACT_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(fltk_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(fltk_PID_WRAPPER_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(fltk_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(fltk_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/pid/wrappers/fltk CACHE INTERNAL "")
set(fltk_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(fltk_PID_WRAPPER_SITE_INTRODUCTION PID wrapper for the fltk project. FLTK is a cross-platform C++ GUI toolkit;. CACHE INTERNAL "")
set(fltk_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr);_Robin_Passama(_CNRS/LIRMM)" CACHE INTERNAL "")
set(fltk_PID_WRAPPER_YEARS 2018 CACHE INTERNAL "")
set(fltk_PID_WRAPPER_LICENSE GNULGPL CACHE INTERNAL "")
set(fltk_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:pid/wrappers/fltk.git CACHE INTERNAL "")
set(fltk_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/wrappers/fltk.git CACHE INTERNAL "")
set(fltk_DESCRIPTION "FLTK is a cross-platform C++ GUI toolkit" CACHE INTERNAL "")
set(fltk_FRAMEWORK pid CACHE INTERNAL "")
set(fltk_CATEGORIES "programming/gui" CACHE INTERNAL "")
set(fltk_AUTHORS "FLTK authors" CACHE INTERNAL "")
set(fltk_PROJECT_SITE http://www.fltk.org CACHE INTERNAL "")
set(fltk_LICENSES GNUGPL CACHE INTERNAL "")
set(fltk_REFERENCES  CACHE INTERNAL "")
