#### referencing package upboardexample mode ####
set(upboardexample_MAIN_AUTHOR _Clement_Rebut CACHE INTERNAL "")
set(upboardexample_MAIN_INSTITUTION  CACHE INTERNAL "")
set(upboardexample_CONTACT_MAIL  CACHE INTERNAL "")
set(upboardexample_FRAMEWORK  CACHE INTERNAL "")
set(upboardexample_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(upboardexample_PROJECT_PAGE  CACHE INTERNAL "")
set(upboardexample_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(upboardexample_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(upboardexample_AUTHORS_AND_INSTITUTIONS "_Clement_Rebut();_Charles_Villard" CACHE INTERNAL "")
set(upboardexample_DESCRIPTION "This;package;centralise;all;drivers;use;example;for;the;upboard" CACHE INTERNAL "")
set(upboardexample_YEARS 2019 CACHE INTERNAL "")
set(upboardexample_LICENSE CeCILL CACHE INTERNAL "")
set(upboardexample_ADDRESS git@gite.lirmm.fr:hardio/examples/upboardexample.git CACHE INTERNAL "")
set(upboardexample_PUBLIC_ADDRESS https://gite.lirmm.fr/hardio/examples/upboardexample.git CACHE INTERNAL "")
set(upboardexample_CATEGORIES CACHE INTERNAL "")
set(upboardexample_REFERENCES  CACHE INTERNAL "")
