#### referencing wrapper of external package urg_library ####
set(urg_library_PID_WRAPPER_CONTACT_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(urg_library_PID_WRAPPER_CONTACT_INSTITUTION _LIRMM-CNRS CACHE INTERNAL "")
set(urg_library_PID_WRAPPER_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(urg_library_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(urg_library_PID_WRAPPER_PROJECT_PAGE  CACHE INTERNAL "")
set(urg_library_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(urg_library_PID_WRAPPER_SITE_INTRODUCTION  CACHE INTERNAL "")
set(urg_library_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM-CNRS)" CACHE INTERNAL "")
set(urg_library_PID_WRAPPER_YEARS 2018 CACHE INTERNAL "")
set(urg_library_PID_WRAPPER_LICENSE BSD CACHE INTERNAL "")
set(urg_library_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:rob-vision-devices/urg_library.git CACHE INTERNAL "")
set(urg_library_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-vision-devices/urg_library.git CACHE INTERNAL "")
set(urg_library_DESCRIPTION "Wrapper;for;urg_library;project,;a;library;to;interact;with;hokuyo;laser;range;scanners." CACHE INTERNAL "")
set(urg_library_FRAMEWORK  CACHE INTERNAL "")
set(urg_library_CATEGORIES CACHE INTERNAL "")
set(urg_library_AUTHORS "Satofumi Kamimura, Adrian Boeing and Katsumi Kimoto" CACHE INTERNAL "")
set(urg_library_PROJECT_SITE http://urgnetwork.sourceforge.net/html/ CACHE INTERNAL "")
set(urg_library_LICENSES Simplified BSD and LGPL CACHE INTERNAL "")
set(urg_library_REFERENCES  CACHE INTERNAL "")
