#### referencing package my-first-package mode ####
set(my-first-package_MAIN_AUTHOR _Mohamed_HAIJOUBI CACHE INTERNAL "")
set(my-first-package_MAIN_INSTITUTION  CACHE INTERNAL "")
set(my-first-package_CONTACT_MAIL  CACHE INTERNAL "")
set(my-first-package_AUTHORS_AND_INSTITUTIONS "_Mohamed_HAIJOUBI()" CACHE INTERNAL "")
set(my-first-package_DESCRIPTION Tutorial PID  CACHE INTERNAL "")
set(my-first-package_YEARS 2017 CACHE INTERNAL "")
set(my-first-package_LICENSE CeCILL CACHE INTERNAL "")
set(my-first-package_ADDRESS git@gite.lirmm.fr:haijoubi/my-first-package.git CACHE INTERNAL "")
set(my-first-package_CATEGORIES CACHE INTERNAL "")
set(my-first-package_AVAILABLE_PLATFORMS linux64cxx11;linux64;linux32;macosx64 CACHE INTERNAL "")
set(my-first-package_AVAILABLE_PLATFORM_linux64cxx11_OS linux CACHE INTERNAL "")
set(my-first-package_AVAILABLE_PLATFORM_linux64cxx11_ARCH 64 CACHE INTERNAL "")
set(my-first-package_AVAILABLE_PLATFORM_linux64cxx11_ABI CXX11 CACHE INTERNAL "")
set(my-first-package_AVAILABLE_PLATFORM_linux64cxx11_CONFIGURATION  CACHE INTERNAL "")
set(my-first-package_AVAILABLE_PLATFORM_linux64_OS linux CACHE INTERNAL "")
set(my-first-package_AVAILABLE_PLATFORM_linux64_ARCH 64 CACHE INTERNAL "")
set(my-first-package_AVAILABLE_PLATFORM_linux64_ABI CXX CACHE INTERNAL "")
set(my-first-package_AVAILABLE_PLATFORM_linux64_CONFIGURATION  CACHE INTERNAL "")
set(my-first-package_AVAILABLE_PLATFORM_linux32_OS linux CACHE INTERNAL "")
set(my-first-package_AVAILABLE_PLATFORM_linux32_ARCH 32 CACHE INTERNAL "")
set(my-first-package_AVAILABLE_PLATFORM_linux32_ABI CXX CACHE INTERNAL "")
set(my-first-package_AVAILABLE_PLATFORM_linux32_CONFIGURATION  CACHE INTERNAL "")
set(my-first-package_AVAILABLE_PLATFORM_macosx64_OS macosx CACHE INTERNAL "")
set(my-first-package_AVAILABLE_PLATFORM_macosx64_ARCH 64 CACHE INTERNAL "")
set(my-first-package_AVAILABLE_PLATFORM_macosx64_ABI CXX CACHE INTERNAL "")
set(my-first-package_AVAILABLE_PLATFORM_macosx64_CONFIGURATION  CACHE INTERNAL "")
set(my-first-package_REFERENCES  CACHE INTERNAL "")
