#### referencing wrapper of external package openvr ####
set(openvr_PID_WRAPPER_CONTACT_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(openvr_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(openvr_PID_WRAPPER_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(openvr_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(openvr_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/rob-vision/msvf/wrappers/openvr CACHE INTERNAL "")
set(openvr_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(openvr_PID_WRAPPER_SITE_INTRODUCTION "PID;wrapper;for;the;external;project;called;OpenVR:;OpenVR;is;an;API;and;runtime;that;allows;access;to;VR;hardware;from;multiple;vendors;without;requiring;that;applications;have;specific;knowledge;of;the;hardware;they;are;targeting" CACHE INTERNAL "")
set(openvr_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr)" CACHE INTERNAL "")
set(openvr_PID_WRAPPER_YEARS 2018 CACHE INTERNAL "")
set(openvr_PID_WRAPPER_LICENSE BSD CACHE INTERNAL "")
set(openvr_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:rob-vision/msvf/wrappers/openvr.git CACHE INTERNAL "")
set(openvr_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-vision/msvf/wrappers/openvr.git CACHE INTERNAL "")
set(openvr_DESCRIPTION "PID wrapper for OpenVR external project" CACHE INTERNAL "")
set(openvr_FRAMEWORK rpc CACHE INTERNAL "")
set(openvr_CATEGORIES "driver/sensor/vision" CACHE INTERNAL "")
set(openvr_AUTHORS "opencv.org members" CACHE INTERNAL "")
set(openvr_PROJECT_SITE https://github.com/ValveSoftware/openvr CACHE INTERNAL "")
set(openvr_LICENSES 3-clause BSD License CACHE INTERNAL "")
set(openvr_REFERENCES  CACHE INTERNAL "")
