#### referencing wrapper of external package protobuf ####
set(protobuf_PID_WRAPPER_CONTACT_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(protobuf_PID_WRAPPER_CONTACT_INSTITUTION _LIRMM CACHE INTERNAL "")
set(protobuf_PID_WRAPPER_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(protobuf_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(protobuf_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/pid/wrappers/protobuf CACHE INTERNAL "")
set(protobuf_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(protobuf_PID_WRAPPER_SITE_INTRODUCTION protobuf;is;a;PID;wrapper;for;the;external;project;called;protobuf.It;implement;Google;data;exchange;format. CACHE INTERNAL "")
set(protobuf_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(protobuf_PID_WRAPPER_YEARS 2019 CACHE INTERNAL "")
set(protobuf_PID_WRAPPER_LICENSE CeCILL-C CACHE INTERNAL "")
set(protobuf_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:pid/wrappers/protobuf.git CACHE INTERNAL "")
set(protobuf_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/wrappers/protobuf.git CACHE INTERNAL "")
set(protobuf_DESCRIPTION "protobuf;project;provides;an;efficient;serialization;API;in;C++." CACHE INTERNAL "")
set(protobuf_FRAMEWORK pid CACHE INTERNAL "")
set(protobuf_CATEGORIES "programming/serialization" CACHE INTERNAL "")
set(protobuf_AUTHORS "Google Inc." CACHE INTERNAL "")
set(protobuf_PROJECT_SITE https://github.com/protocolbuffers/protobuf CACHE INTERNAL "")
set(protobuf_LICENSES protobuf license CACHE INTERNAL "")
set(protobuf_REFERENCES  CACHE INTERNAL "")
