#### referencing wrapper of external package aruco ####
set(aruco_PID_WRAPPER_CONTACT_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(aruco_PID_WRAPPER_CONTACT_INSTITUTION _LIRMM-CNRS CACHE INTERNAL "")
set(aruco_PID_WRAPPER_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(aruco_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(aruco_PID_WRAPPER_PROJECT_PAGE  CACHE INTERNAL "")
set(aruco_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(aruco_PID_WRAPPER_SITE_INTRODUCTION  CACHE INTERNAL "")
set(aruco_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM-CNRS)" CACHE INTERNAL "")
set(aruco_PID_WRAPPER_YEARS 2018 CACHE INTERNAL "")
set(aruco_PID_WRAPPER_LICENSE BSD CACHE INTERNAL "")
set(aruco_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:rob-vision-devices/aruco.git CACHE INTERNAL "")
set(aruco_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-vision-devices/aruco.git CACHE INTERNAL "")
set(aruco_DESCRIPTION "Wrapper;for;aruco;project,;a;minimal;library;to;detect;various;markers." CACHE INTERNAL "")
set(aruco_FRAMEWORK  CACHE INTERNAL "")
set(aruco_CATEGORIES CACHE INTERNAL "")
set(aruco_AUTHORS "AVA group of the University of Cordoba." CACHE INTERNAL "")
set(aruco_PROJECT_SITE https://www.uco.es/investiga/grupos/ava/node/26 CACHE INTERNAL "")
set(aruco_LICENSES Simplified BSD CACHE INTERNAL "")
set(aruco_REFERENCES  CACHE INTERNAL "")
