#### referencing wrapper of external package nanomsg ####
set(nanomsg_PID_WRAPPER_CONTACT_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(nanomsg_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(nanomsg_PID_WRAPPER_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(nanomsg_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(nanomsg_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/pid/nanomsg CACHE INTERNAL "")
set(nanomsg_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(nanomsg_PID_WRAPPER_SITE_INTRODUCTION The;nanomsg;library;is;a;simple;high-performance;implementation;of;several;scalability;protocols. CACHE INTERNAL "")
set(nanomsg_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr)" CACHE INTERNAL "")
set(nanomsg_PID_WRAPPER_YEARS 2018 CACHE INTERNAL "")
set(nanomsg_PID_WRAPPER_LICENSE GNULGPL CACHE INTERNAL "")
set(nanomsg_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:pid/nanomsg.git CACHE INTERNAL "")
set(nanomsg_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/nanomsg.git CACHE INTERNAL "")
set(nanomsg_DESCRIPTION "The;nanomsg;library;is;a;simple;high-performance;implementation;of;several;scalability;protocols.;Repackaged;for;PID" CACHE INTERNAL "")
set(nanomsg_FRAMEWORK pid CACHE INTERNAL "")
set(nanomsg_CATEGORIES "programming/network" CACHE INTERNAL "")
set(nanomsg_AUTHORS "Martin Sustrik, Garrett D'Amore, and more" CACHE INTERNAL "")
set(nanomsg_PROJECT_SITE https://github.com/nanomsg/nanomsg CACHE INTERNAL "")
set(nanomsg_LICENSES MIT CACHE INTERNAL "")
set(nanomsg_REFERENCES  CACHE INTERNAL "")
