#### referencing package hokuyo-laser-scanner-knowbotics mode ####
set(hokuyo-laser-scanner-knowbotics_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(hokuyo-laser-scanner-knowbotics_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(hokuyo-laser-scanner-knowbotics_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(hokuyo-laser-scanner-knowbotics_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(hokuyo-laser-scanner-knowbotics_DESCRIPTION knowbotics code to manage hokuyo drivers CACHE INTERNAL "")
set(hokuyo-laser-scanner-knowbotics_YEARS 2015 CACHE INTERNAL "")
set(hokuyo-laser-scanner-knowbotics_LICENSE CeCILL-C CACHE INTERNAL "")
set(hokuyo-laser-scanner-knowbotics_ADDRESS git@gite.lirmm.fr:rob-vision-devices/hokuyo-laser-scanner-knowbotics.git CACHE INTERNAL "")
set(hokuyo-laser-scanner-knowbotics_CATEGORIES "knowbotics/laser-scanner;laser-scanner/hokuyo" CACHE INTERNAL "")
set(hokuyo-laser-scanner-knowbotics_AVAILABLE_PLATFORMS linux64cxx11;linux64;linux32;macosx64 CACHE INTERNAL "")
set(hokuyo-laser-scanner-knowbotics_AVAILABLE_PLATFORM_linux64cxx11_OS linux CACHE INTERNAL "")
set(hokuyo-laser-scanner-knowbotics_AVAILABLE_PLATFORM_linux64cxx11_ARCH 64 CACHE INTERNAL "")
set(hokuyo-laser-scanner-knowbotics_AVAILABLE_PLATFORM_linux64cxx11_ABI CXX11 CACHE INTERNAL "")
set(hokuyo-laser-scanner-knowbotics_AVAILABLE_PLATFORM_linux64cxx11_CONFIGURATION  CACHE INTERNAL "")
set(hokuyo-laser-scanner-knowbotics_AVAILABLE_PLATFORM_linux64_OS linux CACHE INTERNAL "")
set(hokuyo-laser-scanner-knowbotics_AVAILABLE_PLATFORM_linux64_ARCH 64 CACHE INTERNAL "")
set(hokuyo-laser-scanner-knowbotics_AVAILABLE_PLATFORM_linux64_ABI CXX CACHE INTERNAL "")
set(hokuyo-laser-scanner-knowbotics_AVAILABLE_PLATFORM_linux64_CONFIGURATION  CACHE INTERNAL "")
set(hokuyo-laser-scanner-knowbotics_AVAILABLE_PLATFORM_linux32_OS linux CACHE INTERNAL "")
set(hokuyo-laser-scanner-knowbotics_AVAILABLE_PLATFORM_linux32_ARCH 32 CACHE INTERNAL "")
set(hokuyo-laser-scanner-knowbotics_AVAILABLE_PLATFORM_linux32_ABI CXX CACHE INTERNAL "")
set(hokuyo-laser-scanner-knowbotics_AVAILABLE_PLATFORM_linux32_CONFIGURATION  CACHE INTERNAL "")
set(hokuyo-laser-scanner-knowbotics_AVAILABLE_PLATFORM_macosx64_OS macosx CACHE INTERNAL "")
set(hokuyo-laser-scanner-knowbotics_AVAILABLE_PLATFORM_macosx64_ARCH 64 CACHE INTERNAL "")
set(hokuyo-laser-scanner-knowbotics_AVAILABLE_PLATFORM_macosx64_ABI CXX CACHE INTERNAL "")
set(hokuyo-laser-scanner-knowbotics_AVAILABLE_PLATFORM_macosx64_CONFIGURATION  CACHE INTERNAL "")
set(hokuyo-laser-scanner-knowbotics_REFERENCES  CACHE INTERNAL "")
