#### referencing package cooperative-task-controller-ros mode ####
set(cooperative-task-controller-ros_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(cooperative-task-controller-ros_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(cooperative-task-controller-ros_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(cooperative-task-controller-ros_FRAMEWORK  CACHE INTERNAL "")
set(cooperative-task-controller-ros_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(cooperative-task-controller-ros_PROJECT_PAGE  CACHE INTERNAL "")
set(cooperative-task-controller-ros_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(cooperative-task-controller-ros_SITE_INTRODUCTION  CACHE INTERNAL "")
set(cooperative-task-controller-ros_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(cooperative-task-controller-ros_DESCRIPTION "ROS interface for the cooperative-task-controller package" CACHE INTERNAL "")
set(cooperative-task-controller-ros_YEARS 2018 CACHE INTERNAL "")
set(cooperative-task-controller-ros_LICENSE GNULGPL CACHE INTERNAL "")
set(cooperative-task-controller-ros_ADDRESS git@gite.lirmm.fr:ur-robots/cooperative-task-controller-ros.git CACHE INTERNAL "")
set(cooperative-task-controller-ros_PUBLIC_ADDRESS https://gite.lirmm.fr/ur-robots/cooperative-task-controller-ros.git CACHE INTERNAL "")
set(cooperative-task-controller-ros_CATEGORIES CACHE INTERNAL "")
set(cooperative-task-controller-ros_REFERENCES  CACHE INTERNAL "")
