#### referencing package quadprog mode ####
set(quadprog_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(quadprog_MAIN_INSTITUTION _CNRS/LIRMM CACHE INTERNAL "")
set(quadprog_CONTACT_MAIL robin.passama@lirmm.fr CACHE INTERNAL "")
set(quadprog_FRAMEWORK rpc CACHE INTERNAL "")
set(quadprog_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(quadprog_PROJECT_PAGE https://gite.lirmm.fr/rob-miscellaneous/quadprog CACHE INTERNAL "")
set(quadprog_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(quadprog_SITE_INTRODUCTION PID version of the package create by Luca Di Gaspero and Eric Moyer. This is a C++ library implementing the algorithm of Goldfarb and Idnani for the solution of a (convex) Quadratic Programming problem by means of an active-set dual method. CACHE INTERNAL "")
set(quadprog_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_CNRS/LIRMM)" CACHE INTERNAL "")
set(quadprog_DESCRIPTION "PID version of the package create by Luca Di Gaspero and Eric Moyer. This is a C++ library implementing the algorithm of Goldfarb and Idnani for the solution of a (convex) Quadratic Programming problem by means of an active-set dual method." CACHE INTERNAL "")
set(quadprog_YEARS 2016 CACHE INTERNAL "")
set(quadprog_LICENSE GNULGPL CACHE INTERNAL "")
set(quadprog_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/quadprog.git CACHE INTERNAL "")
set(quadprog_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/quadprog.git CACHE INTERNAL "")
set(quadprog_CATEGORIES "algorithm/optimization" CACHE INTERNAL "")
set(quadprog_REFERENCES  CACHE INTERNAL "")
