#### referencing package rbdyn mode ####
set(rbdyn_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(rbdyn_MAIN_INSTITUTION _CNRS/LIRMM CACHE INTERNAL "")
set(rbdyn_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(rbdyn_FRAMEWORK rpc CACHE INTERNAL "")
set(rbdyn_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rbdyn_PROJECT_PAGE https://gite.lirmm.fr/rob-miscellaneous/rbdyn CACHE INTERNAL "")
set(rbdyn_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rbdyn_SITE_INTRODUCTION "PID repackaging of RBDyn (https://github.com/jrl-umi3218/RBDyn): RBDyn provides a set of classes and functions to model the dynamics of rigid body systems. All this implementation is based on Roy Featherstone Rigid Body Dynamics Algorithms book." CACHE INTERNAL "")
set(rbdyn_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_CNRS/LIRMM);_Joris_Vaillant(_CNRS/LIRMM);_Robin_Passama(_CNRS/LIRMM)" CACHE INTERNAL "")
set(rbdyn_DESCRIPTION "PID;repackaging;of;RBDyn:;https://github.com/jrl-umi3218/RBDyn" CACHE INTERNAL "")
set(rbdyn_YEARS 2017 CACHE INTERNAL "")
set(rbdyn_LICENSE GNULGPL CACHE INTERNAL "")
set(rbdyn_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/rbdyn.git CACHE INTERNAL "")
set(rbdyn_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/rbdyn.git CACHE INTERNAL "")
set(rbdyn_CATEGORIES "algorithm/math" CACHE INTERNAL "")
set(rbdyn_REFERENCES  CACHE INTERNAL "")
