#### referencing package gram-savitzky-golay mode ####
set(gram-savitzky-golay_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(gram-savitzky-golay_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(gram-savitzky-golay_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(gram-savitzky-golay_FRAMEWORK  CACHE INTERNAL "")
set(gram-savitzky-golay_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(gram-savitzky-golay_PROJECT_PAGE  CACHE INTERNAL "")
set(gram-savitzky-golay_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(gram-savitzky-golay_SITE_INTRODUCTION  CACHE INTERNAL "")
set(gram-savitzky-golay_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM);_Arnaud_Tanguy(_LIRMM)" CACHE INTERNAL "")
set(gram-savitzky-golay_DESCRIPTION "C++ Implementation of Savitzky-Golay filtering based on Gram polynomials" CACHE INTERNAL "")
set(gram-savitzky-golay_YEARS 2018 CACHE INTERNAL "")
set(gram-savitzky-golay_LICENSE GNULGPL CACHE INTERNAL "")
set(gram-savitzky-golay_ADDRESS git@gite.lirmm.fr:signal-processing/gram-savitzky-golay.git CACHE INTERNAL "")
set(gram-savitzky-golay_PUBLIC_ADDRESS https://gite.lirmm.fr/signal-processing/gram-savitzky-golay.git CACHE INTERNAL "")
set(gram-savitzky-golay_CATEGORIES CACHE INTERNAL "")
set(gram-savitzky-golay_REFERENCES  CACHE INTERNAL "")
