#### referencing wrapper of external package blackmagic-decklink ####
set(blackmagic-decklink_PID_WRAPPER_CONTACT_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(blackmagic-decklink_PID_WRAPPER_CONTACT_INSTITUTION _CNRS/LIRMM CACHE INTERNAL "")
set(blackmagic-decklink_PID_WRAPPER_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(blackmagic-decklink_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(blackmagic-decklink_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/robmed/devices/blackmagic-decklink CACHE INTERNAL "")
set(blackmagic-decklink_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(blackmagic-decklink_PID_WRAPPER_SITE_INTRODUCTION "DeckLink API is used to connect a PC with DeckLink video acquisition cards provided by Black Magic Design company." CACHE INTERNAL "")
set(blackmagic-decklink_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_CNRS/LIRMM)" CACHE INTERNAL "")
set(blackmagic-decklink_PID_WRAPPER_YEARS 2019 CACHE INTERNAL "")
set(blackmagic-decklink_PID_WRAPPER_LICENSE BSD CACHE INTERNAL "")
set(blackmagic-decklink_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:robmed/devices/blackmagic-decklink.git CACHE INTERNAL "")
set(blackmagic-decklink_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/robmed/devices/blackmagic-decklink.git CACHE INTERNAL "")
set(blackmagic-decklink_DESCRIPTION "DeckLink;API;is;used;to;connect;a;PC;with;acquisition;cards;provided;by;Black;Magic;Design;company." CACHE INTERNAL "")
set(blackmagic-decklink_FRAMEWORK rpc CACHE INTERNAL "")
set(blackmagic-decklink_CATEGORIES "driver/sensor/vision" CACHE INTERNAL "")
set(blackmagic-decklink_AUTHORS "Black Magic Design Company" CACHE INTERNAL "")
set(blackmagic-decklink_PROJECT_SITE https://www.blackmagicdesign.com/products/decklink CACHE INTERNAL "")
set(blackmagic-decklink_LICENSES Black Magic Open source Free use license  CACHE INTERNAL "")
set(blackmagic-decklink_REFERENCES  CACHE INTERNAL "")
