#### referencing wrapper of external package ffmpeg ####
set(ffmpeg_PID_WRAPPER_CONTACT_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(ffmpeg_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(ffmpeg_PID_WRAPPER_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(ffmpeg_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(ffmpeg_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/pid/ffmpeg CACHE INTERNAL "")
set(ffmpeg_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(ffmpeg_PID_WRAPPER_SITE_INTRODUCTION ffmpeg;is;a;PID;wrapper;for;the;external;project;called;FFmpeg.;FFmpeg;is;the;leading;multimedia;framework,;able;to;decode,;encode,;transcode,;mux,;demux,;stream,;filter;and;play;pretty;much;anything;that;humans;and;machines;have;created. CACHE INTERNAL "")
set(ffmpeg_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr)" CACHE INTERNAL "")
set(ffmpeg_PID_WRAPPER_YEARS 2018 CACHE INTERNAL "")
set(ffmpeg_PID_WRAPPER_LICENSE GNULGPL CACHE INTERNAL "")
set(ffmpeg_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:pid/ffmpeg.git CACHE INTERNAL "")
set(ffmpeg_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/ffmpeg.git CACHE INTERNAL "")
set(ffmpeg_DESCRIPTION "FFmpeg is able to decode, encode, transcode, mux, demux, stream, filter multimedia formats. Repackaged for PID" CACHE INTERNAL "")
set(ffmpeg_FRAMEWORK pid CACHE INTERNAL "")
set(ffmpeg_CATEGORIES "programming/multimedia" CACHE INTERNAL "")
set(ffmpeg_AUTHORS "FFmpeg developers" CACHE INTERNAL "")
set(ffmpeg_PROJECT_SITE https://www.ffmpeg.org/ CACHE INTERNAL "")
set(ffmpeg_LICENSES GNULGPL CACHE INTERNAL "")
set(ffmpeg_REFERENCES  CACHE INTERNAL "")
