#### referencing package pid-os-utilities mode ####
set(pid-os-utilities_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(pid-os-utilities_MAIN_INSTITUTION  CACHE INTERNAL "")
set(pid-os-utilities_CONTACT_MAIL  CACHE INTERNAL "")
set(pid-os-utilities_FRAMEWORK pid CACHE INTERNAL "")
set(pid-os-utilities_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(pid-os-utilities_PROJECT_PAGE https://gite.lirmm.fr/pid/pid-os-utilities CACHE INTERNAL "")
set(pid-os-utilities_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(pid-os-utilities_SITE_INTRODUCTION pid-os-utilities;is;a;package;providing;utilities;APIs;for;coders.;These;APIs;are;used;to;abstract;or;simplify;OS;related;APIS. CACHE INTERNAL "")
set(pid-os-utilities_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro();_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(pid-os-utilities_DESCRIPTION Pure C++ utilities used to abstract or simplify OS related APIS CACHE INTERNAL "")
set(pid-os-utilities_YEARS 2016-2017 CACHE INTERNAL "")
set(pid-os-utilities_LICENSE CeCILL CACHE INTERNAL "")
set(pid-os-utilities_ADDRESS git@gite.lirmm.fr:pid/pid-os-utilities.git CACHE INTERNAL "")
set(pid-os-utilities_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/pid-os-utilities.git CACHE INTERNAL "")
set(pid-os-utilities_CATEGORIES "programming/operating_system" CACHE INTERNAL "")
set(pid-os-utilities_REFERENCES  CACHE INTERNAL "")
