#### referencing package cobot-arm-visual-servoing mode ####
set(cobot-arm-visual-servoing_MAIN_AUTHOR _Andrea_Cherubini CACHE INTERNAL "")
set(cobot-arm-visual-servoing_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(cobot-arm-visual-servoing_CONTACT_MAIL cherubini@lirmm.fr CACHE INTERNAL "")
set(cobot-arm-visual-servoing_FRAMEWORK  CACHE INTERNAL "")
set(cobot-arm-visual-servoing_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(cobot-arm-visual-servoing_PROJECT_PAGE  CACHE INTERNAL "")
set(cobot-arm-visual-servoing_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(cobot-arm-visual-servoing_SITE_INTRODUCTION  CACHE INTERNAL "")
set(cobot-arm-visual-servoing_AUTHORS_AND_INSTITUTIONS "_Andrea_Cherubini(_LIRMM);_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(cobot-arm-visual-servoing_DESCRIPTION "Visual servoing code using kuka LWR robot and shadow hands" CACHE INTERNAL "")
set(cobot-arm-visual-servoing_YEARS 2015 CACHE INTERNAL "")
set(cobot-arm-visual-servoing_LICENSE CeCILL-C CACHE INTERNAL "")
set(cobot-arm-visual-servoing_ADDRESS git@gite.lirmm.fr:cobot/cobot-arm-visual-servoing.git CACHE INTERNAL "")
set(cobot-arm-visual-servoing_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(cobot-arm-visual-servoing_CATEGORIES "arm/kuka-lwr;vision" CACHE INTERNAL "")
set(cobot-arm-visual-servoing_REFERENCES  CACHE INTERNAL "")
