#### referencing package space-vec-alg mode ####
set(space-vec-alg_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(space-vec-alg_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(space-vec-alg_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(space-vec-alg_FRAMEWORK  CACHE INTERNAL "")
set(space-vec-alg_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(space-vec-alg_PROJECT_PAGE  CACHE INTERNAL "")
set(space-vec-alg_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(space-vec-alg_SITE_INTRODUCTION  CACHE INTERNAL "")
set(space-vec-alg_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(space-vec-alg_DESCRIPTION PID;version;of;SpaceVecAlg:;https://github.com/jrl-umi3218/SpaceVecAlg CACHE INTERNAL "")
set(space-vec-alg_YEARS 2017 CACHE INTERNAL "")
set(space-vec-alg_LICENSE GNULGPL CACHE INTERNAL "")
set(space-vec-alg_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/space-vec-alg.git CACHE INTERNAL "")
set(space-vec-alg_CATEGORIES "math/linear_algebra" CACHE INTERNAL "")
set(space-vec-alg_REFERENCES  CACHE INTERNAL "")
