#### referencing package rtplot-core mode ####
set(rtplot-core_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(rtplot-core_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(rtplot-core_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(rtplot-core_FRAMEWORK  CACHE INTERNAL "")
set(rtplot-core_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rtplot-core_PROJECT_PAGE  CACHE INTERNAL "")
set(rtplot-core_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rtplot-core_SITE_INTRODUCTION  CACHE INTERNAL "")
set(rtplot-core_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(rtplot-core_DESCRIPTION "Core;functionalities;to;be;used;by;GUI;libraries;for;real;time;plotting" CACHE INTERNAL "")
set(rtplot-core_YEARS 2018 CACHE INTERNAL "")
set(rtplot-core_LICENSE CeCILL CACHE INTERNAL "")
set(rtplot-core_ADDRESS git@github.com:BenjaminNavarro/rtplot-core.git CACHE INTERNAL "")
set(rtplot-core_PUBLIC_ADDRESS https://github.com/BenjaminNavarro/rtplot-core.git CACHE INTERNAL "")
set(rtplot-core_CATEGORIES CACHE INTERNAL "")
set(rtplot-core_REFERENCES  CACHE INTERNAL "")
