#### referencing package hardio_ms5837 mode ####
set(hardio_ms5837_MAIN_AUTHOR _Charles_Villard CACHE INTERNAL "")
set(hardio_ms5837_MAIN_INSTITUTION  CACHE INTERNAL "")
set(hardio_ms5837_CONTACT_MAIL  CACHE INTERNAL "")
set(hardio_ms5837_FRAMEWORK  CACHE INTERNAL "")
set(hardio_ms5837_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(hardio_ms5837_PROJECT_PAGE  CACHE INTERNAL "")
set(hardio_ms5837_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(hardio_ms5837_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(hardio_ms5837_AUTHORS_AND_INSTITUTIONS "_Charles_Villard();_Clement_Rebut" CACHE INTERNAL "")
set(hardio_ms5837_DESCRIPTION "MS5837;is;a;pressure;sensor;from;BlueRov;Robotics;robot" CACHE INTERNAL "")
set(hardio_ms5837_YEARS 2018-2019 CACHE INTERNAL "")
set(hardio_ms5837_LICENSE CeCILL-C CACHE INTERNAL "")
set(hardio_ms5837_ADDRESS git@gite.lirmm.fr:hardio/devices/hardio_ms5837.git CACHE INTERNAL "")
set(hardio_ms5837_PUBLIC_ADDRESS https://gite.lirmm.fr/hardio/devices/hardio_ms5837.git CACHE INTERNAL "")
set(hardio_ms5837_CATEGORIES CACHE INTERNAL "")
set(hardio_ms5837_REFERENCES  CACHE INTERNAL "")
