#### referencing package rkcl-fk-rbdyn mode ####
set(rkcl-fk-rbdyn_MAIN_AUTHOR _Sonny_Tarbouriech CACHE INTERNAL "")
set(rkcl-fk-rbdyn_MAIN_INSTITUTION _Tecnalia CACHE INTERNAL "")
set(rkcl-fk-rbdyn_CONTACT_MAIL  CACHE INTERNAL "")
set(rkcl-fk-rbdyn_FRAMEWORK  CACHE INTERNAL "")
set(rkcl-fk-rbdyn_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rkcl-fk-rbdyn_PROJECT_PAGE  CACHE INTERNAL "")
set(rkcl-fk-rbdyn_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rkcl-fk-rbdyn_SITE_INTRODUCTION  CACHE INTERNAL "")
set(rkcl-fk-rbdyn_AUTHORS_AND_INSTITUTIONS "_Sonny_Tarbouriech(_Tecnalia);_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(rkcl-fk-rbdyn_DESCRIPTION "TODO:;input;a;short;description;of;package;rkcl-fk-rbdyn;utility;here" CACHE INTERNAL "")
set(rkcl-fk-rbdyn_YEARS 2018 CACHE INTERNAL "")
set(rkcl-fk-rbdyn_LICENSE CeCILL CACHE INTERNAL "")
set(rkcl-fk-rbdyn_ADDRESS git@gitlab.com:rkcl/rkcl-fk-rbdyn.git CACHE INTERNAL "")
set(rkcl-fk-rbdyn_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(rkcl-fk-rbdyn_CATEGORIES CACHE INTERNAL "")
set(rkcl-fk-rbdyn_REFERENCES  CACHE INTERNAL "")
