#### referencing wrapper of external package nlopt ####
set(nlopt_PID_WRAPPER_CONTACT_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(nlopt_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(nlopt_PID_WRAPPER_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(nlopt_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(nlopt_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/pid/nlopt CACHE INTERNAL "")
set(nlopt_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(nlopt_PID_WRAPPER_SITE_INTRODUCTION nlopt;is;a;PID;wrapper;for;the;external;project;called;nlopt.;nlopt;is;a;free/open-source;library;for;nonlinear;optimization. CACHE INTERNAL "")
set(nlopt_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr)" CACHE INTERNAL "")
set(nlopt_PID_WRAPPER_YEARS 2018 CACHE INTERNAL "")
set(nlopt_PID_WRAPPER_LICENSE GNULGPL CACHE INTERNAL "")
set(nlopt_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/nlopt.git CACHE INTERNAL "")
set(nlopt_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/nlopt.git CACHE INTERNAL "")
set(nlopt_DESCRIPTION "NLopt is a free/open-source library for nonlinear optimization. Repackaged for PID" CACHE INTERNAL "")
set(nlopt_FRAMEWORK pid CACHE INTERNAL "")
set(nlopt_CATEGORIES "math/optimization" CACHE INTERNAL "")
set(nlopt_AUTHORS "Steven G. Johnson" CACHE INTERNAL "")
set(nlopt_PROJECT_SITE https://nlopt.readthedocs.io/ CACHE INTERNAL "")
set(nlopt_LICENSES GNULGPL CACHE INTERNAL "")
set(nlopt_REFERENCES  CACHE INTERNAL "")
