#### referencing wrapper of external package openblas ####
set(openblas_PID_WRAPPER_CONTACT_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(openblas_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(openblas_PID_WRAPPER_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(openblas_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(openblas_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/pid/wrappers/openblas CACHE INTERNAL "")
set(openblas_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(openblas_PID_WRAPPER_SITE_INTRODUCTION This;project;is;a;PID;wrapper;for;the;external;project;called;openBLAS.;It;provides;routines;for;linear;algebra;problems;resolutions. CACHE INTERNAL "")
set(openblas_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr)" CACHE INTERNAL "")
set(openblas_PID_WRAPPER_YEARS 2018 CACHE INTERNAL "")
set(openblas_PID_WRAPPER_LICENSE BSD CACHE INTERNAL "")
set(openblas_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:pid/wrappers/openblas.git CACHE INTERNAL "")
set(openblas_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/wrappers/lapack.git CACHE INTERNAL "")
set(openblas_DESCRIPTION "PID wrapper for openBLAS project" CACHE INTERNAL "")
set(openblas_FRAMEWORK pid CACHE INTERNAL "")
set(openblas_CATEGORIES "programming/math" CACHE INTERNAL "")
set(openblas_AUTHORS "netlib.org members" CACHE INTERNAL "")
set(openblas_PROJECT_SITE http://www.openblas.net CACHE INTERNAL "")
set(openblas_LICENSES 3-clause BSD License CACHE INTERNAL "")
set(openblas_REFERENCES  CACHE INTERNAL "")
