#### referencing wrapper of external package sophus ####
set(sophus_PID_WRAPPER_CONTACT_AUTHOR _Yohan_Breux CACHE INTERNAL "")
set(sophus_PID_WRAPPER_CONTACT_INSTITUTION _LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(sophus_PID_WRAPPER_CONTACT_MAIL  CACHE INTERNAL "")
set(sophus_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(sophus_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/rob-miscellaneous/sophus CACHE INTERNAL "")
set(sophus_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(sophus_PID_WRAPPER_SITE_INTRODUCTION "Library for operations on Lie group in 2d and 3d geometry" CACHE INTERNAL "")
set(sophus_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Yohan_Breux(_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr)" CACHE INTERNAL "")
set(sophus_PID_WRAPPER_YEARS 2019 CACHE INTERNAL "")
set(sophus_PID_WRAPPER_LICENSE CeCILL CACHE INTERNAL "")
set(sophus_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/sophus.git CACHE INTERNAL "")
set(sophus_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/sophus.git CACHE INTERNAL "")
set(sophus_DESCRIPTION "Library for operations on Lie group in 2d and 3d geometry" CACHE INTERNAL "")
set(sophus_FRAMEWORK rpc CACHE INTERNAL "")
set(sophus_CATEGORIES "programming/math" CACHE INTERNAL "")
set(sophus_AUTHORS "Hauke Strasdat, Steven Lovegrove" CACHE INTERNAL "")
set(sophus_PROJECT_SITE https://github.com/strasdat/Sophus CACHE INTERNAL "")
set(sophus_LICENSES BSD2 CACHE INTERNAL "")
set(sophus_REFERENCES  CACHE INTERNAL "")
