#### referencing package powerswitch mode ####
set(powerswitch_MAIN_AUTHOR _Charles_Villard CACHE INTERNAL "")
set(powerswitch_MAIN_INSTITUTION  CACHE INTERNAL "")
set(powerswitch_CONTACT_MAIL  CACHE INTERNAL "")
set(powerswitch_FRAMEWORK  CACHE INTERNAL "")
set(powerswitch_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(powerswitch_PROJECT_PAGE  CACHE INTERNAL "")
set(powerswitch_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(powerswitch_SITE_INTRODUCTION  CACHE INTERNAL "")
set(powerswitch_AUTHORS_AND_INSTITUTIONS "_Charles_Villard()" CACHE INTERNAL "")
set(powerswitch_DESCRIPTION "This;is;the;library;to;control;the;powerswitch;board" CACHE INTERNAL "")
set(powerswitch_YEARS 2018 CACHE INTERNAL "")
set(powerswitch_LICENSE CeCILL CACHE INTERNAL "")
set(powerswitch_ADDRESS git@gite.lirmm.fr:explore-rov/Drivers/powerswitch.git CACHE INTERNAL "")
set(powerswitch_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(powerswitch_CATEGORIES CACHE INTERNAL "")
set(powerswitch_REFERENCES  CACHE INTERNAL "")
