#### referencing package api-driver-vrep mode ####
set(api-driver-vrep_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(api-driver-vrep_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(api-driver-vrep_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(api-driver-vrep_FRAMEWORK  CACHE INTERNAL "")
set(api-driver-vrep_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(api-driver-vrep_PROJECT_PAGE  CACHE INTERNAL "")
set(api-driver-vrep_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(api-driver-vrep_SITE_INTRODUCTION  CACHE INTERNAL "")
set(api-driver-vrep_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(api-driver-vrep_DESCRIPTION Wrapper for the V-REP C/C++ remote API CACHE INTERNAL "")
set(api-driver-vrep_YEARS 2015 CACHE INTERNAL "")
set(api-driver-vrep_LICENSE CeCILL-C CACHE INTERNAL "")
set(api-driver-vrep_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/api-driver-vrep.git CACHE INTERNAL "")
set(api-driver-vrep_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/api-driver-vrep.git CACHE INTERNAL "")
set(api-driver-vrep_CATEGORIES "simulator/vrep" CACHE INTERNAL "")
set(api-driver-vrep_REFERENCES 0.5.1 CACHE INTERNAL "")
set(api-driver-vrep_REFERENCE_0.5.1 x86_64_linux_abi98;x86_64_linux_abi11 CACHE INTERNAL "")
set(api-driver-vrep_REFERENCE_0.5.1_x86_64_linux_abi98_URL https://gite.lirmm.fr/rob-miscellaneous/rob-miscellaneous-binaries/wikis/api-driver-vrep/0.5.1/linux64/api-driver-vrep-0.5.1-linux64.tar.gz CACHE INTERNAL "")
set(api-driver-vrep_REFERENCE_0.5.1_x86_64_linux_abi98_URL_DEBUG https://gite.lirmm.fr/rob-miscellaneous/rob-miscellaneous-binaries/wikis/api-driver-vrep/0.5.1/linux64/api-driver-vrep-0.5.1-dbg-linux64.tar.gz CACHE INTERNAL "")
set(api-driver-vrep_REFERENCE_0.5.1_x86_64_linux_abi11_URL https://gite.lirmm.fr/rob-miscellaneous/rob-miscellaneous-binaries/wikis/api-driver-vrep/0.5.1/linux64cxx11/api-driver-vrep-0.5.1-linux64cxx11.tar.gz CACHE INTERNAL "")
set(api-driver-vrep_REFERENCE_0.5.1_x86_64_linux_abi11_URL_DEBUG https://gite.lirmm.fr/rob-miscellaneous/rob-miscellaneous-binaries/wikis/api-driver-vrep/0.5.1/linux64cxx11/api-driver-vrep-0.5.1-dbg-linux64cxx11.tar.gz CACHE INTERNAL "")
