#### referencing package the-testpack-a mode ####
set(the-testpack-a_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(the-testpack-a_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(the-testpack-a_AUTHORS_AND_INSTITUTIONS ;"_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(the-testpack-a_DESCRIPTION test package for PID CACHE INTERNAL "")
set(the-testpack-a_YEARS 2013 CACHE INTERNAL "")
set(the-testpack-a_LICENSE CeCILL CACHE INTERNAL "")
set(the-testpack-a_ADDRESS git@idh.lirmm.fr:perso/passama/the-testpack-a.git CACHE INTERNAL "")
set(the-testpack-a_CATEGORIES toto/titi;ffffffffffffff CACHE INTERNAL "")
set(the-testpack-a_REFERENCES 0.4.2;1.6.0 CACHE INTERNAL "")
set(the-testpack-a_REFERENCE_0.4.2 linux CACHE INTERNAL "")
set(the-testpack-a_REFERENCE_0.4.2_linux http://lirmm.lirmm.fr/FileX/get?auto=1&k=E5UWg8sZ08bN8HhVCY2 CACHE INTERNAL "")
set(the-testpack-a_REFERENCE_0.4.2_linux_DEBUG http://lirmm.lirmm.fr/FileX/get?auto=1&k=RtFNxqdfYemEaGRqxdw CACHE INTERNAL "")
set(the-testpack-a_REFERENCE_1.6.0 linux CACHE INTERNAL "")
set(the-testpack-a_REFERENCE_1.6.0_linux http://lirmm.lirmm.fr/FileX/get?auto=1&k=hJAu05uyO52MP7JhBnY CACHE INTERNAL "")
set(the-testpack-a_REFERENCE_1.6.0_linux_DEBUG http://lirmm.lirmm.fr/FileX/get?auto=1&k=ggkhzWAJVmmFBSrtK0a CACHE INTERNAL "")
