#### referencing wrapper of external package asio ####
set(asio_PID_WRAPPER_CONTACT_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(asio_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(asio_PID_WRAPPER_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(asio_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(asio_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/pid/wrappers/asio CACHE INTERNAL "")
set(asio_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(asio_PID_WRAPPER_SITE_INTRODUCTION This project is a PID wrapper for the external project called asio.Asio is a cross-platform C++ library for network and low-level I/O programming that provides developers with a consistent asynchronous model using a modern C++ approach, repackaged for PID. CACHE INTERNAL "")
set(asio_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr)" CACHE INTERNAL "")
set(asio_PID_WRAPPER_YEARS 2018 CACHE INTERNAL "")
set(asio_PID_WRAPPER_LICENSE MIT CACHE INTERNAL "")
set(asio_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:pid/wrappers/asio.git CACHE INTERNAL "")
set(asio_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/wrappers/asio.git CACHE INTERNAL "")
set(asio_DESCRIPTION "Asio is a cross-platform C++ library for network and low-level I/O programming that provides developers with a consistent asynchronous model using a modern C++ approach, repackaged for PID (standalone version)" CACHE INTERNAL "")
set(asio_FRAMEWORK pid CACHE INTERNAL "")
set(asio_CATEGORIES "programming/operating_system;programming/network" CACHE INTERNAL "")
set(asio_AUTHORS "Boost authors" CACHE INTERNAL "")
set(asio_PROJECT_SITE http://think-async.com/Asio CACHE INTERNAL "")
set(asio_LICENSES Boost Software License CACHE INTERNAL "")
set(asio_REFERENCES  CACHE INTERNAL "")
