#### referencing package kuka-visual-servoing mode ####
set(kuka-visual-servoing_MAIN_AUTHOR _Andrea_Cherubini CACHE INTERNAL "")
set(kuka-visual-servoing_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(kuka-visual-servoing_CONTACT_MAIL cherubini@lirmm.fr CACHE INTERNAL "")
set(kuka-visual-servoing_AUTHORS_AND_INSTITUTIONS "_Andrea_Cherubini(_LIRMM);_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(kuka-visual-servoing_DESCRIPTION Visual servoing code using kuka LWR robot CACHE INTERNAL "")
set(kuka-visual-servoing_YEARS 2015 CACHE INTERNAL "")
set(kuka-visual-servoing_LICENSE CeCILL-C CACHE INTERNAL "")
set(kuka-visual-servoing_ADDRESS git@gite.lirmm.fr:kuka-lwr/kuka-visual-servoing.git CACHE INTERNAL "")
set(kuka-visual-servoing_CATEGORIES "arm/kuka-lwr;vision" CACHE INTERNAL "")
set(kuka-visual-servoing_REFERENCES  CACHE INTERNAL "")
