#### referencing package rkcl-driver-ros mode ####
set(rkcl-driver-ros_MAIN_AUTHOR _Sonny_Tarbouriech CACHE INTERNAL "")
set(rkcl-driver-ros_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(rkcl-driver-ros_CONTACT_MAIL  CACHE INTERNAL "")
set(rkcl-driver-ros_FRAMEWORK rkcl-framework CACHE INTERNAL "")
set(rkcl-driver-ros_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rkcl-driver-ros_PROJECT_PAGE https://gite.lirmm.fr/rkcl/rkcl-driver-ros CACHE INTERNAL "")
set(rkcl-driver-ros_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rkcl-driver-ros_SITE_INTRODUCTION "ROS;Driver;for;RKCL" CACHE INTERNAL "")
set(rkcl-driver-ros_AUTHORS_AND_INSTITUTIONS "_Sonny_Tarbouriech(_LIRMM);_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(rkcl-driver-ros_DESCRIPTION "ROS;Driver;for;RKCL" CACHE INTERNAL "")
set(rkcl-driver-ros_YEARS 2019 CACHE INTERNAL "")
set(rkcl-driver-ros_LICENSE CeCILL CACHE INTERNAL "")
set(rkcl-driver-ros_ADDRESS git@gite.lirmm.fr:rkcl/rkcl-driver-ros.git CACHE INTERNAL "")
set(rkcl-driver-ros_PUBLIC_ADDRESS https://gite.lirmm.fr/rkcl/rkcl-driver-ros.git CACHE INTERNAL "")
set(rkcl-driver-ros_CATEGORIES "driver" CACHE INTERNAL "")
set(rkcl-driver-ros_REFERENCES  CACHE INTERNAL "")
