#### referencing package kuka-lwr-knowbotics mode ####
set(kuka-lwr-knowbotics_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(kuka-lwr-knowbotics_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(kuka-lwr-knowbotics_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(kuka-lwr-knowbotics_FRAMEWORK  CACHE INTERNAL "")
set(kuka-lwr-knowbotics_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(kuka-lwr-knowbotics_PROJECT_PAGE  CACHE INTERNAL "")
set(kuka-lwr-knowbotics_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(kuka-lwr-knowbotics_SITE_INTRODUCTION  CACHE INTERNAL "")
set(kuka-lwr-knowbotics_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM);_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(kuka-lwr-knowbotics_DESCRIPTION "A package that describes the Kuka LWR as a Knowbotics object" CACHE INTERNAL "")
set(kuka-lwr-knowbotics_YEARS 2015 CACHE INTERNAL "")
set(kuka-lwr-knowbotics_LICENSE CeCILL-C CACHE INTERNAL "")
set(kuka-lwr-knowbotics_ADDRESS git@gite.lirmm.fr:kuka-lwr/kuka-lwr-knowbotics.git CACHE INTERNAL "")
set(kuka-lwr-knowbotics_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(kuka-lwr-knowbotics_CATEGORIES "arm/kuka-lwr;knowbotics/arm" CACHE INTERNAL "")
set(kuka-lwr-knowbotics_REFERENCES  CACHE INTERNAL "")
