#### referencing package ros-utils mode ####
set(ros-utils_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(ros-utils_MAIN_INSTITUTION _LIRMM_/_CNRS CACHE INTERNAL "")
set(ros-utils_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(ros-utils_FRAMEWORK  CACHE INTERNAL "")
set(ros-utils_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(ros-utils_PROJECT_PAGE  CACHE INTERNAL "")
set(ros-utils_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(ros-utils_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(ros-utils_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM_/_CNRS)" CACHE INTERNAL "")
set(ros-utils_DESCRIPTION "A;set;of;utilities;to;help;interact;with;ROS;from;PID;applications;or;libraries" CACHE INTERNAL "")
set(ros-utils_YEARS 2019 CACHE INTERNAL "")
set(ros-utils_LICENSE CeCILL CACHE INTERNAL "")
set(ros-utils_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/ros-utils.git CACHE INTERNAL "")
set(ros-utils_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/ros-utils.git CACHE INTERNAL "")
set(ros-utils_CATEGORIES CACHE INTERNAL "")
set(ros-utils_REFERENCES  CACHE INTERNAL "")
