#### referencing wrapper of external package catch2 ####
set(catch2_PID_WRAPPER_CONTACT_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(catch2_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(catch2_PID_WRAPPER_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(catch2_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(catch2_PID_WRAPPER_PROJECT_PAGE  CACHE INTERNAL "")
set(catch2_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(catch2_PID_WRAPPER_SITE_INTRODUCTION  CACHE INTERNAL "")
set(catch2_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr)" CACHE INTERNAL "")
set(catch2_PID_WRAPPER_YEARS 2018 CACHE INTERNAL "")
set(catch2_PID_WRAPPER_LICENSE GNULGPL CACHE INTERNAL "")
set(catch2_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:pid/catch2.git CACHE INTERNAL "")
set(catch2_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/catch2.git CACHE INTERNAL "")
set(catch2_DESCRIPTION "A modern, C++-native, header-only, test framework for unit-tests, TDD and BDD" CACHE INTERNAL "")
set(catch2_FRAMEWORK  CACHE INTERNAL "")
set(catch2_CATEGORIES "programming/unit_testing" CACHE INTERNAL "")
set(catch2_AUTHORS "Phil Nash" CACHE INTERNAL "")
set(catch2_PROJECT_SITE https://github.com/catchorg/Catch2 CACHE INTERNAL "")
set(catch2_LICENSES Boost CACHE INTERNAL "")
set(catch2_REFERENCES  CACHE INTERNAL "")
