#### referencing wrapper of external package poco ####
set(poco_PID_WRAPPER_CONTACT_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(poco_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(poco_PID_WRAPPER_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(poco_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(poco_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/pid/wrappers/poco CACHE INTERNAL "")
set(poco_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(poco_PID_WRAPPER_SITE_INTRODUCTION "This;project;is;a;PID;wrapper;for;the;external;project;called;POCO.;It;provides;libraries;for;building;network-;and;internet-based;applications." CACHE INTERNAL "")
set(poco_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr)" CACHE INTERNAL "")
set(poco_PID_WRAPPER_YEARS 2019 CACHE INTERNAL "")
set(poco_PID_WRAPPER_LICENSE CeCILL-C CACHE INTERNAL "")
set(poco_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:pid/wrappers/poco.git CACHE INTERNAL "")
set(poco_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/wrappers/poco.git CACHE INTERNAL "")
set(poco_DESCRIPTION "PID wrapper for the POCO networking framework" CACHE INTERNAL "")
set(poco_FRAMEWORK pid CACHE INTERNAL "")
set(poco_CATEGORIES "programming/network" CACHE INTERNAL "")
set(poco_AUTHORS "Applied Informatics Software Engineering GmbH" CACHE INTERNAL "")
set(poco_PROJECT_SITE https://pocoproject.org CACHE INTERNAL "")
set(poco_LICENSES Boost CACHE INTERNAL "")
set(poco_REFERENCES  CACHE INTERNAL "")
