#### referencing package rbdyn mode ####
set(rbdyn_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(rbdyn_MAIN_INSTITUTION  CACHE INTERNAL "")
set(rbdyn_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(rbdyn_FRAMEWORK  CACHE INTERNAL "")
set(rbdyn_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rbdyn_PROJECT_PAGE  CACHE INTERNAL "")
set(rbdyn_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rbdyn_SITE_INTRODUCTION  CACHE INTERNAL "")
set(rbdyn_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro()" CACHE INTERNAL "")
set(rbdyn_DESCRIPTION PID;version;of;RBDyn:;https://github.com/jrl-umi3218/RBDyn CACHE INTERNAL "")
set(rbdyn_YEARS 2017 CACHE INTERNAL "")
set(rbdyn_LICENSE GNULGPL CACHE INTERNAL "")
set(rbdyn_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/rbdyn.git CACHE INTERNAL "")
set(rbdyn_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/rbdyn.git CACHE INTERNAL "")
set(rbdyn_CATEGORIES CACHE INTERNAL "")
set(rbdyn_REFERENCES  CACHE INTERNAL "")
