#### referencing wrapper of external package dlib ####
set(dlib_PID_WRAPPER_CONTACT_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(dlib_PID_WRAPPER_CONTACT_INSTITUTION _CNRS/LIRMM CACHE INTERNAL "")
set(dlib_PID_WRAPPER_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(dlib_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(dlib_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/pid/wrappers/dlib CACHE INTERNAL "")
set(dlib_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(dlib_PID_WRAPPER_SITE_INTRODUCTION "Dlib is a modern C++ toolkit containing machine learning algorithms and tools for creating complex software in C++ to solve real world problems. It is used in both industry and academia in a wide range of domains including robotics, embedded devices, mobile phones, and large high performance computing environments. Dlib's open source licensing allows you to use it in any application, free of charge." CACHE INTERNAL "")
set(dlib_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_CNRS/LIRMM)" CACHE INTERNAL "")
set(dlib_PID_WRAPPER_YEARS 2019 CACHE INTERNAL "")
set(dlib_PID_WRAPPER_LICENSE CeCILL-C CACHE INTERNAL "")
set(dlib_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:pid/wrappers/dlib.git CACHE INTERNAL "")
set(dlib_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/wrappers/dlib.git CACHE INTERNAL "")
set(dlib_DESCRIPTION "Wrapper;for;DLib;project,;a;modern;C++;toolkit;containing;machine;learning;algorithms;and;tools;for;creating;complex;software;in;C++;to;solve;real;world;problems." CACHE INTERNAL "")
set(dlib_FRAMEWORK pid CACHE INTERNAL "")
set(dlib_CATEGORIES "programming;programming/image;programming/log;programming/meta;programming/gui;programming/operating_system;programming/serialization;testing" CACHE INTERNAL "")
set(dlib_AUTHORS "Davis King and DLib contributors" CACHE INTERNAL "")
set(dlib_PROJECT_SITE http://dlib.net CACHE INTERNAL "")
set(dlib_LICENSES Boost v1 license  CACHE INTERNAL "")
set(dlib_REFERENCES  CACHE INTERNAL "")
