#### referencing package kuka-lwr-driver-fri mode ####
set(kuka-lwr-driver-fri_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(kuka-lwr-driver-fri_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(kuka-lwr-driver-fri_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(kuka-lwr-driver-fri_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM);_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(kuka-lwr-driver-fri_DESCRIPTION Knowbotics API to interface with a real Kuka LWR using the FRI library CACHE INTERNAL "")
set(kuka-lwr-driver-fri_YEARS 2015 CACHE INTERNAL "")
set(kuka-lwr-driver-fri_LICENSE CeCILL-C CACHE INTERNAL "")
set(kuka-lwr-driver-fri_ADDRESS git@gite.lirmm.fr:kuka-lwr/kuka-lwr-driver-fri.git CACHE INTERNAL "")
set(kuka-lwr-driver-fri_CATEGORIES "arm/kuka-lwr" CACHE INTERNAL "")
set(kuka-lwr-driver-fri_REFERENCES  CACHE INTERNAL "")
