#### referencing package hardio_bno055 mode ####
set(hardio_bno055_MAIN_AUTHOR _Charles_Villard CACHE INTERNAL "")
set(hardio_bno055_MAIN_INSTITUTION  CACHE INTERNAL "")
set(hardio_bno055_CONTACT_MAIL  CACHE INTERNAL "")
set(hardio_bno055_FRAMEWORK  CACHE INTERNAL "")
set(hardio_bno055_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(hardio_bno055_PROJECT_PAGE  CACHE INTERNAL "")
set(hardio_bno055_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(hardio_bno055_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(hardio_bno055_AUTHORS_AND_INSTITUTIONS "_Charles_Villard();_Clement_Rebut" CACHE INTERNAL "")
set(hardio_bno055_DESCRIPTION "This;is;the;driver;for;the;IMU;bno055;adafruit" CACHE INTERNAL "")
set(hardio_bno055_YEARS 2018 CACHE INTERNAL "")
set(hardio_bno055_LICENSE CeCILL CACHE INTERNAL "")
set(hardio_bno055_ADDRESS git@gite.lirmm.fr:hardio/devices/hardio_bno055.git CACHE INTERNAL "")
set(hardio_bno055_PUBLIC_ADDRESS https://gite.lirmm.fr/hardio/devices/hardio_bno055.git CACHE INTERNAL "")
set(hardio_bno055_CATEGORIES CACHE INTERNAL "")
set(hardio_bno055_REFERENCES  CACHE INTERNAL "")
