#### referencing wrapper of external package caffe ####
set(caffe_PID_WRAPPER_CONTACT_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(caffe_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM CACHE INTERNAL "")
set(caffe_PID_WRAPPER_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(caffe_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(caffe_PID_WRAPPER_PROJECT_PAGE  CACHE INTERNAL "")
set(caffe_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(caffe_PID_WRAPPER_SITE_INTRODUCTION  CACHE INTERNAL "")
set(caffe_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_CNRS_/_LIRMM)" CACHE INTERNAL "")
set(caffe_PID_WRAPPER_YEARS 2019 CACHE INTERNAL "")
set(caffe_PID_WRAPPER_LICENSE CeCILL-C CACHE INTERNAL "")
set(caffe_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:rob-vision/rob-deep-perception/wrappers/caffe.git CACHE INTERNAL "")
set(caffe_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-vision/rob-deep-perception/wrappers/caffe.git CACHE INTERNAL "")
set(caffe_DESCRIPTION "Wrapper for the caffe project, a framework for programming deep learning algorithms" CACHE INTERNAL "")
set(caffe_FRAMEWORK  CACHE INTERNAL "")
set(caffe_CATEGORIES CACHE INTERNAL "")
set(caffe_AUTHORS "Berkeley Artificial Intelligence Researh (BAIR) Group" CACHE INTERNAL "")
set(caffe_PROJECT_SITE http://caffe.berkeleyvision.org/ CACHE INTERNAL "")
set(caffe_LICENSES openpose license CACHE INTERNAL "")
set(caffe_REFERENCES  CACHE INTERNAL "")
