#### referencing wrapper of external package open-igtlink-io ####
set(open-igtlink-io_PID_WRAPPER_CONTACT_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(open-igtlink-io_PID_WRAPPER_CONTACT_INSTITUTION _CNRS/LIRMM CACHE INTERNAL "")
set(open-igtlink-io_PID_WRAPPER_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(open-igtlink-io_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(open-igtlink-io_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/robmed/devices/open-igtlink-io CACHE INTERNAL "")
set(open-igtlink-io_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(open-igtlink-io_PID_WRAPPER_SITE_INTRODUCTION "open-igtlink-io;is;a;PID;wrapper;for;the;project;called;OpenIGTLinkIO.;OpenIGTLinkIO;contains;several;wrapper;layers;on;top;of;OpenIGTLink.;The;code;originates;from;OpenIGTLink/OpenIGTLinkIF.;The;main;intent;of;the;library;is;to;share;igtl;code;between;Slicer,;CustusX,;IBIS,;MITK;and;other;systems." CACHE INTERNAL "")
set(open-igtlink-io_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_CNRS/LIRMM)" CACHE INTERNAL "")
set(open-igtlink-io_PID_WRAPPER_YEARS 2019 CACHE INTERNAL "")
set(open-igtlink-io_PID_WRAPPER_LICENSE CeCILL-C CACHE INTERNAL "")
set(open-igtlink-io_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:robmed/devices/open-igtlink-io.git CACHE INTERNAL "")
set(open-igtlink-io_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/robmed/devices/open-igtlink-io.git CACHE INTERNAL "")
set(open-igtlink-io_DESCRIPTION "free,;open-source;library;utility;library;for;openigtlink." CACHE INTERNAL "")
set(open-igtlink-io_FRAMEWORK rpc CACHE INTERNAL "")
set(open-igtlink-io_CATEGORIES "driver/sensor/vision" CACHE INTERNAL "")
set(open-igtlink-io_AUTHORS "Library for interfacing to openigtlink/OpenIGTLink, dependent on VTK and Qt. Based on openigtlink/OpenIGTLinkIF" CACHE INTERNAL "")
set(open-igtlink-io_PROJECT_SITE https://github.com/IGSIO/OpenIGTLinkIO CACHE INTERNAL "")
set(open-igtlink-io_LICENSES Apache 2.0  CACHE INTERNAL "")
set(open-igtlink-io_REFERENCES  CACHE INTERNAL "")
