#### referencing wrapper of external package fmt ####
set(fmt_PID_WRAPPER_CONTACT_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(fmt_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(fmt_PID_WRAPPER_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(fmt_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(fmt_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/pid/wrappers/fmt CACHE INTERNAL "")
set(fmt_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(fmt_PID_WRAPPER_SITE_INTRODUCTION "this project is a PID wrapper for external project called fmy. fmt is an open-source formatting library for C++." CACHE INTERNAL "")
set(fmt_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr)" CACHE INTERNAL "")
set(fmt_PID_WRAPPER_YEARS 2019 CACHE INTERNAL "")
set(fmt_PID_WRAPPER_LICENSE MIT CACHE INTERNAL "")
set(fmt_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:pid/wrappers/fmt.git CACHE INTERNAL "")
set(fmt_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/wrappers/fmt.git CACHE INTERNAL "")
set(fmt_DESCRIPTION "wrapper of the {fmt} project, an open-source formatting library for C++." CACHE INTERNAL "")
set(fmt_FRAMEWORK pid CACHE INTERNAL "")
set(fmt_CATEGORIES "programming/parser" CACHE INTERNAL "")
set(fmt_AUTHORS "Victor Zverovich and contributors" CACHE INTERNAL "")
set(fmt_PROJECT_SITE https://github.com/fmtlib/fmt CACHE INTERNAL "")
set(fmt_LICENSES MIT License CACHE INTERNAL "")
set(fmt_REFERENCES  CACHE INTERNAL "")
