#### referencing package waterdetect mode ####
set(waterdetect_MAIN_AUTHOR _Charles_Villard CACHE INTERNAL "")
set(waterdetect_MAIN_INSTITUTION  CACHE INTERNAL "")
set(waterdetect_CONTACT_MAIL  CACHE INTERNAL "")
set(waterdetect_FRAMEWORK  CACHE INTERNAL "")
set(waterdetect_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(waterdetect_PROJECT_PAGE  CACHE INTERNAL "")
set(waterdetect_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(waterdetect_SITE_INTRODUCTION  CACHE INTERNAL "")
set(waterdetect_AUTHORS_AND_INSTITUTIONS "_Charles_Villard()" CACHE INTERNAL "")
set(waterdetect_DESCRIPTION "This;is;the;driver;of;the;water;entry;detection" CACHE INTERNAL "")
set(waterdetect_YEARS 2018 CACHE INTERNAL "")
set(waterdetect_LICENSE CeCILL CACHE INTERNAL "")
set(waterdetect_ADDRESS git@gite.lirmm.fr:explore-rov/Drivers/waterdetect.git CACHE INTERNAL "")
set(waterdetect_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(waterdetect_CATEGORIES CACHE INTERNAL "")
set(waterdetect_REFERENCES  CACHE INTERNAL "")
