#### referencing package robotics-library mode ####
set(robotics-library_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(robotics-library_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(robotics-library_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(robotics-library_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(robotics-library_DESCRIPTION PID wrapper for Robotics Library CACHE INTERNAL "")
set(robotics-library_YEARS 2015 CACHE INTERNAL "")
set(robotics-library_LICENSE CeCILL-C CACHE INTERNAL "")
set(robotics-library_ADDRESS git@gite.lirmm.fr:pid_external_deps/robotics-library.git CACHE INTERNAL "")
set(robotics-library_CATEGORIES motion/trajectory CACHE INTERNAL "")
set(robotics-library_REFERENCES  CACHE INTERNAL "")
