#### referencing wrapper of external package cli11 ####
set(cli11_PID_WRAPPER_CONTACT_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(cli11_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(cli11_PID_WRAPPER_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(cli11_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(cli11_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/pid/wrappers/cli11 CACHE INTERNAL "")
set(cli11_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(cli11_PID_WRAPPER_SITE_INTRODUCTION "This project is a PID wrapper for external project called CLI11. This is a command line parser for C++11 and beyond that provides a rich feature set with a simple and intuitive interface" CACHE INTERNAL "")
set(cli11_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr)" CACHE INTERNAL "")
set(cli11_PID_WRAPPER_YEARS 2019 CACHE INTERNAL "")
set(cli11_PID_WRAPPER_LICENSE GNULGPL CACHE INTERNAL "")
set(cli11_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:pid/wrappers/cli11.git CACHE INTERNAL "")
set(cli11_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/wrappers/cli11.git CACHE INTERNAL "")
set(cli11_DESCRIPTION "CLI11 is a command line parser for C++11 and beyond that provides a rich feature set with a simple and intuitive interface" CACHE INTERNAL "")
set(cli11_FRAMEWORK pid CACHE INTERNAL "")
set(cli11_CATEGORIES "programming/parser" CACHE INTERNAL "")
set(cli11_AUTHORS "Henry Schreiner and other contributors" CACHE INTERNAL "")
set(cli11_PROJECT_SITE https://github.com/CLIUtils/CLI11 CACHE INTERNAL "")
set(cli11_LICENSES MIT CACHE INTERNAL "")
set(cli11_REFERENCES  CACHE INTERNAL "")
