#### referencing framework rpc mode ####
set(rpc_FRAMEWORK_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(rpc_FRAMEWORK_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(rpc_FRAMEWORK_YEARS 2019 CACHE INTERNAL "")
set(rpc_FRAMEWORK_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(rpc_FRAMEWORK_SITE http://rob-miscellaneous.lirmm.net/rpc-framework/ CACHE INTERNAL "")
set(rpc_FRAMEWORK_PROJECT_PAGE https://gite.lirmm.fr/rob-vision/rob-deep-perception/rdp-framework CACHE INTERNAL "")
set(rpc_FRAMEWORK_DESCRIPTION RDP is a framework implementing deep learning approaches for robot perception. CACHE INTERNAL "")
set(rpc_FRAMEWORK_LICENSE CeCILL-C CACHE INTERNAL "")
set(rpc_FRAMEWORK_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/rpc-framework.git CACHE INTERNAL "")
set(rpc_FRAMEWORK_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(rpc_FRAMEWORK_CATEGORIES "driver;driver/robot;driver/sensor;simulator;simulator/robot;simulator/sensor;algorithm;algorithm/control;algorithm/signal;algorithm/navigation;algorithm/optimization" CACHE INTERNAL "")
