#### referencing package flir-sdk mode ####
set(flir-sdk_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(flir-sdk_MAIN_INSTITUTION _LIRMM_/_CNRS CACHE INTERNAL "")
set(flir-sdk_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(flir-sdk_FRAMEWORK  CACHE INTERNAL "")
set(flir-sdk_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(flir-sdk_PROJECT_PAGE  CACHE INTERNAL "")
set(flir-sdk_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(flir-sdk_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(flir-sdk_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM_/_CNRS)" CACHE INTERNAL "")
set(flir-sdk_DESCRIPTION "SDK;to;control;the;FLIR;pan-tilt;units;plus;a;C++;wrapper" CACHE INTERNAL "")
set(flir-sdk_YEARS 2019 CACHE INTERNAL "")
set(flir-sdk_LICENSE CSRU CACHE INTERNAL "")
set(flir-sdk_ADDRESS git@gite.lirmm.fr:rob-vision-devices/flir-sdk.git CACHE INTERNAL "")
set(flir-sdk_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(flir-sdk_CATEGORIES CACHE INTERNAL "")
set(flir-sdk_REFERENCES  CACHE INTERNAL "")
