#### referencing wrapper of external package flatbuffers ####
set(flatbuffers_PID_WRAPPER_CONTACT_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(flatbuffers_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(flatbuffers_PID_WRAPPER_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(flatbuffers_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(flatbuffers_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/pid/wrappers/flatbuffers CACHE INTERNAL "")
set(flatbuffers_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(flatbuffers_PID_WRAPPER_SITE_INTRODUCTION PID wrapper for the flatbuffers library. flatbuffers is a memory efficient serialization library. CACHE INTERNAL "")
set(flatbuffers_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr)" CACHE INTERNAL "")
set(flatbuffers_PID_WRAPPER_YEARS 2018 CACHE INTERNAL "")
set(flatbuffers_PID_WRAPPER_LICENSE GNULGPL CACHE INTERNAL "")
set(flatbuffers_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:pid/wrappers/flatbuffers.git CACHE INTERNAL "")
set(flatbuffers_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/wrappers/flatbuffers.git CACHE INTERNAL "")
set(flatbuffers_DESCRIPTION "flatbuffers is a memory efficient serialization library." CACHE INTERNAL "")
set(flatbuffers_FRAMEWORK pid CACHE INTERNAL "")
set(flatbuffers_CATEGORIES "programming/serialization" CACHE INTERNAL "")
set(flatbuffers_AUTHORS "Wouter van Oortmerssen and other contributors" CACHE INTERNAL "")
set(flatbuffers_PROJECT_SITE https://github.com/google/flatbuffers CACHE INTERNAL "")
set(flatbuffers_LICENSES Apache-2.0 CACHE INTERNAL "")
set(flatbuffers_REFERENCES  CACHE INTERNAL "")
