#### referencing environment raspberry_pi3b_explore mode ####
set(raspberry_pi3b_explore_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(raspberry_pi3b_explore_MAIN_INSTITUTION _CNRS/LIRMM CACHE INTERNAL "")
set(raspberry_pi3b_explore_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_CNRS/LIRMM)" CACHE INTERNAL "")
set(raspberry_pi3b_explore_YEARS 2019 CACHE INTERNAL "")
set(raspberry_pi3b_explore_CONTACT_MAIL robin.passama@lirmm.fr CACHE INTERNAL "")
set(raspberry_pi3b_explore_ADDRESS git@gite.lirmm.fr:pid/environments/raspberry_pi3b_explore.git CACHE INTERNAL "")
set(raspberry_pi3b_explore_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/environments/raspberry_pi3b_explore.git CACHE INTERNAL "")
set(raspberry_pi3b_explore_LICENSE CeCILL-C CACHE INTERNAL "")
set(raspberry_pi3b_explore_DESCRIPTION The environment describing the raspberry Pi 3 Model B+ used by EXPLORE team CACHE INTERNAL "")
