#### referencing package hardio_waterdetect mode ####
set(hardio_waterdetect_MAIN_AUTHOR _Charles_Villard CACHE INTERNAL "")
set(hardio_waterdetect_MAIN_INSTITUTION  CACHE INTERNAL "")
set(hardio_waterdetect_CONTACT_MAIL  CACHE INTERNAL "")
set(hardio_waterdetect_FRAMEWORK  CACHE INTERNAL "")
set(hardio_waterdetect_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(hardio_waterdetect_PROJECT_PAGE  CACHE INTERNAL "")
set(hardio_waterdetect_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(hardio_waterdetect_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(hardio_waterdetect_AUTHORS_AND_INSTITUTIONS "_Charles_Villard();_Clement_Rebut" CACHE INTERNAL "")
set(hardio_waterdetect_DESCRIPTION "This;is;the;driver;of;the;water;entry;detection" CACHE INTERNAL "")
set(hardio_waterdetect_YEARS 2018 CACHE INTERNAL "")
set(hardio_waterdetect_LICENSE CeCILL CACHE INTERNAL "")
set(hardio_waterdetect_ADDRESS git@gite.lirmm.fr:hardio/devices/hardio_waterdetect.git CACHE INTERNAL "")
set(hardio_waterdetect_PUBLIC_ADDRESS https://gite.lirmm.fr/hardio/devices/hardio_waterdetect.git CACHE INTERNAL "")
set(hardio_waterdetect_CATEGORIES CACHE INTERNAL "")
set(hardio_waterdetect_REFERENCES  CACHE INTERNAL "")
