#### referencing package virtuose mode ####
set(virtuose_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(virtuose_MAIN_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(virtuose_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(virtuose_FRAMEWORK  CACHE INTERNAL "")
set(virtuose_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(virtuose_PROJECT_PAGE  CACHE INTERNAL "")
set(virtuose_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(virtuose_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(virtuose_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr)" CACHE INTERNAL "")
set(virtuose_DESCRIPTION "C++;wrapper;for;the;original;virtuose;C;API" CACHE INTERNAL "")
set(virtuose_YEARS 2020 CACHE INTERNAL "")
set(virtuose_LICENSE CeCILL CACHE INTERNAL "")
set(virtuose_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/drivers/virtuose.git CACHE INTERNAL "")
set(virtuose_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(virtuose_CATEGORIES CACHE INTERNAL "")
set(virtuose_REFERENCES  CACHE INTERNAL "")
