#### referencing package rkcl-ati-force-sensor-driver mode ####
set(rkcl-ati-force-sensor-driver_MAIN_AUTHOR _Sonny_Tarbouriech CACHE INTERNAL "")
set(rkcl-ati-force-sensor-driver_MAIN_INSTITUTION _Tecnalia CACHE INTERNAL "")
set(rkcl-ati-force-sensor-driver_CONTACT_MAIL  CACHE INTERNAL "")
set(rkcl-ati-force-sensor-driver_FRAMEWORK  CACHE INTERNAL "")
set(rkcl-ati-force-sensor-driver_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rkcl-ati-force-sensor-driver_PROJECT_PAGE  CACHE INTERNAL "")
set(rkcl-ati-force-sensor-driver_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rkcl-ati-force-sensor-driver_SITE_INTRODUCTION  CACHE INTERNAL "")
set(rkcl-ati-force-sensor-driver_AUTHORS_AND_INSTITUTIONS "_Sonny_Tarbouriech(_Tecnalia);_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(rkcl-ati-force-sensor-driver_DESCRIPTION "TODO:;input;a;short;description;of;package;rkcl-ati-force-sensor-driver;utility;here" CACHE INTERNAL "")
set(rkcl-ati-force-sensor-driver_YEARS 2019 CACHE INTERNAL "")
set(rkcl-ati-force-sensor-driver_LICENSE CeCILL CACHE INTERNAL "")
set(rkcl-ati-force-sensor-driver_ADDRESS git@gitlab.com:rkcl/rkcl-ati-force-sensor-driver.git CACHE INTERNAL "")
set(rkcl-ati-force-sensor-driver_PUBLIC_ADDRESS https://gitlab.com/rkcl/rkcl-ati-force-sensor-driver.git CACHE INTERNAL "")
set(rkcl-ati-force-sensor-driver_CATEGORIES CACHE INTERNAL "")
set(rkcl-ati-force-sensor-driver_REFERENCES  CACHE INTERNAL "")
