#### referencing package the-testpack-a mode ####
set(the-testpack-a_MAIN_AUTHOR _Robin_Passama_INSTITUION_LIRMM CACHE INTERNAL "")
set(the-testpack-a_MAIN_INSTITUTION  CACHE INTERNAL "")
set(the-testpack-a_AUTHORS_AND_INSTITUTIONS _Robin_Passama_INSTITUION_LIRMM() CACHE INTERNAL "")
set(the-testpack-a_DESCRIPTION test;package;for;PID CACHE INTERNAL "")
set(the-testpack-a_YEARS 2013 CACHE INTERNAL "")
set(the-testpack-a_LICENSE CeCILL CACHE INTERNAL "")
set(the-testpack-a_ADDRESS git@idh.lirmm.fr:perso/passama/the-testpack-a.git CACHE INTERNAL "")
set(the-testpack-a_CATEGORIES toto/titi;ffffffffffffff CACHE INTERNAL "")
set(the-testpack-a_REFERENCES 0.4.2;1.6.0 CACHE INTERNAL "")
set(the-testpack-a_REFERENCE_0.4.2 linux CACHE INTERNAL "")
set(the-testpack-a_REFERENCE_0.4.2_linux http://lirmm.lirmm.fr/FileX/get?auto=1&k=a600abhRHflFFI8jWem CACHE INTERNAL "")
set(the-testpack-a_REFERENCE_0.4.2_linux_DEBUG http://lirmm.lirmm.fr/FileX/get?auto=1&k=LCZpDG4pc2zv0cTE1ui CACHE INTERNAL "")
set(the-testpack-a_REFERENCE_1.6.0 linux CACHE INTERNAL "")
set(the-testpack-a_REFERENCE_1.6.0_linux http://lirmm.lirmm.fr/FileX/get?auto=1&k=duggvR4jNpel0kzzlpg CACHE INTERNAL "")
set(the-testpack-a_REFERENCE_1.6.0_linux_DEBUG http://lirmm.lirmm.fr/FileX/get?auto=1&k=kVoomuLXS7L3UGPaits CACHE INTERNAL "")
