#### referencing wrapper of external package nanomsgxx ####
set(nanomsgxx_PID_WRAPPER_CONTACT_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(nanomsgxx_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(nanomsgxx_PID_WRAPPER_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(nanomsgxx_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(nanomsgxx_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/pid/nanomsgxx CACHE INTERNAL "")
set(nanomsgxx_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(nanomsgxx_PID_WRAPPER_SITE_INTRODUCTION nanomsgxx;is;a;binding;of;the;nanomsg;library;for;C++11. CACHE INTERNAL "")
set(nanomsgxx_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr)" CACHE INTERNAL "")
set(nanomsgxx_PID_WRAPPER_YEARS 2018 CACHE INTERNAL "")
set(nanomsgxx_PID_WRAPPER_LICENSE GNULGPL CACHE INTERNAL "")
set(nanomsgxx_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:pid/nanomsgxx.git CACHE INTERNAL "")
set(nanomsgxx_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/nanomsgxx.git CACHE INTERNAL "")
set(nanomsgxx_DESCRIPTION "nanomsgxx;is;a;binding;of;the;nanomsg;library;for;C++11.;Repackaged;for;PID." CACHE INTERNAL "")
set(nanomsgxx_FRAMEWORK pid CACHE INTERNAL "")
set(nanomsgxx_CATEGORIES "programming/network" CACHE INTERNAL "")
set(nanomsgxx_AUTHORS "Achille Roussel and other contributors" CACHE INTERNAL "")
set(nanomsgxx_PROJECT_SITE https://github.com/achille-roussel/nanomsgxx CACHE INTERNAL "")
set(nanomsgxx_LICENSES MIT CACHE INTERNAL "")
set(nanomsgxx_REFERENCES  CACHE INTERNAL "")
