#### referencing package config mode ####
set(config_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(config_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(config_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(config_AUTHORS_AND_INSTITUTIONS ; "_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(config_DESCRIPTION set of libraries and tools used to manage configuration of programs and libraries using configuration files CACHE INTERNAL "")
set(config_YEARS 2014 CACHE INTERNAL "")
set(config_LICENSE CeCILL-C CACHE INTERNAL "")
set(config_ADDRESS git@rob-dev.lirmm.fr:pid/config.git CACHE INTERNAL "")
set(config_CATEGORIES  CACHE INTERNAL "")
set(config_REFERENCES  CACHE INTERNAL "")
