#### referencing package cobot-arm-visual-servoing mode ####
set(cobot-arm-visual-servoing_MAIN_AUTHOR _Andrea_Cherubini CACHE INTERNAL "")
set(cobot-arm-visual-servoing_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(cobot-arm-visual-servoing_CONTACT_MAIL cherubini@lirmm.fr CACHE INTERNAL "")
set(cobot-arm-visual-servoing_AUTHORS_AND_INSTITUTIONS "_Andrea_Cherubini(_LIRMM);_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(cobot-arm-visual-servoing_DESCRIPTION Visual servoing code using kuka LWR robot and shadow hands CACHE INTERNAL "")
set(cobot-arm-visual-servoing_YEARS 2015 CACHE INTERNAL "")
set(cobot-arm-visual-servoing_LICENSE CeCILL-C CACHE INTERNAL "")
set(cobot-arm-visual-servoing_ADDRESS git@gite.lirmm.fr:cobot/cobot-arm-visual-servoing.git CACHE INTERNAL "")
set(cobot-arm-visual-servoing_CATEGORIES "arm/kuka-lwr;vision" CACHE INTERNAL "")
set(cobot-arm-visual-servoing_AVAILABLE_PLATFORMS linux64cxx11;linux64;linux32;macosx64 CACHE INTERNAL "")
set(cobot-arm-visual-servoing_AVAILABLE_PLATFORM_linux64cxx11_OS linux CACHE INTERNAL "")
set(cobot-arm-visual-servoing_AVAILABLE_PLATFORM_linux64cxx11_ARCH 64 CACHE INTERNAL "")
set(cobot-arm-visual-servoing_AVAILABLE_PLATFORM_linux64cxx11_ABI CXX11 CACHE INTERNAL "")
set(cobot-arm-visual-servoing_AVAILABLE_PLATFORM_linux64cxx11_CONFIGURATION  CACHE INTERNAL "")
set(cobot-arm-visual-servoing_AVAILABLE_PLATFORM_linux64_OS linux CACHE INTERNAL "")
set(cobot-arm-visual-servoing_AVAILABLE_PLATFORM_linux64_ARCH 64 CACHE INTERNAL "")
set(cobot-arm-visual-servoing_AVAILABLE_PLATFORM_linux64_ABI CXX CACHE INTERNAL "")
set(cobot-arm-visual-servoing_AVAILABLE_PLATFORM_linux64_CONFIGURATION  CACHE INTERNAL "")
set(cobot-arm-visual-servoing_AVAILABLE_PLATFORM_linux32_OS linux CACHE INTERNAL "")
set(cobot-arm-visual-servoing_AVAILABLE_PLATFORM_linux32_ARCH 32 CACHE INTERNAL "")
set(cobot-arm-visual-servoing_AVAILABLE_PLATFORM_linux32_ABI CXX CACHE INTERNAL "")
set(cobot-arm-visual-servoing_AVAILABLE_PLATFORM_linux32_CONFIGURATION  CACHE INTERNAL "")
set(cobot-arm-visual-servoing_AVAILABLE_PLATFORM_macosx64_OS macosx CACHE INTERNAL "")
set(cobot-arm-visual-servoing_AVAILABLE_PLATFORM_macosx64_ARCH 64 CACHE INTERNAL "")
set(cobot-arm-visual-servoing_AVAILABLE_PLATFORM_macosx64_ABI CXX CACHE INTERNAL "")
set(cobot-arm-visual-servoing_AVAILABLE_PLATFORM_macosx64_CONFIGURATION  CACHE INTERNAL "")
set(cobot-arm-visual-servoing_REFERENCES  CACHE INTERNAL "")
