#### referencing package pid-network-utilities mode ####
set(pid-network-utilities_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(pid-network-utilities_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(pid-network-utilities_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(pid-network-utilities_FRAMEWORK pid CACHE INTERNAL "")
set(pid-network-utilities_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(pid-network-utilities_PROJECT_PAGE https://gite.lirmm.fr/pid/pid-network-utilities CACHE INTERNAL "")
set(pid-network-utilities_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(pid-network-utilities_SITE_INTRODUCTION pid-network-utilities;is;a;package;providing;a;APIs;to;ease;the;coding;of;simple;network;protocols;like;UDP,;TCP,;etc.;It;is;based;on;boost;asio. CACHE INTERNAL "")
set(pid-network-utilities_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM);_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(pid-network-utilities_DESCRIPTION A package providing libraries to standardize and ease the implementation of network protocol. CACHE INTERNAL "")
set(pid-network-utilities_YEARS 2016 CACHE INTERNAL "")
set(pid-network-utilities_LICENSE CeCILL-C CACHE INTERNAL "")
set(pid-network-utilities_ADDRESS git@gite.lirmm.fr:pid/pid-network-utilities.git CACHE INTERNAL "")
set(pid-network-utilities_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/pid-network-utilities.git CACHE INTERNAL "")
set(pid-network-utilities_CATEGORIES "programming/operating_system" CACHE INTERNAL "")
set(pid-network-utilities_REFERENCES  CACHE INTERNAL "")
