#### referencing package omni-tentacles-based-navigation mode ####
set(omni-tentacles-based-navigation_MAIN_AUTHOR _Abdellah_Khelloufi CACHE INTERNAL "")
set(omni-tentacles-based-navigation_MAIN_INSTITUTION _CDTA CACHE INTERNAL "")
set(omni-tentacles-based-navigation_CONTACT_MAIL  CACHE INTERNAL "")
set(omni-tentacles-based-navigation_FRAMEWORK  CACHE INTERNAL "")
set(omni-tentacles-based-navigation_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(omni-tentacles-based-navigation_PROJECT_PAGE  CACHE INTERNAL "")
set(omni-tentacles-based-navigation_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(omni-tentacles-based-navigation_SITE_INTRODUCTION  CACHE INTERNAL "")
set(omni-tentacles-based-navigation_AUTHORS_AND_INSTITUTIONS "_Abdellah_Khelloufi(_CDTA);_Mohamed_Haijoubi(_LIRMM);_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(omni-tentacles-based-navigation_DESCRIPTION "navigation task Implementation using the omni tentacles approach " CACHE INTERNAL "")
set(omni-tentacles-based-navigation_YEARS 2017 CACHE INTERNAL "")
set(omni-tentacles-based-navigation_LICENSE CeCILL CACHE INTERNAL "")
set(omni-tentacles-based-navigation_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/omni-tentacles-based-navigation.git CACHE INTERNAL "")
set(omni-tentacles-based-navigation_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(omni-tentacles-based-navigation_CATEGORIES "mobile-robot/modified-youbot;mobile-robot/simulated;knowbotics/mobile-robot;simulator/vrep" CACHE INTERNAL "")
set(omni-tentacles-based-navigation_REFERENCES  CACHE INTERNAL "")
