#### referencing package pid-log mode ####
set(pid-log_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(pid-log_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(pid-log_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(pid-log_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(pid-log_DESCRIPTION A package that defines libraries to easily manage logging CACHE INTERNAL "")
set(pid-log_YEARS 2014 CACHE INTERNAL "")
set(pid-log_LICENSE CeCILL-C CACHE INTERNAL "")
set(pid-log_ADDRESS git@gite.lirmm.fr:pid/pid-log.git CACHE INTERNAL "")
set(pid-log_CATEGORIES "programming/log" CACHE INTERNAL "")
set(pid-log_REFERENCES  CACHE INTERNAL "")
