#### referencing wrapper of external package json ####
set(json_PID_WRAPPER_CONTACT_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(json_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(json_PID_WRAPPER_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(json_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(json_PID_WRAPPER_PROJECT_PAGE  CACHE INTERNAL "")
set(json_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(json_PID_WRAPPER_SITE_INTRODUCTION  CACHE INTERNAL "")
set(json_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr);_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(json_PID_WRAPPER_YEARS 2018 CACHE INTERNAL "")
set(json_PID_WRAPPER_LICENSE MIT CACHE INTERNAL "")
set(json_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:pid/json.git CACHE INTERNAL "")
set(json_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/json.git CACHE INTERNAL "")
set(json_DESCRIPTION "JSON for Modern C++, a C++11 header-only JSON class, repackaged for PID" CACHE INTERNAL "")
set(json_FRAMEWORK  CACHE INTERNAL "")
set(json_CATEGORIES "programming/configuration" CACHE INTERNAL "")
set(json_AUTHORS "Niels Lohmann and other contributors" CACHE INTERNAL "")
set(json_PROJECT_SITE https://github.com/nlohmann/json CACHE INTERNAL "")
set(json_LICENSES MIT License CACHE INTERNAL "")
set(json_REFERENCES  CACHE INTERNAL "")
