#### referencing wrapper of external package atracsys-fusiontrack ####
set(atracsys-fusiontrack_PID_WRAPPER_CONTACT_AUTHOR _Pierre_Chatellier CACHE INTERNAL "")
set(atracsys-fusiontrack_PID_WRAPPER_CONTACT_INSTITUTION  CACHE INTERNAL "")
set(atracsys-fusiontrack_PID_WRAPPER_CONTACT_MAIL  CACHE INTERNAL "")
set(atracsys-fusiontrack_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(atracsys-fusiontrack_PID_WRAPPER_PROJECT_PAGE  CACHE INTERNAL "")
set(atracsys-fusiontrack_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(atracsys-fusiontrack_PID_WRAPPER_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(atracsys-fusiontrack_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Pierre_Chatellier()" CACHE INTERNAL "")
set(atracsys-fusiontrack_PID_WRAPPER_YEARS 2019 CACHE INTERNAL "")
set(atracsys-fusiontrack_PID_WRAPPER_LICENSE CeCILL-C CACHE INTERNAL "")
set(atracsys-fusiontrack_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:robmed/devices/atracsys-fusiontrack.git CACHE INTERNAL "")
set(atracsys-fusiontrack_PID_WRAPPER_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(atracsys-fusiontrack_DESCRIPTION "Wrapper For Atracsys fusiontrack localization system." CACHE INTERNAL "")
set(atracsys-fusiontrack_FRAMEWORK  CACHE INTERNAL "")
set(atracsys-fusiontrack_CATEGORIES CACHE INTERNAL "")
set(atracsys-fusiontrack_AUTHORS "" CACHE INTERNAL "")
set(atracsys-fusiontrack_PROJECT_SITE  CACHE INTERNAL "")
set(atracsys-fusiontrack_LICENSES  CACHE INTERNAL "")
set(atracsys-fusiontrack_REFERENCES  CACHE INTERNAL "")
