#### referencing package trajectory-generators-knowbotics mode ####
set(trajectory-generators-knowbotics_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(trajectory-generators-knowbotics_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(trajectory-generators-knowbotics_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(trajectory-generators-knowbotics_FRAMEWORK  CACHE INTERNAL "")
set(trajectory-generators-knowbotics_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(trajectory-generators-knowbotics_PROJECT_PAGE  CACHE INTERNAL "")
set(trajectory-generators-knowbotics_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(trajectory-generators-knowbotics_SITE_INTRODUCTION  CACHE INTERNAL "")
set(trajectory-generators-knowbotics_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM);_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(trajectory-generators-knowbotics_DESCRIPTION "Online and offline trajectory generators for Knowbotics" CACHE INTERNAL "")
set(trajectory-generators-knowbotics_YEARS 2018 CACHE INTERNAL "")
set(trajectory-generators-knowbotics_LICENSE CeCILL-C CACHE INTERNAL "")
set(trajectory-generators-knowbotics_ADDRESS git@gite.lirmm.fr:knowbotics/trajectory-generators-knowbotics.git CACHE INTERNAL "")
set(trajectory-generators-knowbotics_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(trajectory-generators-knowbotics_CATEGORIES "knowbotics/trajectory" CACHE INTERNAL "")
set(trajectory-generators-knowbotics_REFERENCES  CACHE INTERNAL "")
