#### referencing package ethercatcpp-assist mode ####
set(ethercatcpp-assist_MAIN_AUTHOR _Meline_Arnaud CACHE INTERNAL "")
set(ethercatcpp-assist_MAIN_INSTITUTION  CACHE INTERNAL "")
set(ethercatcpp-assist_CONTACT_MAIL meline@lirmm.fr CACHE INTERNAL "")
set(ethercatcpp-assist_FRAMEWORK ethercatcpp CACHE INTERNAL "")
set(ethercatcpp-assist_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(ethercatcpp-assist_PROJECT_PAGE https://gite.lirmm.fr/ethercatcpp/ethercatcpp-assist CACHE INTERNAL "")
set(ethercatcpp-assist_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(ethercatcpp-assist_SITE_INTRODUCTION ethercatcpp-assist;is;a;package;providing;the;ethercat;driver;for;assist;robot. CACHE INTERNAL "")
set(ethercatcpp-assist_AUTHORS_AND_INSTITUTIONS "_Meline_Arnaud()" CACHE INTERNAL "")
set(ethercatcpp-assist_DESCRIPTION "ethercat driver library for ASSIST robot" CACHE INTERNAL "")
set(ethercatcpp-assist_YEARS 2018 CACHE INTERNAL "")
set(ethercatcpp-assist_LICENSE CeCILL-C CACHE INTERNAL "")
set(ethercatcpp-assist_ADDRESS git@gite.lirmm.fr:ethercatcpp/ethercatcpp-assist.git CACHE INTERNAL "")
set(ethercatcpp-assist_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(ethercatcpp-assist_CATEGORIES "ethercat/robot" CACHE INTERNAL "")
set(ethercatcpp-assist_REFERENCES  CACHE INTERNAL "")
