#### referencing package ethercatcpp mode ####
set(ethercatcpp_FRAMEWORK_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(ethercatcpp_FRAMEWORK_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(ethercatcpp_FRAMEWORK_YEARS 2018 CACHE INTERNAL "")
set(ethercatcpp_FRAMEWORK_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(ethercatcpp_FRAMEWORK_SITE http://ethercatcpp.lirmm.net/ethercatcpp-framework CACHE INTERNAL "")
set(ethercatcpp_FRAMEWORK_PROJECT_PAGE https://gite.lirmm.fr/ethercatcpp/ethercatcpp-framework CACHE INTERNAL "")
set(ethercatcpp_FRAMEWORK_DESCRIPTION Framework grouping all projects related to the use of ethercatcpp based libraries. It provides drivers for various ethercat devices as weel as a mechanism to define new ethercat drivers. CACHE INTERNAL "")
set(ethercatcpp_FRAMEWORK_LICENSE CeCILL-C CACHE INTERNAL "")
set(ethercatcpp_FRAMEWORK_ADDRESS git@gite.lirmm.fr:ethercatcpp/ethercatcpp-framework.git CACHE INTERNAL "")
set(ethercatcpp_FRAMEWORK_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM);_Arnaud_Meline(_LIRMM)" CACHE INTERNAL "")
set(ethercatcpp_FRAMEWORK_CATEGORIES "ethercat;ethercat/network_device;ethercat/sensor;ethercat/actuator;ethercat/robot;ethercat/actuator/drive;ethercat/sensor/encoder;ethercat/sensor/force_sensor" CACHE INTERNAL "")
