#### referencing package logging mode ####
set(logging_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(logging_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(logging_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(logging_AUTHORS_AND_INSTITUTIONS ; "_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(logging_DESCRIPTION A package that defines libraries to easily manage logging CACHE INTERNAL "")
set(logging_YEARS 2014 CACHE INTERNAL "")
set(logging_LICENSE CeCILL-C CACHE INTERNAL "")
set(logging_ADDRESS git@rob-dev.lirmm.fr:pid/logging.git CACHE INTERNAL "")
set(logging_CATEGORIES  CACHE INTERNAL "")
set(logging_REFERENCES  CACHE INTERNAL "")
