#### referencing package rkcl-driver-flir-ptu mode ####
set(rkcl-driver-flir-ptu_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(rkcl-driver-flir-ptu_MAIN_INSTITUTION _LIRMM_/_CNRS_EMAIL_navarro@lirmm.fr CACHE INTERNAL "")
set(rkcl-driver-flir-ptu_CONTACT_MAIL  CACHE INTERNAL "")
set(rkcl-driver-flir-ptu_FRAMEWORK  CACHE INTERNAL "")
set(rkcl-driver-flir-ptu_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rkcl-driver-flir-ptu_PROJECT_PAGE  CACHE INTERNAL "")
set(rkcl-driver-flir-ptu_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rkcl-driver-flir-ptu_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(rkcl-driver-flir-ptu_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM_/_CNRS_EMAIL_navarro@lirmm.fr)" CACHE INTERNAL "")
set(rkcl-driver-flir-ptu_DESCRIPTION "RKCL;interface;for;FLIR;pan-tilt;units" CACHE INTERNAL "")
set(rkcl-driver-flir-ptu_YEARS 2019 CACHE INTERNAL "")
set(rkcl-driver-flir-ptu_LICENSE CeCILL CACHE INTERNAL "")
set(rkcl-driver-flir-ptu_ADDRESS git@gite.lirmm.fr:rkcl/rkcl-driver-flir-ptu.git CACHE INTERNAL "")
set(rkcl-driver-flir-ptu_PUBLIC_ADDRESS https://gite.lirmm.fr/rkcl/rkcl-driver-flir-ptu.git CACHE INTERNAL "")
set(rkcl-driver-flir-ptu_CATEGORIES CACHE INTERNAL "")
set(rkcl-driver-flir-ptu_REFERENCES  CACHE INTERNAL "")
