#### referencing package wrench-cone-lib mode ####
set(wrench-cone-lib_MAIN_AUTHOR _Vincent_Samy CACHE INTERNAL "")
set(wrench-cone-lib_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(wrench-cone-lib_CONTACT_MAIL vsamy@outlook.fr CACHE INTERNAL "")
set(wrench-cone-lib_FRAMEWORK  CACHE INTERNAL "")
set(wrench-cone-lib_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(wrench-cone-lib_PROJECT_PAGE  CACHE INTERNAL "")
set(wrench-cone-lib_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(wrench-cone-lib_SITE_INTRODUCTION  CACHE INTERNAL "")
set(wrench-cone-lib_AUTHORS_AND_INSTITUTIONS "_Vincent_Samy(_LIRMM)" CACHE INTERNAL "")
set(wrench-cone-lib_DESCRIPTION "This library implements the Contact Wrench Cone as given [here](https://scaron.info/papers/journal/caron-tro-2016.pdf). It uses cdd for the polyhedron computation and Eigen for the matrix part. Python bindings are also available." CACHE INTERNAL "")
set(wrench-cone-lib_YEARS 2017 CACHE INTERNAL "")
set(wrench-cone-lib_LICENSE CeCILL-C CACHE INTERNAL "")
set(wrench-cone-lib_ADDRESS git@github.com:vsamy/wrench-cone-lib.git CACHE INTERNAL "")
set(wrench-cone-lib_PUBLIC_ADDRESS https://github.com/vsamy/wrench-cone-lib.git CACHE INTERNAL "")
set(wrench-cone-lib_CATEGORIES CACHE INTERNAL "")
set(wrench-cone-lib_REFERENCES  CACHE INTERNAL "")
