#### referencing package eigen-qp mode ####
set(eigen-qp_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(eigen-qp_MAIN_INSTITUTION _CNRS/LIRMM CACHE INTERNAL "")
set(eigen-qp_CONTACT_MAIL robin.passama@lirmm.fr CACHE INTERNAL "")
set(eigen-qp_FRAMEWORK rpc CACHE INTERNAL "")
set(eigen-qp_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(eigen-qp_PROJECT_PAGE https://gite.lirmm.fr/rob-miscellaneous/eigen-qp CACHE INTERNAL "")
set(eigen-qp_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(eigen-qp_SITE_INTRODUCTION "PID repackaging of 2 projects interfacing eigen with quadratic programming solvers: https://github.com/jrl-umi3218/eigen-quadprog and https://github.com/jrl-umi3218/eigen-qld. These projects implement quadratic programming solvers through Eigen3 library." CACHE INTERNAL "")
set(eigen-qp_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_CNRS/LIRMM);_Joris_Vaillant(_CNRS/UM_LIRMM_and_CNRS/AIST_JRL);_Pierre_Gergondet(_CNRS/AIST_JRL)" CACHE INTERNAL "")
set(eigen-qp_DESCRIPTION "quadratic programming solvers through Eigen3 library, by Joris Vaillant (<joris dot vaillant at gmail dot com>) and QLD solver for eigen by JRL (original author is Pierre Gergondet). PID native package wrapping projects https://github.com/jrl-umi3218/eigen-quadprog and https://github.com/jrl-umi3218/eigen-qld" CACHE INTERNAL "")
set(eigen-qp_YEARS 2017 CACHE INTERNAL "")
set(eigen-qp_LICENSE GNULGPL CACHE INTERNAL "")
set(eigen-qp_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/eigen-qp.git CACHE INTERNAL "")
set(eigen-qp_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/eigen-qp.git CACHE INTERNAL "")
set(eigen-qp_CATEGORIES "algorithm/optimization" CACHE INTERNAL "")
set(eigen-qp_REFERENCES  CACHE INTERNAL "")
