#### referencing package rkcl-collision-sch mode ####
set(rkcl-collision-sch_MAIN_AUTHOR _Sonny_Tarbouriech CACHE INTERNAL "")
set(rkcl-collision-sch_MAIN_INSTITUTION _Tecnalia CACHE INTERNAL "")
set(rkcl-collision-sch_CONTACT_MAIL  CACHE INTERNAL "")
set(rkcl-collision-sch_FRAMEWORK rkcl-framework CACHE INTERNAL "")
set(rkcl-collision-sch_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rkcl-collision-sch_PROJECT_PAGE https://gite.lirmm.fr/rkcl/rkcl-collision-sch CACHE INTERNAL "")
set(rkcl-collision-sch_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rkcl-collision-sch_SITE_INTRODUCTION "Define;a;collision;avoidance;processor;based;on;sch-core" CACHE INTERNAL "")
set(rkcl-collision-sch_AUTHORS_AND_INSTITUTIONS "_Sonny_Tarbouriech(_Tecnalia);_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(rkcl-collision-sch_DESCRIPTION "Define;a;collision;avoidance;processor;based;on;sch-core" CACHE INTERNAL "")
set(rkcl-collision-sch_YEARS 2018 CACHE INTERNAL "")
set(rkcl-collision-sch_LICENSE CeCILL CACHE INTERNAL "")
set(rkcl-collision-sch_ADDRESS git@gite.lirmm.fr:rkcl/rkcl-collision-sch.git CACHE INTERNAL "")
set(rkcl-collision-sch_PUBLIC_ADDRESS https://gite.lirmm.fr/rkcl/rkcl-collision-sch.git CACHE INTERNAL "")
set(rkcl-collision-sch_CATEGORIES "processor" CACHE INTERNAL "")
set(rkcl-collision-sch_REFERENCES  CACHE INTERNAL "")
