#### referencing package api-wrapper-nidaqmx mode ####
set(api-wrapper-nidaqmx_MAIN_AUTHOR _Xavier_Gorron CACHE INTERNAL "")
set(api-wrapper-nidaqmx_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(api-wrapper-nidaqmx_CONTACT_MAIL  CACHE INTERNAL "")
set(api-wrapper-nidaqmx_AUTHORS_AND_INSTITUTIONS "_Xavier_Gorron(_LIRMM);_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(api-wrapper-nidaqmx_DESCRIPTION Knowbotics wrapper for the NIDAQmx Base acquisition tools CACHE INTERNAL "")
set(api-wrapper-nidaqmx_YEARS 2015 CACHE INTERNAL "")
set(api-wrapper-nidaqmx_LICENSE CeCILL-C CACHE INTERNAL "")
set(api-wrapper-nidaqmx_ADDRESS git@gite.lirmm.fr:pid_external_deps/api-wrapper-nidaqmx.git CACHE INTERNAL "")
set(api-wrapper-nidaqmx_CATEGORIES "" CACHE INTERNAL "")
set(api-wrapper-nidaqmx_REFERENCES  CACHE INTERNAL "")
