#### referencing package rpiexample mode ####
set(rpiexample_MAIN_AUTHOR _Charles_Villard CACHE INTERNAL "")
set(rpiexample_MAIN_INSTITUTION  CACHE INTERNAL "")
set(rpiexample_CONTACT_MAIL  CACHE INTERNAL "")
set(rpiexample_FRAMEWORK  CACHE INTERNAL "")
set(rpiexample_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rpiexample_PROJECT_PAGE  CACHE INTERNAL "")
set(rpiexample_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rpiexample_SITE_INTRODUCTION  CACHE INTERNAL "")
set(rpiexample_AUTHORS_AND_INSTITUTIONS "_Charles_Villard()" CACHE INTERNAL "")
set(rpiexample_DESCRIPTION "This;package;centralise;all;drivers;use;example;for;the;Raspberry;pi;3" CACHE INTERNAL "")
set(rpiexample_YEARS 2018 CACHE INTERNAL "")
set(rpiexample_LICENSE CeCILL CACHE INTERNAL "")
set(rpiexample_ADDRESS git@gite.lirmm.fr:explore-rov/Drivers/rpiexample.git CACHE INTERNAL "")
set(rpiexample_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(rpiexample_CATEGORIES CACHE INTERNAL "")
set(rpiexample_REFERENCES  CACHE INTERNAL "")
