#### referencing package hardiorpi mode ####
set(hardiorpi_MAIN_AUTHOR _Charles_Villard CACHE INTERNAL "")
set(hardiorpi_MAIN_INSTITUTION  CACHE INTERNAL "")
set(hardiorpi_CONTACT_MAIL  CACHE INTERNAL "")
set(hardiorpi_FRAMEWORK  CACHE INTERNAL "")
set(hardiorpi_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(hardiorpi_PROJECT_PAGE  CACHE INTERNAL "")
set(hardiorpi_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(hardiorpi_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(hardiorpi_AUTHORS_AND_INSTITUTIONS "_Charles_Villard();_Clement_Rebut" CACHE INTERNAL "")
set(hardiorpi_DESCRIPTION "This;is;the;implementation;of;hardiocore;for;Rpi3" CACHE INTERNAL "")
set(hardiorpi_YEARS 2018 CACHE INTERNAL "")
set(hardiorpi_LICENSE CeCILL CACHE INTERNAL "")
set(hardiorpi_ADDRESS git@gite.lirmm.fr:hardio/cards/hardiorpi.git CACHE INTERNAL "")
set(hardiorpi_PUBLIC_ADDRESS https://gite.lirmm.fr/hardio/cards/hardiorpi.git CACHE INTERNAL "")
set(hardiorpi_CATEGORIES CACHE INTERNAL "")
set(hardiorpi_REFERENCES  CACHE INTERNAL "")
