#### referencing package omni-tentacles-based-navigation mode ####
set(omni-tentacles-based-navigation_MAIN_AUTHOR _Abdellah_Khelloufi CACHE INTERNAL "")
set(omni-tentacles-based-navigation_MAIN_INSTITUTION  CACHE INTERNAL "")
set(omni-tentacles-based-navigation_CONTACT_MAIL  CACHE INTERNAL "")
set(omni-tentacles-based-navigation_AUTHORS_AND_INSTITUTIONS "_Abdellah_Khelloufi()" CACHE INTERNAL "")
set(omni-tentacles-based-navigation_DESCRIPTION navigation task Implementation using the omni tentacles approach  CACHE INTERNAL "")
set(omni-tentacles-based-navigation_YEARS 2017 CACHE INTERNAL "")
set(omni-tentacles-based-navigation_LICENSE CeCILL CACHE INTERNAL "")
set(omni-tentacles-based-navigation_ADDRESS git@gite.lirmm.fr:abdellah_khe_at_gmail_com/omni-tentacles-based-navigation.git CACHE INTERNAL "")
set(omni-tentacles-based-navigation_CATEGORIES "mobile-robot/modified-youbot;mobile-robot/simulated;knowbotics/mobile-robot;simulator/vrep" CACHE INTERNAL "")
set(omni-tentacles-based-navigation_AVAILABLE_PLATFORMS linux64cxx11;linux64;linux32;macosx64 CACHE INTERNAL "")
set(omni-tentacles-based-navigation_AVAILABLE_PLATFORM_linux64cxx11_OS linux CACHE INTERNAL "")
set(omni-tentacles-based-navigation_AVAILABLE_PLATFORM_linux64cxx11_ARCH 64 CACHE INTERNAL "")
set(omni-tentacles-based-navigation_AVAILABLE_PLATFORM_linux64cxx11_ABI CXX11 CACHE INTERNAL "")
set(omni-tentacles-based-navigation_AVAILABLE_PLATFORM_linux64cxx11_CONFIGURATION  CACHE INTERNAL "")
set(omni-tentacles-based-navigation_AVAILABLE_PLATFORM_linux64_OS linux CACHE INTERNAL "")
set(omni-tentacles-based-navigation_AVAILABLE_PLATFORM_linux64_ARCH 64 CACHE INTERNAL "")
set(omni-tentacles-based-navigation_AVAILABLE_PLATFORM_linux64_ABI CXX CACHE INTERNAL "")
set(omni-tentacles-based-navigation_AVAILABLE_PLATFORM_linux64_CONFIGURATION  CACHE INTERNAL "")
set(omni-tentacles-based-navigation_AVAILABLE_PLATFORM_linux32_OS linux CACHE INTERNAL "")
set(omni-tentacles-based-navigation_AVAILABLE_PLATFORM_linux32_ARCH 32 CACHE INTERNAL "")
set(omni-tentacles-based-navigation_AVAILABLE_PLATFORM_linux32_ABI CXX CACHE INTERNAL "")
set(omni-tentacles-based-navigation_AVAILABLE_PLATFORM_linux32_CONFIGURATION  CACHE INTERNAL "")
set(omni-tentacles-based-navigation_AVAILABLE_PLATFORM_macosx64_OS macosx CACHE INTERNAL "")
set(omni-tentacles-based-navigation_AVAILABLE_PLATFORM_macosx64_ARCH 64 CACHE INTERNAL "")
set(omni-tentacles-based-navigation_AVAILABLE_PLATFORM_macosx64_ABI CXX CACHE INTERNAL "")
set(omni-tentacles-based-navigation_AVAILABLE_PLATFORM_macosx64_CONFIGURATION  CACHE INTERNAL "")
set(omni-tentacles-based-navigation_REFERENCES  CACHE INTERNAL "")
