#### referencing package shadow-hand-driver-vrep mode ####
set(shadow-hand-driver-vrep_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(shadow-hand-driver-vrep_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(shadow-hand-driver-vrep_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(shadow-hand-driver-vrep_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM);_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(shadow-hand-driver-vrep_DESCRIPTION A package to interface with a simulated Shadow Dexterous hand on V-REP CACHE INTERNAL "")
set(shadow-hand-driver-vrep_YEARS 2015 CACHE INTERNAL "")
set(shadow-hand-driver-vrep_LICENSE CeCILL-C CACHE INTERNAL "")
set(shadow-hand-driver-vrep_ADDRESS git@gite.lirmm.fr:shadow-hands/shadow-hand-driver-vrep.git CACHE INTERNAL "")
set(shadow-hand-driver-vrep_CATEGORIES "hand/shadow-dexterous;hand/simulated;simulator/vrep;knowbotics/hand" CACHE INTERNAL "")
set(shadow-hand-driver-vrep_REFERENCES  CACHE INTERNAL "")
