#### referencing wrapper of external package lapack ####
set(lapack_PID_WRAPPER_CONTACT_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(lapack_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(lapack_PID_WRAPPER_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(lapack_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(lapack_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/pid/wrappers/lapack CACHE INTERNAL "")
set(lapack_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(lapack_PID_WRAPPER_SITE_INTRODUCTION This;project;is;a;PID;wrapper;for;the;external;project;called;lapack.;It;provides;routines;for;linear;algebra;problems;resolutions. CACHE INTERNAL "")
set(lapack_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr)" CACHE INTERNAL "")
set(lapack_PID_WRAPPER_YEARS 2018 CACHE INTERNAL "")
set(lapack_PID_WRAPPER_LICENSE BSD CACHE INTERNAL "")
set(lapack_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:pid/wrappers/lapack.git CACHE INTERNAL "")
set(lapack_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/wrappers/lapack.git CACHE INTERNAL "")
set(lapack_DESCRIPTION "PID wrapper for opencv external project" CACHE INTERNAL "")
set(lapack_FRAMEWORK pid CACHE INTERNAL "")
set(lapack_CATEGORIES "programming/linear_algebra" CACHE INTERNAL "")
set(lapack_AUTHORS "netlib.org members" CACHE INTERNAL "")
set(lapack_PROJECT_SITE http://www.netlib.org/lapack CACHE INTERNAL "")
set(lapack_LICENSES 3-clause BSD License CACHE INTERNAL "")
set(lapack_REFERENCES  CACHE INTERNAL "")
