#### referencing wrapper of external package cpp-taskflow ####
set(cpp-taskflow_PID_WRAPPER_CONTACT_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(cpp-taskflow_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(cpp-taskflow_PID_WRAPPER_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(cpp-taskflow_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(cpp-taskflow_PID_WRAPPER_PROJECT_PAGE  CACHE INTERNAL "")
set(cpp-taskflow_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(cpp-taskflow_PID_WRAPPER_SITE_INTRODUCTION  CACHE INTERNAL "")
set(cpp-taskflow_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr)" CACHE INTERNAL "")
set(cpp-taskflow_PID_WRAPPER_YEARS 2019 CACHE INTERNAL "")
set(cpp-taskflow_PID_WRAPPER_LICENSE MIT CACHE INTERNAL "")
set(cpp-taskflow_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:pid/cpp-taskflow.git CACHE INTERNAL "")
set(cpp-taskflow_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/cpp-taskflow.git CACHE INTERNAL "")
set(cpp-taskflow_DESCRIPTION "Modern C++ Parallel Task Programming Library, repackaged for PID" CACHE INTERNAL "")
set(cpp-taskflow_FRAMEWORK  CACHE INTERNAL "")
set(cpp-taskflow_CATEGORIES "programming/operating_system" CACHE INTERNAL "")
set(cpp-taskflow_AUTHORS "Tsung-Wei Huang and other contributors" CACHE INTERNAL "")
set(cpp-taskflow_PROJECT_SITE https://github.com/cpp-taskflow/cpp-taskflow CACHE INTERNAL "")
set(cpp-taskflow_LICENSES MIT License CACHE INTERNAL "")
set(cpp-taskflow_REFERENCES  CACHE INTERNAL "")
