#### referencing wrapper of external package dqrobotics ####
set(dqrobotics_PID_WRAPPER_CONTACT_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(dqrobotics_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(dqrobotics_PID_WRAPPER_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(dqrobotics_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(dqrobotics_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/rob-miscellaneous/dqrobotics CACHE INTERNAL "")
set(dqrobotics_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(dqrobotics_PID_WRAPPER_SITE_INTRODUCTION "dqrobotics;is;a;PID;wrapper;for;the;external;project;called;DQ;Robotics.;DQ;Robotics;provides;dual;quaternion;algebra;and;kinematic;calculation;algorithms." CACHE INTERNAL "")
set(dqrobotics_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr)" CACHE INTERNAL "")
set(dqrobotics_PID_WRAPPER_YEARS 2019 CACHE INTERNAL "")
set(dqrobotics_PID_WRAPPER_LICENSE GNULGPL CACHE INTERNAL "")
set(dqrobotics_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/dqrobotics.git CACHE INTERNAL "")
set(dqrobotics_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/dqrobotics.git CACHE INTERNAL "")
set(dqrobotics_DESCRIPTION "DQ Robotics is a standalone open-source (LGPLv3) library for robot modelling and control. It provides dual quaternion algebra and kinematic calculation algorithms in MATLAB and C++." CACHE INTERNAL "")
set(dqrobotics_FRAMEWORK rpc CACHE INTERNAL "")
set(dqrobotics_CATEGORIES "algorithm/math;algorithm/control" CACHE INTERNAL "")
set(dqrobotics_AUTHORS "Murilo M Marinho" CACHE INTERNAL "")
set(dqrobotics_PROJECT_SITE https://dqrobotics.github.io CACHE INTERNAL "")
set(dqrobotics_LICENSES GNULGPL CACHE INTERNAL "")
set(dqrobotics_REFERENCES  CACHE INTERNAL "")
