#### referencing package contact-based-manipulation mode ####
set(contact-based-manipulation_MAIN_AUTHOR _Jihong_Zhu CACHE INTERNAL "")
set(contact-based-manipulation_MAIN_INSTITUTION  CACHE INTERNAL "")
set(contact-based-manipulation_CONTACT_MAIL  CACHE INTERNAL "")
set(contact-based-manipulation_FRAMEWORK  CACHE INTERNAL "")
set(contact-based-manipulation_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(contact-based-manipulation_PROJECT_PAGE  CACHE INTERNAL "")
set(contact-based-manipulation_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(contact-based-manipulation_SITE_INTRODUCTION  CACHE INTERNAL "")
set(contact-based-manipulation_AUTHORS_AND_INSTITUTIONS "_Jihong_Zhu()" CACHE INTERNAL "")
set(contact-based-manipulation_DESCRIPTION "TODO:;input;a;short;description;of;package;contact-based-manipulation;utility;here" CACHE INTERNAL "")
set(contact-based-manipulation_YEARS 2019 CACHE INTERNAL "")
set(contact-based-manipulation_LICENSE CeCILL CACHE INTERNAL "")
set(contact-based-manipulation_ADDRESS git@gite.lirmm.fr:zhu/contact-based-manipulation.git CACHE INTERNAL "")
set(contact-based-manipulation_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(contact-based-manipulation_CATEGORIES CACHE INTERNAL "")
set(contact-based-manipulation_REFERENCES  CACHE INTERNAL "")
