#### referencing package panda-robot mode ####
set(panda-robot_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(panda-robot_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(panda-robot_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(panda-robot_FRAMEWORK rpc CACHE INTERNAL "")
set(panda-robot_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(panda-robot_PROJECT_PAGE https://gite.lirmm.fr/rob-miscellaneous/drivers/panda-robot.git CACHE INTERNAL "")
set(panda-robot_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(panda-robot_SITE_INTRODUCTION "A wrapper for the Franka Panda robot driver, based on libfranka." CACHE INTERNAL "")
set(panda-robot_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(panda-robot_DESCRIPTION "A wrapper for the Franka Panda robot driver, based on libfranka." CACHE INTERNAL "")
set(panda-robot_YEARS 2019 CACHE INTERNAL "")
set(panda-robot_LICENSE CeCILL CACHE INTERNAL "")
set(panda-robot_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/drivers/panda-robot.git CACHE INTERNAL "")
set(panda-robot_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/drivers/panda-robot.git CACHE INTERNAL "")
set(panda-robot_CATEGORIES CACHE INTERNAL "")
set(panda-robot_REFERENCES  CACHE INTERNAL "")
