#### referencing package robotics-library mode ####
set(robotics-library_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(robotics-library_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(robotics-library_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(robotics-library_FRAMEWORK rpc CACHE INTERNAL "")
set(robotics-library_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(robotics-library_PROJECT_PAGE https://gite.lirmm.fr/rob-miscellaneous/quadprog CACHE INTERNAL "")
set(robotics-library_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(robotics-library_SITE_INTRODUCTION The Robotics Library (RL) is a self-contained C++ library for robot kinematics, motion planning and control. It covers mathematics, kinematics and dynamics, hardware abstraction, motion planning, collision detection, and visualization. CACHE INTERNAL "")
set(robotics-library_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM);_Robin_Passama(_CNRS/LIRMM)" CACHE INTERNAL "")
set(robotics-library_DESCRIPTION "PID wrapper for Robotics Libraryi (http://www.roboticslibrary.org)" CACHE INTERNAL "")
set(robotics-library_YEARS 2015 CACHE INTERNAL "")
set(robotics-library_LICENSE CeCILL-C CACHE INTERNAL "")
set(robotics-library_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/robotics-library.git CACHE INTERNAL "")
set(robotics-library_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/robotics-library.git CACHE INTERNAL "")
set(robotics-library_CATEGORIES "algorithm;algorithm/control;algorithm/math" CACHE INTERNAL "")
set(robotics-library_REFERENCES  CACHE INTERNAL "")
