#### referencing package neobotix-mpo700-knowbotics mode ####
set(neobotix-mpo700-knowbotics_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(neobotix-mpo700-knowbotics_MAIN_INSTITUTION  CACHE INTERNAL "")
set(neobotix-mpo700-knowbotics_CONTACT_MAIL  CACHE INTERNAL "")
set(neobotix-mpo700-knowbotics_AUTHORS_AND_INSTITUTIONS ; "_Robin_Passama()" CACHE INTERNAL "")
set(neobotix-mpo700-knowbotics_DESCRIPTION contains the basic objects to use with theneobotix mpo700 platform CACHE INTERNAL "")
set(neobotix-mpo700-knowbotics_YEARS 2015 CACHE INTERNAL "")
set(neobotix-mpo700-knowbotics_LICENSE CeCILL-C CACHE INTERNAL "")
set(neobotix-mpo700-knowbotics_ADDRESS git@rob-dev.lirmm.fr:neobotix-mpo700/neobotix-mpo700-knowbotics.git CACHE INTERNAL "")
set(neobotix-mpo700-knowbotics_CATEGORIES robot/vehicle/ground;driver/neobotix-mpo700 CACHE INTERNAL "")
set(neobotix-mpo700-knowbotics_REFERENCES  CACHE INTERNAL "")
