#### referencing package rkcl-robmed-apps mode ####
set(rkcl-robmed-apps_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(rkcl-robmed-apps_MAIN_INSTITUTION _LIRMM_/_CNRS CACHE INTERNAL "")
set(rkcl-robmed-apps_CONTACT_MAIL  CACHE INTERNAL "")
set(rkcl-robmed-apps_FRAMEWORK  CACHE INTERNAL "")
set(rkcl-robmed-apps_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rkcl-robmed-apps_PROJECT_PAGE  CACHE INTERNAL "")
set(rkcl-robmed-apps_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rkcl-robmed-apps_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(rkcl-robmed-apps_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM_/_CNRS)" CACHE INTERNAL "")
set(rkcl-robmed-apps_DESCRIPTION "Collection;of;applications;for;medical;robotics;based;on;RKCL" CACHE INTERNAL "")
set(rkcl-robmed-apps_YEARS 2019 CACHE INTERNAL "")
set(rkcl-robmed-apps_LICENSE CeCILL CACHE INTERNAL "")
set(rkcl-robmed-apps_ADDRESS git@gite.lirmm.fr:robmed/demos/rkcl-robmed-apps.git CACHE INTERNAL "")
set(rkcl-robmed-apps_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(rkcl-robmed-apps_CATEGORIES CACHE INTERNAL "")
set(rkcl-robmed-apps_REFERENCES  CACHE INTERNAL "")
