#### referencing package ethercatcpp-tensegrity mode ####
set(ethercatcpp-tensegrity_MAIN_AUTHOR _Meline_Arnaud CACHE INTERNAL "")
set(ethercatcpp-tensegrity_MAIN_INSTITUTION  CACHE INTERNAL "")
set(ethercatcpp-tensegrity_CONTACT_MAIL meline@lirmm.fr CACHE INTERNAL "")
set(ethercatcpp-tensegrity_FRAMEWORK ethercatcpp CACHE INTERNAL "")
set(ethercatcpp-tensegrity_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(ethercatcpp-tensegrity_PROJECT_PAGE https://gite.lirmm.fr/ethercatcpp/ethercatcpp-tensegrity CACHE INTERNAL "")
set(ethercatcpp-tensegrity_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(ethercatcpp-tensegrity_SITE_INTRODUCTION ethercatcpp-tensegrity;is;a;package;providing;the;ethercat;driver;for;tensegrity;robot. CACHE INTERNAL "")
set(ethercatcpp-tensegrity_AUTHORS_AND_INSTITUTIONS "_Meline_Arnaud()" CACHE INTERNAL "")
set(ethercatcpp-tensegrity_DESCRIPTION "Ethercat driver library for Tensegrity Robot" CACHE INTERNAL "")
set(ethercatcpp-tensegrity_YEARS 2018 CACHE INTERNAL "")
set(ethercatcpp-tensegrity_LICENSE CeCILL-C CACHE INTERNAL "")
set(ethercatcpp-tensegrity_ADDRESS git@gite.lirmm.fr:ethercatcpp/ethercatcpp-tensegrity.git CACHE INTERNAL "")
set(ethercatcpp-tensegrity_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(ethercatcpp-tensegrity_CATEGORIES "ethercat/robot" CACHE INTERNAL "")
set(ethercatcpp-tensegrity_REFERENCES  CACHE INTERNAL "")
