#### referencing wrapper of external package octomap ####
set(octomap_PID_WRAPPER_CONTACT_AUTHOR _yohan CACHE INTERNAL "")
set(octomap_PID_WRAPPER_CONTACT_INSTITUTION _lirmm CACHE INTERNAL "")
set(octomap_PID_WRAPPER_CONTACT_MAIL breux@lirmm.fr CACHE INTERNAL "")
set(octomap_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(octomap_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/rob-miscellaneous/octomap.git CACHE INTERNAL "")
set(octomap_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(octomap_PID_WRAPPER_SITE_INTRODUCTION This project is a PID wrapper for the external project called octomap. It is used for efficient probabilitic 3D mapping representation using octrees. CACHE INTERNAL "")
set(octomap_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_yohan(_lirmm)" CACHE INTERNAL "")
set(octomap_PID_WRAPPER_YEARS 2019 CACHE INTERNAL "")
set(octomap_PID_WRAPPER_LICENSE BSD CACHE INTERNAL "")
set(octomap_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/octomap.git CACHE INTERNAL "")
set(octomap_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/octomap.git CACHE INTERNAL "")
set(octomap_DESCRIPTION "PID wrapper for the octomap library (Probabilistic 3D Mapping Framework Based on Octrees)" CACHE INTERNAL "")
set(octomap_FRAMEWORK rpc CACHE INTERNAL "")
set(octomap_CATEGORIES "algorithm/3d" CACHE INTERNAL "")
set(octomap_AUTHORS "Octomap developper team" CACHE INTERNAL "")
set(octomap_PROJECT_SITE https://octomap.github.io/ CACHE INTERNAL "")
set(octomap_LICENSES BSD-3-Clause CACHE INTERNAL "")
set(octomap_REFERENCES  CACHE INTERNAL "")
