#### referencing wrapper of external package open-igtlink ####
set(open-igtlink_PID_WRAPPER_CONTACT_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(open-igtlink_PID_WRAPPER_CONTACT_INSTITUTION _CNRS/LIRMM CACHE INTERNAL "")
set(open-igtlink_PID_WRAPPER_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(open-igtlink_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(open-igtlink_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/robmed/devices/open-igtlink CACHE INTERNAL "")
set(open-igtlink_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(open-igtlink_PID_WRAPPER_SITE_INTRODUCTION "PID Wrapper for the open IGT link project. OpenIGTLink is an open-source network communication interface specifically designed for image-guided interventions. It aims to provide a plug-and-play unified real-time communications (URTC) in operating rooms (ORs) for image-guided interventions, where imagers, sensors, surgical robots,and computers from different vendors work cooperatively. This URTC will ensure the seamless data flow among those components and enable a closed-loop process of planning, control, delivery, and feedback. Examples applications of URTC include but not limited to: stereotactic surgical guidance using optical position sensor and medical image visualization software, intraoperative image guidance using real-time MRI and medical image visualization software, robot-assisted interventions using robotic devices and surgical planning software" CACHE INTERNAL "")
set(open-igtlink_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_CNRS/LIRMM)" CACHE INTERNAL "")
set(open-igtlink_PID_WRAPPER_YEARS 2019 CACHE INTERNAL "")
set(open-igtlink_PID_WRAPPER_LICENSE BSD CACHE INTERNAL "")
set(open-igtlink_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:robmed/devices/open-igtlink.git CACHE INTERNAL "")
set(open-igtlink_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/robmed/devices/open-igtlink.git CACHE INTERNAL "")
set(open-igtlink_DESCRIPTION "OpenIGTLink;provides;a;standardized;mechanism;for;communication;among;computers;and;devices;in;operating;rooms;for;wide;variety;of;image-guided;therapy;(;IGT;);applications." CACHE INTERNAL "")
set(open-igtlink_FRAMEWORK rpc CACHE INTERNAL "")
set(open-igtlink_CATEGORIES "driver/sensor/vision" CACHE INTERNAL "")
set(open-igtlink_AUTHORS "The OpenIGTLink Community and Brigham and Women's Hospital " CACHE INTERNAL "")
set(open-igtlink_PROJECT_SITE http://openigtlink.org/ CACHE INTERNAL "")
set(open-igtlink_LICENSES BSD license  CACHE INTERNAL "")
set(open-igtlink_REFERENCES  CACHE INTERNAL "")
