#### referencing package rtplot mode ####
set(rtplot_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(rtplot_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(rtplot_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(rtplot_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM);_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(rtplot_DESCRIPTION rtplot takes commands from stdin to display graphs. See the wiki for usage CACHE INTERNAL "")
set(rtplot_YEARS 2015 CACHE INTERNAL "")
set(rtplot_LICENSE CeCILL-C CACHE INTERNAL "")
set(rtplot_ADDRESS git@gite.lirmm.fr:pid/rtplot.git CACHE INTERNAL "")
set(rtplot_CATEGORIES CACHE INTERNAL "")
set(rtplot_AVAILABLE_PLATFORMS linux64cxx11;linux64;linux32;macosx64 CACHE INTERNAL "")
set(rtplot_AVAILABLE_PLATFORM_linux64cxx11_OS linux CACHE INTERNAL "")
set(rtplot_AVAILABLE_PLATFORM_linux64cxx11_ARCH 64 CACHE INTERNAL "")
set(rtplot_AVAILABLE_PLATFORM_linux64cxx11_ABI CXX11 CACHE INTERNAL "")
set(rtplot_AVAILABLE_PLATFORM_linux64cxx11_CONFIGURATION posix CACHE INTERNAL "")
set(rtplot_AVAILABLE_PLATFORM_linux64_OS linux CACHE INTERNAL "")
set(rtplot_AVAILABLE_PLATFORM_linux64_ARCH 64 CACHE INTERNAL "")
set(rtplot_AVAILABLE_PLATFORM_linux64_ABI CXX CACHE INTERNAL "")
set(rtplot_AVAILABLE_PLATFORM_linux64_CONFIGURATION posix CACHE INTERNAL "")
set(rtplot_AVAILABLE_PLATFORM_linux32_OS linux CACHE INTERNAL "")
set(rtplot_AVAILABLE_PLATFORM_linux32_ARCH 32 CACHE INTERNAL "")
set(rtplot_AVAILABLE_PLATFORM_linux32_ABI CXX CACHE INTERNAL "")
set(rtplot_AVAILABLE_PLATFORM_linux32_CONFIGURATION posix CACHE INTERNAL "")
set(rtplot_AVAILABLE_PLATFORM_macosx64_OS macosx CACHE INTERNAL "")
set(rtplot_AVAILABLE_PLATFORM_macosx64_ARCH 64 CACHE INTERNAL "")
set(rtplot_AVAILABLE_PLATFORM_macosx64_ABI CXX CACHE INTERNAL "")
set(rtplot_AVAILABLE_PLATFORM_macosx64_CONFIGURATION posix CACHE INTERNAL "")
set(rtplot_REFERENCES  CACHE INTERNAL "")
