#### referencing package kuka-lwr-driver-fri mode ####
set(kuka-lwr-driver-fri_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(kuka-lwr-driver-fri_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(kuka-lwr-driver-fri_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(kuka-lwr-driver-fri_AUTHORS_AND_INSTITUTIONS ; "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(kuka-lwr-driver-fri_DESCRIPTION A package to interface with a real Kuka LWR using the FRI library CACHE INTERNAL "")
set(kuka-lwr-driver-fri_YEARS 2015 CACHE INTERNAL "")
set(kuka-lwr-driver-fri_LICENSE CeCILL-C CACHE INTERNAL "")
set(kuka-lwr-driver-fri_ADDRESS git@rob-dev.lirmm.fr:kuka-lwr-knowbotics/kuka-kwr-driver-fri.git CACHE INTERNAL "")
set(kuka-lwr-driver-fri_CATEGORIES robot/arm;driver/fri CACHE INTERNAL "")
set(kuka-lwr-driver-fri_REFERENCES  CACHE INTERNAL "")
