#### referencing package imglibs-interop mode ####
set(imglibs-interop_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(imglibs-interop_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(imglibs-interop_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(imglibs-interop_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM);_Sebastien_Druon(_LIRMM)" CACHE INTERNAL "")
set(imglibs-interop_DESCRIPTION A library for image interoperability CACHE INTERNAL "")
set(imglibs-interop_YEARS 2016 CACHE INTERNAL "")
set(imglibs-interop_LICENSE CeCILL-C CACHE INTERNAL "")
set(imglibs-interop_ADDRESS git@gite.lirmm.fr:rob-vision/imglibs-interop.git CACHE INTERNAL "")
set(imglibs-interop_CATEGORIES CACHE INTERNAL "")
set(imglibs-interop_AVAILABLE_PLATFORMS linux64cxx11;linux64;linux32;macosx64 CACHE INTERNAL "")
set(imglibs-interop_AVAILABLE_PLATFORM_linux64cxx11_OS linux CACHE INTERNAL "")
set(imglibs-interop_AVAILABLE_PLATFORM_linux64cxx11_ARCH 64 CACHE INTERNAL "")
set(imglibs-interop_AVAILABLE_PLATFORM_linux64cxx11_ABI CXX11 CACHE INTERNAL "")
set(imglibs-interop_AVAILABLE_PLATFORM_linux64cxx11_CONFIGURATION posix CACHE INTERNAL "")
set(imglibs-interop_AVAILABLE_PLATFORM_linux64_OS linux CACHE INTERNAL "")
set(imglibs-interop_AVAILABLE_PLATFORM_linux64_ARCH 64 CACHE INTERNAL "")
set(imglibs-interop_AVAILABLE_PLATFORM_linux64_ABI CXX CACHE INTERNAL "")
set(imglibs-interop_AVAILABLE_PLATFORM_linux64_CONFIGURATION posix CACHE INTERNAL "")
set(imglibs-interop_AVAILABLE_PLATFORM_linux32_OS linux CACHE INTERNAL "")
set(imglibs-interop_AVAILABLE_PLATFORM_linux32_ARCH 32 CACHE INTERNAL "")
set(imglibs-interop_AVAILABLE_PLATFORM_linux32_ABI CXX CACHE INTERNAL "")
set(imglibs-interop_AVAILABLE_PLATFORM_linux32_CONFIGURATION posix CACHE INTERNAL "")
set(imglibs-interop_AVAILABLE_PLATFORM_macosx64_OS macosx CACHE INTERNAL "")
set(imglibs-interop_AVAILABLE_PLATFORM_macosx64_ARCH 64 CACHE INTERNAL "")
set(imglibs-interop_AVAILABLE_PLATFORM_macosx64_ABI CXX CACHE INTERNAL "")
set(imglibs-interop_AVAILABLE_PLATFORM_macosx64_CONFIGURATION posix CACHE INTERNAL "")
set(imglibs-interop_REFERENCES  CACHE INTERNAL "")
