#### referencing package dsp-filters mode ####
set(dsp-filters_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(dsp-filters_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(dsp-filters_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(dsp-filters_FRAMEWORK  CACHE INTERNAL "")
set(dsp-filters_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(dsp-filters_PROJECT_PAGE  CACHE INTERNAL "")
set(dsp-filters_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(dsp-filters_SITE_INTRODUCTION  CACHE INTERNAL "")
set(dsp-filters_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(dsp-filters_DESCRIPTION "Wrapper for https://github.com/vinniefalco/DSPFilters" CACHE INTERNAL "")
set(dsp-filters_YEARS 2016 CACHE INTERNAL "")
set(dsp-filters_LICENSE CeCILL-C CACHE INTERNAL "")
set(dsp-filters_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/dsp-filters.git CACHE INTERNAL "")
set(dsp-filters_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/dsp-filters.git CACHE INTERNAL "")
set(dsp-filters_CATEGORIES CACHE INTERNAL "")
set(dsp-filters_REFERENCES  CACHE INTERNAL "")
