#### referencing environment gcc_toolchain mode ####
set(gcc_toolchain_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(gcc_toolchain_MAIN_INSTITUTION _CNRS/LIRMM CACHE INTERNAL "")
set(gcc_toolchain_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_CNRS/LIRMM)" CACHE INTERNAL "")
set(gcc_toolchain_YEARS 2019 CACHE INTERNAL "")
set(gcc_toolchain_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(gcc_toolchain_ADDRESS git@gite.lirmm.fr:pid/environments/gcc_toolchain.git CACHE INTERNAL "")
set(gcc_toolchain_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/environments/gcc_toolchain.git CACHE INTERNAL "")
set(gcc_toolchain_LICENSE CeCILL-C CACHE INTERNAL "")
set(gcc_toolchain_DESCRIPTION using GNU gcc toolchain to build C/C++ code of projects CACHE INTERNAL "")
