#### referencing package ptz-dlink-dcs5222l mode ####
set(ptz-dlink-dcs5222l_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(ptz-dlink-dcs5222l_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(ptz-dlink-dcs5222l_CONTACT_MAIL  CACHE INTERNAL "")
set(ptz-dlink-dcs5222l_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM);_Florian_Raffalli(_LIRMM)" CACHE INTERNAL "")
set(ptz-dlink-dcs5222l_DESCRIPTION Driver software to deal with the DCS522L DLINK camera CACHE INTERNAL "")
set(ptz-dlink-dcs5222l_YEARS 2015 CACHE INTERNAL "")
set(ptz-dlink-dcs5222l_LICENSE CeCILL-C CACHE INTERNAL "")
set(ptz-dlink-dcs5222l_ADDRESS git@gite.lirmm.fr:rob-vision-devices/ptz-dlink-dcs5222l.git CACHE INTERNAL "")
set(ptz-dlink-dcs5222l_CATEGORIES "camera/dlink" CACHE INTERNAL "")
set(ptz-dlink-dcs5222l_REFERENCES  CACHE INTERNAL "")
