#### referencing wrapper of external package qhull ####
set(qhull_PID_WRAPPER_CONTACT_AUTHOR _Arnaud_Meline CACHE INTERNAL "")
set(qhull_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(qhull_PID_WRAPPER_CONTACT_MAIL arnaud.meline@lirmm.fr CACHE INTERNAL "")
set(qhull_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(qhull_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/rob-vision/msvf/wrappers/qhull CACHE INTERNAL "")
set(qhull_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(qhull_PID_WRAPPER_SITE_INTRODUCTION "This project is a PID wrapper for the external project called Qhull. Qhull computes the convex hull, Delaunay triangulation, Voronoi diagram, halfspace intersection about a point, furthest-site Delaunay triangulation, and furthest-site Voronoi diagram. The source code runs in 2-d, 3-d, 4-d, and higher dimensions. Qhull implements the Quickhull algorithm for computing the convex hull. It handles roundoff errors from floating point arithmetic. It computes volumes, surface areas, and approximations to the convex hull." CACHE INTERNAL "")
set(qhull_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Arnaud_Meline(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr)" CACHE INTERNAL "")
set(qhull_PID_WRAPPER_YEARS 2019 CACHE INTERNAL "")
set(qhull_PID_WRAPPER_LICENSE BSD CACHE INTERNAL "")
set(qhull_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:rob-vision/msvf/wrappers/qhull.git CACHE INTERNAL "")
set(qhull_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-vision/msvf/wrappers/qhull.git CACHE INTERNAL "")
set(qhull_DESCRIPTION "PID;wrapper;for;Qhull;external;project" CACHE INTERNAL "")
set(qhull_FRAMEWORK rpc CACHE INTERNAL "")
set(qhull_CATEGORIES "algorithm/3d;algorithm/virtual_reality" CACHE INTERNAL "")
set(qhull_AUTHORS "C. Bradford Barber and Hannu Huhdanpaa" CACHE INTERNAL "")
set(qhull_PROJECT_SITE http://www.qhull.org/ CACHE INTERNAL "")
set(qhull_LICENSES Qhull License CACHE INTERNAL "")
set(qhull_REFERENCES  CACHE INTERNAL "")
