#### referencing package reflexxes mode ####
set(reflexxes_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(reflexxes_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(reflexxes_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(reflexxes_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(reflexxes_DESCRIPTION PID Wrapper for the Reflexxes Type-II library CACHE INTERNAL "")
set(reflexxes_YEARS 2015 CACHE INTERNAL "")
set(reflexxes_LICENSE CeCILL-C CACHE INTERNAL "")
set(reflexxes_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/reflexxes.git CACHE INTERNAL "")
set(reflexxes_CATEGORIES "motion/trajectory" CACHE INTERNAL "")
set(reflexxes_AVAILABLE_PLATFORMS linux64cxx11;linux64;linux32;macosx64 CACHE INTERNAL "")
set(reflexxes_AVAILABLE_PLATFORM_linux64cxx11_OS linux CACHE INTERNAL "")
set(reflexxes_AVAILABLE_PLATFORM_linux64cxx11_ARCH 64 CACHE INTERNAL "")
set(reflexxes_AVAILABLE_PLATFORM_linux64cxx11_ABI CXX11 CACHE INTERNAL "")
set(reflexxes_AVAILABLE_PLATFORM_linux64cxx11_CONFIGURATION  CACHE INTERNAL "")
set(reflexxes_AVAILABLE_PLATFORM_linux64_OS linux CACHE INTERNAL "")
set(reflexxes_AVAILABLE_PLATFORM_linux64_ARCH 64 CACHE INTERNAL "")
set(reflexxes_AVAILABLE_PLATFORM_linux64_ABI CXX CACHE INTERNAL "")
set(reflexxes_AVAILABLE_PLATFORM_linux64_CONFIGURATION  CACHE INTERNAL "")
set(reflexxes_AVAILABLE_PLATFORM_linux32_OS linux CACHE INTERNAL "")
set(reflexxes_AVAILABLE_PLATFORM_linux32_ARCH 32 CACHE INTERNAL "")
set(reflexxes_AVAILABLE_PLATFORM_linux32_ABI CXX CACHE INTERNAL "")
set(reflexxes_AVAILABLE_PLATFORM_linux32_CONFIGURATION  CACHE INTERNAL "")
set(reflexxes_AVAILABLE_PLATFORM_macosx64_OS macosx CACHE INTERNAL "")
set(reflexxes_AVAILABLE_PLATFORM_macosx64_ARCH 64 CACHE INTERNAL "")
set(reflexxes_AVAILABLE_PLATFORM_macosx64_ABI CXX CACHE INTERNAL "")
set(reflexxes_AVAILABLE_PLATFORM_macosx64_CONFIGURATION  CACHE INTERNAL "")
set(reflexxes_REFERENCES 1.2.1 CACHE INTERNAL "")
set(reflexxes_REFERENCE_1.2.1 linux64;linux64cxx11 CACHE INTERNAL "")
set(reflexxes_REFERENCE_1.2.1_linux64_URL https://gite.lirmm.fr/rob-miscellaneous/rob-miscellaneous-binaries/wikis/reflexxes/1.2.1/linux64/reflexxes-1.2.1-linux64.tar.gz CACHE INTERNAL "")
set(reflexxes_REFERENCE_1.2.1_linux64_URL_DEBUG https://gite.lirmm.fr/rob-miscellaneous/rob-miscellaneous-binaries/wikis/reflexxes/1.2.1/linux64/reflexxes-1.2.1-dbg-linux64.tar.gz CACHE INTERNAL "")
set(reflexxes_REFERENCE_1.2.1_linux64cxx11_URL https://gite.lirmm.fr/rob-miscellaneous/rob-miscellaneous-binaries/wikis/reflexxes/1.2.1/linux64cxx11/reflexxes-1.2.1-linux64cxx11.tar.gz CACHE INTERNAL "")
set(reflexxes_REFERENCE_1.2.1_linux64cxx11_URL_DEBUG https://gite.lirmm.fr/rob-miscellaneous/rob-miscellaneous-binaries/wikis/reflexxes/1.2.1/linux64cxx11/reflexxes-1.2.1-dbg-linux64cxx11.tar.gz CACHE INTERNAL "")
