#### referencing package pioneer3DX-driver mode ####
set(pioneer3DX-driver_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(pioneer3DX-driver_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(pioneer3DX-driver_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(pioneer3DX-driver_FRAMEWORK  CACHE INTERNAL "")
set(pioneer3DX-driver_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(pioneer3DX-driver_PROJECT_PAGE  CACHE INTERNAL "")
set(pioneer3DX-driver_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(pioneer3DX-driver_SITE_INTRODUCTION  CACHE INTERNAL "")
set(pioneer3DX-driver_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(pioneer3DX-driver_DESCRIPTION "Driver software for Pioneer 3DX robot" CACHE INTERNAL "")
set(pioneer3DX-driver_YEARS 2017 CACHE INTERNAL "")
set(pioneer3DX-driver_LICENSE CeCILL-C CACHE INTERNAL "")
set(pioneer3DX-driver_ADDRESS git@gite.lirmm.fr:pioneer3DX/pioneer3DX-driver.git CACHE INTERNAL "")
set(pioneer3DX-driver_PUBLIC_ADDRESS https://gite.lirmm.fr/pioneer3DX/pioneer3DX-driver.git CACHE INTERNAL "")
set(pioneer3DX-driver_CATEGORIES CACHE INTERNAL "")
set(pioneer3DX-driver_REFERENCES  CACHE INTERNAL "")
