#### referencing wrapper of external package tinyxml2 ####
set(tinyxml2_PID_WRAPPER_CONTACT_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(tinyxml2_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(tinyxml2_PID_WRAPPER_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(tinyxml2_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(tinyxml2_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/pid/tinyxml2 CACHE INTERNAL "")
set(tinyxml2_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(tinyxml2_PID_WRAPPER_SITE_INTRODUCTION tinyxml2;is;a;PID;wrapper;for;the;external;project;called;TinyXML-2.;TinyXML-2;is;a;simple,;small,;efficient,;C++;XML;parser;that;can;be;easily;integrated;into;other;programs. CACHE INTERNAL "")
set(tinyxml2_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr)" CACHE INTERNAL "")
set(tinyxml2_PID_WRAPPER_YEARS 2018 CACHE INTERNAL "")
set(tinyxml2_PID_WRAPPER_LICENSE GNULGPL CACHE INTERNAL "")
set(tinyxml2_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:pid/tinyxml2.git CACHE INTERNAL "")
set(tinyxml2_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/tinyxml2.git CACHE INTERNAL "")
set(tinyxml2_DESCRIPTION "TinyXML-2 is a simple, small, efficient, C++ XML parser. Repackaged for PID" CACHE INTERNAL "")
set(tinyxml2_FRAMEWORK pid CACHE INTERNAL "")
set(tinyxml2_CATEGORIES "programming/parser" CACHE INTERNAL "")
set(tinyxml2_AUTHORS "Lee Thomason" CACHE INTERNAL "")
set(tinyxml2_PROJECT_SITE https://github.com/leethomason/tinyxml2 CACHE INTERNAL "")
set(tinyxml2_LICENSES zlib CACHE INTERNAL "")
set(tinyxml2_REFERENCES  CACHE INTERNAL "")
