#### referencing package libfranka mode ####
set(libfranka_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(libfranka_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(libfranka_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(libfranka_FRAMEWORK rpc CACHE INTERNAL "")
set(libfranka_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(libfranka_PROJECT_PAGE https://gite.lirmm.fr/rob-miscellaneous/drivers/libfranka.git CACHE INTERNAL "")
set(libfranka_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(libfranka_SITE_INTRODUCTION "PID repackaging of libfranka (https://github.com/frankaemika/libfranka): a C++ library for Franka Emika research robots." CACHE INTERNAL "")
set(libfranka_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM);_Florian_Walsh(_Franka_Emika);_Simon_Gabl(_Franka_Emika)" CACHE INTERNAL "")
set(libfranka_DESCRIPTION "PID wrapper for the libfranka library" CACHE INTERNAL "")
set(libfranka_YEARS 2019 CACHE INTERNAL "")
set(libfranka_LICENSE Apache CACHE INTERNAL "")
set(libfranka_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/drivers/libfranka.git CACHE INTERNAL "")
set(libfranka_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/drivers/libfranka.git CACHE INTERNAL "")
set(libfranka_CATEGORIES "driver/robot" CACHE INTERNAL "")
set(libfranka_REFERENCES  CACHE INTERNAL "")
