#### referencing package hokuyo-driver mode ####
set(hokuyo-driver_MAIN_AUTHOR _Robin_Passama_INSTUTION_LIRMM CACHE INTERNAL "")
set(hokuyo-driver_MAIN_INSTITUTION  CACHE INTERNAL "")
set(hokuyo-driver_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(hokuyo-driver_FRAMEWORK  CACHE INTERNAL "")
set(hokuyo-driver_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(hokuyo-driver_PROJECT_PAGE  CACHE INTERNAL "")
set(hokuyo-driver_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(hokuyo-driver_SITE_INTRODUCTION  CACHE INTERNAL "")
set(hokuyo-driver_AUTHORS_AND_INSTITUTIONS "_Robin_Passama_INSTUTION_LIRMM()" CACHE INTERNAL "")
set(hokuyo-driver_DESCRIPTION a little library that wraps URG library to manage hokuyo laser scanners CACHE INTERNAL "")
set(hokuyo-driver_YEARS 2015 CACHE INTERNAL "")
set(hokuyo-driver_LICENSE CeCILL-C CACHE INTERNAL "")
set(hokuyo-driver_ADDRESS git@gite.lirmm.fr:rob-vision-devices/hokuyo-driver.git CACHE INTERNAL "")
set(hokuyo-driver_CATEGORIES "laser-scanners/driver" CACHE INTERNAL "")
set(hokuyo-driver_REFERENCES  CACHE INTERNAL "")
