#### referencing package nanomsgxx mode ####
set(nanomsgxx_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(nanomsgxx_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(nanomsgxx_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(nanomsgxx_FRAMEWORK  CACHE INTERNAL "")
set(nanomsgxx_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(nanomsgxx_PROJECT_PAGE  CACHE INTERNAL "")
set(nanomsgxx_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(nanomsgxx_SITE_INTRODUCTION  CACHE INTERNAL "")
set(nanomsgxx_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM);_Achille_Roussel(_achille.roussel@gmail.com)" CACHE INTERNAL "")
set(nanomsgxx_DESCRIPTION "nanomsgxx;is;a;binding;of;the;nanomsg;library;for;C++11.;Repackaged;for;PID." CACHE INTERNAL "")
set(nanomsgxx_YEARS 2019 CACHE INTERNAL "")
set(nanomsgxx_LICENSE MIT CACHE INTERNAL "")
set(nanomsgxx_ADDRESS git@gite.lirmm.fr:pid/nanomsgxx.git CACHE INTERNAL "")
set(nanomsgxx_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/nanomsgxx.git CACHE INTERNAL "")
set(nanomsgxx_CATEGORIES CACHE INTERNAL "")
set(nanomsgxx_REFERENCES  CACHE INTERNAL "")
