#### referencing package hardio_flasher mode ####
set(hardio_flasher_MAIN_AUTHOR _JoseL_VilchisM CACHE INTERNAL "")
set(hardio_flasher_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(hardio_flasher_CONTACT_MAIL jlvilchismedina@lirmm.fr CACHE INTERNAL "")
set(hardio_flasher_FRAMEWORK  CACHE INTERNAL "")
set(hardio_flasher_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(hardio_flasher_PROJECT_PAGE  CACHE INTERNAL "")
set(hardio_flasher_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(hardio_flasher_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(hardio_flasher_AUTHORS_AND_INSTITUTIONS "_JoseL_VilchisM(_LIRMM)" CACHE INTERNAL "")
set(hardio_flasher_DESCRIPTION "TODO:;input;a;short;description;of;package;hardio_flasher;utility;here" CACHE INTERNAL "")
set(hardio_flasher_YEARS 2019 CACHE INTERNAL "")
set(hardio_flasher_LICENSE CeCILL CACHE INTERNAL "")
set(hardio_flasher_ADDRESS git@gite.lirmm.fr:hardio/devices/hardio_flasher.git CACHE INTERNAL "")
set(hardio_flasher_PUBLIC_ADDRESS https://gite.lirmm.fr/hardio/devices/hardio_flasher.git CACHE INTERNAL "")
set(hardio_flasher_CATEGORIES CACHE INTERNAL "")
set(hardio_flasher_REFERENCES  CACHE INTERNAL "")
