#### referencing framework rkcl-framework mode ####
set(rkcl-framework_FRAMEWORK_MAIN_AUTHOR _Sonny_Tarbouriech CACHE INTERNAL "")
set(rkcl-framework_FRAMEWORK_MAIN_INSTITUTION  CACHE INTERNAL "")
set(rkcl-framework_FRAMEWORK_YEARS 2020 CACHE INTERNAL "")
set(rkcl-framework_FRAMEWORK_CONTACT_MAIL  CACHE INTERNAL "")
set(rkcl-framework_FRAMEWORK_SITE http://rkcl.lirmm.net/rkcl-framework CACHE INTERNAL "")
set(rkcl-framework_FRAMEWORK_PROJECT_PAGE https://gite.lirmm.fr/rkcl/rkcl-framework CACHE INTERNAL "")
set(rkcl-framework_FRAMEWORK_DESCRIPTION Framework for the Robot Kinematic Control Library (RKCL) CACHE INTERNAL "")
set(rkcl-framework_FRAMEWORK_LICENSE CeCILL CACHE INTERNAL "")
set(rkcl-framework_FRAMEWORK_ADDRESS git@gitlab.com:rkcl/rkcl-framework.git CACHE INTERNAL "")
set(rkcl-framework_FRAMEWORK_AUTHORS_AND_INSTITUTIONS "_Sonny_Tarbouriech" CACHE INTERNAL "")
set(rkcl-framework_FRAMEWORK_CATEGORIES "core;processor;driver;robot;application;solver" CACHE INTERNAL "")
