#### referencing package rkcl-core mode ####
set(rkcl-core_MAIN_AUTHOR _Sonny_Tarbouriech CACHE INTERNAL "")
set(rkcl-core_MAIN_INSTITUTION _Tecnalia CACHE INTERNAL "")
set(rkcl-core_CONTACT_MAIL  CACHE INTERNAL "")
set(rkcl-core_FRAMEWORK rkcl-framework CACHE INTERNAL "")
set(rkcl-core_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rkcl-core_PROJECT_PAGE https://gite.lirmm.fr/rkcl/rkcl-core CACHE INTERNAL "")
set(rkcl-core_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rkcl-core_SITE_INTRODUCTION "Core;of;the;Robot;Kinematic;Control;Library." CACHE INTERNAL "")
set(rkcl-core_AUTHORS_AND_INSTITUTIONS "_Sonny_Tarbouriech(_Tecnalia);_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(rkcl-core_DESCRIPTION "Core;of;the;Robot;Kinematic;Control;Library." CACHE INTERNAL "")
set(rkcl-core_YEARS 2018 CACHE INTERNAL "")
set(rkcl-core_LICENSE CeCILL CACHE INTERNAL "")
set(rkcl-core_ADDRESS git@gite.lirmm.fr:rkcl/rkcl-core.git CACHE INTERNAL "")
set(rkcl-core_PUBLIC_ADDRESS https://gite.lirmm.fr/rkcl/rkcl-core.git CACHE INTERNAL "")
set(rkcl-core_CATEGORIES "core" CACHE INTERNAL "")
set(rkcl-core_REFERENCES  CACHE INTERNAL "")
