#### referencing package Pioneer_datas mode ####
set(Pioneer_datas_MAIN_AUTHOR _philippe CACHE INTERNAL "")
set(Pioneer_datas_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(Pioneer_datas_CONTACT_MAIL  CACHE INTERNAL "")
set(Pioneer_datas_FRAMEWORK  CACHE INTERNAL "")
set(Pioneer_datas_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(Pioneer_datas_PROJECT_PAGE  CACHE INTERNAL "")
set(Pioneer_datas_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(Pioneer_datas_SITE_INTRODUCTION  CACHE INTERNAL "")
set(Pioneer_datas_AUTHORS_AND_INSTITUTIONS "_philippe(_LIRMM)" CACHE INTERNAL "")
set(Pioneer_datas_DESCRIPTION "Library to describe every data structure exchanged in Pioneer3DX Contract2 architecture." CACHE INTERNAL "")
set(Pioneer_datas_YEARS 2018 CACHE INTERNAL "")
set(Pioneer_datas_LICENSE CeCILL CACHE INTERNAL "")
set(Pioneer_datas_ADDRESS git@gite.lirmm.fr:pioneer3DX/Pioneer_datas.git CACHE INTERNAL "")
set(Pioneer_datas_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(Pioneer_datas_CATEGORIES CACHE INTERNAL "")
set(Pioneer_datas_REFERENCES  CACHE INTERNAL "")
