#### referencing package comedilib mode ####
set(comedilib_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(comedilib_MAIN_INSTITUTION _University_of_Montpellier_/_LIRMM CACHE INTERNAL "")
set(comedilib_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(comedilib_FRAMEWORK rpc CACHE INTERNAL "")
set(comedilib_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(comedilib_PROJECT_PAGE https://gite.lirmm.fr/rob-miscellaneous/comedilib CACHE INTERNAL "")
set(comedilib_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(comedilib_SITE_INTRODUCTION "PID repackaging of Comedi project (http://comedi.org/): interface for control and measurement device on linux. Mainly used to manage PCI acquisition cards to acquire data coming from force sensors." CACHE INTERNAL "")
set(comedilib_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_University_of_Montpellier_/_LIRMM);_Robin_Passama(_CNRS/LIRMM)" CACHE INTERNAL "")
set(comedilib_DESCRIPTION "PID repackaging of Comedi project (http://comedi.org/): interface for control and measurement device on linux. Mainly used to manage PCI acquisition cards." CACHE INTERNAL "")
set(comedilib_YEARS 2015 CACHE INTERNAL "")
set(comedilib_LICENSE CeCILL-C CACHE INTERNAL "")
set(comedilib_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/comedilib.git CACHE INTERNAL "")
set(comedilib_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/comedilib.git CACHE INTERNAL "")
set(comedilib_CATEGORIES "driver/electronic_device" CACHE INTERNAL "")
set(comedilib_REFERENCES  CACHE INTERNAL "")
