#### referencing package rkcl-app-utility mode ####
set(rkcl-app-utility_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(rkcl-app-utility_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(rkcl-app-utility_CONTACT_MAIL  CACHE INTERNAL "")
set(rkcl-app-utility_FRAMEWORK rkcl-framework CACHE INTERNAL "")
set(rkcl-app-utility_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rkcl-app-utility_PROJECT_PAGE https://gite.lirmm.fr/rkcl/rkcl-app-utility CACHE INTERNAL "")
set(rkcl-app-utility_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rkcl-app-utility_SITE_INTRODUCTION "Utility;to;ease;the;creation;of;applications;based;on;RKCL." CACHE INTERNAL "")
set(rkcl-app-utility_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM);_Sonny_Tarbouriech(_LIRMM)" CACHE INTERNAL "")
set(rkcl-app-utility_DESCRIPTION "Utility;to;ease;the;creation;of;applications;based;on;RKCL." CACHE INTERNAL "")
set(rkcl-app-utility_YEARS 2019 CACHE INTERNAL "")
set(rkcl-app-utility_LICENSE CeCILL CACHE INTERNAL "")
set(rkcl-app-utility_ADDRESS git@gite.lirmm.fr:rkcl/rkcl-app-utility.git CACHE INTERNAL "")
set(rkcl-app-utility_PUBLIC_ADDRESS https://gite.lirmm.fr/rkcl/rkcl-app-utility.git CACHE INTERNAL "")
set(rkcl-app-utility_CATEGORIES "core" CACHE INTERNAL "")
set(rkcl-app-utility_REFERENCES  CACHE INTERNAL "")
