#### referencing package imu mode ####
set(imu_MAIN_AUTHOR _Charles_Villard CACHE INTERNAL "")
set(imu_MAIN_INSTITUTION  CACHE INTERNAL "")
set(imu_CONTACT_MAIL  CACHE INTERNAL "")
set(imu_FRAMEWORK  CACHE INTERNAL "")
set(imu_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(imu_PROJECT_PAGE  CACHE INTERNAL "")
set(imu_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(imu_SITE_INTRODUCTION  CACHE INTERNAL "")
set(imu_AUTHORS_AND_INSTITUTIONS "_Charles_Villard()" CACHE INTERNAL "")
set(imu_DESCRIPTION "This;tool;use;an;IMU;driver;calibrate;the;sensors;and;do;fusion;of;sensors" CACHE INTERNAL "")
set(imu_YEARS 2018 CACHE INTERNAL "")
set(imu_LICENSE CeCILL CACHE INTERNAL "")
set(imu_ADDRESS git@gite.lirmm.fr:explore-rov/tools/imu.git CACHE INTERNAL "")
set(imu_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(imu_CATEGORIES CACHE INTERNAL "")
set(imu_REFERENCES  CACHE INTERNAL "")
