#### referencing package physical-quantities mode ####
set(physical-quantities_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(physical-quantities_MAIN_INSTITUTION _LIRMM_/_CNRS CACHE INTERNAL "")
set(physical-quantities_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(physical-quantities_FRAMEWORK rpc CACHE INTERNAL "")
set(physical-quantities_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(physical-quantities_PROJECT_PAGE https://gite.lirmm.fr/rob-miscellaneous/physical-quantities CACHE INTERNAL "")
set(physical-quantities_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(physical-quantities_SITE_INTRODUCTION "Provides common scalar and spatial physical quantities types as well as unit conversion facilities." CACHE INTERNAL "")
set(physical-quantities_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM_/_CNRS)" CACHE INTERNAL "")
set(physical-quantities_DESCRIPTION "Provides;common;scalar;and;spatial;physical;quantities;types;as;well;as;unit;conversion;facilities" CACHE INTERNAL "")
set(physical-quantities_YEARS 2019 CACHE INTERNAL "")
set(physical-quantities_LICENSE CeCILL CACHE INTERNAL "")
set(physical-quantities_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/physical-quantities.git CACHE INTERNAL "")
set(physical-quantities_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/physical-quantities.git CACHE INTERNAL "")
set(physical-quantities_CATEGORIES "algorithm/math" CACHE INTERNAL "")
set(physical-quantities_REFERENCES  CACHE INTERNAL "")
