#### referencing package cobot-mobile-manipulation-RPY mode ####
set(cobot-mobile-manipulation-RPY_MAIN_AUTHOR _Mohamed_Sorour CACHE INTERNAL "")
set(cobot-mobile-manipulation-RPY_MAIN_INSTITUTION  CACHE INTERNAL "")
set(cobot-mobile-manipulation-RPY_CONTACT_MAIL  CACHE INTERNAL "")
set(cobot-mobile-manipulation-RPY_FRAMEWORK  CACHE INTERNAL "")
set(cobot-mobile-manipulation-RPY_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(cobot-mobile-manipulation-RPY_PROJECT_PAGE  CACHE INTERNAL "")
set(cobot-mobile-manipulation-RPY_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(cobot-mobile-manipulation-RPY_SITE_INTRODUCTION  CACHE INTERNAL "")
set(cobot-mobile-manipulation-RPY_AUTHORS_AND_INSTITUTIONS "_Mohamed_Sorour()" CACHE INTERNAL "")
set(cobot-mobile-manipulation-RPY_DESCRIPTION TODO CACHE INTERNAL "")
set(cobot-mobile-manipulation-RPY_YEARS 2017 CACHE INTERNAL "")
set(cobot-mobile-manipulation-RPY_LICENSE CeCILL CACHE INTERNAL "")
set(cobot-mobile-manipulation-RPY_ADDRESS git@gite.lirmm.fr:cobot/cobot-mobile-manipulation-RPY.git CACHE INTERNAL "")
set(cobot-mobile-manipulation-RPY_CATEGORIES CACHE INTERNAL "")
set(cobot-mobile-manipulation-RPY_REFERENCES  CACHE INTERNAL "")
