#### referencing package rkcl-driver-panda mode ####
set(rkcl-driver-panda_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(rkcl-driver-panda_MAIN_INSTITUTION _LIRMM_/_CNRS CACHE INTERNAL "")
set(rkcl-driver-panda_CONTACT_MAIL  CACHE INTERNAL "")
set(rkcl-driver-panda_FRAMEWORK  CACHE INTERNAL "")
set(rkcl-driver-panda_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rkcl-driver-panda_PROJECT_PAGE  CACHE INTERNAL "")
set(rkcl-driver-panda_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rkcl-driver-panda_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(rkcl-driver-panda_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM_/_CNRS)" CACHE INTERNAL "")
set(rkcl-driver-panda_DESCRIPTION "RKCL;driver;for;the;Franka;Panda;robot" CACHE INTERNAL "")
set(rkcl-driver-panda_YEARS 2019 CACHE INTERNAL "")
set(rkcl-driver-panda_LICENSE CeCILL CACHE INTERNAL "")
set(rkcl-driver-panda_ADDRESS git@gitlab.com:rkcl/rkcl-driver-panda.git CACHE INTERNAL "")
set(rkcl-driver-panda_PUBLIC_ADDRESS https://gitlab.com/rkcl/rkcl-driver-panda.git CACHE INTERNAL "")
set(rkcl-driver-panda_CATEGORIES CACHE INTERNAL "")
set(rkcl-driver-panda_REFERENCES  CACHE INTERNAL "")
