#### referencing package shadow-hand-knowbotics mode ####
set(shadow-hand-knowbotics_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(shadow-hand-knowbotics_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(shadow-hand-knowbotics_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(shadow-hand-knowbotics_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)";"_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(shadow-hand-knowbotics_DESCRIPTION A package that describes the Shadow Dexterous Hand as a Knowbotics object CACHE INTERNAL "")
set(shadow-hand-knowbotics_YEARS 2015 CACHE INTERNAL "")
set(shadow-hand-knowbotics_LICENSE CeCILL-C CACHE INTERNAL "")
set(shadow-hand-knowbotics_ADDRESS git@rob-dev.lirmm.fr:shadow-hands/shadow-hand-knowbotics.git CACHE INTERNAL "")
set(shadow-hand-knowbotics_CATEGORIES robot/hand;driver/hand CACHE INTERNAL "")
set(shadow-hand-knowbotics_REFERENCES  CACHE INTERNAL "")
