#### referencing package dsp-filters mode ####
set(dsp-filters_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(dsp-filters_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(dsp-filters_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(dsp-filters_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(dsp-filters_DESCRIPTION Wrapper for https://github.com/vinniefalco/DSPFilters CACHE INTERNAL "")
set(dsp-filters_YEARS 2016 CACHE INTERNAL "")
set(dsp-filters_LICENSE CeCILL-C CACHE INTERNAL "")
set(dsp-filters_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/dsp-filters.git CACHE INTERNAL "")
set(dsp-filters_CATEGORIES CACHE INTERNAL "")
set(dsp-filters_AVAILABLE_PLATFORMS linux64cxx11;linux64;linux32;macosx64 CACHE INTERNAL "")
set(dsp-filters_AVAILABLE_PLATFORM_linux64cxx11_OS linux CACHE INTERNAL "")
set(dsp-filters_AVAILABLE_PLATFORM_linux64cxx11_ARCH 64 CACHE INTERNAL "")
set(dsp-filters_AVAILABLE_PLATFORM_linux64cxx11_ABI CXX11 CACHE INTERNAL "")
set(dsp-filters_AVAILABLE_PLATFORM_linux64cxx11_CONFIGURATION  CACHE INTERNAL "")
set(dsp-filters_AVAILABLE_PLATFORM_linux64_OS linux CACHE INTERNAL "")
set(dsp-filters_AVAILABLE_PLATFORM_linux64_ARCH 64 CACHE INTERNAL "")
set(dsp-filters_AVAILABLE_PLATFORM_linux64_ABI CXX CACHE INTERNAL "")
set(dsp-filters_AVAILABLE_PLATFORM_linux64_CONFIGURATION  CACHE INTERNAL "")
set(dsp-filters_AVAILABLE_PLATFORM_linux32_OS linux CACHE INTERNAL "")
set(dsp-filters_AVAILABLE_PLATFORM_linux32_ARCH 32 CACHE INTERNAL "")
set(dsp-filters_AVAILABLE_PLATFORM_linux32_ABI CXX CACHE INTERNAL "")
set(dsp-filters_AVAILABLE_PLATFORM_linux32_CONFIGURATION  CACHE INTERNAL "")
set(dsp-filters_AVAILABLE_PLATFORM_macosx64_OS macosx CACHE INTERNAL "")
set(dsp-filters_AVAILABLE_PLATFORM_macosx64_ARCH 64 CACHE INTERNAL "")
set(dsp-filters_AVAILABLE_PLATFORM_macosx64_ABI CXX CACHE INTERNAL "")
set(dsp-filters_AVAILABLE_PLATFORM_macosx64_CONFIGURATION  CACHE INTERNAL "")
set(dsp-filters_REFERENCES  CACHE INTERNAL "")
