#### referencing package robotics-library mode ####
set(robotics-library_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(robotics-library_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(robotics-library_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(robotics-library_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(robotics-library_DESCRIPTION PID wrapper for Robotics Libraryi (http://www.roboticslibrary.org) CACHE INTERNAL "")
set(robotics-library_YEARS 2015 CACHE INTERNAL "")
set(robotics-library_LICENSE CeCILL-C CACHE INTERNAL "")
set(robotics-library_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/robotics-library.git CACHE INTERNAL "")
set(robotics-library_CATEGORIES "motion/trajectory" CACHE INTERNAL "")
set(robotics-library_AVAILABLE_PLATFORMS linux64cxx11;linux64;linux32;macosx64 CACHE INTERNAL "")
set(robotics-library_AVAILABLE_PLATFORM_linux64cxx11_OS linux CACHE INTERNAL "")
set(robotics-library_AVAILABLE_PLATFORM_linux64cxx11_ARCH 64 CACHE INTERNAL "")
set(robotics-library_AVAILABLE_PLATFORM_linux64cxx11_ABI CXX11 CACHE INTERNAL "")
set(robotics-library_AVAILABLE_PLATFORM_linux64cxx11_CONFIGURATION  CACHE INTERNAL "")
set(robotics-library_AVAILABLE_PLATFORM_linux64_OS linux CACHE INTERNAL "")
set(robotics-library_AVAILABLE_PLATFORM_linux64_ARCH 64 CACHE INTERNAL "")
set(robotics-library_AVAILABLE_PLATFORM_linux64_ABI CXX CACHE INTERNAL "")
set(robotics-library_AVAILABLE_PLATFORM_linux64_CONFIGURATION  CACHE INTERNAL "")
set(robotics-library_AVAILABLE_PLATFORM_linux32_OS linux CACHE INTERNAL "")
set(robotics-library_AVAILABLE_PLATFORM_linux32_ARCH 32 CACHE INTERNAL "")
set(robotics-library_AVAILABLE_PLATFORM_linux32_ABI CXX CACHE INTERNAL "")
set(robotics-library_AVAILABLE_PLATFORM_linux32_CONFIGURATION  CACHE INTERNAL "")
set(robotics-library_AVAILABLE_PLATFORM_macosx64_OS macosx CACHE INTERNAL "")
set(robotics-library_AVAILABLE_PLATFORM_macosx64_ARCH 64 CACHE INTERNAL "")
set(robotics-library_AVAILABLE_PLATFORM_macosx64_ABI CXX CACHE INTERNAL "")
set(robotics-library_AVAILABLE_PLATFORM_macosx64_CONFIGURATION  CACHE INTERNAL "")
set(robotics-library_REFERENCES 0.6.1 CACHE INTERNAL "")
set(robotics-library_REFERENCE_0.6.1 linux64;linux64cxx11 CACHE INTERNAL "")
set(robotics-library_REFERENCE_0.6.1_linux64_URL https://gite.lirmm.fr/rob-miscellaneous/rob-miscellaneous-binaries/wikis/robotics-library/0.6.1/linux64/robotics-library-0.6.1-linux64.tar.gz CACHE INTERNAL "")
set(robotics-library_REFERENCE_0.6.1_linux64_URL_DEBUG https://gite.lirmm.fr/rob-miscellaneous/rob-miscellaneous-binaries/wikis/robotics-library/0.6.1/linux64/robotics-library-0.6.1-dbg-linux64.tar.gz CACHE INTERNAL "")
set(robotics-library_REFERENCE_0.6.1_linux64cxx11_URL https://gite.lirmm.fr/rob-miscellaneous/rob-miscellaneous-binaries/wikis/robotics-library/0.6.1/linux64cxx11/robotics-library-0.6.1-linux64cxx11.tar.gz CACHE INTERNAL "")
set(robotics-library_REFERENCE_0.6.1_linux64cxx11_URL_DEBUG https://gite.lirmm.fr/rob-miscellaneous/rob-miscellaneous-binaries/wikis/robotics-library/0.6.1/linux64cxx11/robotics-library-0.6.1-dbg-linux64cxx11.tar.gz CACHE INTERNAL "")
