#### referencing package eigen-extensions mode ####
set(eigen-extensions_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(eigen-extensions_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(eigen-extensions_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(eigen-extensions_FRAMEWORK  CACHE INTERNAL "")
set(eigen-extensions_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(eigen-extensions_PROJECT_PAGE  CACHE INTERNAL "")
set(eigen-extensions_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(eigen-extensions_SITE_INTRODUCTION  CACHE INTERNAL "")
set(eigen-extensions_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(eigen-extensions_DESCRIPTION Declare several extensions for the Eigen library (e.g. pseudo-inverse, skew-symmetric matrix, etc) CACHE INTERNAL "")
set(eigen-extensions_YEARS 2015 CACHE INTERNAL "")
set(eigen-extensions_LICENSE CeCILL-C CACHE INTERNAL "")
set(eigen-extensions_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/eigen-extensions.git CACHE INTERNAL "")
set(eigen-extensions_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/eigen-extensions.git CACHE INTERNAL "")
set(eigen-extensions_CATEGORIES "math/linear_algebra" CACHE INTERNAL "")
set(eigen-extensions_REFERENCES  CACHE INTERNAL "")
