#### referencing package my-first-package mode ####
set(my-first-package_MAIN_AUTHOR _philippe CACHE INTERNAL "")
set(my-first-package_MAIN_INSTITUTION  CACHE INTERNAL "")
set(my-first-package_CONTACT_MAIL  CACHE INTERNAL "")
set(my-first-package_FRAMEWORK  CACHE INTERNAL "")
set(my-first-package_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(my-first-package_PROJECT_PAGE  CACHE INTERNAL "")
set(my-first-package_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(my-first-package_SITE_INTRODUCTION  CACHE INTERNAL "")
set(my-first-package_AUTHORS_AND_INSTITUTIONS "_philippe()" CACHE INTERNAL "")
set(my-first-package_DESCRIPTION My 'first' package CACHE INTERNAL "")
set(my-first-package_YEARS 2017 CACHE INTERNAL "")
set(my-first-package_LICENSE CeCILL CACHE INTERNAL "")
set(my-first-package_ADDRESS git@gite.lirmm.fr:plambert/my-first-package.git CACHE INTERNAL "")
set(my-first-package_CATEGORIES CACHE INTERNAL "")
set(my-first-package_REFERENCES  CACHE INTERNAL "")
