#### referencing package hardio_mavlink mode ####
set(hardio_mavlink_MAIN_AUTHOR _Clement_Rebut CACHE INTERNAL "")
set(hardio_mavlink_MAIN_INSTITUTION  CACHE INTERNAL "")
set(hardio_mavlink_CONTACT_MAIL  CACHE INTERNAL "")
set(hardio_mavlink_FRAMEWORK  CACHE INTERNAL "")
set(hardio_mavlink_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(hardio_mavlink_PROJECT_PAGE  CACHE INTERNAL "")
set(hardio_mavlink_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(hardio_mavlink_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(hardio_mavlink_AUTHORS_AND_INSTITUTIONS "_Clement_Rebut()" CACHE INTERNAL "")
set(hardio_mavlink_DESCRIPTION "TODO:;input;a;short;description;of;package;hardio_mavlink;utility;here" CACHE INTERNAL "")
set(hardio_mavlink_YEARS 2019 CACHE INTERNAL "")
set(hardio_mavlink_LICENSE CeCILL CACHE INTERNAL "")
set(hardio_mavlink_ADDRESS git@gite.lirmm.fr:hardio/devices/hardio_mavlink.git CACHE INTERNAL "")
set(hardio_mavlink_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(hardio_mavlink_CATEGORIES CACHE INTERNAL "")
set(hardio_mavlink_REFERENCES  CACHE INTERNAL "")
