#### referencing package metalimbs-robot mode ####
set(metalimbs-robot_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(metalimbs-robot_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(metalimbs-robot_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(metalimbs-robot_FRAMEWORK  CACHE INTERNAL "")
set(metalimbs-robot_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(metalimbs-robot_PROJECT_PAGE  CACHE INTERNAL "")
set(metalimbs-robot_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(metalimbs-robot_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(metalimbs-robot_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(metalimbs-robot_DESCRIPTION "Driver for the Metalimbs robot" CACHE INTERNAL "")
set(metalimbs-robot_YEARS 2019 CACHE INTERNAL "")
set(metalimbs-robot_LICENSE GNUGPL CACHE INTERNAL "")
set(metalimbs-robot_ADDRESS git@gite.lirmm.fr:erato/metalimbs-robot.git CACHE INTERNAL "")
set(metalimbs-robot_PUBLIC_ADDRESS https://gite.lirmm.fr/erato/metalimbs-robot.git CACHE INTERNAL "")
set(metalimbs-robot_CATEGORIES CACHE INTERNAL "")
set(metalimbs-robot_REFERENCES  CACHE INTERNAL "")
