#### referencing wrapper of external package libusb ####
set(libusb_PID_WRAPPER_CONTACT_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(libusb_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(libusb_PID_WRAPPER_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(libusb_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(libusb_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/pid/libusb CACHE INTERNAL "")
set(libusb_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(libusb_PID_WRAPPER_SITE_INTRODUCTION libusb;is;a;PID;wrapper;for;the;external;project;called;libusb.;libusb;is;a;library;for;USB;device;access;from;Linux,;macOS,;Windows,;OpenBSD/NetBSD;and;Haiku;userspace. CACHE INTERNAL "")
set(libusb_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr)" CACHE INTERNAL "")
set(libusb_PID_WRAPPER_YEARS 2018 CACHE INTERNAL "")
set(libusb_PID_WRAPPER_LICENSE GNULGPL CACHE INTERNAL "")
set(libusb_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:pid/libusb.git CACHE INTERNAL "")
set(libusb_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/libusb.git CACHE INTERNAL "")
set(libusb_DESCRIPTION "libusb is a library for USB device access from Linux, macOS, Windows, OpenBSD/NetBSD and Haiku userspace. Repackaged for PID" CACHE INTERNAL "")
set(libusb_FRAMEWORK pid CACHE INTERNAL "")
set(libusb_CATEGORIES "programming/io" CACHE INTERNAL "")
set(libusb_AUTHORS "Hans de Goede, Xiaofan Chen, Ludovic Rousseau, Nathan Hjelm and Chris Dickens" CACHE INTERNAL "")
set(libusb_PROJECT_SITE http://libusb.info/ CACHE INTERNAL "")
set(libusb_LICENSES GNULGPL CACHE INTERNAL "")
set(libusb_REFERENCES  CACHE INTERNAL "")
