#### referencing package fes-knowbotics mode ####
set(fes-knowbotics_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(fes-knowbotics_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(fes-knowbotics_CONTACT_MAIL  CACHE INTERNAL "")
set(fes-knowbotics_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(fes-knowbotics_DESCRIPTION Package containg generic kbot types, concepts and processors for the Functional Electrical Stimulation domain. CACHE INTERNAL "")
set(fes-knowbotics_YEARS 2016 CACHE INTERNAL "")
set(fes-knowbotics_LICENSE CeCILL-C CACHE INTERNAL "")
set(fes-knowbotics_ADDRESS git@gite.lirmm.fr:knowbotics/fes-knowbotics.git CACHE INTERNAL "")
set(fes-knowbotics_CATEGORIES "knowbotics/fes" CACHE INTERNAL "")
set(fes-knowbotics_AVAILABLE_PLATFORMS linux64cxx11;linux64;linux32;macosx64 CACHE INTERNAL "")
set(fes-knowbotics_AVAILABLE_PLATFORM_linux64cxx11_OS linux CACHE INTERNAL "")
set(fes-knowbotics_AVAILABLE_PLATFORM_linux64cxx11_ARCH 64 CACHE INTERNAL "")
set(fes-knowbotics_AVAILABLE_PLATFORM_linux64cxx11_ABI CXX11 CACHE INTERNAL "")
set(fes-knowbotics_AVAILABLE_PLATFORM_linux64cxx11_CONFIGURATION  CACHE INTERNAL "")
set(fes-knowbotics_AVAILABLE_PLATFORM_linux64_OS linux CACHE INTERNAL "")
set(fes-knowbotics_AVAILABLE_PLATFORM_linux64_ARCH 64 CACHE INTERNAL "")
set(fes-knowbotics_AVAILABLE_PLATFORM_linux64_ABI CXX CACHE INTERNAL "")
set(fes-knowbotics_AVAILABLE_PLATFORM_linux64_CONFIGURATION  CACHE INTERNAL "")
set(fes-knowbotics_AVAILABLE_PLATFORM_linux32_OS linux CACHE INTERNAL "")
set(fes-knowbotics_AVAILABLE_PLATFORM_linux32_ARCH 32 CACHE INTERNAL "")
set(fes-knowbotics_AVAILABLE_PLATFORM_linux32_ABI CXX CACHE INTERNAL "")
set(fes-knowbotics_AVAILABLE_PLATFORM_linux32_CONFIGURATION  CACHE INTERNAL "")
set(fes-knowbotics_AVAILABLE_PLATFORM_macosx64_OS macosx CACHE INTERNAL "")
set(fes-knowbotics_AVAILABLE_PLATFORM_macosx64_ARCH 64 CACHE INTERNAL "")
set(fes-knowbotics_AVAILABLE_PLATFORM_macosx64_ABI CXX CACHE INTERNAL "")
set(fes-knowbotics_AVAILABLE_PLATFORM_macosx64_CONFIGURATION  CACHE INTERNAL "")
set(fes-knowbotics_REFERENCES  CACHE INTERNAL "")
