#### referencing wrapper of external package itk ####
set(itk_PID_WRAPPER_CONTACT_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(itk_PID_WRAPPER_CONTACT_INSTITUTION _CNRS/LIRMM CACHE INTERNAL "")
set(itk_PID_WRAPPER_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(itk_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(itk_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/robmed/algorithms/itk CACHE INTERNAL "")
set(itk_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(itk_PID_WRAPPER_SITE_INTRODUCTION "itk;is;a;PID;wrapper;for;theNational;Library;of;Medicine;Insight;Segmentation;and;Registration;Toolkit;project:;an;open-source,;cross-platform;system;that;provides;developers;with;an;extensive;suite;of;software;tools;for;image;analysis." CACHE INTERNAL "")
set(itk_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_CNRS/LIRMM)" CACHE INTERNAL "")
set(itk_PID_WRAPPER_YEARS 2019 CACHE INTERNAL "")
set(itk_PID_WRAPPER_LICENSE CeCILL-C CACHE INTERNAL "")
set(itk_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:robmed/algorithms/itk.git CACHE INTERNAL "")
set(itk_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/robmed/algorithms/itk.git CACHE INTERNAL "")
set(itk_DESCRIPTION "Wrapper;of;the;National;Library;of;Medicine;Insight;Segmentation;and;Registration;Toolkit:;an;open-source,;cross-platform;system;that;provides;developers;with;an;extensive;suite;of;software;tools;for;image;analysis." CACHE INTERNAL "")
set(itk_FRAMEWORK rpc CACHE INTERNAL "")
set(itk_CATEGORIES "algorithm/vision" CACHE INTERNAL "")
set(itk_AUTHORS "InsightSoftwareConsortium" CACHE INTERNAL "")
set(itk_PROJECT_SITE https://itk.org/itkindex.html CACHE INTERNAL "")
set(itk_LICENSES  Apache License Version 2.0 CACHE INTERNAL "")
set(itk_REFERENCES  CACHE INTERNAL "")
