#### referencing package pid mode ####
set(pid_FRAMEWORK_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(pid_FRAMEWORK_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(pid_FRAMEWORK_YEARS 2016 CACHE INTERNAL "")
set(pid_FRAMEWORK_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(pid_FRAMEWORK_SITE http://127.0.0.1:4000 CACHE INTERNAL "")
set(pid_FRAMEWORK_PROJECT_PAGE https://gite.lirmm.fr/passama/pid-framework CACHE INTERNAL "")
set(pid_FRAMEWORK_DESCRIPTION PID is a development methodology supported by a software framework. CACHE INTERNAL "")
set(pid_FRAMEWORK_LICENSE CeCILL-C CACHE INTERNAL "")
set(pid_FRAMEWORK_ADDRESS git@gite.lirmm.fr:passama/pid-framework.git CACHE INTERNAL "")
set(pid_FRAMEWORK_AUTHORS_AND_INSTITUTIONS "_Robin_Passama()" CACHE INTERNAL "")
set(pid_FRAMEWORK_CATEGORIES "programming/resources_management;programming/logging;programming/configuration" CACHE INTERNAL "")
