#### referencing package rkcl-driver-vrep mode ####
set(rkcl-driver-vrep_MAIN_AUTHOR _Sonny_Tarbouriech CACHE INTERNAL "")
set(rkcl-driver-vrep_MAIN_INSTITUTION _Tecnalia CACHE INTERNAL "")
set(rkcl-driver-vrep_CONTACT_MAIL  CACHE INTERNAL "")
set(rkcl-driver-vrep_FRAMEWORK  CACHE INTERNAL "")
set(rkcl-driver-vrep_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rkcl-driver-vrep_PROJECT_PAGE  CACHE INTERNAL "")
set(rkcl-driver-vrep_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rkcl-driver-vrep_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(rkcl-driver-vrep_AUTHORS_AND_INSTITUTIONS "_Sonny_Tarbouriech(_Tecnalia);_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(rkcl-driver-vrep_DESCRIPTION "V-REP;driver;for;RKCL" CACHE INTERNAL "")
set(rkcl-driver-vrep_YEARS 2018 CACHE INTERNAL "")
set(rkcl-driver-vrep_LICENSE CeCILL CACHE INTERNAL "")
set(rkcl-driver-vrep_ADDRESS git@gite.lirmm.fr:rkcl/rkcl-driver-vrep.git CACHE INTERNAL "")
set(rkcl-driver-vrep_PUBLIC_ADDRESS https://gite.lirmm.fr/rkcl/rkcl-driver-vrep.git CACHE INTERNAL "")
set(rkcl-driver-vrep_CATEGORIES CACHE INTERNAL "")
set(rkcl-driver-vrep_REFERENCES  CACHE INTERNAL "")
