#### referencing package rkcl-ur-robot mode ####
set(rkcl-ur-robot_MAIN_AUTHOR _Sonny_Tarbouriech CACHE INTERNAL "")
set(rkcl-ur-robot_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(rkcl-ur-robot_CONTACT_MAIL  CACHE INTERNAL "")
set(rkcl-ur-robot_FRAMEWORK rkcl-framework CACHE INTERNAL "")
set(rkcl-ur-robot_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rkcl-ur-robot_PROJECT_PAGE https://gite.lirmm.fr/rkcl/rkcl-ur-robot CACHE INTERNAL "")
set(rkcl-ur-robot_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rkcl-ur-robot_SITE_INTRODUCTION "Helper;package;to;work;with;Universal;robots;manipulator;arms" CACHE INTERNAL "")
set(rkcl-ur-robot_AUTHORS_AND_INSTITUTIONS "_Sonny_Tarbouriech(_LIRMM)" CACHE INTERNAL "")
set(rkcl-ur-robot_DESCRIPTION "Helper;package;to;work;with;Universal;robots;manipulator;arms" CACHE INTERNAL "")
set(rkcl-ur-robot_YEARS 2020 CACHE INTERNAL "")
set(rkcl-ur-robot_LICENSE CeCILL CACHE INTERNAL "")
set(rkcl-ur-robot_ADDRESS git@gite.lirmm.fr:rkcl/rkcl-ur-robot.git CACHE INTERNAL "")
set(rkcl-ur-robot_PUBLIC_ADDRESS https://gite.lirmm.fr/rkcl/rkcl-ur-robot.git CACHE INTERNAL "")
set(rkcl-ur-robot_CATEGORIES "robot" CACHE INTERNAL "")
set(rkcl-ur-robot_REFERENCES  CACHE INTERNAL "")
