#### referencing package general-utilities mode ####
set(general-utilities_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(general-utilities_MAIN_INSTITUTION  CACHE INTERNAL "")
set(general-utilities_CONTACT_MAIL  CACHE INTERNAL "")
set(general-utilities_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro()" CACHE INTERNAL "")
set(general-utilities_DESCRIPTION A set of pure C++ utilities CACHE INTERNAL "")
set(general-utilities_YEARS 2016 CACHE INTERNAL "")
set(general-utilities_LICENSE CeCILL CACHE INTERNAL "")
set(general-utilities_ADDRESS git@gite.lirmm.fr:pid/general-utilities.git CACHE INTERNAL "")
set(general-utilities_CATEGORIES CACHE INTERNAL "")
set(general-utilities_AVAILABLE_PLATFORMS linux64cxx11;linux64;linux32;macosx64 CACHE INTERNAL "")
set(general-utilities_AVAILABLE_PLATFORM_linux64cxx11_OS linux CACHE INTERNAL "")
set(general-utilities_AVAILABLE_PLATFORM_linux64cxx11_ARCH 64 CACHE INTERNAL "")
set(general-utilities_AVAILABLE_PLATFORM_linux64cxx11_ABI CXX11 CACHE INTERNAL "")
set(general-utilities_AVAILABLE_PLATFORM_linux64cxx11_CONFIGURATION posix CACHE INTERNAL "")
set(general-utilities_AVAILABLE_PLATFORM_linux64_OS linux CACHE INTERNAL "")
set(general-utilities_AVAILABLE_PLATFORM_linux64_ARCH 64 CACHE INTERNAL "")
set(general-utilities_AVAILABLE_PLATFORM_linux64_ABI CXX CACHE INTERNAL "")
set(general-utilities_AVAILABLE_PLATFORM_linux64_CONFIGURATION posix CACHE INTERNAL "")
set(general-utilities_AVAILABLE_PLATFORM_linux32_OS linux CACHE INTERNAL "")
set(general-utilities_AVAILABLE_PLATFORM_linux32_ARCH 32 CACHE INTERNAL "")
set(general-utilities_AVAILABLE_PLATFORM_linux32_ABI CXX CACHE INTERNAL "")
set(general-utilities_AVAILABLE_PLATFORM_linux32_CONFIGURATION posix CACHE INTERNAL "")
set(general-utilities_AVAILABLE_PLATFORM_macosx64_OS macosx CACHE INTERNAL "")
set(general-utilities_AVAILABLE_PLATFORM_macosx64_ARCH 64 CACHE INTERNAL "")
set(general-utilities_AVAILABLE_PLATFORM_macosx64_ABI CXX CACHE INTERNAL "")
set(general-utilities_AVAILABLE_PLATFORM_macosx64_CONFIGURATION posix CACHE INTERNAL "")
set(general-utilities_REFERENCES  CACHE INTERNAL "")
