#### referencing wrapper of external package virtuose-api ####
set(virtuose-api_PID_WRAPPER_CONTACT_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(virtuose-api_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(virtuose-api_PID_WRAPPER_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(virtuose-api_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(virtuose-api_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/rob-miscellaneous/drivers/virtuose-api CACHE INTERNAL "")
set(virtuose-api_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(virtuose-api_PID_WRAPPER_SITE_INTRODUCTION "PID;wrapper;for;the;external;project;called;VirtuoseAPI" CACHE INTERNAL "")
set(virtuose-api_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr)" CACHE INTERNAL "")
set(virtuose-api_PID_WRAPPER_YEARS 2019 CACHE INTERNAL "")
set(virtuose-api_PID_WRAPPER_LICENSE BSD CACHE INTERNAL "")
set(virtuose-api_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/drivers/virtuose-api.git CACHE INTERNAL "")
set(virtuose-api_PID_WRAPPER_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(virtuose-api_DESCRIPTION "PID wrapper for VirtuoseAPI external project" CACHE INTERNAL "")
set(virtuose-api_FRAMEWORK rpc CACHE INTERNAL "")
set(virtuose-api_CATEGORIES "driver/robot/arm" CACHE INTERNAL "")
set(virtuose-api_AUTHORS "HAPTION: Pascal Louveau" CACHE INTERNAL "")
set(virtuose-api_PROJECT_SITE https://www.haption.com CACHE INTERNAL "")
set(virtuose-api_LICENSES CSRU CACHE INTERNAL "")
set(virtuose-api_REFERENCES  CACHE INTERNAL "")
