#### referencing package fltk-gui mode ####
set(fltk-gui_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(fltk-gui_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(fltk-gui_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(fltk-gui_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(fltk-gui_DESCRIPTION A package to simplify the use of the FLT:K library inside PID CACHE INTERNAL "")
set(fltk-gui_YEARS 2015 CACHE INTERNAL "")
set(fltk-gui_LICENSE CeCILL-C CACHE INTERNAL "")
set(fltk-gui_ADDRESS git@gite.lirmm.fr:pid_external_deps/fltk-gui.git CACHE INTERNAL "")
set(fltk-gui_CATEGORIES CACHE INTERNAL "")
set(fltk-gui_REFERENCES  CACHE INTERNAL "")
