#### referencing package sch-core mode ####
set(sch-core_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(sch-core_MAIN_INSTITUTION  CACHE INTERNAL "")
set(sch-core_CONTACT_MAIL  CACHE INTERNAL "")
set(sch-core_FRAMEWORK  CACHE INTERNAL "")
set(sch-core_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(sch-core_PROJECT_PAGE  CACHE INTERNAL "")
set(sch-core_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(sch-core_SITE_INTRODUCTION  CACHE INTERNAL "")
set(sch-core_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro()" CACHE INTERNAL "")
set(sch-core_DESCRIPTION "Wrapping;of;sch-core;(;https://github.com/jrl-umi3218/sch-core;);with;PID;to;avoid;Boost;system;dependency" CACHE INTERNAL "")
set(sch-core_YEARS 2017 CACHE INTERNAL "")
set(sch-core_LICENSE GNUGPL CACHE INTERNAL "")
set(sch-core_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/sch-core.git CACHE INTERNAL "")
set(sch-core_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(sch-core_CATEGORIES CACHE INTERNAL "")
set(sch-core_REFERENCES  CACHE INTERNAL "")
