#### referencing package rkcl-ur-app mode ####
set(rkcl-ur-app_MAIN_AUTHOR _Sonny_Tarbouriech CACHE INTERNAL "")
set(rkcl-ur-app_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(rkcl-ur-app_CONTACT_MAIL  CACHE INTERNAL "")
set(rkcl-ur-app_FRAMEWORK rkcl-framework CACHE INTERNAL "")
set(rkcl-ur-app_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rkcl-ur-app_PROJECT_PAGE https://gite.lirmm.fr/rkcl/rkcl-ur-app CACHE INTERNAL "")
set(rkcl-ur-app_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rkcl-ur-app_SITE_INTRODUCTION "Application;package;for;Universal;Robots;arms" CACHE INTERNAL "")
set(rkcl-ur-app_AUTHORS_AND_INSTITUTIONS "_Sonny_Tarbouriech(_LIRMM)" CACHE INTERNAL "")
set(rkcl-ur-app_DESCRIPTION "Application;package;for;Universal;Robots;arms" CACHE INTERNAL "")
set(rkcl-ur-app_YEARS 2019 CACHE INTERNAL "")
set(rkcl-ur-app_LICENSE CeCILL CACHE INTERNAL "")
set(rkcl-ur-app_ADDRESS git@gite.lirmm.fr:rkcl/rkcl-ur-app.git CACHE INTERNAL "")
set(rkcl-ur-app_PUBLIC_ADDRESS https://gite.lirmm.fr/rkcl/rkcl-ur-app.git CACHE INTERNAL "")
set(rkcl-ur-app_CATEGORIES "application" CACHE INTERNAL "")
set(rkcl-ur-app_REFERENCES  CACHE INTERNAL "")
