#### referencing wrapper of external package gtsam ####
set(gtsam_PID_WRAPPER_CONTACT_AUTHOR _Yohan_Breux CACHE INTERNAL "")
set(gtsam_PID_WRAPPER_CONTACT_INSTITUTION _lirmm CACHE INTERNAL "")
set(gtsam_PID_WRAPPER_CONTACT_MAIL breux@lirmm.fr CACHE INTERNAL "")
set(gtsam_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(gtsam_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/rob-miscellaneous/gtsam.git CACHE INTERNAL "")
set(gtsam_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(gtsam_PID_WRAPPER_SITE_INTRODUCTION This project is a PID wrapper for the external project called gtsam. It is used for solving efficiently graphSLAM problems in robotics and vision. CACHE INTERNAL "")
set(gtsam_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Yohan_Breux(_lirmm)" CACHE INTERNAL "")
set(gtsam_PID_WRAPPER_YEARS 2019 CACHE INTERNAL "")
set(gtsam_PID_WRAPPER_LICENSE BSD CACHE INTERNAL "")
set(gtsam_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/gtsam.git CACHE INTERNAL "")
set(gtsam_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/gtsam.git CACHE INTERNAL "")
set(gtsam_DESCRIPTION "PID Wrapper for the GTSAM (Georgia Tech Smoothing and Mapping library) library." CACHE INTERNAL "")
set(gtsam_FRAMEWORK rpc CACHE INTERNAL "")
set(gtsam_CATEGORIES "algorithm/navigation;algorithm/optimization;algorithm/slam" CACHE INTERNAL "")
set(gtsam_AUTHORS "GTSAM developper team" CACHE INTERNAL "")
set(gtsam_PROJECT_SITE https://bitbucket.org/gtborg/gtsam CACHE INTERNAL "")
set(gtsam_LICENSES BSD CACHE INTERNAL "")
set(gtsam_REFERENCES  CACHE INTERNAL "")
