#### referencing package hardioup mode ####
set(hardioup_MAIN_AUTHOR _Clément_Rebut CACHE INTERNAL "")
set(hardioup_MAIN_INSTITUTION  CACHE INTERNAL "")
set(hardioup_CONTACT_MAIL  CACHE INTERNAL "")
set(hardioup_FRAMEWORK  CACHE INTERNAL "")
set(hardioup_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(hardioup_PROJECT_PAGE  CACHE INTERNAL "")
set(hardioup_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(hardioup_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(hardioup_AUTHORS_AND_INSTITUTIONS "_Clément_Rebut()" CACHE INTERNAL "")
set(hardioup_DESCRIPTION "This;is;the;implementation;of;hardiocore;for;upboard" CACHE INTERNAL "")
set(hardioup_YEARS 2019 CACHE INTERNAL "")
set(hardioup_LICENSE CeCILL CACHE INTERNAL "")
set(hardioup_ADDRESS git@gite.lirmm.fr:hardio/cards/hardioup.git CACHE INTERNAL "")
set(hardioup_PUBLIC_ADDRESS https://gite.lirmm.fr/hardio/cards/hardioup.git CACHE INTERNAL "")
set(hardioup_CATEGORIES CACHE INTERNAL "")
set(hardioup_REFERENCES  CACHE INTERNAL "")
