#### referencing package signal-processing-knowbotics mode ####
set(signal-processing-knowbotics_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(signal-processing-knowbotics_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(signal-processing-knowbotics_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(signal-processing-knowbotics_FRAMEWORK  CACHE INTERNAL "")
set(signal-processing-knowbotics_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(signal-processing-knowbotics_PROJECT_PAGE  CACHE INTERNAL "")
set(signal-processing-knowbotics_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(signal-processing-knowbotics_SITE_INTRODUCTION  CACHE INTERNAL "")
set(signal-processing-knowbotics_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM);_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(signal-processing-knowbotics_DESCRIPTION "Filter and other processing tools for signal like data" CACHE INTERNAL "")
set(signal-processing-knowbotics_YEARS 2015 CACHE INTERNAL "")
set(signal-processing-knowbotics_LICENSE CeCILL-C CACHE INTERNAL "")
set(signal-processing-knowbotics_ADDRESS git@gite.lirmm.fr:knowbotics/signal-processing-knowbotics.git CACHE INTERNAL "")
set(signal-processing-knowbotics_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(signal-processing-knowbotics_CATEGORIES CACHE INTERNAL "")
set(signal-processing-knowbotics_REFERENCES  CACHE INTERNAL "")
