#### referencing package omni-tentacles mode ####
set(omni-tentacles_MAIN_AUTHOR _Abdellah_Khelloufi CACHE INTERNAL "")
set(omni-tentacles_MAIN_INSTITUTION _CDTA CACHE INTERNAL "")
set(omni-tentacles_CONTACT_MAIL abdellah.khe@gmail.com CACHE INTERNAL "")
set(omni-tentacles_AUTHORS_AND_INSTITUTIONS "_Abdellah_Khelloufi(_CDTA)" CACHE INTERNAL "")
set(omni-tentacles_DESCRIPTION Tentacle approach for omnidirectionnal robot. Provide a C++ library to use tentacles. CACHE INTERNAL "")
set(omni-tentacles_YEARS 2016 CACHE INTERNAL "")
set(omni-tentacles_LICENSE CeCILL-C CACHE INTERNAL "")
set(omni-tentacles_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/omni-tentacles.git CACHE INTERNAL "")
set(omni-tentacles_CATEGORIES CACHE INTERNAL "")
set(omni-tentacles_AVAILABLE_PLATFORMS linux64cxx11;linux64;linux32;macosx64 CACHE INTERNAL "")
set(omni-tentacles_AVAILABLE_PLATFORM_linux64cxx11_OS linux CACHE INTERNAL "")
set(omni-tentacles_AVAILABLE_PLATFORM_linux64cxx11_ARCH 64 CACHE INTERNAL "")
set(omni-tentacles_AVAILABLE_PLATFORM_linux64cxx11_ABI CXX11 CACHE INTERNAL "")
set(omni-tentacles_AVAILABLE_PLATFORM_linux64cxx11_CONFIGURATION  CACHE INTERNAL "")
set(omni-tentacles_AVAILABLE_PLATFORM_linux64_OS linux CACHE INTERNAL "")
set(omni-tentacles_AVAILABLE_PLATFORM_linux64_ARCH 64 CACHE INTERNAL "")
set(omni-tentacles_AVAILABLE_PLATFORM_linux64_ABI CXX CACHE INTERNAL "")
set(omni-tentacles_AVAILABLE_PLATFORM_linux64_CONFIGURATION  CACHE INTERNAL "")
set(omni-tentacles_AVAILABLE_PLATFORM_linux32_OS linux CACHE INTERNAL "")
set(omni-tentacles_AVAILABLE_PLATFORM_linux32_ARCH 32 CACHE INTERNAL "")
set(omni-tentacles_AVAILABLE_PLATFORM_linux32_ABI CXX CACHE INTERNAL "")
set(omni-tentacles_AVAILABLE_PLATFORM_linux32_CONFIGURATION  CACHE INTERNAL "")
set(omni-tentacles_AVAILABLE_PLATFORM_macosx64_OS macosx CACHE INTERNAL "")
set(omni-tentacles_AVAILABLE_PLATFORM_macosx64_ARCH 64 CACHE INTERNAL "")
set(omni-tentacles_AVAILABLE_PLATFORM_macosx64_ABI CXX CACHE INTERNAL "")
set(omni-tentacles_AVAILABLE_PLATFORM_macosx64_CONFIGURATION  CACHE INTERNAL "")
set(omni-tentacles_REFERENCES  CACHE INTERNAL "")
