#### referencing package udp-interface mode ####
set(udp-interface_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(udp-interface_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(udp-interface_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(udp-interface_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(udp-interface_DESCRIPTION Generic UDP server and client CACHE INTERNAL "")
set(udp-interface_YEARS 2016 CACHE INTERNAL "")
set(udp-interface_LICENSE CeCILL-C CACHE INTERNAL "")
set(udp-interface_ADDRESS git@gite.lirmm.fr:pid_external_deps/udp-interface.git CACHE INTERNAL "")
set(udp-interface_CATEGORIES "programming/io" CACHE INTERNAL "")
set(udp-interface_REFERENCES  CACHE INTERNAL "")
