#### referencing package ati-force-sensor-driver mode ####
set(ati-force-sensor-driver_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(ati-force-sensor-driver_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(ati-force-sensor-driver_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(ati-force-sensor-driver_FRAMEWORK  CACHE INTERNAL "")
set(ati-force-sensor-driver_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(ati-force-sensor-driver_PROJECT_PAGE  CACHE INTERNAL "")
set(ati-force-sensor-driver_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(ati-force-sensor-driver_SITE_INTRODUCTION  CACHE INTERNAL "")
set(ati-force-sensor-driver_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(ati-force-sensor-driver_DESCRIPTION "ATI force sensor driver (uses Comedi)" CACHE INTERNAL "")
set(ati-force-sensor-driver_YEARS 2018 CACHE INTERNAL "")
set(ati-force-sensor-driver_LICENSE CeCILL-C CACHE INTERNAL "")
set(ati-force-sensor-driver_ADDRESS git@gite.lirmm.fr:rob-force-sensors/ati-force-sensor-driver.git CACHE INTERNAL "")
set(ati-force-sensor-driver_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-force-sensors/ati-force-sensor-driver.git CACHE INTERNAL "")
set(ati-force-sensor-driver_CATEGORIES "force-sensor/ati" CACHE INTERNAL "")
set(ati-force-sensor-driver_REFERENCES  CACHE INTERNAL "")
