#### referencing package hokuyo_p3dx mode ####
set(hokuyo_p3dx_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(hokuyo_p3dx_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(hokuyo_p3dx_CONTACT_MAIL  CACHE INTERNAL "")
set(hokuyo_p3dx_FRAMEWORK  CACHE INTERNAL "")
set(hokuyo_p3dx_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(hokuyo_p3dx_PROJECT_PAGE  CACHE INTERNAL "")
set(hokuyo_p3dx_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(hokuyo_p3dx_SITE_INTRODUCTION  CACHE INTERNAL "")
set(hokuyo_p3dx_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM);_Guillaume_Lefebvre()" CACHE INTERNAL "")
set(hokuyo_p3dx_DESCRIPTION "TODO: input a short description of package hokuyo_p3dx utility here" CACHE INTERNAL "")
set(hokuyo_p3dx_YEARS 2017 CACHE INTERNAL "")
set(hokuyo_p3dx_LICENSE CeCILL CACHE INTERNAL "")
set(hokuyo_p3dx_ADDRESS git@gite.lirmm.fr:pioneer3DX/hokuyo_p3dx.git CACHE INTERNAL "")
set(hokuyo_p3dx_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(hokuyo_p3dx_CATEGORIES CACHE INTERNAL "")
set(hokuyo_p3dx_REFERENCES  CACHE INTERNAL "")
