#### referencing package contact-establishing-tool mode ####
set(contact-establishing-tool_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(contact-establishing-tool_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(contact-establishing-tool_CONTACT_MAIL Benjamin.Navarro@lirmm.fr CACHE INTERNAL "")
set(contact-establishing-tool_FRAMEWORK  CACHE INTERNAL "")
set(contact-establishing-tool_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(contact-establishing-tool_PROJECT_PAGE  CACHE INTERNAL "")
set(contact-establishing-tool_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(contact-establishing-tool_SITE_INTRODUCTION  CACHE INTERNAL "")
set(contact-establishing-tool_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM);_Mohamed_Sorour(_LIRMM)" CACHE INTERNAL "")
set(contact-establishing-tool_DESCRIPTION Models;and;applications;related;to;the;contact;establishing;tool CACHE INTERNAL "")
set(contact-establishing-tool_YEARS 2017 CACHE INTERNAL "")
set(contact-establishing-tool_LICENSE CeCILL CACHE INTERNAL "")
set(contact-establishing-tool_ADDRESS git@gite.lirmm.fr:cobot/contact-establishing-tool.git CACHE INTERNAL "")
set(contact-establishing-tool_CATEGORIES CACHE INTERNAL "")
set(contact-establishing-tool_REFERENCES  CACHE INTERNAL "")
