#### referencing package api-driver-vrep mode ####
set(api-driver-vrep_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(api-driver-vrep_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(api-driver-vrep_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(api-driver-vrep_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(api-driver-vrep_DESCRIPTION Wrapper for the V-REP C/C++ remote API CACHE INTERNAL "")
set(api-driver-vrep_YEARS 20145 CACHE INTERNAL "")
set(api-driver-vrep_LICENSE CeCILL-C CACHE INTERNAL "")
set(api-driver-vrep_ADDRESS git@rob-dev.lirmm.fr:pid_external_deps/api-driver-vrep.git CACHE INTERNAL "")
set(api-driver-vrep_CATEGORIES driver/vrep CACHE INTERNAL "")
set(api-driver-vrep_REFERENCES  CACHE INTERNAL "")
