#### referencing package rkcl-panda-robot mode ####
set(rkcl-panda-robot_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(rkcl-panda-robot_MAIN_INSTITUTION _LIRMM_/_CNRS CACHE INTERNAL "")
set(rkcl-panda-robot_CONTACT_MAIL  CACHE INTERNAL "")
set(rkcl-panda-robot_FRAMEWORK  CACHE INTERNAL "")
set(rkcl-panda-robot_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rkcl-panda-robot_PROJECT_PAGE  CACHE INTERNAL "")
set(rkcl-panda-robot_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rkcl-panda-robot_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(rkcl-panda-robot_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM_/_CNRS)" CACHE INTERNAL "")
set(rkcl-panda-robot_DESCRIPTION "Helper;package;to;work;with;the;Franka;Panda;robot" CACHE INTERNAL "")
set(rkcl-panda-robot_YEARS 2019 CACHE INTERNAL "")
set(rkcl-panda-robot_LICENSE CeCILL CACHE INTERNAL "")
set(rkcl-panda-robot_ADDRESS git@gitlab.com:rkcl/rkcl-panda-robot.git CACHE INTERNAL "")
set(rkcl-panda-robot_PUBLIC_ADDRESS https://gitlab.com/rkcl/rkcl-panda-robot.git CACHE INTERNAL "")
set(rkcl-panda-robot_CATEGORIES CACHE INTERNAL "")
set(rkcl-panda-robot_REFERENCES  CACHE INTERNAL "")
