#### referencing package rereflexxes mode ####
set(rereflexxes_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(rereflexxes_MAIN_INSTITUTION _LIRMM_/_CNRS CACHE INTERNAL "")
set(rereflexxes_CONTACT_MAIL  CACHE INTERNAL "")
set(rereflexxes_FRAMEWORK  CACHE INTERNAL "")
set(rereflexxes_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rereflexxes_PROJECT_PAGE  CACHE INTERNAL "")
set(rereflexxes_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rereflexxes_SITE_INTRODUCTION  CACHE INTERNAL "")
set(rereflexxes_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM_/_CNRS)" CACHE INTERNAL "")
set(rereflexxes_DESCRIPTION "ReReflexxes;is;a;rewrite;of;the;Reflexxes;online;trajectory;generator;for;a;modern;C++;API;and;with;the;addition;of;Cartesian;space;trajectories" CACHE INTERNAL "")
set(rereflexxes_YEARS 2019 CACHE INTERNAL "")
set(rereflexxes_LICENSE GNULGPL CACHE INTERNAL "")
set(rereflexxes_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/rereflexxes.git CACHE INTERNAL "")
set(rereflexxes_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/rereflexxes.git CACHE INTERNAL "")
set(rereflexxes_CATEGORIES CACHE INTERNAL "")
set(rereflexxes_REFERENCES  CACHE INTERNAL "")
