#### referencing package robot-models-knowbotics mode ####
set(robot-models-knowbotics_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(robot-models-knowbotics_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(robot-models-knowbotics_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(robot-models-knowbotics_FRAMEWORK  CACHE INTERNAL "")
set(robot-models-knowbotics_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(robot-models-knowbotics_PROJECT_PAGE  CACHE INTERNAL "")
set(robot-models-knowbotics_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(robot-models-knowbotics_SITE_INTRODUCTION  CACHE INTERNAL "")
set(robot-models-knowbotics_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM);_Robin_Passama(_LIRMM);_Sonny_Tarbouriech(_LIRMM)" CACHE INTERNAL "")
set(robot-models-knowbotics_DESCRIPTION "A set of robot model computation algorithms for Knowbotics" CACHE INTERNAL "")
set(robot-models-knowbotics_YEARS 2018 CACHE INTERNAL "")
set(robot-models-knowbotics_LICENSE CeCILL-C CACHE INTERNAL "")
set(robot-models-knowbotics_ADDRESS git@gite.lirmm.fr:knowbotics/robot-models-knowbotics.git CACHE INTERNAL "")
set(robot-models-knowbotics_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(robot-models-knowbotics_CATEGORIES "knowbotics/model" CACHE INTERNAL "")
set(robot-models-knowbotics_REFERENCES  CACHE INTERNAL "")
