#### referencing wrapper of external package vimba ####
set(vimba_PID_WRAPPER_CONTACT_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(vimba_PID_WRAPPER_CONTACT_INSTITUTION _CNRS/LIRMM CACHE INTERNAL "")
set(vimba_PID_WRAPPER_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(vimba_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(vimba_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/rob-vision-devices/vimba CACHE INTERNAL "")
set(vimba_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(vimba_PID_WRAPPER_SITE_INTRODUCTION "Vimba;is;a;software;suite;provided;by;Allied;Vision;Technology;company.;It;is;used;to;intarfec;c/c++;code;with;various;industrial;cameras;provided;by;AVT." CACHE INTERNAL "")
set(vimba_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_CNRS/LIRMM)" CACHE INTERNAL "")
set(vimba_PID_WRAPPER_YEARS 2019 CACHE INTERNAL "")
set(vimba_PID_WRAPPER_LICENSE GNULGPL CACHE INTERNAL "")
set(vimba_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:rob-vision-devices/vimba.git CACHE INTERNAL "")
set(vimba_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-vision-devices/vimba.git CACHE INTERNAL "")
set(vimba_DESCRIPTION "PID wrapper for the vimba project, developped by Allied Vision Technology company. Provides API to interface with various cameras from AVT." CACHE INTERNAL "")
set(vimba_FRAMEWORK rpc CACHE INTERNAL "")
set(vimba_CATEGORIES "driver/sensor/vision" CACHE INTERNAL "")
set(vimba_AUTHORS "Allied Vision Technology Gmbh" CACHE INTERNAL "")
set(vimba_PROJECT_SITE https://www.alliedvision.com CACHE INTERNAL "")
set(vimba_LICENSES Allied Vision Technology license for Vimba CACHE INTERNAL "")
set(vimba_REFERENCES  CACHE INTERNAL "")
