#### referencing package stereo-vision mode ####
set(stereo-vision_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(stereo-vision_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(stereo-vision_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(stereo-vision_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM);_Florian_Raffalli(_LIRMM)" CACHE INTERNAL "")
set(stereo-vision_DESCRIPTION stereo vision libs and applications CACHE INTERNAL "")
set(stereo-vision_YEARS 2015 CACHE INTERNAL "")
set(stereo-vision_LICENSE CeCILL-C CACHE INTERNAL "")
set(stereo-vision_ADDRESS git@gite.lirmm.fr:rob-vision-devices/stereo-vision.git CACHE INTERNAL "")
set(stereo-vision_CATEGORIES "vision" CACHE INTERNAL "")
set(stereo-vision_REFERENCES  CACHE INTERNAL "")
