#### referencing wrapper of external package tensorflow ####
set(tensorflow_PID_WRAPPER_CONTACT_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(tensorflow_PID_WRAPPER_CONTACT_INSTITUTION _LIRMM CACHE INTERNAL "")
set(tensorflow_PID_WRAPPER_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(tensorflow_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(tensorflow_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/rob-vision/rob-deep-perception/wrappers/tensorflow CACHE INTERNAL "")
set(tensorflow_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(tensorflow_PID_WRAPPER_SITE_INTRODUCTION tensorflow;is;a;PID;wrapper;for;the;external;project;called;tensorflow.;It;implements;a;high;level;API;for;Machine;Learning;programming. CACHE INTERNAL "")
set(tensorflow_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(tensorflow_PID_WRAPPER_YEARS 2019 CACHE INTERNAL "")
set(tensorflow_PID_WRAPPER_LICENSE CeCILL-C CACHE INTERNAL "")
set(tensorflow_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:rob-vision/rob-deep-perception/wrappers/tensorflow.git CACHE INTERNAL "")
set(tensorflow_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-vision/rob-deep-perception/wrappers/tensorflow.git CACHE INTERNAL "")
set(tensorflow_DESCRIPTION "tensorflow;is;an;API;for;programming;DNN;in;C++." CACHE INTERNAL "")
set(tensorflow_FRAMEWORK rdp CACHE INTERNAL "")
set(tensorflow_CATEGORIES "dnn" CACHE INTERNAL "")
set(tensorflow_AUTHORS "Tensorflow authors" CACHE INTERNAL "")
set(tensorflow_PROJECT_SITE https://www.tensorflow.org CACHE INTERNAL "")
set(tensorflow_LICENSES Apache license V2 CACHE INTERNAL "")
set(tensorflow_REFERENCES  CACHE INTERNAL "")
