#### referencing package rtplot-fltk mode ####
set(rtplot-fltk_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(rtplot-fltk_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(rtplot-fltk_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(rtplot-fltk_FRAMEWORK  CACHE INTERNAL "")
set(rtplot-fltk_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rtplot-fltk_PROJECT_PAGE  CACHE INTERNAL "")
set(rtplot-fltk_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rtplot-fltk_SITE_INTRODUCTION  CACHE INTERNAL "")
set(rtplot-fltk_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM);_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(rtplot-fltk_DESCRIPTION "Real time plotting library and application based on FLTK" CACHE INTERNAL "")
set(rtplot-fltk_YEARS 2016 CACHE INTERNAL "")
set(rtplot-fltk_LICENSE CeCILL CACHE INTERNAL "")
set(rtplot-fltk_ADDRESS git@gite.lirmm.fr:pid/rtplot-fltk.git CACHE INTERNAL "")
set(rtplot-fltk_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(rtplot-fltk_CATEGORIES CACHE INTERNAL "")
set(rtplot-fltk_REFERENCES  CACHE INTERNAL "")
