#### referencing wrapper of external package forcedimension-sdk ####
set(forcedimension-sdk_PID_WRAPPER_CONTACT_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(forcedimension-sdk_PID_WRAPPER_CONTACT_INSTITUTION _LIRMM-CNRS CACHE INTERNAL "")
set(forcedimension-sdk_PID_WRAPPER_CONTACT_MAIL  CACHE INTERNAL "")
set(forcedimension-sdk_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(forcedimension-sdk_PID_WRAPPER_PROJECT_PAGE  CACHE INTERNAL "")
set(forcedimension-sdk_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(forcedimension-sdk_PID_WRAPPER_SITE_INTRODUCTION  CACHE INTERNAL "")
set(forcedimension-sdk_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM-CNRS)" CACHE INTERNAL "")
set(forcedimension-sdk_PID_WRAPPER_YEARS 2018 CACHE INTERNAL "")
set(forcedimension-sdk_PID_WRAPPER_LICENSE CeCILL-C CACHE INTERNAL "")
set(forcedimension-sdk_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:raven2/forcedimension-sdk.git CACHE INTERNAL "")
set(forcedimension-sdk_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/raven2/forcedimension-sdk.git CACHE INTERNAL "")
set(forcedimension-sdk_DESCRIPTION "PID Wrapper for the Force dimension SDK used to control haptic devices." CACHE INTERNAL "")
set(forcedimension-sdk_FRAMEWORK  CACHE INTERNAL "")
set(forcedimension-sdk_CATEGORIES "driver;driver/haptic_device" CACHE INTERNAL "")
set(forcedimension-sdk_AUTHORS "Force Dimension" CACHE INTERNAL "")
set(forcedimension-sdk_PROJECT_SITE http://www.forcedimension.com CACHE INTERNAL "")
set(forcedimension-sdk_LICENSES Force Dimension private license CACHE INTERNAL "")
set(forcedimension-sdk_REFERENCES  CACHE INTERNAL "")
