#### referencing package force-sensor-driver-vrep mode ####
set(force-sensor-driver-vrep_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(force-sensor-driver-vrep_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(force-sensor-driver-vrep_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(force-sensor-driver-vrep_AUTHORS_AND_INSTITUTIONS ; "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(force-sensor-driver-vrep_DESCRIPTION A package to interface with a simulated Kuka LWR on V-REP CACHE INTERNAL "")
set(force-sensor-driver-vrep_YEARS 2015 CACHE INTERNAL "")
set(force-sensor-driver-vrep_LICENSE CeCILL-C CACHE INTERNAL "")
set(force-sensor-driver-vrep_ADDRESS git@rob-dev.lirmm.fr:force-sensors/force-sensor-driver-vrep.git CACHE INTERNAL "")
set(force-sensor-driver-vrep_CATEGORIES sensor/force;driver/vrep CACHE INTERNAL "")
set(force-sensor-driver-vrep_REFERENCES  CACHE INTERNAL "")
