#### referencing package mrpt-gtsam mode ####
set(mrpt-gtsam_MAIN_AUTHOR _Yohan_Breux CACHE INTERNAL "")
set(mrpt-gtsam_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(mrpt-gtsam_CONTACT_MAIL breux@lirmm.fr CACHE INTERNAL "")
set(mrpt-gtsam_FRAMEWORK rpc CACHE INTERNAL "")
set(mrpt-gtsam_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(mrpt-gtsam_PROJECT_PAGE https://gite.lirmm.fr/breux/mrpt-gtsam CACHE INTERNAL "")
set(mrpt-gtsam_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(mrpt-gtsam_SITE_INTRODUCTION Extension of MRPT by integrating GTSAM algorithms for graphSLAM. CACHE INTERNAL "")
set(mrpt-gtsam_AUTHORS_AND_INSTITUTIONS "_Yohan_Breux(_LIRMM)" CACHE INTERNAL "")
set(mrpt-gtsam_DESCRIPTION "Integration of GTSAM into graphSLAM module of MRPT" CACHE INTERNAL "")
set(mrpt-gtsam_YEARS 2019 CACHE INTERNAL "")
set(mrpt-gtsam_LICENSE CeCILL CACHE INTERNAL "")
set(mrpt-gtsam_ADDRESS git@gite.lirmm.fr:breux/mrpt-gtsam.git CACHE INTERNAL "")
set(mrpt-gtsam_PUBLIC_ADDRESS https://gite.lirmm.fr/breux/mrpt-gtsam.git CACHE INTERNAL "")
set(mrpt-gtsam_CATEGORIES "algorithm/slam" CACHE INTERNAL "")
set(mrpt-gtsam_REFERENCES  CACHE INTERNAL "")
