#### referencing package rob-integration mode ####
set(rob-integration_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(rob-integration_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(rob-integration_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(rob-integration_AUTHORS_AND_INSTITUTIONS ;"_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(rob-integration_DESCRIPTION an API to ease integration of various robotics code CACHE INTERNAL "")
set(rob-integration_YEARS 2014 CACHE INTERNAL "")
set(rob-integration_LICENSE CeCILL-C CACHE INTERNAL "")
set(rob-integration_ADDRESS git@rob-dev.lirmm.fr:rob-developers/rob-integration.git CACHE INTERNAL "")
set(rob-integration_CATEGORIES  CACHE INTERNAL "")
set(rob-integration_REFERENCES  CACHE INTERNAL "")
