#### referencing package ethercatcpp-clipx mode ####
set(ethercatcpp-clipx_MAIN_AUTHOR _Meline_Arnaud CACHE INTERNAL "")
set(ethercatcpp-clipx_MAIN_INSTITUTION  CACHE INTERNAL "")
set(ethercatcpp-clipx_CONTACT_MAIL meline@lirmm.fr CACHE INTERNAL "")
set(ethercatcpp-clipx_FRAMEWORK ethercatcpp CACHE INTERNAL "")
set(ethercatcpp-clipx_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(ethercatcpp-clipx_PROJECT_PAGE https://gite.lirmm.fr/ethercatcpp/ethercatcpp-clipx CACHE INTERNAL "")
set(ethercatcpp-clipx_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(ethercatcpp-clipx_SITE_INTRODUCTION ethercatcpp-clipx;is;a;package;providing;the;ethercat;driver;for;clipx;force;sensor. CACHE INTERNAL "")
set(ethercatcpp-clipx_AUTHORS_AND_INSTITUTIONS "_Meline_Arnaud()" CACHE INTERNAL "")
set(ethercatcpp-clipx_DESCRIPTION "Ethercat driver libraries for HMB ClipX" CACHE INTERNAL "")
set(ethercatcpp-clipx_YEARS 2018 CACHE INTERNAL "")
set(ethercatcpp-clipx_LICENSE CeCILL-C CACHE INTERNAL "")
set(ethercatcpp-clipx_ADDRESS git@gite.lirmm.fr:ethercatcpp/ethercatcpp-clipx.git CACHE INTERNAL "")
set(ethercatcpp-clipx_PUBLIC_ADDRESS https://gite.lirmm.fr/ethercatcpp/ethercatcpp-clipx.git CACHE INTERNAL "")
set(ethercatcpp-clipx_CATEGORIES "ethercat/sensor/force_sensor" CACHE INTERNAL "")
set(ethercatcpp-clipx_REFERENCES  CACHE INTERNAL "")
