#### referencing package prostim-driver mode ####
set(prostim-driver_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(prostim-driver_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(prostim-driver_CONTACT_MAIL  CACHE INTERNAL "")
set(prostim-driver_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(prostim-driver_DESCRIPTION Driver library for the PROSTIM stimulator CACHE INTERNAL "")
set(prostim-driver_YEARS 2016 CACHE INTERNAL "")
set(prostim-driver_LICENSE CeCILL-C CACHE INTERNAL "")
set(prostim-driver_ADDRESS git@gite.lirmm.fr:rob-fes-devices/prostim-driver.git CACHE INTERNAL "")
set(prostim-driver_CATEGORIES "fes/stimulator" CACHE INTERNAL "")
set(prostim-driver_AVAILABLE_PLATFORMS linux64cxx11;linux64;linux32;macosx64 CACHE INTERNAL "")
set(prostim-driver_AVAILABLE_PLATFORM_linux64cxx11_OS linux CACHE INTERNAL "")
set(prostim-driver_AVAILABLE_PLATFORM_linux64cxx11_ARCH 64 CACHE INTERNAL "")
set(prostim-driver_AVAILABLE_PLATFORM_linux64cxx11_ABI CXX11 CACHE INTERNAL "")
set(prostim-driver_AVAILABLE_PLATFORM_linux64cxx11_CONFIGURATION posix CACHE INTERNAL "")
set(prostim-driver_AVAILABLE_PLATFORM_linux64_OS linux CACHE INTERNAL "")
set(prostim-driver_AVAILABLE_PLATFORM_linux64_ARCH 64 CACHE INTERNAL "")
set(prostim-driver_AVAILABLE_PLATFORM_linux64_ABI CXX CACHE INTERNAL "")
set(prostim-driver_AVAILABLE_PLATFORM_linux64_CONFIGURATION posix CACHE INTERNAL "")
set(prostim-driver_AVAILABLE_PLATFORM_linux32_OS linux CACHE INTERNAL "")
set(prostim-driver_AVAILABLE_PLATFORM_linux32_ARCH 32 CACHE INTERNAL "")
set(prostim-driver_AVAILABLE_PLATFORM_linux32_ABI CXX CACHE INTERNAL "")
set(prostim-driver_AVAILABLE_PLATFORM_linux32_CONFIGURATION posix CACHE INTERNAL "")
set(prostim-driver_AVAILABLE_PLATFORM_macosx64_OS macosx CACHE INTERNAL "")
set(prostim-driver_AVAILABLE_PLATFORM_macosx64_ARCH 64 CACHE INTERNAL "")
set(prostim-driver_AVAILABLE_PLATFORM_macosx64_ABI CXX CACHE INTERNAL "")
set(prostim-driver_AVAILABLE_PLATFORM_macosx64_CONFIGURATION posix CACHE INTERNAL "")
set(prostim-driver_REFERENCES  CACHE INTERNAL "")
