#### referencing package vive-pro-ar mode ####
set(vive-pro-ar_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(vive-pro-ar_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(vive-pro-ar_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(vive-pro-ar_FRAMEWORK  CACHE INTERNAL "")
set(vive-pro-ar_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(vive-pro-ar_PROJECT_PAGE  CACHE INTERNAL "")
set(vive-pro-ar_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(vive-pro-ar_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(vive-pro-ar_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(vive-pro-ar_DESCRIPTION "Augmented Reality for the HTC Vive Pro" CACHE INTERNAL "")
set(vive-pro-ar_YEARS 2019 CACHE INTERNAL "")
set(vive-pro-ar_LICENSE CeCILL CACHE INTERNAL "")
set(vive-pro-ar_ADDRESS git@gite.lirmm.fr:rob-vision/vr-ar/vive-pro-ar.git CACHE INTERNAL "")
set(vive-pro-ar_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-vision/vr-ar/vive-pro-ar.git CACHE INTERNAL "")
set(vive-pro-ar_CATEGORIES CACHE INTERNAL "")
set(vive-pro-ar_REFERENCES  CACHE INTERNAL "")
