#### referencing package rkcl-driver-vrep mode ####
set(rkcl-driver-vrep_MAIN_AUTHOR _Sonny_Tarbouriech CACHE INTERNAL "")
set(rkcl-driver-vrep_MAIN_INSTITUTION _Tecnalia CACHE INTERNAL "")
set(rkcl-driver-vrep_CONTACT_MAIL  CACHE INTERNAL "")
set(rkcl-driver-vrep_FRAMEWORK  CACHE INTERNAL "")
set(rkcl-driver-vrep_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rkcl-driver-vrep_PROJECT_PAGE  CACHE INTERNAL "")
set(rkcl-driver-vrep_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rkcl-driver-vrep_SITE_INTRODUCTION  CACHE INTERNAL "")
set(rkcl-driver-vrep_AUTHORS_AND_INSTITUTIONS "_Sonny_Tarbouriech(_Tecnalia);_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(rkcl-driver-vrep_DESCRIPTION "TODO:;input;a;short;description;of;package;rkcl-driver-vrep;utility;here" CACHE INTERNAL "")
set(rkcl-driver-vrep_YEARS 2018 CACHE INTERNAL "")
set(rkcl-driver-vrep_LICENSE CeCILL CACHE INTERNAL "")
set(rkcl-driver-vrep_ADDRESS git@gitlab.com:rkcl/rkcl-driver-vrep.git CACHE INTERNAL "")
set(rkcl-driver-vrep_PUBLIC_ADDRESS https://gitlab.com/rkcl/rkcl-driver-vrep.git CACHE INTERNAL "")
set(rkcl-driver-vrep_CATEGORIES CACHE INTERNAL "")
set(rkcl-driver-vrep_REFERENCES  CACHE INTERNAL "")
