#### referencing package encoder-board-driver mode ####
set(encoder-board-driver_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(encoder-board-driver_MAIN_INSTITUTION  CACHE INTERNAL "")
set(encoder-board-driver_CONTACT_MAIL  CACHE INTERNAL "")
set(encoder-board-driver_FRAMEWORK  CACHE INTERNAL "")
set(encoder-board-driver_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(encoder-board-driver_PROJECT_PAGE  CACHE INTERNAL "")
set(encoder-board-driver_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(encoder-board-driver_SITE_INTRODUCTION  CACHE INTERNAL "")
set(encoder-board-driver_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro()" CACHE INTERNAL "")
set(encoder-board-driver_DESCRIPTION "driver;for;encoder;board" CACHE INTERNAL "")
set(encoder-board-driver_YEARS 2018 CACHE INTERNAL "")
set(encoder-board-driver_LICENSE CeCILL CACHE INTERNAL "")
set(encoder-board-driver_ADDRESS git@gite.lirmm.fr:cobot/encoder-board-driver.git CACHE INTERNAL "")
set(encoder-board-driver_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(encoder-board-driver_CATEGORIES CACHE INTERNAL "")
set(encoder-board-driver_REFERENCES  CACHE INTERNAL "")
