#### referencing environment gfortran_toolchain mode ####
set(gfortran_toolchain_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(gfortran_toolchain_MAIN_INSTITUTION _CNRS/LIRMM CACHE INTERNAL "")
set(gfortran_toolchain_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_CNRS/LIRMM)" CACHE INTERNAL "")
set(gfortran_toolchain_YEARS 2019 CACHE INTERNAL "")
set(gfortran_toolchain_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(gfortran_toolchain_ADDRESS git@gite.lirmm.fr:pid/environments/gfortran_toolchain.git CACHE INTERNAL "")
set(gfortran_toolchain_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/environments/gfortran_toolchain.git CACHE INTERNAL "")
set(gfortran_toolchain_LICENSE CeCILL-C CACHE INTERNAL "")
set(gfortran_toolchain_DESCRIPTION using GNU gfortran toolchain to build Fortran code of projects CACHE INTERNAL "")
