#### referencing package neobotix-mpo700-udp-interface mode ####
set(neobotix-mpo700-udp-interface_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(neobotix-mpo700-udp-interface_MAIN_INSTITUTION _CNRS/LIRMM CACHE INTERNAL "")
set(neobotix-mpo700-udp-interface_CONTACT_MAIL robin.passama@lirmm.fr CACHE INTERNAL "")
set(neobotix-mpo700-udp-interface_FRAMEWORK rpc CACHE INTERNAL "")
set(neobotix-mpo700-udp-interface_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(neobotix-mpo700-udp-interface_PROJECT_PAGE https://gite.lirmm.fr/neobotix-mpo700/neobotix-mpo700-udp-interface CACHE INTERNAL "")
set(neobotix-mpo700-udp-interface_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(neobotix-mpo700-udp-interface_SITE_INTRODUCTION "`neobotix-mpo700-udp-interface`;package;provides;an;API;that;enable;the;udp;communication;between;a;PC;and;the;neobotix;MPO700;platform.;This;package;must;be;used;together;with;the;package;`mpo700-embedded-udp-interface`." CACHE INTERNAL "")
set(neobotix-mpo700-udp-interface_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_CNRS/LIRMM);_Benjamin_Navarro(_CNRS/LIRMM)" CACHE INTERNAL "")
set(neobotix-mpo700-udp-interface_DESCRIPTION "project providing libraries to enable udp communication between a PC and the neobotix MPO700 platform" CACHE INTERNAL "")
set(neobotix-mpo700-udp-interface_YEARS 2015 CACHE INTERNAL "")
set(neobotix-mpo700-udp-interface_LICENSE CeCILL-C CACHE INTERNAL "")
set(neobotix-mpo700-udp-interface_ADDRESS git@gite.lirmm.fr:neobotix-mpo700/neobotix-mpo700-udp-interface.git CACHE INTERNAL "")
set(neobotix-mpo700-udp-interface_PUBLIC_ADDRESS https://gite.lirmm.fr/neobotix-mpo700/neobotix-mpo700-udp-interface.git CACHE INTERNAL "")
set(neobotix-mpo700-udp-interface_CATEGORIES "driver/robot/mobile" CACHE INTERNAL "")
set(neobotix-mpo700-udp-interface_REFERENCES  CACHE INTERNAL "")
