#### referencing package mpo700-controller mode ####
set(mpo700-controller_MAIN_AUTHOR _Mohamed_Sorour CACHE INTERNAL "")
set(mpo700-controller_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(mpo700-controller_CONTACT_MAIL Mohamed.Sorour@lirmm.fr CACHE INTERNAL "")
set(mpo700-controller_FRAMEWORK  CACHE INTERNAL "")
set(mpo700-controller_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(mpo700-controller_PROJECT_PAGE  CACHE INTERNAL "")
set(mpo700-controller_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(mpo700-controller_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(mpo700-controller_AUTHORS_AND_INSTITUTIONS "_Mohamed_Sorour(_LIRMM);_Robin_Passama(_LIRMM);_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(mpo700-controller_DESCRIPTION "API for implementing low level controller for the mpo700 mobile robot" CACHE INTERNAL "")
set(mpo700-controller_YEARS 2017 CACHE INTERNAL "")
set(mpo700-controller_LICENSE CeCILL-C CACHE INTERNAL "")
set(mpo700-controller_ADDRESS git@gite.lirmm.fr:neobotix-mpo700/mpo700-controller.git CACHE INTERNAL "")
set(mpo700-controller_PUBLIC_ADDRESS https://gite.lirmm.fr/neobotix-mpo700/mpo700-controller.git CACHE INTERNAL "")
set(mpo700-controller_CATEGORIES CACHE INTERNAL "")
set(mpo700-controller_REFERENCES  CACHE INTERNAL "")
