#### referencing package hardio_powerswitch mode ####
set(hardio_powerswitch_MAIN_AUTHOR _Charles_Villard CACHE INTERNAL "")
set(hardio_powerswitch_MAIN_INSTITUTION  CACHE INTERNAL "")
set(hardio_powerswitch_CONTACT_MAIL  CACHE INTERNAL "")
set(hardio_powerswitch_FRAMEWORK  CACHE INTERNAL "")
set(hardio_powerswitch_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(hardio_powerswitch_PROJECT_PAGE  CACHE INTERNAL "")
set(hardio_powerswitch_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(hardio_powerswitch_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(hardio_powerswitch_AUTHORS_AND_INSTITUTIONS "_Charles_Villard();_Clement_Rebut" CACHE INTERNAL "")
set(hardio_powerswitch_DESCRIPTION "This;is;the;library;to;control;the;powerswitch;board" CACHE INTERNAL "")
set(hardio_powerswitch_YEARS 2018 CACHE INTERNAL "")
set(hardio_powerswitch_LICENSE CeCILL CACHE INTERNAL "")
set(hardio_powerswitch_ADDRESS git@gite.lirmm.fr:hardio/devices/hardio_powerswitch.git CACHE INTERNAL "")
set(hardio_powerswitch_PUBLIC_ADDRESS https://gite.lirmm.fr/hardio/devices/hardio_powerswitch.git CACHE INTERNAL "")
set(hardio_powerswitch_CATEGORIES CACHE INTERNAL "")
set(hardio_powerswitch_REFERENCES  CACHE INTERNAL "")
