#### referencing package api-driver-vrep mode ####
set(api-driver-vrep_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(api-driver-vrep_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(api-driver-vrep_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(api-driver-vrep_FRAMEWORK rpc CACHE INTERNAL "")
set(api-driver-vrep_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(api-driver-vrep_PROJECT_PAGE https://gite.lirmm.fr/rob-miscellaneous/api-driver-vrep CACHE INTERNAL "")
set(api-driver-vrep_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(api-driver-vrep_SITE_INTRODUCTION "C/C++ remote programming API for V-REP simulator (http://coppeliarobotics.com/). This is a transformation into PID of V-REP API." CACHE INTERNAL "")
set(api-driver-vrep_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(api-driver-vrep_DESCRIPTION "PID package providing V-REP C/C++ remote API" CACHE INTERNAL "")
set(api-driver-vrep_YEARS 2015 CACHE INTERNAL "")
set(api-driver-vrep_LICENSE CeCILL-C CACHE INTERNAL "")
set(api-driver-vrep_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/api-driver-vrep.git CACHE INTERNAL "")
set(api-driver-vrep_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/api-driver-vrep.git CACHE INTERNAL "")
set(api-driver-vrep_CATEGORIES "simulator" CACHE INTERNAL "")
set(api-driver-vrep_REFERENCES  CACHE INTERNAL "")
