#### referencing wrapper of external package mraa ####
set(mraa_PID_WRAPPER_CONTACT_AUTHOR _Clement Rebut CACHE INTERNAL "")
set(mraa_PID_WRAPPER_CONTACT_INSTITUTION  CACHE INTERNAL "")
set(mraa_PID_WRAPPER_CONTACT_MAIL clement.rebut@epita.fr CACHE INTERNAL "")
set(mraa_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(mraa_PID_WRAPPER_PROJECT_PAGE  CACHE INTERNAL "")
set(mraa_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(mraa_PID_WRAPPER_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(mraa_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Clement Rebut()" CACHE INTERNAL "")
set(mraa_PID_WRAPPER_YEARS 2019 CACHE INTERNAL "")
set(mraa_PID_WRAPPER_LICENSE CeCILL CACHE INTERNAL "")
set(mraa_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:hardio/wrappers/mraa.git CACHE INTERNAL "")
set(mraa_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/hardio/wrappers/mraa.git CACHE INTERNAL "")
set(mraa_DESCRIPTION "wrapper for mraa, that allows the use of gpio pins" CACHE INTERNAL "")
set(mraa_FRAMEWORK  CACHE INTERNAL "")
set(mraa_CATEGORIES CACHE INTERNAL "")
set(mraa_AUTHORS "Intel" CACHE INTERNAL "")
set(mraa_PROJECT_SITE https://github.com/intel-iot-devkit/mraa CACHE INTERNAL "")
set(mraa_LICENSES MIT CACHE INTERNAL "")
set(mraa_REFERENCES  CACHE INTERNAL "")
