#### referencing wrapper of external package vtk ####
set(vtk_PID_WRAPPER_CONTACT_AUTHOR _Arnaud_Meline CACHE INTERNAL "")
set(vtk_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(vtk_PID_WRAPPER_CONTACT_MAIL arnaud.meline@lirmm.fr CACHE INTERNAL "")
set(vtk_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(vtk_PID_WRAPPER_PROJECT_PAGE  CACHE INTERNAL "")
set(vtk_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(vtk_PID_WRAPPER_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(vtk_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Arnaud_Meline(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr)" CACHE INTERNAL "")
set(vtk_PID_WRAPPER_YEARS 2019 CACHE INTERNAL "")
set(vtk_PID_WRAPPER_LICENSE BSD CACHE INTERNAL "")
set(vtk_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:rob-vision/msvf/wrappers/vtk.git CACHE INTERNAL "")
set(vtk_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-vision/msvf/wrappers/vtk.git CACHE INTERNAL "")
set(vtk_DESCRIPTION "PID;wrapper;for;Visualization;Toolkit;(;vtk;);external;project" CACHE INTERNAL "")
set(vtk_FRAMEWORK  CACHE INTERNAL "")
set(vtk_CATEGORIES CACHE INTERNAL "")
set(vtk_AUTHORS "Kitware" CACHE INTERNAL "")
set(vtk_PROJECT_SITE https://vtk.org/ CACHE INTERNAL "")
set(vtk_LICENSES BSD License CACHE INTERNAL "")
set(vtk_REFERENCES  CACHE INTERNAL "")
