#### referencing package mc_rtc-bazar-bridge mode ####
set(mc_rtc-bazar-bridge_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(mc_rtc-bazar-bridge_MAIN_INSTITUTION  CACHE INTERNAL "")
set(mc_rtc-bazar-bridge_CONTACT_MAIL  CACHE INTERNAL "")
set(mc_rtc-bazar-bridge_FRAMEWORK  CACHE INTERNAL "")
set(mc_rtc-bazar-bridge_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(mc_rtc-bazar-bridge_PROJECT_PAGE  CACHE INTERNAL "")
set(mc_rtc-bazar-bridge_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(mc_rtc-bazar-bridge_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(mc_rtc-bazar-bridge_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro()" CACHE INTERNAL "")
set(mc_rtc-bazar-bridge_DESCRIPTION "Bridge;to;make;mc_rtc;talk;to;the;BAZAR;robot" CACHE INTERNAL "")
set(mc_rtc-bazar-bridge_YEARS 2019 CACHE INTERNAL "")
set(mc_rtc-bazar-bridge_LICENSE BSD CACHE INTERNAL "")
set(mc_rtc-bazar-bridge_ADDRESS git@gite.lirmm.fr:cobot/mc_rtc-bazar-bridge.git CACHE INTERNAL "")
set(mc_rtc-bazar-bridge_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(mc_rtc-bazar-bridge_CATEGORIES CACHE INTERNAL "")
set(mc_rtc-bazar-bridge_REFERENCES  CACHE INTERNAL "")
