#### referencing package rkcl-filters mode ####
set(rkcl-filters_MAIN_AUTHOR _Sonny_Tarbouriech CACHE INTERNAL "")
set(rkcl-filters_MAIN_INSTITUTION _Tecnalia CACHE INTERNAL "")
set(rkcl-filters_CONTACT_MAIL  CACHE INTERNAL "")
set(rkcl-filters_FRAMEWORK rkcl-framework CACHE INTERNAL "")
set(rkcl-filters_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rkcl-filters_PROJECT_PAGE https://gite.lirmm.fr/rkcl/rkcl-filters CACHE INTERNAL "")
set(rkcl-filters_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rkcl-filters_SITE_INTRODUCTION "Library;of;filters;to;be;used;in;rkcl" CACHE INTERNAL "")
set(rkcl-filters_AUTHORS_AND_INSTITUTIONS "_Sonny_Tarbouriech(_Tecnalia)" CACHE INTERNAL "")
set(rkcl-filters_DESCRIPTION "Library;of;filters;to;be;used;in;rkcl" CACHE INTERNAL "")
set(rkcl-filters_YEARS 2019 CACHE INTERNAL "")
set(rkcl-filters_LICENSE CeCILL CACHE INTERNAL "")
set(rkcl-filters_ADDRESS git@gite.lirmm.fr:rkcl/rkcl-filters.git CACHE INTERNAL "")
set(rkcl-filters_PUBLIC_ADDRESS https://gite.lirmm.fr/rkcl/rkcl-filters.git CACHE INTERNAL "")
set(rkcl-filters_CATEGORIES "processor" CACHE INTERNAL "")
set(rkcl-filters_REFERENCES  CACHE INTERNAL "")
