#### referencing package imglibs-opencv mode ####
set(imglibs-opencv_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(imglibs-opencv_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(imglibs-opencv_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(imglibs-opencv_FRAMEWORK  CACHE INTERNAL "")
set(imglibs-opencv_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(imglibs-opencv_PROJECT_PAGE  CACHE INTERNAL "")
set(imglibs-opencv_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(imglibs-opencv_SITE_INTRODUCTION  CACHE INTERNAL "")
set(imglibs-opencv_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM);_Mohamed_HAIJOUBI(_LIRMM)" CACHE INTERNAL "")
set(imglibs-opencv_DESCRIPTION "wrapper for opencv 2.4 libraries" CACHE INTERNAL "")
set(imglibs-opencv_YEARS 2017 CACHE INTERNAL "")
set(imglibs-opencv_LICENSE CeCILL CACHE INTERNAL "")
set(imglibs-opencv_ADDRESS git@gite.lirmm.fr:rob-vision/imglibs-opencv.git CACHE INTERNAL "")
set(imglibs-opencv_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(imglibs-opencv_CATEGORIES CACHE INTERNAL "")
set(imglibs-opencv_REFERENCES  CACHE INTERNAL "")
