#### referencing package torque-controllers mode ####
set(torque-controllers_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(torque-controllers_MAIN_INSTITUTION _CNRS/LIRMM CACHE INTERNAL "")
set(torque-controllers_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(torque-controllers_FRAMEWORK rpc CACHE INTERNAL "")
set(torque-controllers_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(torque-controllers_PROJECT_PAGE https://gite.lirmm.fr/rob-controllers/torque-controllers CACHE INTERNAL "")
set(torque-controllers_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(torque-controllers_SITE_INTRODUCTION "torque-controllers;provides;a;set;of;torque;controllers;for;robots" CACHE INTERNAL "")
set(torque-controllers_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_CNRS/LIRMM);_Mariana_De_Paula_Assis_Fonseca(_Universidade_Federal_de_Minas_Gerais)" CACHE INTERNAL "")
set(torque-controllers_DESCRIPTION "A set of torque controllers" CACHE INTERNAL "")
set(torque-controllers_YEARS 2019 CACHE INTERNAL "")
set(torque-controllers_LICENSE CeCILL-C CACHE INTERNAL "")
set(torque-controllers_ADDRESS git@gite.lirmm.fr:rob-controllers/torque-controllers.git CACHE INTERNAL "")
set(torque-controllers_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-controllers/torque-controllers.git CACHE INTERNAL "")
set(torque-controllers_CATEGORIES "algorithm/control" CACHE INTERNAL "")
set(torque-controllers_REFERENCES  CACHE INTERNAL "")
