#### referencing package WrenchConeLib mode ####
set(WrenchConeLib_MAIN_AUTHOR _vsamy CACHE INTERNAL "")
set(WrenchConeLib_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(WrenchConeLib_CONTACT_MAIL vincent.samy@lirmm.fr CACHE INTERNAL "")
set(WrenchConeLib_FRAMEWORK  CACHE INTERNAL "")
set(WrenchConeLib_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(WrenchConeLib_PROJECT_PAGE  CACHE INTERNAL "")
set(WrenchConeLib_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(WrenchConeLib_SITE_INTRODUCTION  CACHE INTERNAL "")
set(WrenchConeLib_AUTHORS_AND_INSTITUTIONS "_vsamy(_LIRMM)" CACHE INTERNAL "")
set(WrenchConeLib_DESCRIPTION "This library implements the Contact Wrench Cone as given [here](https://scaron.info/papers/journal/caron-tro-2016.pdf). It uses cdd for the polyhedron computation and Eigen for the matrix part. Python bindings are also available." CACHE INTERNAL "")
set(WrenchConeLib_YEARS 2017 CACHE INTERNAL "")
set(WrenchConeLib_LICENSE CeCILL-C CACHE INTERNAL "")
set(WrenchConeLib_ADDRESS git@github.com:vsamy/WrenchConeLib.git CACHE INTERNAL "")
set(WrenchConeLib_PUBLIC_ADDRESS https://github.com/vsamy/WrenchConeLib.git CACHE INTERNAL "")
set(WrenchConeLib_CATEGORIES CACHE INTERNAL "")
set(WrenchConeLib_REFERENCES  CACHE INTERNAL "")
