#### referencing package pioneer-apps mode ####
set(pioneer-apps_MAIN_AUTHOR _Philippe_Lambert CACHE INTERNAL "")
set(pioneer-apps_MAIN_INSTITUTION  CACHE INTERNAL "")
set(pioneer-apps_CONTACT_MAIL  CACHE INTERNAL "")
set(pioneer-apps_FRAMEWORK  CACHE INTERNAL "")
set(pioneer-apps_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(pioneer-apps_PROJECT_PAGE  CACHE INTERNAL "")
set(pioneer-apps_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(pioneer-apps_SITE_INTRODUCTION  CACHE INTERNAL "")
set(pioneer-apps_AUTHORS_AND_INSTITUTIONS "_Philippe_Lambert()" CACHE INTERNAL "")
set(pioneer-apps_DESCRIPTION "Package utiliser pour développer des applications liés au pioneer" CACHE INTERNAL "")
set(pioneer-apps_YEARS 2017 CACHE INTERNAL "")
set(pioneer-apps_LICENSE CeCILL CACHE INTERNAL "")
set(pioneer-apps_ADDRESS git@gite.lirmm.fr:pioneer3DX/pioneer-apps.git CACHE INTERNAL "")
set(pioneer-apps_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(pioneer-apps_CATEGORIES CACHE INTERNAL "")
set(pioneer-apps_REFERENCES  CACHE INTERNAL "")
