#### referencing package kuka-lwr-applications mode ####
set(kuka-lwr-applications_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(kuka-lwr-applications_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(kuka-lwr-applications_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(kuka-lwr-applications_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM);_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(kuka-lwr-applications_DESCRIPTION A package that contains several applications for the Kuka LWR CACHE INTERNAL "")
set(kuka-lwr-applications_YEARS 2015 CACHE INTERNAL "")
set(kuka-lwr-applications_LICENSE CeCILL-C CACHE INTERNAL "")
set(kuka-lwr-applications_ADDRESS git@gite.lirmm.fr:kuka-lwr/kuka-lwr-applications.git CACHE INTERNAL "")
set(kuka-lwr-applications_CATEGORIES "arm/kuka-lwr" CACHE INTERNAL "")
set(kuka-lwr-applications_REFERENCES  CACHE INTERNAL "")
