#### referencing package shadow-hand-knowbotics mode ####
set(shadow-hand-knowbotics_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(shadow-hand-knowbotics_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(shadow-hand-knowbotics_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(shadow-hand-knowbotics_FRAMEWORK  CACHE INTERNAL "")
set(shadow-hand-knowbotics_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(shadow-hand-knowbotics_PROJECT_PAGE  CACHE INTERNAL "")
set(shadow-hand-knowbotics_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(shadow-hand-knowbotics_SITE_INTRODUCTION  CACHE INTERNAL "")
set(shadow-hand-knowbotics_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM);_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(shadow-hand-knowbotics_DESCRIPTION "A package that describes the Shadow Dexterous Hand as a Knowbotics object" CACHE INTERNAL "")
set(shadow-hand-knowbotics_YEARS 2015 CACHE INTERNAL "")
set(shadow-hand-knowbotics_LICENSE CeCILL-C CACHE INTERNAL "")
set(shadow-hand-knowbotics_ADDRESS git@gite.lirmm.fr:shadow-hands/shadow-hand-knowbotics.git CACHE INTERNAL "")
set(shadow-hand-knowbotics_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(shadow-hand-knowbotics_CATEGORIES "hand/shadow-dexterous;knowbotics/hand" CACHE INTERNAL "")
set(shadow-hand-knowbotics_REFERENCES  CACHE INTERNAL "")
