#### referencing package sch-core mode ####
set(sch-core_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(sch-core_MAIN_INSTITUTION  CACHE INTERNAL "")
set(sch-core_CONTACT_MAIL  CACHE INTERNAL "")
set(sch-core_FRAMEWORK rpc CACHE INTERNAL "")
set(sch-core_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(sch-core_PROJECT_PAGE https://gite.lirmm.fr/rob-miscellaneous/sch-core CACHE INTERNAL "")
set(sch-core_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(sch-core_SITE_INTRODUCTION "PID repackaging of DSPFilters project (https://github.com/vinniefalco/DSPFilters): sch-core is an Efficient implementation of GJK algorithm for proximity queries (collision detection, distance computations, penetration depths and withness points) between convex shapes. The library can be extended to any convex shape for which we can compute the support function, but it already supports polyhedrons, boxes, spheres and ellipsoids, and it is particularly optimized for strictly convex hulls (SCH/STP-BV)." CACHE INTERNAL "")
set(sch-core_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro()" CACHE INTERNAL "")
set(sch-core_DESCRIPTION "PID repackaging of sch-core (https://github.com/jrl-umi3218/sch-core)" CACHE INTERNAL "")
set(sch-core_YEARS 2017 CACHE INTERNAL "")
set(sch-core_LICENSE GNUGPL CACHE INTERNAL "")
set(sch-core_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/sch-core.git CACHE INTERNAL "")
set(sch-core_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/sch-core.git CACHE INTERNAL "")
set(sch-core_CATEGORIES "algorithm/3d" CACHE INTERNAL "")
set(sch-core_REFERENCES  CACHE INTERNAL "")
