#### referencing package rkcl-osqp-solver mode ####
set(rkcl-osqp-solver_MAIN_AUTHOR _Sonny_Tarbouriech CACHE INTERNAL "")
set(rkcl-osqp-solver_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(rkcl-osqp-solver_CONTACT_MAIL  CACHE INTERNAL "")
set(rkcl-osqp-solver_FRAMEWORK  CACHE INTERNAL "")
set(rkcl-osqp-solver_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rkcl-osqp-solver_PROJECT_PAGE  CACHE INTERNAL "")
set(rkcl-osqp-solver_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rkcl-osqp-solver_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(rkcl-osqp-solver_AUTHORS_AND_INSTITUTIONS "_Sonny_Tarbouriech(_LIRMM)" CACHE INTERNAL "")
set(rkcl-osqp-solver_DESCRIPTION "OSQP;solver;wrapped;in;RKCL" CACHE INTERNAL "")
set(rkcl-osqp-solver_YEARS 2020 CACHE INTERNAL "")
set(rkcl-osqp-solver_LICENSE CeCILL CACHE INTERNAL "")
set(rkcl-osqp-solver_ADDRESS git@gitlab.com:rkcl/rkcl-osqp-solver.git CACHE INTERNAL "")
set(rkcl-osqp-solver_PUBLIC_ADDRESS https://gitlab.com/rkcl/rkcl-osqp-solver.git CACHE INTERNAL "")
set(rkcl-osqp-solver_CATEGORIES CACHE INTERNAL "")
set(rkcl-osqp-solver_REFERENCES  CACHE INTERNAL "")
