#### referencing package eigen-quadprog mode ####
set(eigen-quadprog_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(eigen-quadprog_MAIN_INSTITUTION  CACHE INTERNAL "")
set(eigen-quadprog_CONTACT_MAIL  CACHE INTERNAL "")
set(eigen-quadprog_FRAMEWORK  CACHE INTERNAL "")
set(eigen-quadprog_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(eigen-quadprog_PROJECT_PAGE  CACHE INTERNAL "")
set(eigen-quadprog_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(eigen-quadprog_SITE_INTRODUCTION  CACHE INTERNAL "")
set(eigen-quadprog_AUTHORS_AND_INSTITUTIONS "_Robin_Passama();_Joris_Vaillant(_LIRMM)" CACHE INTERNAL "")
set(eigen-quadprog_DESCRIPTION "QuadProg QP solver through Eigen3 library, by Joris Vaillant (<joris dot vaillant at gmail dot com>). PID native package wrapping project https://github.com/jrl-umi3218/eigen-quadprog" CACHE INTERNAL "")
set(eigen-quadprog_YEARS 2017 CACHE INTERNAL "")
set(eigen-quadprog_LICENSE GNULGPL CACHE INTERNAL "")
set(eigen-quadprog_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/eigen-quadprog.git CACHE INTERNAL "")
set(eigen-quadprog_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(eigen-quadprog_CATEGORIES CACHE INTERNAL "")
set(eigen-quadprog_REFERENCES  CACHE INTERNAL "")
