#### referencing package rkcl-driver-neobotix-mpo700 mode ####
set(rkcl-driver-neobotix-mpo700_MAIN_AUTHOR _Sonny_Tarbouriech CACHE INTERNAL "")
set(rkcl-driver-neobotix-mpo700_MAIN_INSTITUTION _Tecnalia CACHE INTERNAL "")
set(rkcl-driver-neobotix-mpo700_CONTACT_MAIL  CACHE INTERNAL "")
set(rkcl-driver-neobotix-mpo700_FRAMEWORK  CACHE INTERNAL "")
set(rkcl-driver-neobotix-mpo700_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rkcl-driver-neobotix-mpo700_PROJECT_PAGE  CACHE INTERNAL "")
set(rkcl-driver-neobotix-mpo700_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rkcl-driver-neobotix-mpo700_SITE_INTRODUCTION  CACHE INTERNAL "")
set(rkcl-driver-neobotix-mpo700_AUTHORS_AND_INSTITUTIONS "_Sonny_Tarbouriech(_Tecnalia);_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(rkcl-driver-neobotix-mpo700_DESCRIPTION "TODO:;input;a;short;description;of;package;rkcl-driver-neobotix-mpo700;utility;here" CACHE INTERNAL "")
set(rkcl-driver-neobotix-mpo700_YEARS 2019 CACHE INTERNAL "")
set(rkcl-driver-neobotix-mpo700_LICENSE CeCILL CACHE INTERNAL "")
set(rkcl-driver-neobotix-mpo700_ADDRESS git@gitlab.com:rkcl/rkcl-driver-neobotix-mpo700.git CACHE INTERNAL "")
set(rkcl-driver-neobotix-mpo700_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(rkcl-driver-neobotix-mpo700_CATEGORIES CACHE INTERNAL "")
set(rkcl-driver-neobotix-mpo700_REFERENCES  CACHE INTERNAL "")
