#### referencing wrapper of external package raisim-lib ####
set(raisim-lib_PID_WRAPPER_CONTACT_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(raisim-lib_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(raisim-lib_PID_WRAPPER_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(raisim-lib_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(raisim-lib_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/rob-miscellaneous/raisim-lib CACHE INTERNAL "")
set(raisim-lib_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(raisim-lib_PID_WRAPPER_SITE_INTRODUCTION "This project is a PID wrapper for the external project called raisimLib. raisimLib is a physics engine for robotics and ai research." CACHE INTERNAL "")
set(raisim-lib_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr)" CACHE INTERNAL "")
set(raisim-lib_PID_WRAPPER_YEARS 2020 CACHE INTERNAL "")
set(raisim-lib_PID_WRAPPER_LICENSE CeCILL-C CACHE INTERNAL "")
set(raisim-lib_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/raisim-lib.git CACHE INTERNAL "")
set(raisim-lib_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/raisim-lib.git CACHE INTERNAL "")
set(raisim-lib_DESCRIPTION "raisimLib is a physics engine for robotics and ai research" CACHE INTERNAL "")
set(raisim-lib_FRAMEWORK rpc CACHE INTERNAL "")
set(raisim-lib_CATEGORIES "simulator" CACHE INTERNAL "")
set(raisim-lib_AUTHORS "Jemin Hwangbo" CACHE INTERNAL "")
set(raisim-lib_PROJECT_SITE https://github.com/leggedrobotics/raisimLib CACHE INTERNAL "")
set(raisim-lib_LICENSES ETH Zurich EULA CACHE INTERNAL "")
set(raisim-lib_REFERENCES  CACHE INTERNAL "")
