#### referencing package signal-processing-knowbotics mode ####
set(signal-processing-knowbotics_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(signal-processing-knowbotics_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(signal-processing-knowbotics_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(signal-processing-knowbotics_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(signal-processing-knowbotics_DESCRIPTION Filter and other processing tools for signal like data CACHE INTERNAL "")
set(signal-processing-knowbotics_YEARS 2015 CACHE INTERNAL "")
set(signal-processing-knowbotics_LICENSE CeCILL-C CACHE INTERNAL "")
set(signal-processing-knowbotics_ADDRESS git@gite.lirmm.fr:knowbotics/signal-processing-knowbotics.git CACHE INTERNAL "")
set(signal-processing-knowbotics_CATEGORIES CACHE INTERNAL "")
set(signal-processing-knowbotics_AVAILABLE_PLATFORMS linux64;linux32;macosx64;macosx32 CACHE INTERNAL "")
set(signal-processing-knowbotics_AVAILABLE_PLATFORM_linux64_OS linux CACHE INTERNAL "")
set(signal-processing-knowbotics_AVAILABLE_PLATFORM_linux64_ARCH 64 CACHE INTERNAL "")
set(signal-processing-knowbotics_AVAILABLE_PLATFORM_linux64_CONFIGURATION  CACHE INTERNAL "")
set(signal-processing-knowbotics_AVAILABLE_PLATFORM_linux32_OS linux CACHE INTERNAL "")
set(signal-processing-knowbotics_AVAILABLE_PLATFORM_linux32_ARCH 32 CACHE INTERNAL "")
set(signal-processing-knowbotics_AVAILABLE_PLATFORM_linux32_CONFIGURATION  CACHE INTERNAL "")
set(signal-processing-knowbotics_AVAILABLE_PLATFORM_macosx64_OS macosx CACHE INTERNAL "")
set(signal-processing-knowbotics_AVAILABLE_PLATFORM_macosx64_ARCH 64 CACHE INTERNAL "")
set(signal-processing-knowbotics_AVAILABLE_PLATFORM_macosx64_CONFIGURATION  CACHE INTERNAL "")
set(signal-processing-knowbotics_AVAILABLE_PLATFORM_macosx32_OS macosx CACHE INTERNAL "")
set(signal-processing-knowbotics_AVAILABLE_PLATFORM_macosx32_ARCH 32 CACHE INTERNAL "")
set(signal-processing-knowbotics_AVAILABLE_PLATFORM_macosx32_CONFIGURATION  CACHE INTERNAL "")
set(signal-processing-knowbotics_REFERENCES  CACHE INTERNAL "")
