#### referencing package camera-calibration mode ####
set(camera-calibration_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(camera-calibration_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(camera-calibration_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(camera-calibration_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM);_Florian_Raffalli(_LIRMM)" CACHE INTERNAL "")
set(camera-calibration_DESCRIPTION some code used to calibrate camera based on openCV CACHE INTERNAL "")
set(camera-calibration_YEARS 2015 CACHE INTERNAL "")
set(camera-calibration_LICENSE CeCILL-C CACHE INTERNAL "")
set(camera-calibration_ADDRESS git@gite.lirmm.fr:rob-vision-devices/camera-calibration.git CACHE INTERNAL "")
set(camera-calibration_CATEGORIES  CACHE INTERNAL "")
set(camera-calibration_REFERENCES  CACHE INTERNAL "")
