#### referencing wrapper of external package eigen ####
set(eigen_PID_WRAPPER_CONTACT_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(eigen_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(eigen_PID_WRAPPER_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(eigen_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(eigen_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/pid/eigen CACHE INTERNAL "")
set(eigen_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(eigen_PID_WRAPPER_SITE_INTRODUCTION eigen;is;a;PID;wrapper;for;the;external;project;called;Eigen.;Eigen;provides;C++;API;for;linear;algebra;and;matrix;programming. CACHE INTERNAL "")
set(eigen_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr)" CACHE INTERNAL "")
set(eigen_PID_WRAPPER_YEARS 2018 CACHE INTERNAL "")
set(eigen_PID_WRAPPER_LICENSE GNULGPL CACHE INTERNAL "")
set(eigen_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:pid/wrappers/eigen.git CACHE INTERNAL "")
set(eigen_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/wrappers/eigen.git CACHE INTERNAL "")
set(eigen_DESCRIPTION "external package providing linear algebra and related math utilities" CACHE INTERNAL "")
set(eigen_FRAMEWORK pid CACHE INTERNAL "")
set(eigen_CATEGORIES "programming/math;math/linear_algebra" CACHE INTERNAL "")
set(eigen_AUTHORS "Eigen developers team" CACHE INTERNAL "")
set(eigen_PROJECT_SITE http://eigen.tuxfamily.org CACHE INTERNAL "")
set(eigen_LICENSES MPL2 CACHE INTERNAL "")
set(eigen_REFERENCES  CACHE INTERNAL "")
