#### referencing wrapper of external package yoctolib_cpp ####
set(yoctolib_cpp_PID_WRAPPER_CONTACT_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(yoctolib_cpp_PID_WRAPPER_CONTACT_INSTITUTION _CNRS/LIRMM CACHE INTERNAL "")
set(yoctolib_cpp_PID_WRAPPER_CONTACT_MAIL robin.passama@lirmm.fr CACHE INTERNAL "")
set(yoctolib_cpp_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(yoctolib_cpp_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/rob-miscellaneous/yoctolib_cpp CACHE INTERNAL "")
set(yoctolib_cpp_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(yoctolib_cpp_PID_WRAPPER_SITE_INTRODUCTION "PID wapper for the yoctolib library. This library is used to interface sofwtare with devices developped by the yoctopuce SARL company." CACHE INTERNAL "")
set(yoctolib_cpp_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_CNRS/LIRMM)" CACHE INTERNAL "")
set(yoctolib_cpp_PID_WRAPPER_YEARS 2018 CACHE INTERNAL "")
set(yoctolib_cpp_PID_WRAPPER_LICENSE CeCILL-C CACHE INTERNAL "")
set(yoctolib_cpp_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/yoctolib_cpp.git CACHE INTERNAL "")
set(yoctolib_cpp_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/yoctolib_cpp.git CACHE INTERNAL "")
set(yoctolib_cpp_DESCRIPTION "Wrapper;for;yoctolib_cpp;project,;a;library;to;interact;with;devices;from;yoctopuce" CACHE INTERNAL "")
set(yoctolib_cpp_FRAMEWORK rpc CACHE INTERNAL "")
set(yoctolib_cpp_CATEGORIES "driver/electronic_device" CACHE INTERNAL "")
set(yoctolib_cpp_AUTHORS "Yoctopuce SARL" CACHE INTERNAL "")
set(yoctolib_cpp_PROJECT_SITE http://www.yoctopuce.com CACHE INTERNAL "")
set(yoctolib_cpp_LICENSES Yoctopuce Licence CACHE INTERNAL "")
set(yoctolib_cpp_REFERENCES  CACHE INTERNAL "")
