#### referencing package stm32-mylib mode ####
set(stm32-mylib_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(stm32-mylib_MAIN_INSTITUTION  CACHE INTERNAL "")
set(stm32-mylib_CONTACT_MAIL  CACHE INTERNAL "")
set(stm32-mylib_FRAMEWORK  CACHE INTERNAL "")
set(stm32-mylib_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(stm32-mylib_PROJECT_PAGE  CACHE INTERNAL "")
set(stm32-mylib_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(stm32-mylib_SITE_INTRODUCTION  CACHE INTERNAL "")
set(stm32-mylib_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro()" CACHE INTERNAL "")
set(stm32-mylib_DESCRIPTION C++;wrapper;for;some;STM32;internal;and;external;peripherals CACHE INTERNAL "")
set(stm32-mylib_YEARS 2017 CACHE INTERNAL "")
set(stm32-mylib_LICENSE CeCILL CACHE INTERNAL "")
set(stm32-mylib_ADDRESS git@gite.lirmm.fr:stm32/stm32-mylib.git CACHE INTERNAL "")
set(stm32-mylib_CATEGORIES CACHE INTERNAL "")
set(stm32-mylib_REFERENCES  CACHE INTERNAL "")
