#### referencing package reflexxes mode ####
set(reflexxes_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(reflexxes_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(reflexxes_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(reflexxes_FRAMEWORK  CACHE INTERNAL "")
set(reflexxes_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(reflexxes_PROJECT_PAGE  CACHE INTERNAL "")
set(reflexxes_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(reflexxes_SITE_INTRODUCTION  CACHE INTERNAL "")
set(reflexxes_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(reflexxes_DESCRIPTION PID Wrapper for the Reflexxes Type-II library CACHE INTERNAL "")
set(reflexxes_YEARS 2015 CACHE INTERNAL "")
set(reflexxes_LICENSE CeCILL-C CACHE INTERNAL "")
set(reflexxes_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/reflexxes.git CACHE INTERNAL "")
set(reflexxes_CATEGORIES "motion/trajectory" CACHE INTERNAL "")
set(reflexxes_REFERENCES 1.2.1 CACHE INTERNAL "")
set(reflexxes_REFERENCE_1.2.1 x86_64_linux_abi98;x86_64_linux_abi11 CACHE INTERNAL "")
set(reflexxes_REFERENCE_1.2.1_x86_64_linux_abi98_URL https://gite.lirmm.fr/rob-miscellaneous/rob-miscellaneous-binaries/wikis/reflexxes/1.2.1/linux64/reflexxes-1.2.1-linux64.tar.gz CACHE INTERNAL "")
set(reflexxes_REFERENCE_1.2.1_x86_64_linux_abi98_URL_DEBUG https://gite.lirmm.fr/rob-miscellaneous/rob-miscellaneous-binaries/wikis/reflexxes/1.2.1/linux64/reflexxes-1.2.1-dbg-linux64.tar.gz CACHE INTERNAL "")
set(reflexxes_REFERENCE_1.2.1_x86_64_linux_abi11_URL https://gite.lirmm.fr/rob-miscellaneous/rob-miscellaneous-binaries/wikis/reflexxes/1.2.1/linux64cxx11/reflexxes-1.2.1-linux64cxx11.tar.gz CACHE INTERNAL "")
set(reflexxes_REFERENCE_1.2.1_x86_64_linux_abi11_URL_DEBUG https://gite.lirmm.fr/rob-miscellaneous/rob-miscellaneous-binaries/wikis/reflexxes/1.2.1/linux64cxx11/reflexxes-1.2.1-dbg-linux64cxx11.tar.gz CACHE INTERNAL "")
