#### referencing wrapper of external package opencv ####
set(opencv_PID_WRAPPER_CONTACT_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(opencv_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(opencv_PID_WRAPPER_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(opencv_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(opencv_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/pid/opencv CACHE INTERNAL "")
set(opencv_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(opencv_PID_WRAPPER_SITE_INTRODUCTION This;project;is;a;PID;wrapper;for;the;external;project;called;opencv.;opencv;provides;many;libraries;used;for;image;processing. CACHE INTERNAL "")
set(opencv_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr)" CACHE INTERNAL "")
set(opencv_PID_WRAPPER_YEARS 2018 CACHE INTERNAL "")
set(opencv_PID_WRAPPER_LICENSE BSD CACHE INTERNAL "")
set(opencv_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:pid/opencv.git CACHE INTERNAL "")
set(opencv_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/opencv.git CACHE INTERNAL "")
set(opencv_DESCRIPTION "PID wrapper for opencv external project" CACHE INTERNAL "")
set(opencv_FRAMEWORK pid CACHE INTERNAL "")
set(opencv_CATEGORIES "programming/image" CACHE INTERNAL "")
set(opencv_AUTHORS "opencv.org members" CACHE INTERNAL "")
set(opencv_PROJECT_SITE http://www.opencv.org CACHE INTERNAL "")
set(opencv_LICENSES 3-clause BSD License CACHE INTERNAL "")
set(opencv_REFERENCES  CACHE INTERNAL "")
