#### referencing package neobotix-mpo700-udp-interface mode ####
set(neobotix-mpo700-udp-interface_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(neobotix-mpo700-udp-interface_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(neobotix-mpo700-udp-interface_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(neobotix-mpo700-udp-interface_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(neobotix-mpo700-udp-interface_DESCRIPTION project providings libraries to enable udp communication between a PC and the neobotix MPO700 platform CACHE INTERNAL "")
set(neobotix-mpo700-udp-interface_YEARS 2015 CACHE INTERNAL "")
set(neobotix-mpo700-udp-interface_LICENSE CeCILL-C CACHE INTERNAL "")
set(neobotix-mpo700-udp-interface_ADDRESS git@gite.lirmm.fr:neobotix-mpo700/neobotix-mpo700-udp-interface.git CACHE INTERNAL "")
set(neobotix-mpo700-udp-interface_CATEGORIES "mobile-robot/mpo700" CACHE INTERNAL "")
set(neobotix-mpo700-udp-interface_REFERENCES  CACHE INTERNAL "")
