#### referencing environment nvcc_toolchain mode ####
set(nvcc_toolchain_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(nvcc_toolchain_MAIN_INSTITUTION _CNRS/LIRMM CACHE INTERNAL "")
set(nvcc_toolchain_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_CNRS/LIRMM)" CACHE INTERNAL "")
set(nvcc_toolchain_YEARS 2019 CACHE INTERNAL "")
set(nvcc_toolchain_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(nvcc_toolchain_ADDRESS git@gite.lirmm.fr:pid/environments/nvcc_toolchain.git CACHE INTERNAL "")
set(nvcc_toolchain_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/environments/nvcc_toolchain.git CACHE INTERNAL "")
set(nvcc_toolchain_LICENSE CeCILL-C CACHE INTERNAL "")
set(nvcc_toolchain_DESCRIPTION using CUDA nvcc toolchain to build code for NVIDIA GPU CACHE INTERNAL "")
