#### referencing package target-pose-in-robot-frame mode ####
set(target-pose-in-robot-frame_MAIN_AUTHOR _Abdellah_Khelloufi CACHE INTERNAL "")
set(target-pose-in-robot-frame_MAIN_INSTITUTION  CACHE INTERNAL "")
set(target-pose-in-robot-frame_CONTACT_MAIL  CACHE INTERNAL "")
set(target-pose-in-robot-frame_FRAMEWORK  CACHE INTERNAL "")
set(target-pose-in-robot-frame_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(target-pose-in-robot-frame_PROJECT_PAGE  CACHE INTERNAL "")
set(target-pose-in-robot-frame_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(target-pose-in-robot-frame_SITE_INTRODUCTION  CACHE INTERNAL "")
set(target-pose-in-robot-frame_AUTHORS_AND_INSTITUTIONS "_Abdellah_Khelloufi();_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(target-pose-in-robot-frame_DESCRIPTION "Calculate the target pose in the robot frame using odometry and target pose in the world frame." CACHE INTERNAL "")
set(target-pose-in-robot-frame_YEARS 2017 CACHE INTERNAL "")
set(target-pose-in-robot-frame_LICENSE CeCILL CACHE INTERNAL "")
set(target-pose-in-robot-frame_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/target-pose-in-robot-frame.git CACHE INTERNAL "")
set(target-pose-in-robot-frame_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(target-pose-in-robot-frame_CATEGORIES "mobile-robot/modified-youbot;mobile-robot/simulated;knowbotics/mobile-robot;simulator/vrep" CACHE INTERNAL "")
set(target-pose-in-robot-frame_REFERENCES  CACHE INTERNAL "")
