#### referencing package yocto-watt-driver mode ####
set(yocto-watt-driver_MAIN_AUTHOR _Philippe_Lambert CACHE INTERNAL "")
set(yocto-watt-driver_MAIN_INSTITUTION _University_of_Montpellier_/_LIRMM CACHE INTERNAL "")
set(yocto-watt-driver_CONTACT_MAIL plambert@lirmm.fr CACHE INTERNAL "")
set(yocto-watt-driver_FRAMEWORK rpc CACHE INTERNAL "")
set(yocto-watt-driver_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(yocto-watt-driver_PROJECT_PAGE https://gite.lirmm.fr/pioneer3DX/yocto-watt-driver CACHE INTERNAL "")
set(yocto-watt-driver_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(yocto-watt-driver_SITE_INTRODUCTION "PID package providing simple API to use watt-metters from Yoctopuce SARL company." CACHE INTERNAL "")
set(yocto-watt-driver_AUTHORS_AND_INSTITUTIONS "_Philippe_Lambert(_University_of_Montpellier_/_LIRMM);_Robin_Passama(_CNRS_/_LIRMM)" CACHE INTERNAL "")
set(yocto-watt-driver_DESCRIPTION "Driver;library;for;watt-meters;from;Yoctopuce;company" CACHE INTERNAL "")
set(yocto-watt-driver_YEARS 2017 CACHE INTERNAL "")
set(yocto-watt-driver_LICENSE CeCILL CACHE INTERNAL "")
set(yocto-watt-driver_ADDRESS git@gite.lirmm.fr:pioneer3DX/yocto-watt-driver.git CACHE INTERNAL "")
set(yocto-watt-driver_PUBLIC_ADDRESS https://gite.lirmm.fr/pioneer3DX/yocto-watt-driver.git CACHE INTERNAL "")
set(yocto-watt-driver_CATEGORIES "driver/electronic_device" CACHE INTERNAL "")
set(yocto-watt-driver_REFERENCES  CACHE INTERNAL "")
