#### referencing package shadow-hand-applications mode ####
set(shadow-hand-applications_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(shadow-hand-applications_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(shadow-hand-applications_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(shadow-hand-applications_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(shadow-hand-applications_DESCRIPTION A package containing applications for the Shadow Dexterous hand CACHE INTERNAL "")
set(shadow-hand-applications_YEARS 2015 CACHE INTERNAL "")
set(shadow-hand-applications_LICENSE CeCILL-C CACHE INTERNAL "")
set(shadow-hand-applications_ADDRESS git@gite.lirmm.fr:shadow-hands/shadow-hand-applications.git CACHE INTERNAL "")
set(shadow-hand-applications_CATEGORIES "robot/hand" CACHE INTERNAL "")
set(shadow-hand-applications_REFERENCES  CACHE INTERNAL "")
