#### referencing package space-vec-alg mode ####
set(space-vec-alg_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(space-vec-alg_MAIN_INSTITUTION _CNRS/LIRMM CACHE INTERNAL "")
set(space-vec-alg_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(space-vec-alg_FRAMEWORK rpc CACHE INTERNAL "")
set(space-vec-alg_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(space-vec-alg_PROJECT_PAGE https://gite.lirmm.fr/rob-miscellaneous/space-vec-alg CACHE INTERNAL "")
set(space-vec-alg_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(space-vec-alg_SITE_INTRODUCTION "PID repackaging of SpaceVecAlg (https://github.com/jrl-umi3218/SpaceVecAlg): implementation of spatial vector algebra with the Eigen3 linear algebra library. All this implementation is based on appendix A of Roy Featherstone Rigid Body Dynamics Algorithms book." CACHE INTERNAL "")
set(space-vec-alg_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_CNRS/LIRMM);_Joris_Vaillant(_CNRS-UM/LIRMM_and_CNRS-AIST/JRL);_Robin_Passama(_CNRS/LIRMM)" CACHE INTERNAL "")
set(space-vec-alg_DESCRIPTION "PID;repackaging;of;SpaceVecAlg:;https://github.com/jrl-umi3218/SpaceVecAlg" CACHE INTERNAL "")
set(space-vec-alg_YEARS 2012-2019 CACHE INTERNAL "")
set(space-vec-alg_LICENSE GNULGPL CACHE INTERNAL "")
set(space-vec-alg_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/space-vec-alg.git CACHE INTERNAL "")
set(space-vec-alg_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/space-vec-alg.git CACHE INTERNAL "")
set(space-vec-alg_CATEGORIES "algorithm/math" CACHE INTERNAL "")
set(space-vec-alg_REFERENCES  CACHE INTERNAL "")
