#### referencing package open-phri mode ####
set(open-phri_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(open-phri_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(open-phri_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(open-phri_FRAMEWORK  CACHE INTERNAL "")
set(open-phri_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(open-phri_PROJECT_PAGE  CACHE INTERNAL "")
set(open-phri_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(open-phri_SITE_INTRODUCTION  CACHE INTERNAL "")
set(open-phri_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(open-phri_DESCRIPTION OpenPHRI: a generic framework to easily and safely control robots in interactions with humans CACHE INTERNAL "")
set(open-phri_YEARS 2017 CACHE INTERNAL "")
set(open-phri_LICENSE GNULGPL CACHE INTERNAL "")
set(open-phri_ADDRESS git@github.com:BenjaminNavarro/open-phri.git CACHE INTERNAL "")
set(open-phri_CATEGORIES CACHE INTERNAL "")
set(open-phri_REFERENCES  CACHE INTERNAL "")
