#### referencing package rkcl-qld-solver mode ####
set(rkcl-qld-solver_MAIN_AUTHOR _Sonny_Tarbouriech CACHE INTERNAL "")
set(rkcl-qld-solver_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(rkcl-qld-solver_CONTACT_MAIL  CACHE INTERNAL "")
set(rkcl-qld-solver_FRAMEWORK rkcl-framework CACHE INTERNAL "")
set(rkcl-qld-solver_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rkcl-qld-solver_PROJECT_PAGE https://gite.lirmm.fr/rkcl/rkcl-qld-solver CACHE INTERNAL "")
set(rkcl-qld-solver_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rkcl-qld-solver_SITE_INTRODUCTION "RKCL;wrapper;for;the;QLD;(;linear;quadratic;programming;);solver" CACHE INTERNAL "")
set(rkcl-qld-solver_AUTHORS_AND_INSTITUTIONS "_Sonny_Tarbouriech(_LIRMM)" CACHE INTERNAL "")
set(rkcl-qld-solver_DESCRIPTION "RKCL;wrapper;for;the;QLD;(;linear;quadratic;programming;);solver" CACHE INTERNAL "")
set(rkcl-qld-solver_YEARS 2020 CACHE INTERNAL "")
set(rkcl-qld-solver_LICENSE CeCILL CACHE INTERNAL "")
set(rkcl-qld-solver_ADDRESS git@gite.lirmm.fr:rkcl/rkcl-qld-solver.git CACHE INTERNAL "")
set(rkcl-qld-solver_PUBLIC_ADDRESS https://gite.lirmm.fr/rkcl/rkcl-qld-solver.git CACHE INTERNAL "")
set(rkcl-qld-solver_CATEGORIES "solver" CACHE INTERNAL "")
set(rkcl-qld-solver_REFERENCES  CACHE INTERNAL "")
