#### referencing package kuka-lwr-driver-vrep mode ####
set(kuka-lwr-driver-vrep_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(kuka-lwr-driver-vrep_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(kuka-lwr-driver-vrep_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(kuka-lwr-driver-vrep_AUTHORS_AND_INSTITUTIONS ;"_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(kuka-lwr-driver-vrep_DESCRIPTION A package to interface with a simulated Kuka LWR on V-REP CACHE INTERNAL "")
set(kuka-lwr-driver-vrep_YEARS 20145 CACHE INTERNAL "")
set(kuka-lwr-driver-vrep_LICENSE CeCILL-C CACHE INTERNAL "")
set(kuka-lwr-driver-vrep_ADDRESS git@rob-dev.lirmm.fr:kuka-lwr-knowbotics/kuka-lwr-knowbotics.git CACHE INTERNAL "")
set(kuka-lwr-driver-vrep_CATEGORIES robot/arm;driver/vrep CACHE INTERNAL "")
set(kuka-lwr-driver-vrep_REFERENCES  CACHE INTERNAL "")
