#### referencing package pygen-converter mode ####
set(pygen-converter_MAIN_AUTHOR _Vincent_Samy CACHE INTERNAL "")
set(pygen-converter_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(pygen-converter_CONTACT_MAIL vincent.samy@lirmm.fr CACHE INTERNAL "")
set(pygen-converter_FRAMEWORK  CACHE INTERNAL "")
set(pygen-converter_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(pygen-converter_PROJECT_PAGE  CACHE INTERNAL "")
set(pygen-converter_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(pygen-converter_SITE_INTRODUCTION  CACHE INTERNAL "")
set(pygen-converter_AUTHORS_AND_INSTITUTIONS "_Vincent_Samy(_LIRMM)" CACHE INTERNAL "")
set(pygen-converter_DESCRIPTION "This is an header only library that provides list to eigen and numpy to eigen converters for boost python." CACHE INTERNAL "")
set(pygen-converter_YEARS 2017 CACHE INTERNAL "")
set(pygen-converter_LICENSE CeCILL-C CACHE INTERNAL "")
set(pygen-converter_ADDRESS git@github.com:vsamy/pygen-converter.git CACHE INTERNAL "")
set(pygen-converter_PUBLIC_ADDRESS https://github.com/vsamy/pygen-converter.git CACHE INTERNAL "")
set(pygen-converter_CATEGORIES CACHE INTERNAL "")
set(pygen-converter_REFERENCES  CACHE INTERNAL "")
