#### referencing package pid-rpath mode ####
set(pid-rpath_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(pid-rpath_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(pid-rpath_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(pid-rpath_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(pid-rpath_DESCRIPTION Default package of PID, used to manage runtime path of executables CACHE INTERNAL "")
set(pid-rpath_YEARS 2015 CACHE INTERNAL "")
set(pid-rpath_LICENSE CeCILL-C CACHE INTERNAL "")
set(pid-rpath_ADDRESS git@gite.lirmm.fr:pid/pid-rpath.git CACHE INTERNAL "")
set(pid-rpath_CATEGORIES "programming/resources_management" CACHE INTERNAL "")
set(pid-rpath_AVAILABLE_PLATFORMS linux64;linux32;macosx64;macosx32 CACHE INTERNAL "")
set(pid-rpath_AVAILABLE_PLATFORM_linux64_OS linux CACHE INTERNAL "")
set(pid-rpath_AVAILABLE_PLATFORM_linux64_ARCH 64 CACHE INTERNAL "")
set(pid-rpath_AVAILABLE_PLATFORM_linux64_CONFIGURATION  CACHE INTERNAL "")
set(pid-rpath_AVAILABLE_PLATFORM_linux32_OS linux CACHE INTERNAL "")
set(pid-rpath_AVAILABLE_PLATFORM_linux32_ARCH 32 CACHE INTERNAL "")
set(pid-rpath_AVAILABLE_PLATFORM_linux32_CONFIGURATION  CACHE INTERNAL "")
set(pid-rpath_AVAILABLE_PLATFORM_macosx64_OS macosx CACHE INTERNAL "")
set(pid-rpath_AVAILABLE_PLATFORM_macosx64_ARCH 64 CACHE INTERNAL "")
set(pid-rpath_AVAILABLE_PLATFORM_macosx64_CONFIGURATION  CACHE INTERNAL "")
set(pid-rpath_AVAILABLE_PLATFORM_macosx32_OS macosx CACHE INTERNAL "")
set(pid-rpath_AVAILABLE_PLATFORM_macosx32_ARCH 32 CACHE INTERNAL "")
set(pid-rpath_AVAILABLE_PLATFORM_macosx32_CONFIGURATION  CACHE INTERNAL "")
set(pid-rpath_REFERENCES 1.0.0;1.0.0 CACHE INTERNAL "")
set(pid-rpath_REFERENCE_1.0.0 linux64;linux32 CACHE INTERNAL "")
set(pid-rpath_REFERENCE_1.0.0_linux64_URL https://gite.lirmm.fr/pid/pid-binaries/wikis/pid-rpath/1.0.0/linux64/pid-rpath-1.0.0-linux64.tar.gz CACHE INTERNAL "")
set(pid-rpath_REFERENCE_1.0.0_linux64_URL_DEBUG https://gite.lirmm.fr/pid/pid-binaries/wikis/pid-rpath/1.0.0/linux64/pid-rpath-1.0.0-dbg-linux64.tar.gz CACHE INTERNAL "")
set(pid-rpath_REFERENCE_1.0.0_linux32_URL https://gite.lirmm.fr/pid/pid-binaries/wikis/pid-rpath/1.0.0/linux32/pid-rpath-1.0.0-linux32.tar.gz.gz CACHE INTERNAL "")
set(pid-rpath_REFERENCE_1.0.0_linux32_URL_DEBUG https://gite.lirmm.fr/pid/pid-binaries/wikis/pid-rpath/1.0.0/linux32/pid-rpath-1.0.0-dbg-linux32.tar.gz CACHE INTERNAL "")
set(pid-rpath_REFERENCE_1.0.0 linux64;linux32 CACHE INTERNAL "")
set(pid-rpath_REFERENCE_1.0.0_linux64_URL https://gite.lirmm.fr/pid/pid-binaries/wikis/pid-rpath/1.0.0/linux64/pid-rpath-1.0.0-linux64.tar.gz CACHE INTERNAL "")
set(pid-rpath_REFERENCE_1.0.0_linux64_URL_DEBUG https://gite.lirmm.fr/pid/pid-binaries/wikis/pid-rpath/1.0.0/linux64/pid-rpath-1.0.0-dbg-linux64.tar.gz CACHE INTERNAL "")
set(pid-rpath_REFERENCE_1.0.0_linux32_URL https://gite.lirmm.fr/pid/pid-binaries/wikis/pid-rpath/1.0.0/linux32/pid-rpath-1.0.0-linux32.tar.gz.gz CACHE INTERNAL "")
set(pid-rpath_REFERENCE_1.0.0_linux32_URL_DEBUG https://gite.lirmm.fr/pid/pid-binaries/wikis/pid-rpath/1.0.0/linux32/pid-rpath-1.0.0-dbg-linux32.tar.gz CACHE INTERNAL "")
