#### referencing package ethercatcpp-shadow mode ####
set(ethercatcpp-shadow_MAIN_AUTHOR _Meline_Arnaud CACHE INTERNAL "")
set(ethercatcpp-shadow_MAIN_INSTITUTION  CACHE INTERNAL "")
set(ethercatcpp-shadow_CONTACT_MAIL meline@lirmm.fr CACHE INTERNAL "")
set(ethercatcpp-shadow_FRAMEWORK ethercatcpp CACHE INTERNAL "")
set(ethercatcpp-shadow_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(ethercatcpp-shadow_PROJECT_PAGE https://gite.lirmm.fr/ethercatcpp/ethercatcpp-shadow CACHE INTERNAL "")
set(ethercatcpp-shadow_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(ethercatcpp-shadow_SITE_INTRODUCTION ethercatcpp-shadow;is;a;package;providing;the;ethercat;driver;for;shadow;hands. CACHE INTERNAL "")
set(ethercatcpp-shadow_AUTHORS_AND_INSTITUTIONS "_Meline_Arnaud()" CACHE INTERNAL "")
set(ethercatcpp-shadow_DESCRIPTION "Ethercat driver library for shadow hand" CACHE INTERNAL "")
set(ethercatcpp-shadow_YEARS 2018 CACHE INTERNAL "")
set(ethercatcpp-shadow_LICENSE CeCILL-C CACHE INTERNAL "")
set(ethercatcpp-shadow_ADDRESS git@gite.lirmm.fr:ethercatcpp/ethercatcpp-shadow.git CACHE INTERNAL "")
set(ethercatcpp-shadow_PUBLIC_ADDRESS https://gite.lirmm.fr/ethercatcpp/ethercatcpp-shadow.git CACHE INTERNAL "")
set(ethercatcpp-shadow_CATEGORIES "ethercat/robot" CACHE INTERNAL "")
set(ethercatcpp-shadow_REFERENCES  CACHE INTERNAL "")
