#### referencing package leapmotion-knowbotics mode ####
set(leapmotion-knowbotics_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(leapmotion-knowbotics_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(leapmotion-knowbotics_CONTACT_MAIL passama@lirmmm.fr CACHE INTERNAL "")
set(leapmotion-knowbotics_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(leapmotion-knowbotics_DESCRIPTION knowbotics extension for the leapmotion device CACHE INTERNAL "")
set(leapmotion-knowbotics_YEARS 2016 CACHE INTERNAL "")
set(leapmotion-knowbotics_LICENSE CeCILL-C CACHE INTERNAL "")
set(leapmotion-knowbotics_ADDRESS git@gite.lirmm.fr:rob-vision-devices/leapmotion-knowbotics.git CACHE INTERNAL "")
set(leapmotion-knowbotics_CATEGORIES "image;vision;knowbotics/vision" CACHE INTERNAL "")
set(leapmotion-knowbotics_AVAILABLE_PLATFORMS linux64cxx11;linux64;linux32;macosx64 CACHE INTERNAL "")
set(leapmotion-knowbotics_AVAILABLE_PLATFORM_linux64cxx11_OS linux CACHE INTERNAL "")
set(leapmotion-knowbotics_AVAILABLE_PLATFORM_linux64cxx11_ARCH 64 CACHE INTERNAL "")
set(leapmotion-knowbotics_AVAILABLE_PLATFORM_linux64cxx11_ABI CXX11 CACHE INTERNAL "")
set(leapmotion-knowbotics_AVAILABLE_PLATFORM_linux64cxx11_CONFIGURATION  CACHE INTERNAL "")
set(leapmotion-knowbotics_AVAILABLE_PLATFORM_linux64_OS linux CACHE INTERNAL "")
set(leapmotion-knowbotics_AVAILABLE_PLATFORM_linux64_ARCH 64 CACHE INTERNAL "")
set(leapmotion-knowbotics_AVAILABLE_PLATFORM_linux64_ABI CXX CACHE INTERNAL "")
set(leapmotion-knowbotics_AVAILABLE_PLATFORM_linux64_CONFIGURATION  CACHE INTERNAL "")
set(leapmotion-knowbotics_AVAILABLE_PLATFORM_linux32_OS linux CACHE INTERNAL "")
set(leapmotion-knowbotics_AVAILABLE_PLATFORM_linux32_ARCH 32 CACHE INTERNAL "")
set(leapmotion-knowbotics_AVAILABLE_PLATFORM_linux32_ABI CXX CACHE INTERNAL "")
set(leapmotion-knowbotics_AVAILABLE_PLATFORM_linux32_CONFIGURATION  CACHE INTERNAL "")
set(leapmotion-knowbotics_AVAILABLE_PLATFORM_macosx64_OS macosx CACHE INTERNAL "")
set(leapmotion-knowbotics_AVAILABLE_PLATFORM_macosx64_ARCH 64 CACHE INTERNAL "")
set(leapmotion-knowbotics_AVAILABLE_PLATFORM_macosx64_ABI CXX CACHE INTERNAL "")
set(leapmotion-knowbotics_AVAILABLE_PLATFORM_macosx64_CONFIGURATION  CACHE INTERNAL "")
set(leapmotion-knowbotics_REFERENCES  CACHE INTERNAL "")
