#### referencing package ethercatcpp-epos mode ####
set(ethercatcpp-epos_MAIN_AUTHOR _Meline_Arnaud CACHE INTERNAL "")
set(ethercatcpp-epos_MAIN_INSTITUTION  CACHE INTERNAL "")
set(ethercatcpp-epos_CONTACT_MAIL meline@lirmm.fr CACHE INTERNAL "")
set(ethercatcpp-epos_FRAMEWORK ethercatcpp CACHE INTERNAL "")
set(ethercatcpp-epos_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(ethercatcpp-epos_PROJECT_PAGE https://gite.lirmm.fr/ethercatcpp/ethercatcpp-epos CACHE INTERNAL "")
set(ethercatcpp-epos_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(ethercatcpp-epos_SITE_INTRODUCTION ethercatcpp-epos;is;a;package;providing;the;ethercat;driver;for;epos3;and;epos4. CACHE INTERNAL "")
set(ethercatcpp-epos_AUTHORS_AND_INSTITUTIONS "_Meline_Arnaud()" CACHE INTERNAL "")
set(ethercatcpp-epos_DESCRIPTION "ethercat driver libraries for Maxon Epos3 and Epos4" CACHE INTERNAL "")
set(ethercatcpp-epos_YEARS 2018 CACHE INTERNAL "")
set(ethercatcpp-epos_LICENSE CeCILL-C CACHE INTERNAL "")
set(ethercatcpp-epos_ADDRESS git@gite.lirmm.fr:ethercatcpp/ethercatcpp-epos.git CACHE INTERNAL "")
set(ethercatcpp-epos_PUBLIC_ADDRESS https://gite.lirmm.fr/ethercatcpp/ethercatcpp-epos.git CACHE INTERNAL "")
set(ethercatcpp-epos_CATEGORIES "ethercat/actuator/drive" CACHE INTERNAL "")
set(ethercatcpp-epos_REFERENCES  CACHE INTERNAL "")
