#### referencing package pid-log mode ####
set(pid-log_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(pid-log_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(pid-log_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(pid-log_FRAMEWORK pid CACHE INTERNAL "")
set(pid-log_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(pid-log_PROJECT_PAGE https://gite.lirmm.fr/pid/pid-log CACHE INTERNAL "")
set(pid-log_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(pid-log_SITE_INTRODUCTION pid-log;package;provides;a;little;API;to;manage;logs;in;a;clean;and;really;configurable;way.;It;is;based;on;Boost.Log;meta;logging;system.;Its;usage;is;completely;bound;to;the;use;of;PID;system. CACHE INTERNAL "")
set(pid-log_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(pid-log_DESCRIPTION A package that defines libraries to easily manage logging CACHE INTERNAL "")
set(pid-log_YEARS 2014 CACHE INTERNAL "")
set(pid-log_LICENSE CeCILL-C CACHE INTERNAL "")
set(pid-log_ADDRESS git@gite.lirmm.fr:pid/pid-log.git CACHE INTERNAL "")
set(pid-log_CATEGORIES "programming/logging" CACHE INTERNAL "")
set(pid-log_REFERENCES 1.0.0 CACHE INTERNAL "")
set(pid-log_REFERENCE_1.0.0 x86_64_linux_abi98;x86_64_linux_abi11 CACHE INTERNAL "")
set(pid-log_REFERENCE_1.0.0_x86_64_linux_abi98_URL https://gite.lirmm.fr/pid/pid-binaries/wikis/pid-log/1.0.0/linux64/pid-log-1.0.0-linux64.tar.gz CACHE INTERNAL "")
set(pid-log_REFERENCE_1.0.0_x86_64_linux_abi98_URL_DEBUG https://gite.lirmm.fr/pid/pid-binaries/wikis/pid-log/1.0.0/linux64/pid-log-1.0.0-dbg-linux64.tar.gz CACHE INTERNAL "")
set(pid-log_REFERENCE_1.0.0_x86_64_linux_abi11_URL https://gite.lirmm.fr/pid/pid-binaries/wikis/pid-log/1.0.0/linux64cxx11/pid-log-1.0.0-linux64cxx11.tar.gz CACHE INTERNAL "")
set(pid-log_REFERENCE_1.0.0_x86_64_linux_abi11_URL_DEBUG https://gite.lirmm.fr/pid/pid-binaries/wikis/pid-log/1.0.0/linux64cxx11/pid-log-1.0.0-dbg-linux64cxx11.tar.gz CACHE INTERNAL "")
