#### referencing package impedance-controllers mode ####
set(impedance-controllers_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(impedance-controllers_MAIN_INSTITUTION  CACHE INTERNAL "")
set(impedance-controllers_CONTACT_MAIL  CACHE INTERNAL "")
set(impedance-controllers_FRAMEWORK  CACHE INTERNAL "")
set(impedance-controllers_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(impedance-controllers_PROJECT_PAGE  CACHE INTERNAL "")
set(impedance-controllers_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(impedance-controllers_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(impedance-controllers_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro()" CACHE INTERNAL "")
set(impedance-controllers_DESCRIPTION "A;set;of;impedance;controllers;(;standard;&;QP;based;)" CACHE INTERNAL "")
set(impedance-controllers_YEARS 2019 CACHE INTERNAL "")
set(impedance-controllers_LICENSE CeCILL CACHE INTERNAL "")
set(impedance-controllers_ADDRESS git@gite.lirmm.fr:rob-controllers/impedance-controllers.git CACHE INTERNAL "")
set(impedance-controllers_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-controllers/impedance-controllers.git CACHE INTERNAL "")
set(impedance-controllers_CATEGORIES CACHE INTERNAL "")
set(impedance-controllers_REFERENCES  CACHE INTERNAL "")
