#### referencing wrapper of external package freetype2 ####
set(freetype2_PID_WRAPPER_CONTACT_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(freetype2_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(freetype2_PID_WRAPPER_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(freetype2_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(freetype2_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/pid/wrappers/freetype2 CACHE INTERNAL "")
set(freetype2_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(freetype2_PID_WRAPPER_SITE_INTRODUCTION freetype2;is;a;PID;wrapper;for;the;external;project;called;FreeType2.;FreeType2;is;a;A;Free,;High-Quality,;and;Portable;Font;Engine. CACHE INTERNAL "")
set(freetype2_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr);_Robin_Passama(_CNRS/LIRMM)" CACHE INTERNAL "")
set(freetype2_PID_WRAPPER_YEARS 2018 CACHE INTERNAL "")
set(freetype2_PID_WRAPPER_LICENSE GNULGPL CACHE INTERNAL "")
set(freetype2_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:pid/wrappers/freetype2.git CACHE INTERNAL "")
set(freetype2_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/wrappers/freetype2.git CACHE INTERNAL "")
set(freetype2_DESCRIPTION "PID wrapper for the freetype2 project." CACHE INTERNAL "")
set(freetype2_FRAMEWORK pid CACHE INTERNAL "")
set(freetype2_CATEGORIES "programming/gui" CACHE INTERNAL "")
set(freetype2_AUTHORS "David Turner, Robert Wilhelm, and Werner Lemberg" CACHE INTERNAL "")
set(freetype2_PROJECT_SITE http://freetype.sourceforge.net/index2.html CACHE INTERNAL "")
set(freetype2_LICENSES GNUGPL CACHE INTERNAL "")
set(freetype2_REFERENCES  CACHE INTERNAL "")
