#### referencing package cooperative-task-controller mode ####
set(cooperative-task-controller_MAIN_AUTHOR _Sonny_Tarbouriech CACHE INTERNAL "")
set(cooperative-task-controller_MAIN_INSTITUTION _LIRMM_/_Tecnalia CACHE INTERNAL "")
set(cooperative-task-controller_CONTACT_MAIL sonny.tarbouriech@lirmm.fr CACHE INTERNAL "")
set(cooperative-task-controller_FRAMEWORK  CACHE INTERNAL "")
set(cooperative-task-controller_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(cooperative-task-controller_PROJECT_PAGE  CACHE INTERNAL "")
set(cooperative-task-controller_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(cooperative-task-controller_SITE_INTRODUCTION  CACHE INTERNAL "")
set(cooperative-task-controller_AUTHORS_AND_INSTITUTIONS "_Sonny_Tarbouriech(_LIRMM_/_Tecnalia);_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(cooperative-task-controller_DESCRIPTION "A;set;of;classes;for;dual-arm;control;using;the;cooperative;task;space;representation" CACHE INTERNAL "")
set(cooperative-task-controller_YEARS 2018 CACHE INTERNAL "")
set(cooperative-task-controller_LICENSE GNULGPL CACHE INTERNAL "")
set(cooperative-task-controller_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/cooperative-task-controller.git CACHE INTERNAL "")
set(cooperative-task-controller_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/cooperative-task-controller.git CACHE INTERNAL "")
set(cooperative-task-controller_CATEGORIES CACHE INTERNAL "")
set(cooperative-task-controller_REFERENCES  CACHE INTERNAL "")
