#### referencing package usb-relay-driver mode ####
set(usb-relay-driver_MAIN_AUTHOR _Philippe_Lambert CACHE INTERNAL "")
set(usb-relay-driver_MAIN_INSTITUTION  CACHE INTERNAL "")
set(usb-relay-driver_CONTACT_MAIL  CACHE INTERNAL "")
set(usb-relay-driver_FRAMEWORK  CACHE INTERNAL "")
set(usb-relay-driver_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(usb-relay-driver_PROJECT_PAGE  CACHE INTERNAL "")
set(usb-relay-driver_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(usb-relay-driver_SITE_INTRODUCTION  CACHE INTERNAL "")
set(usb-relay-driver_AUTHORS_AND_INSTITUTIONS "_Philippe_Lambert()" CACHE INTERNAL "")
set(usb-relay-driver_DESCRIPTION "driver library for USB relay" CACHE INTERNAL "")
set(usb-relay-driver_YEARS 2017 CACHE INTERNAL "")
set(usb-relay-driver_LICENSE CeCILL-C CACHE INTERNAL "")
set(usb-relay-driver_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/usb-relay-driver.git CACHE INTERNAL "")
set(usb-relay-driver_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(usb-relay-driver_CATEGORIES CACHE INTERNAL "")
set(usb-relay-driver_REFERENCES  CACHE INTERNAL "")
