#### referencing package rkcl-staubli-robot mode ####
set(rkcl-staubli-robot_MAIN_AUTHOR _Sonny_Tarbouriech CACHE INTERNAL "")
set(rkcl-staubli-robot_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(rkcl-staubli-robot_CONTACT_MAIL  CACHE INTERNAL "")
set(rkcl-staubli-robot_FRAMEWORK rkcl-framework CACHE INTERNAL "")
set(rkcl-staubli-robot_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rkcl-staubli-robot_PROJECT_PAGE https://gite.lirmm.fr/rkcl/rkcl-staubli-robot CACHE INTERNAL "")
set(rkcl-staubli-robot_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rkcl-staubli-robot_SITE_INTRODUCTION "Helper;package;to;work;with;Staubli;manipulator;arms" CACHE INTERNAL "")
set(rkcl-staubli-robot_AUTHORS_AND_INSTITUTIONS "_Sonny_Tarbouriech(_LIRMM)" CACHE INTERNAL "")
set(rkcl-staubli-robot_DESCRIPTION "Helper;package;to;work;with;Staubli;manipulator;arms" CACHE INTERNAL "")
set(rkcl-staubli-robot_YEARS 2020 CACHE INTERNAL "")
set(rkcl-staubli-robot_LICENSE CeCILL CACHE INTERNAL "")
set(rkcl-staubli-robot_ADDRESS git@gite.lirmm.fr:rkcl/rkcl-staubli-robot.git CACHE INTERNAL "")
set(rkcl-staubli-robot_PUBLIC_ADDRESS https://gite.lirmm.fr/rkcl/rkcl-staubli-robot.git CACHE INTERNAL "")
set(rkcl-staubli-robot_CATEGORIES "robot" CACHE INTERNAL "")
set(rkcl-staubli-robot_REFERENCES  CACHE INTERNAL "")
