#### referencing package pid-rpath mode ####
set(pid-rpath_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(pid-rpath_MAIN_INSTITUTION _LIRMM_EMAIL_passama@lirmm.fr CACHE INTERNAL "")
set(pid-rpath_CONTACT_MAIL  CACHE INTERNAL "")
set(pid-rpath_AUTHORS_AND_INSTITUTIONS ; "_Robin_Passama(_LIRMM_EMAIL_passama@lirmm.fr)" CACHE INTERNAL "")
set(pid-rpath_DESCRIPTION one of the default package of PID,used to manage runtime path of executables CACHE INTERNAL "")
set(pid-rpath_YEARS 2015 CACHE INTERNAL "")
set(pid-rpath_LICENSE CeCILL CACHE INTERNAL "")
set(pid-rpath_ADDRESS git@rob-dev.lirmm.fr:pid/pid-rpath.git CACHE INTERNAL "")
set(pid-rpath_CATEGORIES  CACHE INTERNAL "")
set(pid-rpath_REFERENCES  CACHE INTERNAL "")
