#### referencing package kinect2-driver mode ####
set(kinect2-driver_MAIN_AUTHOR _Lambert_Philippe CACHE INTERNAL "")
set(kinect2-driver_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(kinect2-driver_CONTACT_MAIL plambert@lirmm.fr CACHE INTERNAL "")
set(kinect2-driver_FRAMEWORK  CACHE INTERNAL "")
set(kinect2-driver_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(kinect2-driver_PROJECT_PAGE  CACHE INTERNAL "")
set(kinect2-driver_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(kinect2-driver_SITE_INTRODUCTION  CACHE INTERNAL "")
set(kinect2-driver_AUTHORS_AND_INSTITUTIONS "_Lambert_Philippe(_LIRMM)" CACHE INTERNAL "")
set(kinect2-driver_DESCRIPTION "Driver for Microsoft kinect V2 using Freenect 2" CACHE INTERNAL "")
set(kinect2-driver_YEARS 2018 CACHE INTERNAL "")
set(kinect2-driver_LICENSE CeCILL CACHE INTERNAL "")
set(kinect2-driver_ADDRESS git@gite.lirmm.fr:rob-vision-devices/kinect2-driver.git CACHE INTERNAL "")
set(kinect2-driver_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-vision-devices/kinect2-driver.git CACHE INTERNAL "")
set(kinect2-driver_CATEGORIES CACHE INTERNAL "")
set(kinect2-driver_REFERENCES  CACHE INTERNAL "")
