#### referencing package rkcl-app-utility mode ####
set(rkcl-app-utility_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(rkcl-app-utility_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(rkcl-app-utility_CONTACT_MAIL  CACHE INTERNAL "")
set(rkcl-app-utility_FRAMEWORK  CACHE INTERNAL "")
set(rkcl-app-utility_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rkcl-app-utility_PROJECT_PAGE  CACHE INTERNAL "")
set(rkcl-app-utility_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rkcl-app-utility_SITE_INTRODUCTION  CACHE INTERNAL "")
set(rkcl-app-utility_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM);_Sonny_Tarbouriech(_Tecnalia)" CACHE INTERNAL "")
set(rkcl-app-utility_DESCRIPTION "Utility;to;ease;the;creation;of;applications;based;on;RKCL." CACHE INTERNAL "")
set(rkcl-app-utility_YEARS 2019 CACHE INTERNAL "")
set(rkcl-app-utility_LICENSE CeCILL CACHE INTERNAL "")
set(rkcl-app-utility_ADDRESS git@gitlab.com:rkcl/rkcl-app-utility.git CACHE INTERNAL "")
set(rkcl-app-utility_PUBLIC_ADDRESS https://gitlab.com/rkcl/rkcl-app-utility.git CACHE INTERNAL "")
set(rkcl-app-utility_CATEGORIES CACHE INTERNAL "")
set(rkcl-app-utility_REFERENCES  CACHE INTERNAL "")
