#### referencing environment ub18_gcc8 mode ####
set(ub18_gcc8_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(ub18_gcc8_MAIN_INSTITUTION _LIRMM/CNRS CACHE INTERNAL "")
set(ub18_gcc8_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM/CNRS)" CACHE INTERNAL "")
set(ub18_gcc8_YEARS 2019 CACHE INTERNAL "")
set(ub18_gcc8_CONTACT_MAIL robin.passama@lirmm.fr CACHE INTERNAL "")
set(ub18_gcc8_ADDRESS git@gite.lirmm.fr:pid/environments/ub18_gcc8.git CACHE INTERNAL "")
set(ub18_gcc8_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/environments/ub18_gcc8.git CACHE INTERNAL "")
set(ub18_gcc8_LICENSE CeCILL-C CACHE INTERNAL "")
set(ub18_gcc8_DESCRIPTION development environment description for an ubuntu 18 x86_64 platform with gnu 8.3 toolchain CACHE INTERNAL "")
