#### referencing package rkcl-collision-sch mode ####
set(rkcl-collision-sch_MAIN_AUTHOR _Sonny_Tarbouriech CACHE INTERNAL "")
set(rkcl-collision-sch_MAIN_INSTITUTION _Tecnalia CACHE INTERNAL "")
set(rkcl-collision-sch_CONTACT_MAIL  CACHE INTERNAL "")
set(rkcl-collision-sch_FRAMEWORK  CACHE INTERNAL "")
set(rkcl-collision-sch_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rkcl-collision-sch_PROJECT_PAGE  CACHE INTERNAL "")
set(rkcl-collision-sch_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rkcl-collision-sch_SITE_INTRODUCTION  CACHE INTERNAL "")
set(rkcl-collision-sch_AUTHORS_AND_INSTITUTIONS "_Sonny_Tarbouriech(_Tecnalia);_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(rkcl-collision-sch_DESCRIPTION "TODO:;input;a;short;description;of;package;rkcl-collision-sch;utility;here" CACHE INTERNAL "")
set(rkcl-collision-sch_YEARS 2018 CACHE INTERNAL "")
set(rkcl-collision-sch_LICENSE CeCILL CACHE INTERNAL "")
set(rkcl-collision-sch_ADDRESS git@gitlab.com:rkcl/rkcl-collision-sch.git CACHE INTERNAL "")
set(rkcl-collision-sch_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(rkcl-collision-sch_CATEGORIES CACHE INTERNAL "")
set(rkcl-collision-sch_REFERENCES  CACHE INTERNAL "")
