#### referencing package pid-rpath mode ####
set(pid-rpath_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(pid-rpath_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(pid-rpath_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(pid-rpath_FRAMEWORK pid CACHE INTERNAL "")
set(pid-rpath_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(pid-rpath_PROJECT_PAGE https://gite.lirmm.fr/pid/pid-rpath CACHE INTERNAL "")
set(pid-rpath_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(pid-rpath_SITE_INTRODUCTION pid-rpath;is;a;package;providing;a;little;API;to;ease;the;management;of;runtime;resources;within;a;PID;workspace.;Runtime;resources;may;be;either;configuration;files,;executables;or;module;libraries.;Its;usage;is;completely;bound;to;the;use;of;PID;system. CACHE INTERNAL "")
set(pid-rpath_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(pid-rpath_DESCRIPTION Default package of PID, used to manage runtime path of executables CACHE INTERNAL "")
set(pid-rpath_YEARS 2015 CACHE INTERNAL "")
set(pid-rpath_LICENSE CeCILL-C CACHE INTERNAL "")
set(pid-rpath_ADDRESS git@gite.lirmm.fr:pid/pid-rpath.git CACHE INTERNAL "")
set(pid-rpath_CATEGORIES "programming/resources_management" CACHE INTERNAL "")
set(pid-rpath_REFERENCES 1.0.0 CACHE INTERNAL "")
set(pid-rpath_REFERENCE_1.0.0 x86_64_linux_abi98;x86_32_linux_abi98;x86_64_linux_abi11 CACHE INTERNAL "")
set(pid-rpath_REFERENCE_1.0.0_x86_64_linux_abi98_URL https://gite.lirmm.fr/pid/pid-binaries/wikis/pid-rpath/1.0.0/linux64/pid-rpath-1.0.0-linux64.tar.gz CACHE INTERNAL "")
set(pid-rpath_REFERENCE_1.0.0_x86_64_linux_abi98_URL_DEBUG https://gite.lirmm.fr/pid/pid-binaries/wikis/pid-rpath/1.0.0/linux64/pid-rpath-1.0.0-dbg-linux64.tar.gz CACHE INTERNAL "")
set(pid-rpath_REFERENCE_1.0.0_x86_32_linux_abi98_URL https://gite.lirmm.fr/pid/pid-binaries/wikis/pid-rpath/1.0.0/linux32/pid-rpath-1.0.0-linux32.tar.gz.gz CACHE INTERNAL "")
set(pid-rpath_REFERENCE_1.0.0_x86_32_linux_abi98_URL_DEBUG https://gite.lirmm.fr/pid/pid-binaries/wikis/pid-rpath/1.0.0/linux32/pid-rpath-1.0.0-dbg-linux32.tar.gz CACHE INTERNAL "")
set(pid-rpath_REFERENCE_1.0.0_x86_64_linux_abi11_URL https://gite.lirmm.fr/pid/pid-binaries/wikis/pid-rpath/1.0.0/linux64cxx11/pid-rpath-1.0.0-linux64.tar.gz CACHE INTERNAL "")
set(pid-rpath_REFERENCE_1.0.0_x86_64_linux_abi11_URL_DEBUG https://gite.lirmm.fr/pid/pid-binaries/wikis/pid-rpath/1.0.0/linux64cxx11/pid-rpath-1.0.0-dbg-linux64.tar.gz CACHE INTERNAL "")
