#### referencing package comedilib mode ####
set(comedilib_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(comedilib_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(comedilib_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(comedilib_FRAMEWORK  CACHE INTERNAL "")
set(comedilib_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(comedilib_PROJECT_PAGE  CACHE INTERNAL "")
set(comedilib_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(comedilib_SITE_INTRODUCTION  CACHE INTERNAL "")
set(comedilib_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(comedilib_DESCRIPTION "PID Wrapper for the Comedi library" CACHE INTERNAL "")
set(comedilib_YEARS 2018 CACHE INTERNAL "")
set(comedilib_LICENSE CeCILL-C CACHE INTERNAL "")
set(comedilib_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/comedilib.git CACHE INTERNAL "")
set(comedilib_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/comedilib.git CACHE INTERNAL "")
set(comedilib_CATEGORIES "force-sensor/generic" CACHE INTERNAL "")
set(comedilib_REFERENCES  CACHE INTERNAL "")
