#### referencing wrapper of external package plus-toolkit ####
set(plus-toolkit_PID_WRAPPER_CONTACT_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(plus-toolkit_PID_WRAPPER_CONTACT_INSTITUTION _CNRS/LIRMM CACHE INTERNAL "")
set(plus-toolkit_PID_WRAPPER_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(plus-toolkit_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(plus-toolkit_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/robmed/devices/plus-toolkit CACHE INTERNAL "")
set(plus-toolkit_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(plus-toolkit_PID_WRAPPER_SITE_INTRODUCTION "plus-toolkit;is;a;PID;wrapper;for;the;PLUS;toolkit;PlusLib;project:;a;free,;open-source;library;and;applications;for;data;acquisition,;pre-processing,;calibration,;and;real-time;streaming;of;imaging,;position;tracking,;and;other;sensor;data,;used;in;medical;applications." CACHE INTERNAL "")
set(plus-toolkit_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_CNRS/LIRMM)" CACHE INTERNAL "")
set(plus-toolkit_PID_WRAPPER_YEARS 2019 CACHE INTERNAL "")
set(plus-toolkit_PID_WRAPPER_LICENSE CeCILL-C CACHE INTERNAL "")
set(plus-toolkit_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:robmed/devices/plus-toolkit.git CACHE INTERNAL "")
set(plus-toolkit_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/robmed/devices/plus-toolkit.git CACHE INTERNAL "")
set(plus-toolkit_DESCRIPTION "free,;open-source;library;and;applications;for;data;acquisition,;pre-processing,;calibration,;and;real-time;streaming;of;imaging,;position;tracking,;and;other;sensor;data,;used;in;medical;applications." CACHE INTERNAL "")
set(plus-toolkit_FRAMEWORK rpc CACHE INTERNAL "")
set(plus-toolkit_CATEGORIES "driver/sensor/vision" CACHE INTERNAL "")
set(plus-toolkit_AUTHORS "Plus Toolkit Community and PerkLab, Queen's University" CACHE INTERNAL "")
set(plus-toolkit_PROJECT_SITE https://plustoolkit.github.io CACHE INTERNAL "")
set(plus-toolkit_LICENSES modified BSD style license  CACHE INTERNAL "")
set(plus-toolkit_REFERENCES  CACHE INTERNAL "")
