#### referencing wrapper of external package openpose ####
set(openpose_PID_WRAPPER_CONTACT_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(openpose_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM CACHE INTERNAL "")
set(openpose_PID_WRAPPER_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(openpose_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(openpose_PID_WRAPPER_PROJECT_PAGE  CACHE INTERNAL "")
set(openpose_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(openpose_PID_WRAPPER_SITE_INTRODUCTION  CACHE INTERNAL "")
set(openpose_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_CNRS_/_LIRMM)" CACHE INTERNAL "")
set(openpose_PID_WRAPPER_YEARS 2019 CACHE INTERNAL "")
set(openpose_PID_WRAPPER_LICENSE CeCILL-C CACHE INTERNAL "")
set(openpose_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:rob-vision/rob-deep-perception/wrappers/openpose.git CACHE INTERNAL "")
set(openpose_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-vision/rob-deep-perception/wrappers/openpose.git CACHE INTERNAL "")
set(openpose_DESCRIPTION "Wrapper for the openpose project, a real-time multi-person keypoint detection library for body, face, hands, and foot estimation" CACHE INTERNAL "")
set(openpose_FRAMEWORK  CACHE INTERNAL "")
set(openpose_CATEGORIES CACHE INTERNAL "")
set(openpose_AUTHORS "CMU-Perceptual-Computing-Lab" CACHE INTERNAL "")
set(openpose_PROJECT_SITE https://github.com/CMU-Perceptual-Computing-Lab/openpose CACHE INTERNAL "")
set(openpose_LICENSES openpose license CACHE INTERNAL "")
set(openpose_REFERENCES  CACHE INTERNAL "")
