#### referencing package ellipsoid-fit mode ####
set(ellipsoid-fit_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(ellipsoid-fit_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(ellipsoid-fit_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(ellipsoid-fit_FRAMEWORK  CACHE INTERNAL "")
set(ellipsoid-fit_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(ellipsoid-fit_PROJECT_PAGE  CACHE INTERNAL "")
set(ellipsoid-fit_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(ellipsoid-fit_SITE_INTRODUCTION  CACHE INTERNAL "")
set(ellipsoid-fit_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(ellipsoid-fit_DESCRIPTION "Ellipsoid fitting in C++ using Eigen. Widely inspired by https://www.mathworks.com/matlabcentral/fileexchange/24693-ellipsoid-fit" CACHE INTERNAL "")
set(ellipsoid-fit_YEARS 2018 CACHE INTERNAL "")
set(ellipsoid-fit_LICENSE GNULGPL CACHE INTERNAL "")
set(ellipsoid-fit_ADDRESS git@github.com:BenjaminNavarro/ellipsoid-fit.git CACHE INTERNAL "")
set(ellipsoid-fit_PUBLIC_ADDRESS https://github.com/BenjaminNavarro/ellipsoid-fit.git CACHE INTERNAL "")
set(ellipsoid-fit_CATEGORIES CACHE INTERNAL "")
set(ellipsoid-fit_REFERENCES  CACHE INTERNAL "")
