#### referencing package open-phri-fri-driver mode ####
set(open-phri-fri-driver_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(open-phri-fri-driver_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(open-phri-fri-driver_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(open-phri-fri-driver_FRAMEWORK  CACHE INTERNAL "")
set(open-phri-fri-driver_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(open-phri-fri-driver_PROJECT_PAGE  CACHE INTERNAL "")
set(open-phri-fri-driver_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(open-phri-fri-driver_SITE_INTRODUCTION  CACHE INTERNAL "")
set(open-phri-fri-driver_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(open-phri-fri-driver_DESCRIPTION "An OpenPHRI driver for the Kuka LWR4 robot, based on the Fast Research Interface." CACHE INTERNAL "")
set(open-phri-fri-driver_YEARS 2018 CACHE INTERNAL "")
set(open-phri-fri-driver_LICENSE GNULGPL CACHE INTERNAL "")
set(open-phri-fri-driver_ADDRESS git@github.com:BenjaminNavarro/open-phri-fri-driver.git CACHE INTERNAL "")
set(open-phri-fri-driver_PUBLIC_ADDRESS https://github.com/BenjaminNavarro/open-phri-fri-driver.git CACHE INTERNAL "")
set(open-phri-fri-driver_CATEGORIES CACHE INTERNAL "")
set(open-phri-fri-driver_REFERENCES  CACHE INTERNAL "")
