#### referencing package ati-force-sensor-driver-ros mode ####
set(ati-force-sensor-driver-ros_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(ati-force-sensor-driver-ros_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(ati-force-sensor-driver-ros_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(ati-force-sensor-driver-ros_FRAMEWORK  CACHE INTERNAL "")
set(ati-force-sensor-driver-ros_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(ati-force-sensor-driver-ros_PROJECT_PAGE  CACHE INTERNAL "")
set(ati-force-sensor-driver-ros_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(ati-force-sensor-driver-ros_SITE_INTRODUCTION  CACHE INTERNAL "")
set(ati-force-sensor-driver-ros_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(ati-force-sensor-driver-ros_DESCRIPTION "ROS;wrapper;for;the;ati-force-sensor-driver;package" CACHE INTERNAL "")
set(ati-force-sensor-driver-ros_YEARS 2018 CACHE INTERNAL "")
set(ati-force-sensor-driver-ros_LICENSE CeCILL-C CACHE INTERNAL "")
set(ati-force-sensor-driver-ros_ADDRESS git@gite.lirmm.fr:rob-force-sensors/ati-force-sensor-driver-ros.git CACHE INTERNAL "")
set(ati-force-sensor-driver-ros_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-force-sensors/ati-force-sensor-driver-ros.git CACHE INTERNAL "")
set(ati-force-sensor-driver-ros_CATEGORIES CACHE INTERNAL "")
set(ati-force-sensor-driver-ros_REFERENCES  CACHE INTERNAL "")
