#### referencing package copra mode ####
set(copra_MAIN_AUTHOR _Vincent_Samy CACHE INTERNAL "")
set(copra_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(copra_CONTACT_MAIL vsamy@outlook.fr CACHE INTERNAL "")
set(copra_FRAMEWORK  CACHE INTERNAL "")
set(copra_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(copra_PROJECT_PAGE  CACHE INTERNAL "")
set(copra_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(copra_SITE_INTRODUCTION  CACHE INTERNAL "")
set(copra_AUTHORS_AND_INSTITUTIONS "_Vincent_Samy(_LIRMM)" CACHE INTERNAL "")
set(copra_DESCRIPTION "This a C++ implementation of a Time Invariant Linear Model Predictive Controller (LMPC) done in C++14 with python bindings" CACHE INTERNAL "")
set(copra_YEARS 2017 CACHE INTERNAL "")
set(copra_LICENSE CeCILL-C CACHE INTERNAL "")
set(copra_ADDRESS git@github.com:vsamy/copra.git CACHE INTERNAL "")
set(copra_PUBLIC_ADDRESS https://github.com/vsamy/copra.git CACHE INTERNAL "")
set(copra_CATEGORIES CACHE INTERNAL "")
set(copra_REFERENCES  CACHE INTERNAL "")
