#### referencing package localization_lza mode ####
set(localization_lza_MAIN_AUTHOR _Philippe_Lambert CACHE INTERNAL "")
set(localization_lza_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(localization_lza_CONTACT_MAIL  CACHE INTERNAL "")
set(localization_lza_FRAMEWORK  CACHE INTERNAL "")
set(localization_lza_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(localization_lza_PROJECT_PAGE  CACHE INTERNAL "")
set(localization_lza_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(localization_lza_SITE_INTRODUCTION  CACHE INTERNAL "")
set(localization_lza_AUTHORS_AND_INSTITUTIONS "_Philippe_Lambert(_LIRMM)" CACHE INTERNAL "")
set(localization_lza_DESCRIPTION "Localisation algorithm designed by René Zapata" CACHE INTERNAL "")
set(localization_lza_YEARS 2018 CACHE INTERNAL "")
set(localization_lza_LICENSE CeCILL CACHE INTERNAL "")
set(localization_lza_ADDRESS git@gite.lirmm.fr:pioneer3DX/localization_lza.git CACHE INTERNAL "")
set(localization_lza_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(localization_lza_CATEGORIES CACHE INTERNAL "")
set(localization_lza_REFERENCES  CACHE INTERNAL "")
