#### referencing package rkcl-driver-ros mode ####
set(rkcl-driver-ros_MAIN_AUTHOR _Sonny_Tarbouriech CACHE INTERNAL "")
set(rkcl-driver-ros_MAIN_INSTITUTION _Tecnalia CACHE INTERNAL "")
set(rkcl-driver-ros_CONTACT_MAIL  CACHE INTERNAL "")
set(rkcl-driver-ros_FRAMEWORK  CACHE INTERNAL "")
set(rkcl-driver-ros_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rkcl-driver-ros_PROJECT_PAGE  CACHE INTERNAL "")
set(rkcl-driver-ros_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rkcl-driver-ros_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(rkcl-driver-ros_AUTHORS_AND_INSTITUTIONS "_Sonny_Tarbouriech(_Tecnalia);_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(rkcl-driver-ros_DESCRIPTION "TODO:;input;a;short;description;of;package;rkcl-driver-ros;utility;here" CACHE INTERNAL "")
set(rkcl-driver-ros_YEARS 2019 CACHE INTERNAL "")
set(rkcl-driver-ros_LICENSE CeCILL CACHE INTERNAL "")
set(rkcl-driver-ros_ADDRESS git@gitlab.com:rkcl/rkcl-driver-ros.git CACHE INTERNAL "")
set(rkcl-driver-ros_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(rkcl-driver-ros_CATEGORIES CACHE INTERNAL "")
set(rkcl-driver-ros_REFERENCES  CACHE INTERNAL "")
