#### referencing wrapper of external package forcedimension-sdk ####
set(forcedimension-sdk_PID_WRAPPER_CONTACT_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(forcedimension-sdk_PID_WRAPPER_CONTACT_INSTITUTION _CNRS/LIRMM CACHE INTERNAL "")
set(forcedimension-sdk_PID_WRAPPER_CONTACT_MAIL passama@lirmm.Fr CACHE INTERNAL "")
set(forcedimension-sdk_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(forcedimension-sdk_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/robmed/devices/forcedimension-sdk CACHE INTERNAL "")
set(forcedimension-sdk_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(forcedimension-sdk_PID_WRAPPER_SITE_INTRODUCTION "forcedimension-sdk;is;a;PID;wrapper;for;the;SDK;provided;by;force;dimension;company;to;control;theur;haptic;devices." CACHE INTERNAL "")
set(forcedimension-sdk_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_CNRS/LIRMM)" CACHE INTERNAL "")
set(forcedimension-sdk_PID_WRAPPER_YEARS 2018-2019 CACHE INTERNAL "")
set(forcedimension-sdk_PID_WRAPPER_LICENSE CeCILL-C CACHE INTERNAL "")
set(forcedimension-sdk_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:robmed/devices/forcedimension-sdk.git CACHE INTERNAL "")
set(forcedimension-sdk_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/robmed/devices/forcedimension-sdk.git CACHE INTERNAL "")
set(forcedimension-sdk_DESCRIPTION "PID Wrapper for the Force dimension SDK used to control haptic devices." CACHE INTERNAL "")
set(forcedimension-sdk_FRAMEWORK rpc CACHE INTERNAL "")
set(forcedimension-sdk_CATEGORIES "driver/robot" CACHE INTERNAL "")
set(forcedimension-sdk_AUTHORS "Force Dimension" CACHE INTERNAL "")
set(forcedimension-sdk_PROJECT_SITE http://www.forcedimension.com CACHE INTERNAL "")
set(forcedimension-sdk_LICENSES Force Dimension private license CACHE INTERNAL "")
set(forcedimension-sdk_REFERENCES  CACHE INTERNAL "")
