#### referencing package prostim-knowbotics mode ####
set(prostim-knowbotics_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(prostim-knowbotics_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(prostim-knowbotics_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(prostim-knowbotics_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(prostim-knowbotics_DESCRIPTION The knowbotics extension for using the PROSTIM stimulator CACHE INTERNAL "")
set(prostim-knowbotics_YEARS 2016 CACHE INTERNAL "")
set(prostim-knowbotics_LICENSE CeCILL-C CACHE INTERNAL "")
set(prostim-knowbotics_ADDRESS git@gite.lirmm.fr:rob-fes-devices/prostim-knowbotics.git CACHE INTERNAL "")
set(prostim-knowbotics_CATEGORIES "knowbotics/fes;fes/stimulator" CACHE INTERNAL "")
set(prostim-knowbotics_AVAILABLE_PLATFORMS linux64cxx11;linux64;linux32;macosx64 CACHE INTERNAL "")
set(prostim-knowbotics_AVAILABLE_PLATFORM_linux64cxx11_OS linux CACHE INTERNAL "")
set(prostim-knowbotics_AVAILABLE_PLATFORM_linux64cxx11_ARCH 64 CACHE INTERNAL "")
set(prostim-knowbotics_AVAILABLE_PLATFORM_linux64cxx11_ABI CXX11 CACHE INTERNAL "")
set(prostim-knowbotics_AVAILABLE_PLATFORM_linux64cxx11_CONFIGURATION  CACHE INTERNAL "")
set(prostim-knowbotics_AVAILABLE_PLATFORM_linux64_OS linux CACHE INTERNAL "")
set(prostim-knowbotics_AVAILABLE_PLATFORM_linux64_ARCH 64 CACHE INTERNAL "")
set(prostim-knowbotics_AVAILABLE_PLATFORM_linux64_ABI CXX CACHE INTERNAL "")
set(prostim-knowbotics_AVAILABLE_PLATFORM_linux64_CONFIGURATION  CACHE INTERNAL "")
set(prostim-knowbotics_AVAILABLE_PLATFORM_linux32_OS linux CACHE INTERNAL "")
set(prostim-knowbotics_AVAILABLE_PLATFORM_linux32_ARCH 32 CACHE INTERNAL "")
set(prostim-knowbotics_AVAILABLE_PLATFORM_linux32_ABI CXX CACHE INTERNAL "")
set(prostim-knowbotics_AVAILABLE_PLATFORM_linux32_CONFIGURATION  CACHE INTERNAL "")
set(prostim-knowbotics_AVAILABLE_PLATFORM_macosx64_OS macosx CACHE INTERNAL "")
set(prostim-knowbotics_AVAILABLE_PLATFORM_macosx64_ARCH 64 CACHE INTERNAL "")
set(prostim-knowbotics_AVAILABLE_PLATFORM_macosx64_ABI CXX CACHE INTERNAL "")
set(prostim-knowbotics_AVAILABLE_PLATFORM_macosx64_CONFIGURATION  CACHE INTERNAL "")
set(prostim-knowbotics_REFERENCES  CACHE INTERNAL "")
