#### referencing package api-driver-ur mode ####
set(api-driver-ur_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(api-driver-ur_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(api-driver-ur_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(api-driver-ur_FRAMEWORK rpc CACHE INTERNAL "")
set(api-driver-ur_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(api-driver-ur_PROJECT_PAGE https://gite.lirmm.fr/ur-robots/api-driver-ur CACHE INTERNAL "")
set(api-driver-ur_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(api-driver-ur_SITE_INTRODUCTION "Non-ROS and improved version of ur_modern_driver (https://github.com/ThomasTimm/ur_modern_driver) plus an easy to use wrapper" CACHE INTERNAL "")
set(api-driver-ur_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(api-driver-ur_DESCRIPTION "Non-ROS and improved version of ur_modern_driver (https://github.com/ThomasTimm/ur_modern_driver) plus an easy to use wrapper" CACHE INTERNAL "")
set(api-driver-ur_YEARS 2018 CACHE INTERNAL "")
set(api-driver-ur_LICENSE CeCILL-C CACHE INTERNAL "")
set(api-driver-ur_ADDRESS git@gite.lirmm.fr:ur-robots/api-driver-ur.git CACHE INTERNAL "")
set(api-driver-ur_PUBLIC_ADDRESS https://gite.lirmm.fr/ur-robots/api-driver-ur.git CACHE INTERNAL "")
set(api-driver-ur_CATEGORIES "driver/robot/arm" CACHE INTERNAL "")
set(api-driver-ur_REFERENCES  CACHE INTERNAL "")
