#### referencing wrapper of external package pybind11 ####
set(pybind11_PID_WRAPPER_CONTACT_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(pybind11_PID_WRAPPER_CONTACT_INSTITUTION _LIRMM-CNRS CACHE INTERNAL "")
set(pybind11_PID_WRAPPER_CONTACT_MAIL  CACHE INTERNAL "")
set(pybind11_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(pybind11_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/pid/wrappers/pybind11 CACHE INTERNAL "")
set(pybind11_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(pybind11_PID_WRAPPER_SITE_INTRODUCTION this;project;is;a;PID;wrapper;for;the;external;project;called;PyBind11.;This;is;a;lightweight;library;used;to;generate;python;bindings;from;C++11;code. CACHE INTERNAL "")
set(pybind11_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM-CNRS)" CACHE INTERNAL "")
set(pybind11_PID_WRAPPER_YEARS 2018 CACHE INTERNAL "")
set(pybind11_PID_WRAPPER_LICENSE BSD CACHE INTERNAL "")
set(pybind11_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:pid/wrappers/pybind11.git CACHE INTERNAL "")
set(pybind11_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/wrappers/pybind11.git CACHE INTERNAL "")
set(pybind11_DESCRIPTION "PID;wrapper;for;pybind11,;a;lightweigth;python;bingind;generator" CACHE INTERNAL "")
set(pybind11_FRAMEWORK pid CACHE INTERNAL "")
set(pybind11_CATEGORIES "programming/python" CACHE INTERNAL "")
set(pybind11_AUTHORS "Wenzel Jakob and other contributors" CACHE INTERNAL "")
set(pybind11_PROJECT_SITE https://github.com/pybind/pybind11 CACHE INTERNAL "")
set(pybind11_LICENSES BSD-style license CACHE INTERNAL "")
set(pybind11_REFERENCES  CACHE INTERNAL "")
