#### referencing package rtplot-fltk mode ####
set(rtplot-fltk_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(rtplot-fltk_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(rtplot-fltk_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(rtplot-fltk_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(rtplot-fltk_DESCRIPTION Real;time;plotting;library;and;application;based;on;FLTK CACHE INTERNAL "")
set(rtplot-fltk_YEARS 2016 CACHE INTERNAL "")
set(rtplot-fltk_LICENSE CeCILL CACHE INTERNAL "")
set(rtplot-fltk_ADDRESS git@gite.lirmm.fr:pid_external_deps/rtplot-fltk.git CACHE INTERNAL "")
set(rtplot-fltk_CATEGORIES CACHE INTERNAL "")
set(rtplot-fltk_AVAILABLE_PLATFORMS linux64cxx11;linux64;linux32;macosx64 CACHE INTERNAL "")
set(rtplot-fltk_AVAILABLE_PLATFORM_linux64cxx11_OS linux CACHE INTERNAL "")
set(rtplot-fltk_AVAILABLE_PLATFORM_linux64cxx11_ARCH 64 CACHE INTERNAL "")
set(rtplot-fltk_AVAILABLE_PLATFORM_linux64cxx11_ABI CXX11 CACHE INTERNAL "")
set(rtplot-fltk_AVAILABLE_PLATFORM_linux64cxx11_CONFIGURATION  CACHE INTERNAL "")
set(rtplot-fltk_AVAILABLE_PLATFORM_linux64_OS linux CACHE INTERNAL "")
set(rtplot-fltk_AVAILABLE_PLATFORM_linux64_ARCH 64 CACHE INTERNAL "")
set(rtplot-fltk_AVAILABLE_PLATFORM_linux64_ABI CXX CACHE INTERNAL "")
set(rtplot-fltk_AVAILABLE_PLATFORM_linux64_CONFIGURATION  CACHE INTERNAL "")
set(rtplot-fltk_AVAILABLE_PLATFORM_linux32_OS linux CACHE INTERNAL "")
set(rtplot-fltk_AVAILABLE_PLATFORM_linux32_ARCH 32 CACHE INTERNAL "")
set(rtplot-fltk_AVAILABLE_PLATFORM_linux32_ABI CXX CACHE INTERNAL "")
set(rtplot-fltk_AVAILABLE_PLATFORM_linux32_CONFIGURATION  CACHE INTERNAL "")
set(rtplot-fltk_AVAILABLE_PLATFORM_macosx64_OS macosx CACHE INTERNAL "")
set(rtplot-fltk_AVAILABLE_PLATFORM_macosx64_ARCH 64 CACHE INTERNAL "")
set(rtplot-fltk_AVAILABLE_PLATFORM_macosx64_ABI CXX CACHE INTERNAL "")
set(rtplot-fltk_AVAILABLE_PLATFORM_macosx64_CONFIGURATION  CACHE INTERNAL "")
set(rtplot-fltk_REFERENCES  CACHE INTERNAL "")
