#### referencing package ethercat-driver mode ####
set(ethercat-driver_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(ethercat-driver_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(ethercat-driver_CONTACT_MAIL  CACHE INTERNAL "")
set(ethercat-driver_FRAMEWORK  CACHE INTERNAL "")
set(ethercat-driver_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(ethercat-driver_PROJECT_PAGE  CACHE INTERNAL "")
set(ethercat-driver_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(ethercat-driver_SITE_INTRODUCTION  CACHE INTERNAL "")
set(ethercat-driver_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM);_Arnaud_Meline(_LIRMM)" CACHE INTERNAL "")
set(ethercat-driver_DESCRIPTION "ethercat driver libraries for UNIX" CACHE INTERNAL "")
set(ethercat-driver_YEARS 2017 CACHE INTERNAL "")
set(ethercat-driver_LICENSE GNUGPL CACHE INTERNAL "")
set(ethercat-driver_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/ethercat-driver.git CACHE INTERNAL "")
set(ethercat-driver_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/ethercat-driver.git CACHE INTERNAL "")
set(ethercat-driver_CATEGORIES CACHE INTERNAL "")
set(ethercat-driver_REFERENCES  CACHE INTERNAL "")
