#### referencing wrapper of external package nanomsg ####
set(nanomsg_PID_WRAPPER_CONTACT_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(nanomsg_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(nanomsg_PID_WRAPPER_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(nanomsg_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(nanomsg_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/pid/wrappers/nanomsg CACHE INTERNAL "")
set(nanomsg_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(nanomsg_PID_WRAPPER_SITE_INTRODUCTION PID wapper for the nanomsg library. Nanomsg is a simple high-performance implementation of several scalability protocols. These scalability protocols are light-weight messaging protocols which can be used to solve a number of very common messaging patterns, such as request/reply, publish/subscribe, surveyor/respondent, and so forth. These protocols can run over a variety of transports such as TCP, UNIX sockets, and even WebSocket. CACHE INTERNAL "")
set(nanomsg_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr);_Robin_Passama(_CNRS/LIRMM)" CACHE INTERNAL "")
set(nanomsg_PID_WRAPPER_YEARS 2018 CACHE INTERNAL "")
set(nanomsg_PID_WRAPPER_LICENSE GNULGPL CACHE INTERNAL "")
set(nanomsg_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:pid/wrappers/nanomsg.git CACHE INTERNAL "")
set(nanomsg_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/wrappers/nanomsg.git CACHE INTERNAL "")
set(nanomsg_DESCRIPTION "The nanomsg library is a simple high-performance implementation of several scalability protocols." CACHE INTERNAL "")
set(nanomsg_FRAMEWORK pid CACHE INTERNAL "")
set(nanomsg_CATEGORIES "programming/network" CACHE INTERNAL "")
set(nanomsg_AUTHORS "Martin Sustrik, Garrett D'Amore, and more" CACHE INTERNAL "")
set(nanomsg_PROJECT_SITE https://github.com/nanomsg/nanomsg CACHE INTERNAL "")
set(nanomsg_LICENSES MIT CACHE INTERNAL "")
set(nanomsg_REFERENCES  CACHE INTERNAL "")
