#### referencing package fusiontrackcpp mode ####
set(fusiontrackcpp_MAIN_AUTHOR _Pierre_Chatellier CACHE INTERNAL "")
set(fusiontrackcpp_MAIN_INSTITUTION _Université_Montpellier_/_LIRMM CACHE INTERNAL "")
set(fusiontrackcpp_CONTACT_MAIL pierre.chatellier@lirmm.fr CACHE INTERNAL "")
set(fusiontrackcpp_FRAMEWORK  CACHE INTERNAL "")
set(fusiontrackcpp_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(fusiontrackcpp_PROJECT_PAGE  CACHE INTERNAL "")
set(fusiontrackcpp_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(fusiontrackcpp_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(fusiontrackcpp_AUTHORS_AND_INSTITUTIONS "_Pierre_Chatellier(_Université_Montpellier_/_LIRMM)" CACHE INTERNAL "")
set(fusiontrackcpp_DESCRIPTION "C++ wrapper API for fusiontrack optical tracker" CACHE INTERNAL "")
set(fusiontrackcpp_YEARS 2019 CACHE INTERNAL "")
set(fusiontrackcpp_LICENSE CeCILL-C CACHE INTERNAL "")
set(fusiontrackcpp_ADDRESS git@gite.lirmm.fr:robmed/devices/fusiontrackcpp.git CACHE INTERNAL "")
set(fusiontrackcpp_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(fusiontrackcpp_CATEGORIES CACHE INTERNAL "")
set(fusiontrackcpp_REFERENCES  CACHE INTERNAL "")
