#### referencing package rkcl-driver-kuka-fri mode ####
set(rkcl-driver-kuka-fri_MAIN_AUTHOR _Sonny_Tarbouriech CACHE INTERNAL "")
set(rkcl-driver-kuka-fri_MAIN_INSTITUTION _Tecnalia CACHE INTERNAL "")
set(rkcl-driver-kuka-fri_CONTACT_MAIL  CACHE INTERNAL "")
set(rkcl-driver-kuka-fri_FRAMEWORK  CACHE INTERNAL "")
set(rkcl-driver-kuka-fri_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rkcl-driver-kuka-fri_PROJECT_PAGE  CACHE INTERNAL "")
set(rkcl-driver-kuka-fri_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rkcl-driver-kuka-fri_SITE_INTRODUCTION  CACHE INTERNAL "")
set(rkcl-driver-kuka-fri_AUTHORS_AND_INSTITUTIONS "_Sonny_Tarbouriech(_Tecnalia);_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(rkcl-driver-kuka-fri_DESCRIPTION "TODO:;input;a;short;description;of;package;rkcl-driver-kuka-fri;utility;here" CACHE INTERNAL "")
set(rkcl-driver-kuka-fri_YEARS 2019 CACHE INTERNAL "")
set(rkcl-driver-kuka-fri_LICENSE CeCILL CACHE INTERNAL "")
set(rkcl-driver-kuka-fri_ADDRESS git@gitlab.com:rkcl/rkcl-driver-kuka-fri.git CACHE INTERNAL "")
set(rkcl-driver-kuka-fri_PUBLIC_ADDRESS https://gitlab.com/rkcl/rkcl-driver-kuka-fri.git CACHE INTERNAL "")
set(rkcl-driver-kuka-fri_CATEGORIES CACHE INTERNAL "")
set(rkcl-driver-kuka-fri_REFERENCES  CACHE INTERNAL "")
