#### referencing package sys-logging mode ####
set(sys-logging_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(sys-logging_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(sys-logging_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(sys-logging_AUTHORS_AND_INSTITUTIONS ;"_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(sys-logging_DESCRIPTION A package that defines libraries to easily manage logging CACHE INTERNAL "")
set(sys-logging_YEARS 2014 CACHE INTERNAL "")
set(sys-logging_LICENSE CeCILL-C CACHE INTERNAL "")
set(sys-logging_ADDRESS git@rob-dev.lirmm.fr:rob-developers/sys-logging.git CACHE INTERNAL "")
set(sys-logging_CATEGORIES  CACHE INTERNAL "")
set(sys-logging_REFERENCES  CACHE INTERNAL "")
