#### referencing package robot-controllers-knowbotics mode ####
set(robot-controllers-knowbotics_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(robot-controllers-knowbotics_MAIN_INSTITUTION  CACHE INTERNAL "")
set(robot-controllers-knowbotics_CONTACT_MAIL  CACHE INTERNAL "")
set(robot-controllers-knowbotics_FRAMEWORK  CACHE INTERNAL "")
set(robot-controllers-knowbotics_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(robot-controllers-knowbotics_PROJECT_PAGE  CACHE INTERNAL "")
set(robot-controllers-knowbotics_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(robot-controllers-knowbotics_SITE_INTRODUCTION  CACHE INTERNAL "")
set(robot-controllers-knowbotics_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro()" CACHE INTERNAL "")
set(robot-controllers-knowbotics_DESCRIPTION "Various;robot;controllers;for;Knowbotics" CACHE INTERNAL "")
set(robot-controllers-knowbotics_YEARS 2018 CACHE INTERNAL "")
set(robot-controllers-knowbotics_LICENSE CeCILL CACHE INTERNAL "")
set(robot-controllers-knowbotics_ADDRESS git@gite.lirmm.fr:knowbotics/robot-controllers-knowbotics.git CACHE INTERNAL "")
set(robot-controllers-knowbotics_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(robot-controllers-knowbotics_CATEGORIES CACHE INTERNAL "")
set(robot-controllers-knowbotics_REFERENCES  CACHE INTERNAL "")
