#### referencing package arm-controllers-knowbotics mode ####
set(arm-controllers-knowbotics_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(arm-controllers-knowbotics_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(arm-controllers-knowbotics_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(arm-controllers-knowbotics_FRAMEWORK  CACHE INTERNAL "")
set(arm-controllers-knowbotics_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(arm-controllers-knowbotics_PROJECT_PAGE  CACHE INTERNAL "")
set(arm-controllers-knowbotics_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(arm-controllers-knowbotics_SITE_INTRODUCTION  CACHE INTERNAL "")
set(arm-controllers-knowbotics_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM);_Robin_Passama(_LIRMM);_Andrea_Cherubini(_LIRMM);_Sonny_Tarbouriech(_LIRMM/Tecnalia)" CACHE INTERNAL "")
set(arm-controllers-knowbotics_DESCRIPTION "A set of different controllers for robotics arms" CACHE INTERNAL "")
set(arm-controllers-knowbotics_YEARS 2015 CACHE INTERNAL "")
set(arm-controllers-knowbotics_LICENSE CeCILL-C CACHE INTERNAL "")
set(arm-controllers-knowbotics_ADDRESS git@gite.lirmm.fr:knowbotics/arm-controllers-knowbotics.git CACHE INTERNAL "")
set(arm-controllers-knowbotics_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(arm-controllers-knowbotics_CATEGORIES "knowbotics/arm" CACHE INTERNAL "")
set(arm-controllers-knowbotics_REFERENCES  CACHE INTERNAL "")
