#### referencing wrapper of external package osqp ####
set(osqp_PID_WRAPPER_CONTACT_AUTHOR _Sonny_Tarbouriech CACHE INTERNAL "")
set(osqp_PID_WRAPPER_CONTACT_INSTITUTION _LIRMM CACHE INTERNAL "")
set(osqp_PID_WRAPPER_CONTACT_MAIL  CACHE INTERNAL "")
set(osqp_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(osqp_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/rob-miscellaneous/osqp CACHE INTERNAL "")
set(osqp_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(osqp_PID_WRAPPER_SITE_INTRODUCTION "OSQP is a is a numerical optimization package for solving convex quadratic programs" CACHE INTERNAL "")
set(osqp_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Sonny_Tarbouriech(_LIRMM);_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(osqp_PID_WRAPPER_YEARS 2019 CACHE INTERNAL "")
set(osqp_PID_WRAPPER_LICENSE GNUGPL CACHE INTERNAL "")
set(osqp_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/osqp.git CACHE INTERNAL "")
set(osqp_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/osqp.git CACHE INTERNAL "")
set(osqp_DESCRIPTION "PID;wrapper;for;OSQP;solver" CACHE INTERNAL "")
set(osqp_FRAMEWORK rpc CACHE INTERNAL "")
set(osqp_CATEGORIES "algorithm/optimization" CACHE INTERNAL "")
set(osqp_AUTHORS "OSQP project contributors" CACHE INTERNAL "")
set(osqp_PROJECT_SITE https://github.com/oxfordcontrol/osqp CACHE INTERNAL "")
set(osqp_LICENSES Apache 2.0 CACHE INTERNAL "")
set(osqp_REFERENCES  CACHE INTERNAL "")
