#### referencing wrapper of external package libfreenect2 ####
set(libfreenect2_PID_WRAPPER_CONTACT_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(libfreenect2_PID_WRAPPER_CONTACT_INSTITUTION _CNRS/LIRMM CACHE INTERNAL "")
set(libfreenect2_PID_WRAPPER_CONTACT_MAIL  CACHE INTERNAL "")
set(libfreenect2_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(libfreenect2_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/rob-vision-devices/libfreenect2 CACHE INTERNAL "")
set(libfreenect2_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(libfreenect2_PID_WRAPPER_SITE_INTRODUCTION "libfreenect2;is;a;low;level;driver;library;for;Microsoft;kinect;2;RGBD;camera." CACHE INTERNAL "")
set(libfreenect2_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_CNRS/LIRMM)" CACHE INTERNAL "")
set(libfreenect2_PID_WRAPPER_YEARS 2018-2019 CACHE INTERNAL "")
set(libfreenect2_PID_WRAPPER_LICENSE GNUGPL CACHE INTERNAL "")
set(libfreenect2_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:rob-vision-devices/libfreenect2.git CACHE INTERNAL "")
set(libfreenect2_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-vision-devices/libfreenect2.git CACHE INTERNAL "")
set(libfreenect2_DESCRIPTION "PID;wrapper;of;libfreenect2,;driver;library;for;Microsoft;kinect;2;RGBD;camera" CACHE INTERNAL "")
set(libfreenect2_FRAMEWORK rpc CACHE INTERNAL "")
set(libfreenect2_CATEGORIES "driver/sensor/vision" CACHE INTERNAL "")
set(libfreenect2_AUTHORS "OpenKinect project contributors" CACHE INTERNAL "")
set(libfreenect2_PROJECT_SITE https://github.com/OpenKinect CACHE INTERNAL "")
set(libfreenect2_LICENSES GNU GPL CACHE INTERNAL "")
set(libfreenect2_REFERENCES  CACHE INTERNAL "")
