#### referencing wrapper of external package mrpt ####
set(mrpt_PID_WRAPPER_CONTACT_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(mrpt_PID_WRAPPER_CONTACT_INSTITUTION _LIRMM-CNRS CACHE INTERNAL "")
set(mrpt_PID_WRAPPER_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(mrpt_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(mrpt_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/rob-miscellaneous/mrpt CACHE INTERNAL "")
set(mrpt_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(mrpt_PID_WRAPPER_SITE_INTRODUCTION "This project is a PID wrapper for the external project called mrpt. It is a framework for developping SLAM/navigation solutions for robotics." CACHE INTERNAL "")
set(mrpt_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM-CNRS)" CACHE INTERNAL "")
set(mrpt_PID_WRAPPER_YEARS 2018 CACHE INTERNAL "")
set(mrpt_PID_WRAPPER_LICENSE BSD CACHE INTERNAL "")
set(mrpt_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/mrpt.git CACHE INTERNAL "")
set(mrpt_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/mrpt.git CACHE INTERNAL "")
set(mrpt_DESCRIPTION "PID wrapper for project MRPT (Mobile Robot Programming Toolkit)." CACHE INTERNAL "")
set(mrpt_FRAMEWORK rpc CACHE INTERNAL "")
set(mrpt_CATEGORIES "algorithm/navigation;algorithm/slam" CACHE INTERNAL "")
set(mrpt_AUTHORS "mrpt.org members" CACHE INTERNAL "")
set(mrpt_PROJECT_SITE https://www.mrpt.org/ CACHE INTERNAL "")
set(mrpt_LICENSES 3-clause BSD License CACHE INTERNAL "")
set(mrpt_REFERENCES  CACHE INTERNAL "")
