#### referencing package youbot-vrep-driver mode ####
set(youbot-vrep-driver_MAIN_AUTHOR _Abdellah_Khelloufi CACHE INTERNAL "")
set(youbot-vrep-driver_MAIN_INSTITUTION  CACHE INTERNAL "")
set(youbot-vrep-driver_CONTACT_MAIL abdellah.khe@gmail.com CACHE INTERNAL "")
set(youbot-vrep-driver_AUTHORS_AND_INSTITUTIONS "_Abdellah_Khelloufi()" CACHE INTERNAL "")
set(youbot-vrep-driver_DESCRIPTION knowbotics;libraries;to;get;a;modified;you-bot;robot;in;vrep.;This;is;a;mobile;robot;with;swedish;wheels,;with;3;controllable;DOF. CACHE INTERNAL "")
set(youbot-vrep-driver_YEARS 2016 CACHE INTERNAL "")
set(youbot-vrep-driver_LICENSE CeCILL-C CACHE INTERNAL "")
set(youbot-vrep-driver_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/youbot-vrep-driver.git CACHE INTERNAL "")
set(youbot-vrep-driver_CATEGORIES "mobile-robot/modified-youbot;mobile-robot/simulated;knowbotics/mobile-robot;simulator/vrep" CACHE INTERNAL "")
set(youbot-vrep-driver_AVAILABLE_PLATFORMS linux64cxx11;linux64;linux32;macosx64 CACHE INTERNAL "")
set(youbot-vrep-driver_AVAILABLE_PLATFORM_linux64cxx11_OS linux CACHE INTERNAL "")
set(youbot-vrep-driver_AVAILABLE_PLATFORM_linux64cxx11_ARCH 64 CACHE INTERNAL "")
set(youbot-vrep-driver_AVAILABLE_PLATFORM_linux64cxx11_ABI CXX11 CACHE INTERNAL "")
set(youbot-vrep-driver_AVAILABLE_PLATFORM_linux64cxx11_CONFIGURATION  CACHE INTERNAL "")
set(youbot-vrep-driver_AVAILABLE_PLATFORM_linux64_OS linux CACHE INTERNAL "")
set(youbot-vrep-driver_AVAILABLE_PLATFORM_linux64_ARCH 64 CACHE INTERNAL "")
set(youbot-vrep-driver_AVAILABLE_PLATFORM_linux64_ABI CXX CACHE INTERNAL "")
set(youbot-vrep-driver_AVAILABLE_PLATFORM_linux64_CONFIGURATION  CACHE INTERNAL "")
set(youbot-vrep-driver_AVAILABLE_PLATFORM_linux32_OS linux CACHE INTERNAL "")
set(youbot-vrep-driver_AVAILABLE_PLATFORM_linux32_ARCH 32 CACHE INTERNAL "")
set(youbot-vrep-driver_AVAILABLE_PLATFORM_linux32_ABI CXX CACHE INTERNAL "")
set(youbot-vrep-driver_AVAILABLE_PLATFORM_linux32_CONFIGURATION  CACHE INTERNAL "")
set(youbot-vrep-driver_AVAILABLE_PLATFORM_macosx64_OS macosx CACHE INTERNAL "")
set(youbot-vrep-driver_AVAILABLE_PLATFORM_macosx64_ARCH 64 CACHE INTERNAL "")
set(youbot-vrep-driver_AVAILABLE_PLATFORM_macosx64_ABI CXX CACHE INTERNAL "")
set(youbot-vrep-driver_AVAILABLE_PLATFORM_macosx64_CONFIGURATION  CACHE INTERNAL "")
set(youbot-vrep-driver_REFERENCES  CACHE INTERNAL "")
