#### referencing wrapper of external package soem ####
set(soem_PID_WRAPPER_CONTACT_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(soem_PID_WRAPPER_CONTACT_INSTITUTION _LIRMM CACHE INTERNAL "")
set(soem_PID_WRAPPER_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(soem_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(soem_PID_WRAPPER_PROJECT_PAGE  CACHE INTERNAL "")
set(soem_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(soem_PID_WRAPPER_SITE_INTRODUCTION  CACHE INTERNAL "")
set(soem_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM);_Arnaud_Méline(_LIRMM)" CACHE INTERNAL "")
set(soem_PID_WRAPPER_YEARS 2018 CACHE INTERNAL "")
set(soem_PID_WRAPPER_LICENSE CeCILL-C CACHE INTERNAL "")
set(soem_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:ethercatcpp/soem.git CACHE INTERNAL "")
set(soem_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/ethercatcpp/soem.git CACHE INTERNAL "")
set(soem_DESCRIPTION "PID wrapper for SOEM project (see https://github.com/OpenEtherCATsociety/SOEM)" CACHE INTERNAL "")
set(soem_FRAMEWORK  CACHE INTERNAL "")
set(soem_CATEGORIES CACHE INTERNAL "")
set(soem_AUTHORS "OpenEthercat Society" CACHE INTERNAL "")
set(soem_PROJECT_SITE https://github.com/OpenEtherCATsociety/SOEM CACHE INTERNAL "")
set(soem_LICENSES GNU GPL CACHE INTERNAL "")
set(soem_REFERENCES  CACHE INTERNAL "")
