#### referencing package open-phri-metalimbs-driver mode ####
set(open-phri-metalimbs-driver_MAIN_AUTHOR _benjamin_Navarro CACHE INTERNAL "")
set(open-phri-metalimbs-driver_MAIN_INSTITUTION _LIRMM_/_CNRS CACHE INTERNAL "")
set(open-phri-metalimbs-driver_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(open-phri-metalimbs-driver_FRAMEWORK  CACHE INTERNAL "")
set(open-phri-metalimbs-driver_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(open-phri-metalimbs-driver_PROJECT_PAGE  CACHE INTERNAL "")
set(open-phri-metalimbs-driver_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(open-phri-metalimbs-driver_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(open-phri-metalimbs-driver_AUTHORS_AND_INSTITUTIONS "_benjamin_Navarro(_LIRMM_/_CNRS)" CACHE INTERNAL "")
set(open-phri-metalimbs-driver_DESCRIPTION "OpenPHRI;driver;for;the;Metalimb;robot" CACHE INTERNAL "")
set(open-phri-metalimbs-driver_YEARS 2019 CACHE INTERNAL "")
set(open-phri-metalimbs-driver_LICENSE CeCILL CACHE INTERNAL "")
set(open-phri-metalimbs-driver_ADDRESS git@gite.lirmm.fr:erato/open-phri-metalimbs-driver.git CACHE INTERNAL "")
set(open-phri-metalimbs-driver_PUBLIC_ADDRESS https://gite.lirmm.fr/erato/open-phri-metalimbs-driver.git CACHE INTERNAL "")
set(open-phri-metalimbs-driver_CATEGORIES CACHE INTERNAL "")
set(open-phri-metalimbs-driver_REFERENCES  CACHE INTERNAL "")
