#### referencing wrapper of external package simple-web-server ####
set(simple-web-server_PID_WRAPPER_CONTACT_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(simple-web-server_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(simple-web-server_PID_WRAPPER_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(simple-web-server_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(simple-web-server_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/pid/wrappers/simple-web-server CACHE INTERNAL "")
set(simple-web-server_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(simple-web-server_PID_WRAPPER_SITE_INTRODUCTION PID wrapper for the simple-web-server library. It is a very simple, fast, multithreaded, platform independent HTTP and HTTPS server and client library implemented using C++11 and Asio CACHE INTERNAL "")
set(simple-web-server_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr)" CACHE INTERNAL "")
set(simple-web-server_PID_WRAPPER_YEARS 2018 CACHE INTERNAL "")
set(simple-web-server_PID_WRAPPER_LICENSE MIT CACHE INTERNAL "")
set(simple-web-server_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:pid/wrappers/simple-web-server.git CACHE INTERNAL "")
set(simple-web-server_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/wrappers/simple-web-server.git CACHE INTERNAL "")
set(simple-web-server_DESCRIPTION "A very simple, fast, multithreaded, platform independent HTTP and HTTPS server and client library implemented using C++11 and Asio" CACHE INTERNAL "")
set(simple-web-server_FRAMEWORK pid CACHE INTERNAL "")
set(simple-web-server_CATEGORIES "programming/network" CACHE INTERNAL "")
set(simple-web-server_AUTHORS "Ole Christian Eidheim" CACHE INTERNAL "")
set(simple-web-server_PROJECT_SITE https://gitlab.com/eidheim/Simple-Web-Server CACHE INTERNAL "")
set(simple-web-server_LICENSES MIT License CACHE INTERNAL "")
set(simple-web-server_REFERENCES  CACHE INTERNAL "")
