#### referencing package mpo700-controller mode ####
set(mpo700-controller_MAIN_AUTHOR _Mohamed_Sorour CACHE INTERNAL "")
set(mpo700-controller_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(mpo700-controller_CONTACT_MAIL Mohamed.Sorour@lirmm.fr CACHE INTERNAL "")
set(mpo700-controller_AUTHORS_AND_INSTITUTIONS "_Mohamed_Sorour(_LIRMM);_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(mpo700-controller_DESCRIPTION API for implementing low level controller for the mpo700 mobile robot CACHE INTERNAL "")
set(mpo700-controller_YEARS 2017 CACHE INTERNAL "")
set(mpo700-controller_LICENSE CeCILL-C CACHE INTERNAL "")
set(mpo700-controller_ADDRESS git@gite.lirmm.fr:neobotix-mpo700/mpo700-controller.git CACHE INTERNAL "")
set(mpo700-controller_CATEGORIES CACHE INTERNAL "")
set(mpo700-controller_AVAILABLE_PLATFORMS linux64cxx11;linux64;linux32;macosx64 CACHE INTERNAL "")
set(mpo700-controller_AVAILABLE_PLATFORM_linux64cxx11_OS linux CACHE INTERNAL "")
set(mpo700-controller_AVAILABLE_PLATFORM_linux64cxx11_ARCH 64 CACHE INTERNAL "")
set(mpo700-controller_AVAILABLE_PLATFORM_linux64cxx11_ABI CXX11 CACHE INTERNAL "")
set(mpo700-controller_AVAILABLE_PLATFORM_linux64cxx11_CONFIGURATION  CACHE INTERNAL "")
set(mpo700-controller_AVAILABLE_PLATFORM_linux64_OS linux CACHE INTERNAL "")
set(mpo700-controller_AVAILABLE_PLATFORM_linux64_ARCH 64 CACHE INTERNAL "")
set(mpo700-controller_AVAILABLE_PLATFORM_linux64_ABI CXX CACHE INTERNAL "")
set(mpo700-controller_AVAILABLE_PLATFORM_linux64_CONFIGURATION  CACHE INTERNAL "")
set(mpo700-controller_AVAILABLE_PLATFORM_linux32_OS linux CACHE INTERNAL "")
set(mpo700-controller_AVAILABLE_PLATFORM_linux32_ARCH 32 CACHE INTERNAL "")
set(mpo700-controller_AVAILABLE_PLATFORM_linux32_ABI CXX CACHE INTERNAL "")
set(mpo700-controller_AVAILABLE_PLATFORM_linux32_CONFIGURATION  CACHE INTERNAL "")
set(mpo700-controller_AVAILABLE_PLATFORM_macosx64_OS macosx CACHE INTERNAL "")
set(mpo700-controller_AVAILABLE_PLATFORM_macosx64_ARCH 64 CACHE INTERNAL "")
set(mpo700-controller_AVAILABLE_PLATFORM_macosx64_ABI CXX CACHE INTERNAL "")
set(mpo700-controller_AVAILABLE_PLATFORM_macosx64_CONFIGURATION  CACHE INTERNAL "")
set(mpo700-controller_REFERENCES  CACHE INTERNAL "")
