#### referencing package pfoa_algorithms mode ####
set(pfoa_algorithms_MAIN_AUTHOR _Philippe_Lambert CACHE INTERNAL "")
set(pfoa_algorithms_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(pfoa_algorithms_CONTACT_MAIL  CACHE INTERNAL "")
set(pfoa_algorithms_FRAMEWORK  CACHE INTERNAL "")
set(pfoa_algorithms_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(pfoa_algorithms_PROJECT_PAGE  CACHE INTERNAL "")
set(pfoa_algorithms_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(pfoa_algorithms_SITE_INTRODUCTION  CACHE INTERNAL "")
set(pfoa_algorithms_AUTHORS_AND_INSTITUTIONS "_Philippe_Lambert(_LIRMM)" CACHE INTERNAL "")
set(pfoa_algorithms_DESCRIPTION "Path following and obstacle avoidance algorithms (designed by L. Lapierre)" CACHE INTERNAL "")
set(pfoa_algorithms_YEARS 2018 CACHE INTERNAL "")
set(pfoa_algorithms_LICENSE CeCILL CACHE INTERNAL "")
set(pfoa_algorithms_ADDRESS git@gite.lirmm.fr:pioneer3DX/pfoa_algorithms.git CACHE INTERNAL "")
set(pfoa_algorithms_PUBLIC_ADDRESS https://gite.lirmm.fr/pioneer3DX/pfoa_algorithms.git CACHE INTERNAL "")
set(pfoa_algorithms_CATEGORIES CACHE INTERNAL "")
set(pfoa_algorithms_REFERENCES  CACHE INTERNAL "")
