#### referencing wrapper of external package libxml2 ####
set(libxml2_PID_WRAPPER_CONTACT_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(libxml2_PID_WRAPPER_CONTACT_INSTITUTION _CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr CACHE INTERNAL "")
set(libxml2_PID_WRAPPER_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(libxml2_PID_WRAPPER_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(libxml2_PID_WRAPPER_PROJECT_PAGE https://gite.lirmm.fr/pid/libxml2 CACHE INTERNAL "")
set(libxml2_PID_WRAPPER_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(libxml2_PID_WRAPPER_SITE_INTRODUCTION libxml2;is;a;PID;wrapper;for;the;external;project;called;Libxml2.;Libxml2;is;the;XML;C;parser;and;toolkit;developed;for;the;Gnome;project. CACHE INTERNAL "")
set(libxml2_PID_WRAPPER_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr);_Robin_Passama(_CNRS_/_LIRMM:_Laboratoire_d'Informatique_de_Robotique_et_de_Microélectronique_de_Montpellier,_www.lirmm.fr)" CACHE INTERNAL "")
set(libxml2_PID_WRAPPER_YEARS 2018 CACHE INTERNAL "")
set(libxml2_PID_WRAPPER_LICENSE GNULGPL CACHE INTERNAL "")
set(libxml2_PID_WRAPPER_ADDRESS git@gite.lirmm.fr:pid/wrappers/libxml2.git CACHE INTERNAL "")
set(libxml2_PID_WRAPPER_PUBLIC_ADDRESS https://gite.lirmm.fr/pid/wrappers/libxml2.git CACHE INTERNAL "")
set(libxml2_DESCRIPTION "Libxml2 is the XML C parser and toolkit developed for the Gnome project. Repackaged for PID" CACHE INTERNAL "")
set(libxml2_FRAMEWORK pid CACHE INTERNAL "")
set(libxml2_CATEGORIES "programming/parser;programming/serialization" CACHE INTERNAL "")
set(libxml2_AUTHORS "Libxml2 developers" CACHE INTERNAL "")
set(libxml2_PROJECT_SITE http://www.xmlsoft.org/ CACHE INTERNAL "")
set(libxml2_LICENSES MIT CACHE INTERNAL "")
set(libxml2_REFERENCES  CACHE INTERNAL "")
