#### referencing package dsp-filters mode ####
set(dsp-filters_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(dsp-filters_MAIN_INSTITUTION _CNRS/LIRMM CACHE INTERNAL "")
set(dsp-filters_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(dsp-filters_FRAMEWORK rpc CACHE INTERNAL "")
set(dsp-filters_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(dsp-filters_PROJECT_PAGE https://gite.lirmm.fr/rob-miscellaneous/dsp-filters CACHE INTERNAL "")
set(dsp-filters_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(dsp-filters_SITE_INTRODUCTION "PID repackaging of DSPFilters project (https://github.com/vinniefalco/DSPFilters): a collection of useful C++ classes for Digital Signal Processing." CACHE INTERNAL "")
set(dsp-filters_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_CNRS/LIRMM);_Robin_Passama(_CNRS/LIRMM)" CACHE INTERNAL "")
set(dsp-filters_DESCRIPTION "PID repackaging of DSPFilters project (https://github.com/vinniefalco/DSPFilters)" CACHE INTERNAL "")
set(dsp-filters_YEARS 2016 CACHE INTERNAL "")
set(dsp-filters_LICENSE CeCILL-C CACHE INTERNAL "")
set(dsp-filters_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/dsp-filters.git CACHE INTERNAL "")
set(dsp-filters_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/dsp-filters.git CACHE INTERNAL "")
set(dsp-filters_CATEGORIES "algorithm/signal" CACHE INTERNAL "")
set(dsp-filters_REFERENCES  CACHE INTERNAL "")
