#### referencing package comedilib mode ####
set(comedilib_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(comedilib_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(comedilib_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(comedilib_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(comedilib_DESCRIPTION PID Wrapper for the Comedi library CACHE INTERNAL "")
set(comedilib_YEARS 2015 CACHE INTERNAL "")
set(comedilib_LICENSE CeCILL-C CACHE INTERNAL "")
set(comedilib_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/comedilib.git CACHE INTERNAL "")
set(comedilib_CATEGORIES "force-sensor/generic" CACHE INTERNAL "")
set(comedilib_AVAILABLE_PLATFORMS linux64cxx11;linux64;linux32;macosx64 CACHE INTERNAL "")
set(comedilib_AVAILABLE_PLATFORM_linux64cxx11_OS linux CACHE INTERNAL "")
set(comedilib_AVAILABLE_PLATFORM_linux64cxx11_ARCH 64 CACHE INTERNAL "")
set(comedilib_AVAILABLE_PLATFORM_linux64cxx11_ABI CXX11 CACHE INTERNAL "")
set(comedilib_AVAILABLE_PLATFORM_linux64cxx11_CONFIGURATION  CACHE INTERNAL "")
set(comedilib_AVAILABLE_PLATFORM_linux64_OS linux CACHE INTERNAL "")
set(comedilib_AVAILABLE_PLATFORM_linux64_ARCH 64 CACHE INTERNAL "")
set(comedilib_AVAILABLE_PLATFORM_linux64_ABI CXX CACHE INTERNAL "")
set(comedilib_AVAILABLE_PLATFORM_linux64_CONFIGURATION  CACHE INTERNAL "")
set(comedilib_AVAILABLE_PLATFORM_linux32_OS linux CACHE INTERNAL "")
set(comedilib_AVAILABLE_PLATFORM_linux32_ARCH 32 CACHE INTERNAL "")
set(comedilib_AVAILABLE_PLATFORM_linux32_ABI CXX CACHE INTERNAL "")
set(comedilib_AVAILABLE_PLATFORM_linux32_CONFIGURATION  CACHE INTERNAL "")
set(comedilib_AVAILABLE_PLATFORM_macosx64_OS macosx CACHE INTERNAL "")
set(comedilib_AVAILABLE_PLATFORM_macosx64_ARCH 64 CACHE INTERNAL "")
set(comedilib_AVAILABLE_PLATFORM_macosx64_ABI CXX CACHE INTERNAL "")
set(comedilib_AVAILABLE_PLATFORM_macosx64_CONFIGURATION  CACHE INTERNAL "")
set(comedilib_REFERENCES  CACHE INTERNAL "")
