#### referencing package rkcl-otg-reflexxes mode ####
set(rkcl-otg-reflexxes_MAIN_AUTHOR _Sonny_Tarbouriech CACHE INTERNAL "")
set(rkcl-otg-reflexxes_MAIN_INSTITUTION _Tecnalia CACHE INTERNAL "")
set(rkcl-otg-reflexxes_CONTACT_MAIL  CACHE INTERNAL "")
set(rkcl-otg-reflexxes_FRAMEWORK rkcl-framework CACHE INTERNAL "")
set(rkcl-otg-reflexxes_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rkcl-otg-reflexxes_PROJECT_PAGE https://gite.lirmm.fr/rkcl/rkcl-otg-reflexxes CACHE INTERNAL "")
set(rkcl-otg-reflexxes_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rkcl-otg-reflexxes_SITE_INTRODUCTION "Define;a;task;space;online;trajectory;generator;in;RKCL;based;on;Reflexxes." CACHE INTERNAL "")
set(rkcl-otg-reflexxes_AUTHORS_AND_INSTITUTIONS "_Sonny_Tarbouriech(_Tecnalia)" CACHE INTERNAL "")
set(rkcl-otg-reflexxes_DESCRIPTION "Define;a;task;space;online;trajectory;generator;in;RKCL;based;on;Reflexxes." CACHE INTERNAL "")
set(rkcl-otg-reflexxes_YEARS 2019 CACHE INTERNAL "")
set(rkcl-otg-reflexxes_LICENSE CeCILL CACHE INTERNAL "")
set(rkcl-otg-reflexxes_ADDRESS git@gite.lirmm.fr:rkcl/rkcl-otg-reflexxes.git CACHE INTERNAL "")
set(rkcl-otg-reflexxes_PUBLIC_ADDRESS https://gite.lirmm.fr/rkcl/rkcl-otg-reflexxes.git CACHE INTERNAL "")
set(rkcl-otg-reflexxes_CATEGORIES "processor" CACHE INTERNAL "")
set(rkcl-otg-reflexxes_REFERENCES  CACHE INTERNAL "")
