#### referencing package cdd mode ####
set(cdd_MAIN_AUTHOR _vsamy CACHE INTERNAL "")
set(cdd_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(cdd_CONTACT_MAIL vincent.samy@lirmm.fr CACHE INTERNAL "")
set(cdd_FRAMEWORK  CACHE INTERNAL "")
set(cdd_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(cdd_PROJECT_PAGE  CACHE INTERNAL "")
set(cdd_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(cdd_SITE_INTRODUCTION  CACHE INTERNAL "")
set(cdd_AUTHORS_AND_INSTITUTIONS "_vsamy(_LIRMM)" CACHE INTERNAL "")
set(cdd_DESCRIPTION "This is a polytope library. Forked from Fukuda's library: https://www.inf.ethz.ch/personal/fukudak/cdd_home/" CACHE INTERNAL "")
set(cdd_YEARS 2017 CACHE INTERNAL "")
set(cdd_LICENSE GNUGPL CACHE INTERNAL "")
set(cdd_ADDRESS git@github.com:vsamy/cdd.git CACHE INTERNAL "")
set(cdd_PUBLIC_ADDRESS https://github.com/vsamy/cdd.git CACHE INTERNAL "")
set(cdd_CATEGORIES CACHE INTERNAL "")
set(cdd_REFERENCES  CACHE INTERNAL "")
