#### referencing package camera-driver-vrep mode ####
set(camera-driver-vrep_MAIN_AUTHOR _Andrea_Cherubini CACHE INTERNAL "")
set(camera-driver-vrep_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(camera-driver-vrep_CONTACT_MAIL cherubini@lirmm.fr CACHE INTERNAL "")
set(camera-driver-vrep_AUTHORS_AND_INSTITUTIONS "_Andrea_Cherubini(_LIRMM)";"_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(camera-driver-vrep_DESCRIPTION A generic driver for v-rep cameras CACHE INTERNAL "")
set(camera-driver-vrep_YEARS 2015 CACHE INTERNAL "")
set(camera-driver-vrep_LICENSE CeCILL-C CACHE INTERNAL "")
set(camera-driver-vrep_ADDRESS git@rob-dev.lirmm.fr:cameras/camera-driver-vrep.git CACHE INTERNAL "")
set(camera-driver-vrep_CATEGORIES sensor/camera;driver/vrep CACHE INTERNAL "")
set(camera-driver-vrep_REFERENCES  CACHE INTERNAL "")
