#### referencing package eigen-extensions mode ####
set(eigen-extensions_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(eigen-extensions_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(eigen-extensions_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(eigen-extensions_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(eigen-extensions_DESCRIPTION Declare several extensions for the Eigen library (e.g. pseudo-inverse, skew-symmetric matrix, etc) CACHE INTERNAL "")
set(eigen-extensions_YEARS 2015 CACHE INTERNAL "")
set(eigen-extensions_LICENSE CeCILL-C CACHE INTERNAL "")
set(eigen-extensions_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/eigen-extensions.git CACHE INTERNAL "")
set(eigen-extensions_CATEGORIES "math/linear_algebra" CACHE INTERNAL "")
set(eigen-extensions_AVAILABLE_PLATFORMS linux64cxx11;linux64;linux32;macosx64 CACHE INTERNAL "")
set(eigen-extensions_AVAILABLE_PLATFORM_linux64cxx11_OS linux CACHE INTERNAL "")
set(eigen-extensions_AVAILABLE_PLATFORM_linux64cxx11_ARCH 64 CACHE INTERNAL "")
set(eigen-extensions_AVAILABLE_PLATFORM_linux64cxx11_ABI CXX11 CACHE INTERNAL "")
set(eigen-extensions_AVAILABLE_PLATFORM_linux64cxx11_CONFIGURATION  CACHE INTERNAL "")
set(eigen-extensions_AVAILABLE_PLATFORM_linux64_OS linux CACHE INTERNAL "")
set(eigen-extensions_AVAILABLE_PLATFORM_linux64_ARCH 64 CACHE INTERNAL "")
set(eigen-extensions_AVAILABLE_PLATFORM_linux64_ABI CXX CACHE INTERNAL "")
set(eigen-extensions_AVAILABLE_PLATFORM_linux64_CONFIGURATION  CACHE INTERNAL "")
set(eigen-extensions_AVAILABLE_PLATFORM_linux32_OS linux CACHE INTERNAL "")
set(eigen-extensions_AVAILABLE_PLATFORM_linux32_ARCH 32 CACHE INTERNAL "")
set(eigen-extensions_AVAILABLE_PLATFORM_linux32_ABI CXX CACHE INTERNAL "")
set(eigen-extensions_AVAILABLE_PLATFORM_linux32_CONFIGURATION  CACHE INTERNAL "")
set(eigen-extensions_AVAILABLE_PLATFORM_macosx64_OS macosx CACHE INTERNAL "")
set(eigen-extensions_AVAILABLE_PLATFORM_macosx64_ARCH 64 CACHE INTERNAL "")
set(eigen-extensions_AVAILABLE_PLATFORM_macosx64_ABI CXX CACHE INTERNAL "")
set(eigen-extensions_AVAILABLE_PLATFORM_macosx64_CONFIGURATION  CACHE INTERNAL "")
set(eigen-extensions_REFERENCES  CACHE INTERNAL "")
