#### referencing package eigen-fmt mode ####
set(eigen-fmt_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(eigen-fmt_MAIN_INSTITUTION _LIRMM_/_CNRS CACHE INTERNAL "")
set(eigen-fmt_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(eigen-fmt_FRAMEWORK  CACHE INTERNAL "")
set(eigen-fmt_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(eigen-fmt_PROJECT_PAGE  CACHE INTERNAL "")
set(eigen-fmt_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(eigen-fmt_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(eigen-fmt_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM_/_CNRS)" CACHE INTERNAL "")
set(eigen-fmt_DESCRIPTION "Provides;a;custom;formatter;to;be;used;with;the;{fmt};library" CACHE INTERNAL "")
set(eigen-fmt_YEARS 2020 CACHE INTERNAL "")
set(eigen-fmt_LICENSE CeCILL CACHE INTERNAL "")
set(eigen-fmt_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/eigen-fmt.git CACHE INTERNAL "")
set(eigen-fmt_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/eigen-fmt.git CACHE INTERNAL "")
set(eigen-fmt_CATEGORIES CACHE INTERNAL "")
set(eigen-fmt_REFERENCES  CACHE INTERNAL "")
