#### referencing package rkcl-bazar-app mode ####
set(rkcl-bazar-app_MAIN_AUTHOR _Sonny_Tarbouriech CACHE INTERNAL "")
set(rkcl-bazar-app_MAIN_INSTITUTION _Tecnalia CACHE INTERNAL "")
set(rkcl-bazar-app_CONTACT_MAIL  CACHE INTERNAL "")
set(rkcl-bazar-app_FRAMEWORK  CACHE INTERNAL "")
set(rkcl-bazar-app_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rkcl-bazar-app_PROJECT_PAGE  CACHE INTERNAL "")
set(rkcl-bazar-app_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rkcl-bazar-app_SITE_INTRODUCTION  CACHE INTERNAL "")
set(rkcl-bazar-app_AUTHORS_AND_INSTITUTIONS "_Sonny_Tarbouriech(_Tecnalia)" CACHE INTERNAL "")
set(rkcl-bazar-app_DESCRIPTION "TODO:;input;a;short;description;of;package;rkcl-bazar-app;utility;here" CACHE INTERNAL "")
set(rkcl-bazar-app_YEARS 2019 CACHE INTERNAL "")
set(rkcl-bazar-app_LICENSE CeCILL CACHE INTERNAL "")
set(rkcl-bazar-app_ADDRESS git@gitlab.com:rkcl/rkcl-bazar-app.git CACHE INTERNAL "")
set(rkcl-bazar-app_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(rkcl-bazar-app_CATEGORIES CACHE INTERNAL "")
set(rkcl-bazar-app_REFERENCES  CACHE INTERNAL "")
