#### referencing package udp-interface mode ####
set(knowbotics_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(knowbotics_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(knowbotics_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(knowbotics_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(knowbotics_DESCRIPTION Generic UDP server and client CACHE INTERNAL "")
set(knowbotics_YEARS 2016 CACHE INTERNAL "")
set(knowbotics_LICENSE CeCILL-C CACHE INTERNAL "")
set(knowbotics_ADDRESS git@gite.lirmm.fr:pid_external_deps/udp-interface.git CACHE INTERNAL "")
set(knowbotics_CATEGORIES "programming/io" CACHE INTERNAL "")
set(knowbotics_REFERENCES  CACHE INTERNAL "")
