#### referencing package yocto-watt-driver mode ####
set(yocto-watt-driver_MAIN_AUTHOR _Philippe_Lambert CACHE INTERNAL "")
set(yocto-watt-driver_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(yocto-watt-driver_CONTACT_MAIL plambert@lirmm.fr CACHE INTERNAL "")
set(yocto-watt-driver_FRAMEWORK  CACHE INTERNAL "")
set(yocto-watt-driver_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(yocto-watt-driver_PROJECT_PAGE  CACHE INTERNAL "")
set(yocto-watt-driver_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(yocto-watt-driver_SITE_INTRODUCTION  CACHE INTERNAL "")
set(yocto-watt-driver_AUTHORS_AND_INSTITUTIONS "_Philippe_Lambert(_LIRMM)" CACHE INTERNAL "")
set(yocto-watt-driver_DESCRIPTION "driver;library;for;a;watt-meter;from;Yoctopuce;company" CACHE INTERNAL "")
set(yocto-watt-driver_YEARS 2017 CACHE INTERNAL "")
set(yocto-watt-driver_LICENSE CeCILL CACHE INTERNAL "")
set(yocto-watt-driver_ADDRESS git@gite.lirmm.fr:pioneer3DX/yocto-watt-driver.git CACHE INTERNAL "")
set(yocto-watt-driver_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(yocto-watt-driver_CATEGORIES CACHE INTERNAL "")
set(yocto-watt-driver_REFERENCES  CACHE INTERNAL "")
