#### referencing package friction-toolbox mode ####
set(friction-toolbox_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(friction-toolbox_MAIN_INSTITUTION  CACHE INTERNAL "")
set(friction-toolbox_CONTACT_MAIL  CACHE INTERNAL "")
set(friction-toolbox_FRAMEWORK  CACHE INTERNAL "")
set(friction-toolbox_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(friction-toolbox_PROJECT_PAGE  CACHE INTERNAL "")
set(friction-toolbox_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(friction-toolbox_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(friction-toolbox_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro()" CACHE INTERNAL "")
set(friction-toolbox_DESCRIPTION "A;set;of;libraries;and;applications;to;identify;and;compensate;joint;frictions" CACHE INTERNAL "")
set(friction-toolbox_YEARS 2019 CACHE INTERNAL "")
set(friction-toolbox_LICENSE CeCILL CACHE INTERNAL "")
set(friction-toolbox_ADDRESS git@gite.lirmm.fr:rob-miscellaneous/friction-toolbox.git CACHE INTERNAL "")
set(friction-toolbox_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-miscellaneous/friction-toolbox.git CACHE INTERNAL "")
set(friction-toolbox_CATEGORIES CACHE INTERNAL "")
set(friction-toolbox_REFERENCES  CACHE INTERNAL "")
