#### referencing package udp-interface mode ####
set(udp-interface_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(udp-interface_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(udp-interface_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(udp-interface_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(udp-interface_DESCRIPTION Generic UDP server and client CACHE INTERNAL "")
set(udp-interface_YEARS 2016 CACHE INTERNAL "")
set(udp-interface_LICENSE CeCILL CACHE INTERNAL "")
set(udp-interface_ADDRESS git@gite.lirmm.fr:pid/udp-interface.git CACHE INTERNAL "")
set(udp-interface_CATEGORIES CACHE INTERNAL "")
set(udp-interface_AVAILABLE_PLATFORMS linux64cxx11;linux64 CACHE INTERNAL "")
set(udp-interface_AVAILABLE_PLATFORM_linux64cxx11_OS linux CACHE INTERNAL "")
set(udp-interface_AVAILABLE_PLATFORM_linux64cxx11_ARCH 64 CACHE INTERNAL "")
set(udp-interface_AVAILABLE_PLATFORM_linux64cxx11_ABI CXX11 CACHE INTERNAL "")
set(udp-interface_AVAILABLE_PLATFORM_linux64cxx11_CONFIGURATION posix CACHE INTERNAL "")
set(udp-interface_AVAILABLE_PLATFORM_linux64_OS linux CACHE INTERNAL "")
set(udp-interface_AVAILABLE_PLATFORM_linux64_ARCH 64 CACHE INTERNAL "")
set(udp-interface_AVAILABLE_PLATFORM_linux64_ABI CXX CACHE INTERNAL "")
set(udp-interface_AVAILABLE_PLATFORM_linux64_CONFIGURATION posix CACHE INTERNAL "")
set(udp-interface_REFERENCES  CACHE INTERNAL "")
