#### referencing package cobot_cart_docker mode ####
set(cobot_cart_docker_MAIN_AUTHOR _Andrea_Cherubini CACHE INTERNAL "")
set(cobot_cart_docker_MAIN_INSTITUTION  CACHE INTERNAL "")
set(cobot_cart_docker_CONTACT_MAIL  CACHE INTERNAL "")
set(cobot_cart_docker_AUTHORS_AND_INSTITUTIONS ; "_Andrea_Cherubini()" CACHE INTERNAL "")
set(cobot_cart_docker_DESCRIPTION TODO:;input;a;short;description;of;package;cobot_cart_docker;utility;here CACHE INTERNAL "")
set(cobot_cart_docker_YEARS 2015 CACHE INTERNAL "")
set(cobot_cart_docker_LICENSE CeCILL CACHE INTERNAL "")
set(cobot_cart_docker_ADDRESS git@rob-dev.lirmm.fr:idh/cobot_cart_docker.git CACHE INTERNAL "")
set(cobot_cart_docker_CATEGORIES  CACHE INTERNAL "")
set(cobot_cart_docker_REFERENCES  CACHE INTERNAL "")
