#### referencing package quadprog mode ####
set(quadprog_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(quadprog_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(quadprog_CONTACT_MAIL  CACHE INTERNAL "")
set(quadprog_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(quadprog_DESCRIPTION PID version of the package create by Luca Di Gaspero and Eric Moyer. This is a C++ library implementing the algorithm of Goldfarb and Idnani for the solution of a (convex) Quadratic Programming problem by means of an active-set dual method. CACHE INTERNAL "")
set(quadprog_YEARS 2016 CACHE INTERNAL "")
set(quadprog_LICENSE GNULGPL CACHE INTERNAL "")
set(quadprog_ADDRESS git@gite.lirmm.fr:pid_external_deps/quadprog.git CACHE INTERNAL "")
set(quadprog_CATEGORIES CACHE INTERNAL "")
set(quadprog_AVAILABLE_PLATFORMS linux64;linux32;macosx64;macosx32 CACHE INTERNAL "")
set(quadprog_AVAILABLE_PLATFORM_linux64_OS linux CACHE INTERNAL "")
set(quadprog_AVAILABLE_PLATFORM_linux64_ARCH 64 CACHE INTERNAL "")
set(quadprog_AVAILABLE_PLATFORM_linux64_CONFIGURATION  CACHE INTERNAL "")
set(quadprog_AVAILABLE_PLATFORM_linux32_OS linux CACHE INTERNAL "")
set(quadprog_AVAILABLE_PLATFORM_linux32_ARCH 32 CACHE INTERNAL "")
set(quadprog_AVAILABLE_PLATFORM_linux32_CONFIGURATION  CACHE INTERNAL "")
set(quadprog_AVAILABLE_PLATFORM_macosx64_OS macosx CACHE INTERNAL "")
set(quadprog_AVAILABLE_PLATFORM_macosx64_ARCH 64 CACHE INTERNAL "")
set(quadprog_AVAILABLE_PLATFORM_macosx64_CONFIGURATION  CACHE INTERNAL "")
set(quadprog_AVAILABLE_PLATFORM_macosx32_OS macosx CACHE INTERNAL "")
set(quadprog_AVAILABLE_PLATFORM_macosx32_ARCH 32 CACHE INTERNAL "")
set(quadprog_AVAILABLE_PLATFORM_macosx32_CONFIGURATION  CACHE INTERNAL "")
set(quadprog_REFERENCES  CACHE INTERNAL "")
