#### referencing package fltk-gui mode ####
set(fltk-gui_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(fltk-gui_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(fltk-gui_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(fltk-gui_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(fltk-gui_DESCRIPTION A package to simplify the use of the FLTK library inside PID CACHE INTERNAL "")
set(fltk-gui_YEARS 2015 CACHE INTERNAL "")
set(fltk-gui_LICENSE CeCILL-C CACHE INTERNAL "")
set(fltk-gui_ADDRESS git@gite.lirmm.fr:pid_external_deps/fltk-gui.git CACHE INTERNAL "")
set(fltk-gui_CATEGORIES CACHE INTERNAL "")
set(fltk-gui_AVAILABLE_PLATFORMS linux64cxx11;linux64;linux32;macosx64 CACHE INTERNAL "")
set(fltk-gui_AVAILABLE_PLATFORM_linux64cxx11_OS linux CACHE INTERNAL "")
set(fltk-gui_AVAILABLE_PLATFORM_linux64cxx11_ARCH 64 CACHE INTERNAL "")
set(fltk-gui_AVAILABLE_PLATFORM_linux64cxx11_ABI CXX11 CACHE INTERNAL "")
set(fltk-gui_AVAILABLE_PLATFORM_linux64cxx11_CONFIGURATION posix;x11 CACHE INTERNAL "")
set(fltk-gui_AVAILABLE_PLATFORM_linux64_OS linux CACHE INTERNAL "")
set(fltk-gui_AVAILABLE_PLATFORM_linux64_ARCH 64 CACHE INTERNAL "")
set(fltk-gui_AVAILABLE_PLATFORM_linux64_ABI CXX CACHE INTERNAL "")
set(fltk-gui_AVAILABLE_PLATFORM_linux64_CONFIGURATION posix;x11 CACHE INTERNAL "")
set(fltk-gui_AVAILABLE_PLATFORM_linux32_OS linux CACHE INTERNAL "")
set(fltk-gui_AVAILABLE_PLATFORM_linux32_ARCH 32 CACHE INTERNAL "")
set(fltk-gui_AVAILABLE_PLATFORM_linux32_ABI CXX CACHE INTERNAL "")
set(fltk-gui_AVAILABLE_PLATFORM_linux32_CONFIGURATION posix;x11 CACHE INTERNAL "")
set(fltk-gui_AVAILABLE_PLATFORM_macosx64_OS macosx CACHE INTERNAL "")
set(fltk-gui_AVAILABLE_PLATFORM_macosx64_ARCH 64 CACHE INTERNAL "")
set(fltk-gui_AVAILABLE_PLATFORM_macosx64_ABI CXX CACHE INTERNAL "")
set(fltk-gui_AVAILABLE_PLATFORM_macosx64_CONFIGURATION posix;x11 CACHE INTERNAL "")
set(fltk-gui_REFERENCES  CACHE INTERNAL "")
