#### referencing package rkcl-driver-ur mode ####
set(rkcl-driver-ur_MAIN_AUTHOR _Sonny_Tarbouriech CACHE INTERNAL "")
set(rkcl-driver-ur_MAIN_INSTITUTION _Tecnalia CACHE INTERNAL "")
set(rkcl-driver-ur_CONTACT_MAIL  CACHE INTERNAL "")
set(rkcl-driver-ur_FRAMEWORK  CACHE INTERNAL "")
set(rkcl-driver-ur_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rkcl-driver-ur_PROJECT_PAGE  CACHE INTERNAL "")
set(rkcl-driver-ur_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rkcl-driver-ur_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(rkcl-driver-ur_AUTHORS_AND_INSTITUTIONS "_Sonny_Tarbouriech(_Tecnalia);_Benjamin_Navarro(_LIRMM)" CACHE INTERNAL "")
set(rkcl-driver-ur_DESCRIPTION "Universal;Robots;driver;for;RKCL" CACHE INTERNAL "")
set(rkcl-driver-ur_YEARS 2019 CACHE INTERNAL "")
set(rkcl-driver-ur_LICENSE CeCILL CACHE INTERNAL "")
set(rkcl-driver-ur_ADDRESS git@gite.lirmm.fr:rkcl/rkcl-driver-ur.git CACHE INTERNAL "")
set(rkcl-driver-ur_PUBLIC_ADDRESS https://gite.lirmm.fr/rkcl/rkcl-driver-ur.git CACHE INTERNAL "")
set(rkcl-driver-ur_CATEGORIES CACHE INTERNAL "")
set(rkcl-driver-ur_REFERENCES  CACHE INTERNAL "")
