#### referencing package kinect1-driver mode ####
set(kinect1-driver_MAIN_AUTHOR _Philippe_Lambert CACHE INTERNAL "")
set(kinect1-driver_MAIN_INSTITUTION _University_of_MontpellierLIRMM CACHE INTERNAL "")
set(kinect1-driver_CONTACT_MAIL plambert@lirmm.fr CACHE INTERNAL "")
set(kinect1-driver_FRAMEWORK rpc CACHE INTERNAL "")
set(kinect1-driver_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(kinect1-driver_PROJECT_PAGE https://gite.lirmm.fr/rob-vision-devices/kinect1-driver CACHE INTERNAL "")
set(kinect1-driver_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(kinect1-driver_SITE_INTRODUCTION "kinect1-driver provides libaries used to access the kinect 1 vision sensor." CACHE INTERNAL "")
set(kinect1-driver_AUTHORS_AND_INSTITUTIONS "_Philippe_Lambert(_University_of_MontpellierLIRMM);_Robin_Passama(_CNRS/LIRMM)" CACHE INTERNAL "")
set(kinect1-driver_DESCRIPTION "a library that wraps freenect1 library to manage kinect1 sensor" CACHE INTERNAL "")
set(kinect1-driver_YEARS 2017-2019 CACHE INTERNAL "")
set(kinect1-driver_LICENSE CeCILL CACHE INTERNAL "")
set(kinect1-driver_ADDRESS git@gite.lirmm.fr:rob-vision-devices/kinect1-driver.git CACHE INTERNAL "")
set(kinect1-driver_PUBLIC_ADDRESS https://gite.lirmm.fr/rob-vision-devices/kinect1-driver.git CACHE INTERNAL "")
set(kinect1-driver_CATEGORIES "driver/sensor/vision" CACHE INTERNAL "")
set(kinect1-driver_REFERENCES  CACHE INTERNAL "")
