#### referencing package rkcl-bazar-robot mode ####
set(rkcl-bazar-robot_MAIN_AUTHOR _Sonny_Tarbouriech CACHE INTERNAL "")
set(rkcl-bazar-robot_MAIN_INSTITUTION _Tecnalia CACHE INTERNAL "")
set(rkcl-bazar-robot_CONTACT_MAIL  CACHE INTERNAL "")
set(rkcl-bazar-robot_FRAMEWORK  CACHE INTERNAL "")
set(rkcl-bazar-robot_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(rkcl-bazar-robot_PROJECT_PAGE  CACHE INTERNAL "")
set(rkcl-bazar-robot_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(rkcl-bazar-robot_SITE_INTRODUCTION "" CACHE INTERNAL "")
set(rkcl-bazar-robot_AUTHORS_AND_INSTITUTIONS "_Sonny_Tarbouriech(_Tecnalia)" CACHE INTERNAL "")
set(rkcl-bazar-robot_DESCRIPTION "TODO:;input;a;short;description;of;package;rkcl-bazar-robot;utility;here" CACHE INTERNAL "")
set(rkcl-bazar-robot_YEARS 2019 CACHE INTERNAL "")
set(rkcl-bazar-robot_LICENSE CeCILL CACHE INTERNAL "")
set(rkcl-bazar-robot_ADDRESS git@gite.lirmm.fr:rkcl/rkcl-bazar-robot.git CACHE INTERNAL "")
set(rkcl-bazar-robot_PUBLIC_ADDRESS https://gite.lirmm.fr/rkcl/rkcl-bazar-robot.git CACHE INTERNAL "")
set(rkcl-bazar-robot_CATEGORIES CACHE INTERNAL "")
set(rkcl-bazar-robot_REFERENCES  CACHE INTERNAL "")
