#### referencing package the-testpack-d mode ####
set(the-testpack-d_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(the-testpack-d_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(the-testpack-d_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM)";"_John Rambo(_US ARMY)" CACHE INTERNAL "")
set(the-testpack-d_DESCRIPTION test;package;C;for;PID CACHE INTERNAL "")
set(the-testpack-d_YEARS 2013 CACHE INTERNAL "")
set(the-testpack-d_LICENSE CeCILL CACHE INTERNAL "")
set(the-testpack-d_ADDRESS git@idh.lirmm.fr:the-testpack-d.git CACHE INTERNAL "")
set(the-testpack-d_CATEGORIES ertyuio;fhurhruhf/dueuehduehd/jdueueue;fhurhruhf/voilaquoi CACHE INTERNAL "")
set(the-testpack-d_REFERENCES  CACHE INTERNAL "")
