#### referencing package rob-common-data mode ####
set(rob-common-data_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(rob-common-data_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(rob-common-data_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(rob-common-data_AUTHORS_AND_INSTITUTIONS ;"_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(rob-common-data_DESCRIPTION This;package;provide;common;data;types;used;in;all;other;PID;projects CACHE INTERNAL "")
set(rob-common-data_YEARS 2014 CACHE INTERNAL "")
set(rob-common-data_LICENSE CeCILL-C CACHE INTERNAL "")
set(rob-common-data_ADDRESS git@rob-dev.lirmm.fr:rob-developers/rob-common-data.git CACHE INTERNAL "")
set(rob-common-data_CATEGORIES data/basic;data/physic;data/geometry CACHE INTERNAL "")
set(rob-common-data_REFERENCES  CACHE INTERNAL "")
