#### referencing package kuka-lwr-driver-vrep mode ####
set(kuka-lwr-driver-vrep_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(kuka-lwr-driver-vrep_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(kuka-lwr-driver-vrep_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(kuka-lwr-driver-vrep_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM);_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(kuka-lwr-driver-vrep_DESCRIPTION Knowbotics API to interface with a simulated Kuka LWR on V-REP CACHE INTERNAL "")
set(kuka-lwr-driver-vrep_YEARS 2015 CACHE INTERNAL "")
set(kuka-lwr-driver-vrep_LICENSE CeCILL-C CACHE INTERNAL "")
set(kuka-lwr-driver-vrep_ADDRESS git@gite.lirmm.fr:kuka-lwr/kuka-lwr-driver-vrep.git CACHE INTERNAL "")
set(kuka-lwr-driver-vrep_CATEGORIES "arm/kuka-lwr;arm/simulated;simulator/vrep" CACHE INTERNAL "")
set(kuka-lwr-driver-vrep_REFERENCES  CACHE INTERNAL "")
