#### referencing package hardiocore mode ####
set(hardiocore_MAIN_AUTHOR _Charles_Villard CACHE INTERNAL "")
set(hardiocore_MAIN_INSTITUTION  CACHE INTERNAL "")
set(hardiocore_CONTACT_MAIL  CACHE INTERNAL "")
set(hardiocore_FRAMEWORK  CACHE INTERNAL "")
set(hardiocore_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(hardiocore_PROJECT_PAGE  CACHE INTERNAL "")
set(hardiocore_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(hardiocore_SITE_INTRODUCTION  CACHE INTERNAL "")
set(hardiocore_AUTHORS_AND_INSTITUTIONS "_Charles_Villard()" CACHE INTERNAL "")
set(hardiocore_DESCRIPTION "Abstract;low;level;I/O;removing;direct;hardware;implementation" CACHE INTERNAL "")
set(hardiocore_YEARS 2018 CACHE INTERNAL "")
set(hardiocore_LICENSE CeCILL-C CACHE INTERNAL "")
set(hardiocore_ADDRESS git@gite.lirmm.fr:explore-rov/Drivers/hardiocore.git CACHE INTERNAL "")
set(hardiocore_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(hardiocore_CATEGORIES CACHE INTERNAL "")
set(hardiocore_REFERENCES  CACHE INTERNAL "")
