#### referencing package pid-config mode ####
set(pid-config_MAIN_AUTHOR _Robin_Passama CACHE INTERNAL "")
set(pid-config_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(pid-config_CONTACT_MAIL passama@lirmm.fr CACHE INTERNAL "")
set(pid-config_FRAMEWORK pid CACHE INTERNAL "")
set(pid-config_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(pid-config_PROJECT_PAGE https://gite.lirmm.fr/pid/pid-config CACHE INTERNAL "")
set(pid-config_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(pid-config_SITE_INTRODUCTION pid-config;is;a;PID;package;providing;a;little;API;that;eases;the;creation;of;application;configurators.;Configurators;use;files;in;yaml;format;to;set;some;option;of;the;program.;Its;usage;is;completely;bound;to;the;use;of;PID;system. CACHE INTERNAL "")
set(pid-config_AUTHORS_AND_INSTITUTIONS "_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(pid-config_DESCRIPTION set of libraries and tools used to manage configuration of programs and libraries using configuration files CACHE INTERNAL "")
set(pid-config_YEARS 2014 CACHE INTERNAL "")
set(pid-config_LICENSE CeCILL-C CACHE INTERNAL "")
set(pid-config_ADDRESS git@gite.lirmm.fr:pid/pid-config.git CACHE INTERNAL "")
set(pid-config_CATEGORIES "programming/configuration" CACHE INTERNAL "")
set(pid-config_REFERENCES 1.0.0 CACHE INTERNAL "")
set(pid-config_REFERENCE_1.0.0 x86_64_linux_abi98;x86_64_linux_abi11 CACHE INTERNAL "")
set(pid-config_REFERENCE_1.0.0_x86_64_linux_abi98_URL https://gite.lirmm.fr/pid/pid-binaries/wikis/pid-config/1.0.0/linux64/pid-config-1.0.0-linux64.tar.gz CACHE INTERNAL "")
set(pid-config_REFERENCE_1.0.0_x86_64_linux_abi98_URL_DEBUG https://gite.lirmm.fr/pid/pid-binaries/wikis/pid-config/1.0.0/linux64/pid-config-1.0.0-dbg-linux64.tar.gz CACHE INTERNAL "")
set(pid-config_REFERENCE_1.0.0_x86_64_linux_abi11_URL https://gite.lirmm.fr/pid/pid-binaries/wikis/pid-config/1.0.0/linux64cxx11/pid-config-1.0.0-linux64cxx11.tar.gz CACHE INTERNAL "")
set(pid-config_REFERENCE_1.0.0_x86_64_linux_abi11_URL_DEBUG https://gite.lirmm.fr/pid/pid-binaries/wikis/pid-rpath/1.0.0/linux64cxx11/pid-rpath-1.0.0-dbg-linux64.tar.gz CACHE INTERNAL "")
