#### referencing package toolexample mode ####
set(toolexample_MAIN_AUTHOR _Charles_Villard CACHE INTERNAL "")
set(toolexample_MAIN_INSTITUTION  CACHE INTERNAL "")
set(toolexample_CONTACT_MAIL  CACHE INTERNAL "")
set(toolexample_FRAMEWORK  CACHE INTERNAL "")
set(toolexample_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(toolexample_PROJECT_PAGE  CACHE INTERNAL "")
set(toolexample_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(toolexample_SITE_INTRODUCTION  CACHE INTERNAL "")
set(toolexample_AUTHORS_AND_INSTITUTIONS "_Charles_Villard()" CACHE INTERNAL "")
set(toolexample_DESCRIPTION "This;package;show;how;to;use;the;tools;with;a;raspi;implementation" CACHE INTERNAL "")
set(toolexample_YEARS 2018 CACHE INTERNAL "")
set(toolexample_LICENSE CeCILL CACHE INTERNAL "")
set(toolexample_ADDRESS git@gite.lirmm.fr:explore-rov/tools/toolexample.git CACHE INTERNAL "")
set(toolexample_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(toolexample_CATEGORIES CACHE INTERNAL "")
set(toolexample_REFERENCES  CACHE INTERNAL "")
