#### referencing package encoder-udp-bridge mode ####
set(encoder-udp-bridge_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(encoder-udp-bridge_MAIN_INSTITUTION  CACHE INTERNAL "")
set(encoder-udp-bridge_CONTACT_MAIL  CACHE INTERNAL "")
set(encoder-udp-bridge_FRAMEWORK  CACHE INTERNAL "")
set(encoder-udp-bridge_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(encoder-udp-bridge_PROJECT_PAGE  CACHE INTERNAL "")
set(encoder-udp-bridge_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(encoder-udp-bridge_SITE_INTRODUCTION  CACHE INTERNAL "")
set(encoder-udp-bridge_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro()" CACHE INTERNAL "")
set(encoder-udp-bridge_DESCRIPTION A;UDP;bridge;for;4;quadrature;encoders CACHE INTERNAL "")
set(encoder-udp-bridge_YEARS 2017 CACHE INTERNAL "")
set(encoder-udp-bridge_LICENSE CeCILL CACHE INTERNAL "")
set(encoder-udp-bridge_ADDRESS git@gite.lirmm.fr:stm32/encoder-udp-bridge.git CACHE INTERNAL "")
set(encoder-udp-bridge_CATEGORIES CACHE INTERNAL "")
set(encoder-udp-bridge_REFERENCES  CACHE INTERNAL "")
