#### referencing package knowbotics-tools mode ####
set(knowbotics-tools_MAIN_AUTHOR _Benjamin_Navarro CACHE INTERNAL "")
set(knowbotics-tools_MAIN_INSTITUTION _LIRMM CACHE INTERNAL "")
set(knowbotics-tools_CONTACT_MAIL navarro@lirmm.fr CACHE INTERNAL "")
set(knowbotics-tools_FRAMEWORK  CACHE INTERNAL "")
set(knowbotics-tools_SITE_ROOT_PAGE  CACHE INTERNAL "")
set(knowbotics-tools_PROJECT_PAGE  CACHE INTERNAL "")
set(knowbotics-tools_SITE_GIT_ADDRESS  CACHE INTERNAL "")
set(knowbotics-tools_SITE_INTRODUCTION  CACHE INTERNAL "")
set(knowbotics-tools_AUTHORS_AND_INSTITUTIONS "_Benjamin_Navarro(_LIRMM);_Robin_Passama(_LIRMM)" CACHE INTERNAL "")
set(knowbotics-tools_DESCRIPTION "Set of tools based on Knowbotics" CACHE INTERNAL "")
set(knowbotics-tools_YEARS 2015 CACHE INTERNAL "")
set(knowbotics-tools_LICENSE CeCILL-C CACHE INTERNAL "")
set(knowbotics-tools_ADDRESS git@gite.lirmm.fr:knowbotics/knowbotics-tools.git CACHE INTERNAL "")
set(knowbotics-tools_PUBLIC_ADDRESS  CACHE INTERNAL "")
set(knowbotics-tools_CATEGORIES "programming/plot;knowbotics/plot" CACHE INTERNAL "")
set(knowbotics-tools_REFERENCES  CACHE INTERNAL "")
