###
function(classify_Package_Categories package)
foreach(a_category IN ITEMS ${${a_package}_CATEGORIES})
	classify_Category(${a_category} ${package} ROOT_CATEGORIES)	
endforeach()
endfunction()

###
function(reset_All_Categories)
foreach(a_category IN ITEMS ${ROOT_CATEGORIES})
	reset_Category(${a_category})
endforeach()
set(ROOT_CATEGORIES "" CACHE INTERNAL "")
endfunction()

###
function(reset_Category category)
if(${category}_CATEGORIES)
	foreach(a_category IN ITEMS ${${category}_CATEGORIES})
		reset_Category(${a_category})#recursive call
	endforeach()
endif()
if(${category}_CATEGORY_CONTENT)
	set(${category}_CATEGORY_CONTENT CACHE INTERNAL "")
endif()
set(${category}_CATEGORIES CACHE INTERNAL "")
endfunction()

###
function(classify_Category category_full_string package container_variable)
string(REGEX REPLACE "^([^/]+)/(.+)$" "\\1;\\2" CATEGORY_STRING_CONTENT ${category_full_string})
if(NOT CATEGORY_STRING_CONTENT STREQUAL ${category_full_string})# it macthes => there are subcategories
	list(GET CATEGORY_STRING_CONTENT 0 ROOT_OF_CATEGORY)
	list(GET CATEGORY_STRING_CONTENT 1 REMAINING_OF_CATEGORY)
	set(${container_variable} ${${container_variable}} ${ROOT_OF_CATEGORY} CACHE INTERNAL "")
	classify_Category(${REMAINING_OF_CATEGORY} ${package} ${ROOT_OF_CATEGORY}_CATEGORIES)
else()#there is no sub categories
	string(REGEX REPLACE "^(.+)$" "\\1" ROOT_OF_CATEGORY ${category_full_string})
	set(${container_variable} ${${container_variable}} ${ROOT_OF_CATEGORY} CACHE INTERNAL "")	
	set(${ROOT_OF_CATEGORY}_CATEGORY_CONTENT ${${ROOT_OF_CATEGORY}_CATEGORY_CONTENT} ${package} CACHE INTERNAL "")
endif()
endfunction()

function(print_categories RESULT)
set(PRINTED_VALUE "CATEGORIES:\\\n")
foreach(root_cat IN ITEMS ${ROOT_CATEGORIES})
	set(CAT_RESULT "")
	print_Category(${root_cat} 0 CAT_RESULT)
	set(PRINTED_VALUE "${PRINTED_VALUE}${CAT_RESULT}")
endforeach()
set(${RESULT} ${PRINTED_VALUE} PARENT_SCOPE)
endfunction()

function(print_Category category number_of_tabs RESULT)
set(PRINTED_VALUE "")
set(RESULT_STRING "")
set(index ${number_of_tabs})
while(index GREATER 0)
	set(RESULT_STRING "${RESULT_STRING}\\\t")
	math(EXPR index '${index}-1')
endwhile()
if(${category}_CATEGORY_CONTENT)
	#set(PRINTED_VALUE "${PRINTED_VALUE}${RESULT_STRING}${category}:${${category}_CATEGORY_CONTENT}")
	set(PRINTED_VALUE "${PRINTED_VALUE}${RESULT_STRING}${category}:")
	foreach(pack IN ITEMS ${${category}_CATEGORY_CONTENT})
		set(PRINTED_VALUE "${PRINTED_VALUE} ${pack}")
	endforeach()
else()
	set(PRINTED_VALUE "${PRINTED_VALUE}${RESULT_STRING}${category}")
endif()
if(${category}_CATEGORIES)
	set(PRINTED_VALUE "${PRINTED_VALUE}\\\n")	
	math(EXPR sub_cat_nb_tabs '${number_of_tabs}+1')
	foreach(sub_cat IN ITEMS ${${category}_CATEGORIES})
		set(CAT_RESULT "")
		print_Category(${sub_cat} ${sub_cat_nb_tabs} CAT_RESULT)
		set(PRINTED_VALUE "${PRINTED_VALUE}${CAT_RESULT}")
	endforeach()
else()
	set(PRINTED_VALUE "${PRINTED_VALUE}\\\n")
endif()
set(${RESULT} ${PRINTED_VALUE} PARENT_SCOPE)
endfunction()

