set(PLATFORM_arm_32_abi11_TYPE "arm" CACHE INTERNAL "")
set(PLATFORM_arm_32_abi11_ARCH "32" CACHE INTERNAL "")
set(PLATFORM_arm_32_abi11_OS "" CACHE INTERNAL "")
set(PLATFORM_arm_32_abi11_ABI "CXX11" CACHE INTERNAL "")
